import type {SearchFullscreenNavigatorParamList} from '@navigation/types';
import SCREENS from '@src/SCREENS';

// This file is used to define RHP screens that are in relation to the search screen.
const SEARCH_TO_RHP: Partial<Record<keyof SearchFullscreenNavigatorParamList, string[]>> = {
    [SCREENS.SEARCH.ROOT]: [
        SCREENS.SEARCH.ROOT_VERIFY_ACCOUNT,
        SCREENS.SEARCH.REPORT_VERIFY_ACCOUNT,
        SCREENS.SEARCH.TRANSACTION_HOLD_REASON_RHP,
        SCREENS.SEARCH.TRANSACTION_HOLD_REASON_SEARCH,
        SCREENS.SEARCH.SEARCH_REJECT_REASON_RHP,
        SCREENS.SEARCH.TRANSACTIONS_CHANGE_REPORT_SEARCH_RHP,
        SCREENS.SEARCH.COLUMNS_RHP,
        SCREENS.SEARCH.ADVANCED_FILTERS_RHP,
        SCREENS.SEARCH.ADVANCED_FILTERS_CONTENT_RHP,
        SCREENS.SEARCH.CHANGE_APPROVER.ROOT,
        SCREENS.SEARCH.CHANGE_APPROVER.ADD_APPROVER,
        SCREENS.SEARCH.SAVED_SEARCH_RENAME_RHP,
        SCREENS.MONEY_REQUEST.SPLIT_EXPENSE_SEARCH,
        SCREENS.RIGHT_MODAL.SEARCH_MONEY_REQUEST_REPORT,
        SCREENS.RIGHT_MODAL.SEARCH_REPORT,
        SCREENS.RIGHT_MODAL.SEARCH_SAVE,
    ],
};

export default SEARCH_TO_RHP;
