"use strict";
exports.__esModule = true;
var SCREENS_1 = require("@src/SCREENS");
// This file is used to define RHP screens that are in relation to the search screen.
var SEARCH_TO_RHP = [
    SCREENS_1["default"].SEARCH.REPORT_RHP,
    SCREENS_1["default"].SEARCH.TRANSACTION_HOLD_REASON_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_CURRENCY_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_DATE_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_SUBMITTED_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_APPROVED_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_PAID_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_EXPORTED_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_POSTED_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_DESCRIPTION_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_MERCHANT_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_REPORT_ID_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_AMOUNT_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_CATEGORY_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_KEYWORD_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_TAX_RATE_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_EXPENSE_TYPE_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_TAG_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_FROM_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_TO_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_IN_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_WORKSPACE_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_CARD_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_REIMBURSABLE_RHP,
    SCREENS_1["default"].SEARCH.ADVANCED_FILTERS_BILLABLE_RHP,
    SCREENS_1["default"].SEARCH.SAVED_SEARCH_RENAME_RHP,
];
exports["default"] = SEARCH_TO_RHP;
