import CONST from '@src/CONST';
import SCREENS from '@src/SCREENS';

const SIDEBAR_TO_RHP: Record<string, string[]> = {
    [SCREENS.HOME]: [SCREENS.MONEY_REQUEST.CREATE, CONST.TAB_REQUEST.DISTANCE, CONST.TAB_REQUEST.MANUAL, CONST.TAB_REQUEST.SCAN],
    [SCREENS.SETTINGS.ROOT]: [
        SCREENS.SETTINGS.SHARE_CODE,
        SCREENS.SETTINGS.PROFILE.STATUS,
        SCREENS.SETTINGS.PREFERENCES.PRIORITY_MODE,
        SCREENS.SETTINGS.EXIT_SURVEY.REASON,
        SCREENS.SETTINGS.EXIT_SURVEY.RESPONSE,
        SCREENS.SETTINGS.EXIT_SURVEY.CONFIRM,
    ],
};

export default SIDEBAR_TO_RHP;
