import SCREENS from '@src/SCREENS';

const SIDEBAR_TO_RHP: Record<string, string[]> = {
    // @TODO are those really all to home?
    [SCREENS.HOME]: [
        SCREENS.SETTINGS.SHARE_CODE,
        SCREENS.SETTINGS.PROFILE.STATUS,
        SCREENS.SETTINGS.PREFERENCES.PRIORITY_MODE,
        SCREENS.MONEY_REQUEST.CREATE,
        SCREENS.SETTINGS.EXIT_SURVEY.REASON,
        SCREENS.SETTINGS.EXIT_SURVEY.RESPONSE,
        SCREENS.SETTINGS.EXIT_SURVEY.CONFIRM,
        SCREENS.HOME,
    ],
};

export default SIDEBAR_TO_RHP;
