import type {ValueOf} from 'type-fest';
import NAVIGATION_TABS from '@components/Navigation/NavigationTabBar/NAVIGATION_TABS';
import type {FullScreenName} from '@libs/Navigation/types';
import NAVIGATORS from '@src/NAVIGATORS';
import SCREENS from '@src/SCREENS';

const TAB_TO_FULLSCREEN: Record<ValueOf<typeof NAVIGATION_TABS>, FullScreenName[]> = {
    [NAVIGATION_TABS.HOME]: [SCREENS.HOME],
    [NAVIGATION_TABS.INBOX]: [NAVIGATORS.REPORTS_SPLIT_NAVIGATOR],
    [NAVIGATION_TABS.SEARCH]: [NAVIGATORS.SEARCH_FULLSCREEN_NAVIGATOR],
    [NAVIGATION_TABS.SETTINGS]: [NAVIGATORS.SETTINGS_SPLIT_NAVIGATOR],
    [NAVIGATION_TABS.WORKSPACES]: [NAVIGATORS.WORKSPACE_NAVIGATOR],
};

export default TAB_TO_FULLSCREEN;
