import SCREENS from '@src/SCREENS';

const WORKSPACES_LIST_TO_RHP: Record<typeof SCREENS.WORKSPACES_LIST, string[]> = {
    [SCREENS.WORKSPACES_LIST]: [
        SCREENS.WORKSPACE_DUPLICATE.SELECT_FEATURES,
        SCREENS.WORKSPACE_DUPLICATE.ROOT,
        SCREENS.WORKSPACES_VERIFY_DOMAIN,
        SCREENS.WORKSPACES_DOMAIN_VERIFIED,
        SCREENS.WORKSPACES_ADD_DOMAIN,
        SCREENS.WORKSPACES_ADD_DOMAIN_VERIFY_ACCOUNT,
        SCREENS.WORKSPACES_DOMAIN_ADDED,
        SCREENS.WORKSPACES_DOMAIN_ACCESS_RESTRICTED,
    ],
};

export default WORKSPACES_LIST_TO_RHP;
