import SCREENS from '@src/SCREENS';

const WORKSPACES_LIST_TO_RHP: Record<typeof SCREENS.WORKSPACES_LIST, string[]> = {
    [SCREENS.WORKSPACES_LIST]: [SCREENS.WORKSPACE_DUPLICATE.SELECT_FEATURES, SCREENS.WORKSPACE_DUPLICATE.ROOT, SCREENS.WORKSPACES_VERIFY_DOMAIN, SCREENS.WORKSPACES_DOMAIN_VERIFIED],
};

export default WORKSPACES_LIST_TO_RHP;
