// export {default as MoneyReceipts} from '@assets/images/simple-illustrations/simple-illustration__money-receipts.svg';
// export {default as PinkBill} from '@assets/images/simple-illustrations/simple-illustration__bill.svg';
// export {default as InvoiceBlue} from '@assets/images/simple-illustrations/simple-illustration__invoice.svg';
// // export {default as InvoiceOrange} from '@assets/images/simple-illustrations/simple-illustration__invoice-orange.svg';
// export {default as SplitBill} from '@assets/images/simple-illustrations/simple-illustration__splitbill.svg';
// export {default as PerDiem} from '@assets/images/simple-illustrations/simple-illustration__perdiem.svg';
// export {default as Accounting} from '@assets/images/simple-illustrations/simple-illustration__accounting.svg';
// export {default as RealtimeReport} from '@assets/images/simple-illustrations/simple-illustration__realtimereports.svg';
// export {default as Approval} from '@assets/images/simple-illustrations/simple-illustration__approval.svg';
// export {default as Workflows} from '@assets/images/simple-illustrations/simple-illustration__workflows.svg';
// export {default as Rules} from '@assets/images/simple-illustrations/simple-illustration__rules.svg';
// export {default as Stopwatch} from '@assets/images/simple-illustrations/simple-illustration__stopwatch.svg';
// export {default as Hourglass} from '@assets/images/simple-illustrations/simple-illustration__hourglass.svg';
// export {default as RunningTurtle} from '@assets/images/running-turtle.svg';
// export {default as CommentBubbles} from '@assets/images/simple-illustrations/simple-illustration__commentbubbles.svg';
// export {default as CommentBubblesBlue} from '@assets/images/simple-illustrations/simple-illustration__commentbubbles_blue.svg';
// export {default as ThumbsUpStars} from '@assets/images/simple-illustrations/simple-illustration__thumbsupstars.svg';
// export {default as MoneyBadge} from '@assets/images/simple-illustrations/simple-illustration__moneybadge.svg';
// export {default as MoneyWings} from '@assets/images/simple-illustrations/simple-illustration__moneywings.svg';
// export {default as MoneyIntoWallet} from '@assets/images/simple-illustrations/simple-illustration__moneyintowallet.svg';
// export {default as BankArrow} from '@assets/images/simple-illustrations/simple-illustration__bank-arrow.svg';
// // export {default as BankArrowPink} from '@assets/images/simple-illustrations/simple-illustration__bank-arrow-pink.svg';
// // export {default as BankMouseGreen} from '@assets/images/simple-illustrations/simple-illustration__bank-mouse-green.svg';
// // export {default as BankUserGreen} from '@assets/images/simple-illustrations/simple-illustration__bank-user-green.svg';
// export {default as ConciergeBubble} from '@assets/images/simple-illustrations/simple-illustration__concierge-bubble.svg';
// export {default as ConciergeNew} from '@assets/images/simple-illustrations/simple-illustration__concierge.svg';
// // export {default as ConciergeBlue} from '@assets/images/simple-illustrations/simple-illustration__concierge-blue.svg';
// //export {default as ConciergeExclamation} from '@assets/images/simple-illustrations/simple-illustration__concierge-exclamation.svg';
