import CONST from '@src/CONST';
import ACTION_FORM_INPUT_IDS from '@src/types/form/DebugReportActionForm';
import REPORT_FORM_INPUT_IDS from '@src/types/form/DebugReportForm';
import TRANSACTION_FORM_INPUT_IDS from '@src/types/form/DebugTransactionForm';
import TRANSACTION_VIOLATION_FORM_INPUT_IDS from '@src/types/form/DebugTransactionViolationForm';

const DETAILS_CONSTANT_FIELDS = {
    [CONST.DEBUG.FORMS.REPORT]: [
        REPORT_FORM_INPUT_IDS.CHAT_TYPE,
        REPORT_FORM_INPUT_IDS.CURRENCY,
        REPORT_FORM_INPUT_IDS.NOTIFICATION_PREFERENCE,
        REPORT_FORM_INPUT_IDS.TYPE,
        REPORT_FORM_INPUT_IDS.LAST_ACTION_TYPE,
        REPORT_FORM_INPUT_IDS.WRITE_CAPABILITY,
    ],
    [CONST.DEBUG.FORMS.REPORT_ACTION]: [ACTION_FORM_INPUT_IDS.ACTION_NAME],
    [CONST.DEBUG.FORMS.TRANSACTION]: [
        TRANSACTION_FORM_INPUT_IDS.IOU_REQUEST_TYPE,
        TRANSACTION_FORM_INPUT_IDS.MODIFIED_CURRENCY,
        TRANSACTION_FORM_INPUT_IDS.STATUS,
        TRANSACTION_FORM_INPUT_IDS.MCC_GROUP,
        TRANSACTION_FORM_INPUT_IDS.MODIFIED_MCC_GROUP,
    ],
    [CONST.DEBUG.FORMS.TRANSACTION_VIOLATION]: [],
} as Record<string, string[]>;

const DETAILS_CONSTANT_OPTIONS = {
    [CONST.DEBUG.FORMS.REPORT]: {
        [REPORT_FORM_INPUT_IDS.CHAT_TYPE]: CONST.REPORT.CHAT_TYPE,
        [REPORT_FORM_INPUT_IDS.CURRENCY]: CONST.CURRENCY,
        [REPORT_FORM_INPUT_IDS.NOTIFICATION_PREFERENCE]: CONST.REPORT.NOTIFICATION_PREFERENCE,
        [REPORT_FORM_INPUT_IDS.TYPE]: CONST.REPORT.TYPE,
        [REPORT_FORM_INPUT_IDS.WRITE_CAPABILITY]: CONST.REPORT.WRITE_CAPABILITIES,
        [REPORT_FORM_INPUT_IDS.LAST_ACTION_TYPE]: CONST.REPORT.ACTIONS.TYPE,
    },
    [CONST.DEBUG.FORMS.REPORT_ACTION]: {
        [ACTION_FORM_INPUT_IDS.ACTION_NAME]: CONST.REPORT.ACTIONS.TYPE,
    },
    [CONST.DEBUG.FORMS.TRANSACTION]: {
        [TRANSACTION_FORM_INPUT_IDS.IOU_REQUEST_TYPE]: CONST.IOU.REQUEST_TYPE,
        [TRANSACTION_FORM_INPUT_IDS.STATUS]: CONST.TRANSACTION.STATUS,
        [TRANSACTION_FORM_INPUT_IDS.MCC_GROUP]: CONST.MCC_GROUPS,
        [TRANSACTION_FORM_INPUT_IDS.MODIFIED_MCC_GROUP]: CONST.MCC_GROUPS,
    },
    [CONST.DEBUG.FORMS.TRANSACTION_VIOLATION]: {
        [TRANSACTION_VIOLATION_FORM_INPUT_IDS.NAME]: CONST.VIOLATIONS,
        [TRANSACTION_VIOLATION_FORM_INPUT_IDS.TYPE]: CONST.VIOLATION_TYPES,
    },
} as Record<string, Record<string, Record<string, string | Record<string, string>>>>;

const DETAILS_DATETIME_FIELDS = [
    ACTION_FORM_INPUT_IDS.CREATED,
    ACTION_FORM_INPUT_IDS.LAST_MODIFIED,
    REPORT_FORM_INPUT_IDS.LAST_READ_TIME,
    REPORT_FORM_INPUT_IDS.LAST_VISIBLE_ACTION_CREATED,
    REPORT_FORM_INPUT_IDS.LAST_VISIBLE_ACTION_LAST_MODIFIED,
    TRANSACTION_FORM_INPUT_IDS.MODIFIED_CREATED,
] as string[];

const DETAILS_DISABLED_KEYS = [
    ACTION_FORM_INPUT_IDS.REPORT_ACTION_ID,
    REPORT_FORM_INPUT_IDS.REPORT_ID,
    REPORT_FORM_INPUT_IDS.POLICY_ID,
    TRANSACTION_FORM_INPUT_IDS.TRANSACTION_ID,
] as string[];

export {DETAILS_CONSTANT_OPTIONS, DETAILS_CONSTANT_FIELDS, DETAILS_DATETIME_FIELDS, DETAILS_DISABLED_KEYS};
