import type {TupleToUnion} from 'type-fest';
import CONST from '@src/CONST';
import ACTION_FORM_INPUT_IDS from '@src/types/form/DebugReportActionForm';
import REPORT_FORM_INPUT_IDS from '@src/types/form/DebugReportForm';
import TRANSACTION_FORM_INPUT_IDS from '@src/types/form/DebugTransactionForm';

const DETAILS_CONSTANT_OPTIONS = {
    [REPORT_FORM_INPUT_IDS.CHAT_TYPE]: CONST.REPORT.CHAT_TYPE,
    [REPORT_FORM_INPUT_IDS.CURRENCY]: CONST.CURRENCY,
    [REPORT_FORM_INPUT_IDS.NOTIFICATION_PREFERENCE]: CONST.REPORT.NOTIFICATION_PREFERENCE,
    [REPORT_FORM_INPUT_IDS.TYPE]: CONST.REPORT.TYPE,
    [REPORT_FORM_INPUT_IDS.WRITE_CAPABILITY]: CONST.REPORT.WRITE_CAPABILITIES,
    [REPORT_FORM_INPUT_IDS.LAST_ACTION_TYPE]: CONST.REPORT.ACTIONS.TYPE,
    [ACTION_FORM_INPUT_IDS.ACTION_NAME]: CONST.REPORT.ACTIONS.TYPE,
    [TRANSACTION_FORM_INPUT_IDS.IOU_REQUEST_TYPE]: CONST.IOU.REQUEST_TYPE,
    [TRANSACTION_FORM_INPUT_IDS.STATUS]: CONST.TRANSACTION.STATUS,
    [TRANSACTION_FORM_INPUT_IDS.MCC_GROUP]: CONST.MCC_GROUPS,
    [TRANSACTION_FORM_INPUT_IDS.MODIFIED_MCC_GROUP]: CONST.MCC_GROUPS,
};

const DETAILS_CONSTANT_FIELDS = [
    ACTION_FORM_INPUT_IDS.ACTION_NAME,
    REPORT_FORM_INPUT_IDS.CHAT_TYPE,
    REPORT_FORM_INPUT_IDS.CURRENCY,
    REPORT_FORM_INPUT_IDS.NOTIFICATION_PREFERENCE,
    REPORT_FORM_INPUT_IDS.TYPE,
    REPORT_FORM_INPUT_IDS.LAST_ACTION_TYPE,
    REPORT_FORM_INPUT_IDS.WRITE_CAPABILITY,
    TRANSACTION_FORM_INPUT_IDS.IOU_REQUEST_TYPE,
    TRANSACTION_FORM_INPUT_IDS.MODIFIED_CURRENCY,
    TRANSACTION_FORM_INPUT_IDS.STATUS,
    TRANSACTION_FORM_INPUT_IDS.MCC_GROUP,
    TRANSACTION_FORM_INPUT_IDS.MODIFIED_MCC_GROUP,
];

const DETAILS_DATETIME_FIELDS = [
    ACTION_FORM_INPUT_IDS.CREATED,
    ACTION_FORM_INPUT_IDS.LAST_MODIFIED,
    REPORT_FORM_INPUT_IDS.LAST_READ_TIME,
    REPORT_FORM_INPUT_IDS.LAST_VISIBLE_ACTION_CREATED,
    REPORT_FORM_INPUT_IDS.LAST_VISIBLE_ACTION_LAST_MODIFIED,
    TRANSACTION_FORM_INPUT_IDS.MODIFIED_CREATED,
];

const DETAILS_DISABLED_KEYS = [ACTION_FORM_INPUT_IDS.REPORT_ACTION_ID, REPORT_FORM_INPUT_IDS.REPORT_ID, REPORT_FORM_INPUT_IDS.POLICY_ID, TRANSACTION_FORM_INPUT_IDS.TRANSACTION_ID];

type DetailsConstantFieldsKeys = TupleToUnion<typeof DETAILS_CONSTANT_FIELDS>;

type DetailsDatetimeFieldsKeys = TupleToUnion<typeof DETAILS_DATETIME_FIELDS>;
type DetailsDisabledKeys = TupleToUnion<typeof DETAILS_DISABLED_KEYS>;

export type {DetailsConstantFieldsKeys, DetailsDatetimeFieldsKeys, DetailsDisabledKeys};
export {DETAILS_CONSTANT_OPTIONS, DETAILS_CONSTANT_FIELDS, DETAILS_DATETIME_FIELDS, DETAILS_DISABLED_KEYS};
