import SCREENS from '@src/SCREENS';

const SCREENS_WITH_AUTOFOCUS: string[] = [
    SCREENS.WORKSPACE_SWITCHER.ROOT,
    SCREENS.SEARCH_ROOT,
    SCREENS.REPORT,
    SCREENS.REPORT_DESCRIPTION_ROOT,
    SCREENS.PRIVATE_NOTES.EDIT,
    SCREENS.SETTINGS.PROFILE.STATUS,
    SCREENS.SETTINGS.PROFILE.PRONOUNS,
    SCREENS.NEW_TASK.DETAILS,
    SCREENS.MONEY_REQUEST.CREATE,
];

export default SCREENS_WITH_AUTOFOCUS;
