import getSplashBackgroundColor from '@libs/getSplashBackgroundColor';
import colors from '@styles/theme/colors';
import type {ThemeColors} from '@styles/theme/types';
import CONST from '@src/CONST';
import SCREENS from '@src/SCREENS';

const darkTheme = {
    appBG: colors.productDark100 ?? '#FFFFFF',
    splashBG: getSplashBackgroundColor() ?? '#FFFFFF',
    highlightBG: colors.productDark200 ?? '#FFFFFF',
    border: colors.productDark400 ?? '#FFFFFF',
    borderLighter: colors.productDark400 ?? '#FFFFFF',
    borderFocus: colors.green400 ?? '#FFFFFF',
    icon: colors.productDark700 ?? '#FFFFFF',
    iconMenu: colors.green400 ?? '#FFFFFF',
    iconHovered: colors.productDark900 ?? '#FFFFFF',
    iconMenuHovered: colors.green400 ?? '#FFFFFF',
    iconSuccessFill: colors.green400 ?? '#FFFFFF',
    iconDangerFill: colors.red ?? '#FFFFFF',
    iconReversed: colors.productDark100 ?? '#FFFFFF',
    iconColorfulBackground: `${colors.ivory ?? '#FFFFFF'}cc`,
    textSupporting: colors.productDark800 ?? '#FFFFFF',
    text: colors.productDark900 ?? '#FFFFFF',
    textColorfulBackground: colors.ivory ?? '#FFFFFF',
    syntax: colors.productDark800 ?? '#FFFFFF',
    link: colors.blue300 ?? '#FFFFFF',
    linkHover: colors.blue100 ?? '#FFFFFF',
    buttonDefaultBG: colors.productDark400 ?? '#FFFFFF',
    buttonHoveredBG: colors.productDark500 ?? '#FFFFFF',
    buttonPressedBG: colors.productDark600 ?? '#FFFFFF',
    buttonSuccessText: colors.productLight100 ?? '#FFFFFF',
    danger: colors.red ?? '#FFFFFF',
    dangerHover: colors.redHover ?? '#FFFFFF',
    dangerPressed: colors.redHover ?? '#FFFFFF',
    warning: colors.yellow400 ?? '#FFFFFF',
    success: colors.green400 ?? '#FFFFFF',
    successHover: colors.greenHover ?? '#FFFFFF',
    successPressed: colors.greenPressed ?? '#FFFFFF',
    transparent: colors.transparent ?? '#FFFFFF',
    signInPage: colors.green800 ?? '#FFFFFF',
    darkSupportingText: colors.productDark800 ?? '#FFFFFF',

    // Additional keys
    overlay: colors.productDark400 ?? '#FFFFFF',
    inverse: colors.productDark900 ?? '#FFFFFF',
    shadow: colors.black ?? '#FFFFFF',
    componentBG: colors.productDark100 ?? '#FFFFFF',
    hoverComponentBG: colors.productDark300 ?? '#FFFFFF',
    messageHighlightBG: colors.messageHighlightDark ?? '#FFFFFF',
    activeComponentBG: colors.productDark400 ?? '#FFFFFF',
    signInSidebar: colors.green800 ?? '#FFFFFF',
    sidebar: colors.productDark100 ?? '#FFFFFF',
    sidebarHover: colors.productDark300 ?? '#FFFFFF',
    heading: colors.productDark900 ?? '#FFFFFF',
    textLight: colors.productDark900 ?? '#FFFFFF',
    textDark: colors.productDark100 ?? '#FFFFFF',
    textReversed: colors.productLight900 ?? '#FFFFFF',
    textBackground: colors.productDark200 ?? '#FFFFFF',
    textMutedReversed: colors.productDark700 ?? '#FFFFFF',
    textError: colors.red ?? '#FFFFFF',
    offline: colors.productDark700 ?? '#FFFFFF',
    modalBackground: colors.productDark100 ?? '#FFFFFF',
    cardBG: colors.productDark200 ?? '#FFFFFF',
    cardBorder: colors.productDark200 ?? '#FFFFFF',
    spinner: colors.productDark800 ?? '#FFFFFF',
    unreadIndicator: colors.green400 ?? '#FFFFFF',
    placeholderText: colors.productDark700 ?? '#FFFFFF',
    heroCard: colors.blue400 ?? '#FFFFFF',
    uploadPreviewActivityIndicator: colors.productDark200 ?? '#FFFFFF',
    dropUIBG: 'rgba(6,27,9,0.92)',
    receiptDropUIBG: 'rgba(3, 212, 124, 0.84)',
    checkBox: colors.green400 ?? '#FFFFFF',
    imageCropBackgroundColor: colors.productDark700 ?? '#FFFFFF',
    fallbackIconColor: colors.green700 ?? '#FFFFFF',
    reactionActiveBackground: colors.green600 ?? '#FFFFFF',
    reactionActiveText: colors.green100 ?? '#FFFFFF',
    badgeAdHoc: colors.pink600 ?? '#FFFFFF',
    badgeAdHocHover: colors.pink700 ?? '#FFFFFF',
    mentionText: colors.blue100 ?? '#FFFFFF',
    mentionBG: colors.blue600 ?? '#FFFFFF',
    ourMentionText: colors.green100 ?? '#FFFFFF',
    ourMentionBG: colors.green600 ?? '#FFFFFF',
    tooltipSupportingText: colors.productLight800 ?? '#FFFFFF',
    tooltipPrimaryText: colors.productLight900 ?? '#FFFFFF',
    skeletonLHNIn: colors.productDark400 ?? '#FFFFFF',
    skeletonLHNOut: colors.productDark600 ?? '#FFFFFF',
    QRLogo: colors.green400 ?? '#FFFFFF',
    starDefaultBG: 'rgb(254, 228, 94)',
    mapAttributionText: colors.black ?? '#FFFFFF',
    white: colors.white ?? '#FFFFFF',
    videoPlayerBG: `${colors.productDark100 ?? '#FFFFFF'}cc`,
    transparentWhite: `${colors.white ?? '#FFFFFF'}51`,

    // Adding a color here will animate the status bar to the right color when the screen is opened.
    PAGE_THEMES: {
        [SCREENS.HOME]: {
            backgroundColor: colors.productDark100 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.REPORT]: {
            backgroundColor: colors.productDark100 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.SAVE_THE_WORLD.ROOT]: {
            backgroundColor: colors.tangerine800 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.SETTINGS.PREFERENCES.ROOT]: {
            backgroundColor: colors.productDark100 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.SETTINGS.WORKSPACES]: {
            backgroundColor: colors.productDark100 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.SETTINGS.WALLET.ROOT]: {
            backgroundColor: colors.productDark100 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.SETTINGS.PROFILE.STATUS]: {
            backgroundColor: colors.productDark100 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.SETTINGS.ROOT]: {
            backgroundColor: colors.productDark100 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.LEFT_MODAL.WORKSPACE_SWITCHER]: {
            backgroundColor: colors.productDark100 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.SETTINGS.TROUBLESHOOT]: {
            backgroundColor: colors.blue700 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.REFERRAL_DETAILS]: {
            backgroundColor: colors.pink800 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        [SCREENS.RIGHT_MODAL.SIGN_IN]: {
            backgroundColor: colors.productDark200 ?? '#FFFFFF',
            statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
    },

    statusBarStyle: CONST.STATUS_BAR_STYLE.LIGHT_CONTENT,
    colorScheme: CONST.COLOR_SCHEME.DARK,
} satisfies ThemeColors;

export default darkTheme;
