"use strict";
var _a;
Object.defineProperty(exports, "__esModule", { value: true });
var colors_1 = require("@styles/theme/colors");
var CONST_1 = require("@src/CONST");
var SCREENS_1 = require("@src/SCREENS");
var darkTheme = {
    // Figma keys
    appBG: colors_1.default.productDark100,
    splashBG: colors_1.default.green400,
    highlightBG: colors_1.default.productDark200,
    border: colors_1.default.productDark400,
    borderLighter: colors_1.default.productDark400,
    borderFocus: colors_1.default.green400,
    icon: colors_1.default.productDark700,
    iconMenu: colors_1.default.green400,
    iconHovered: colors_1.default.productDark900,
    iconMenuHovered: colors_1.default.green400,
    iconSuccessFill: colors_1.default.green400,
    iconDangerFill: colors_1.default.red,
    iconReversed: colors_1.default.productDark100,
    iconColorfulBackground: "".concat(colors_1.default.ivory, "cc"),
    textSupporting: colors_1.default.productDark800,
    text: colors_1.default.productDark900,
    textColorfulBackground: colors_1.default.ivory,
    textReceiptDropZone: colors_1.default.green700,
    textAttachmentDropZone: colors_1.default.blue700,
    syntax: colors_1.default.productDark800,
    link: colors_1.default.blue300,
    linkHover: colors_1.default.blue100,
    buttonDefaultBG: colors_1.default.productDark400,
    buttonHoveredBG: colors_1.default.productDark500,
    buttonPressedBG: colors_1.default.productDark600,
    buttonSuccessText: colors_1.default.productLight100,
    danger: colors_1.default.red,
    dangerHover: colors_1.default.redHover,
    dangerPressed: colors_1.default.redHover,
    warning: colors_1.default.yellow400,
    success: colors_1.default.green400,
    successHover: colors_1.default.greenHover,
    successPressed: colors_1.default.greenPressed,
    transparent: colors_1.default.transparent,
    signInPage: colors_1.default.green800,
    darkSupportingText: colors_1.default.productDark800,
    // Additional keys
    overlay: colors_1.default.productDark400,
    inverse: colors_1.default.productDark900,
    shadow: '0px 4px 12px 0px rgba(2,18,4,0.24)',
    componentBG: colors_1.default.productDark100,
    hoverComponentBG: colors_1.default.productDark300,
    messageHighlightBG: colors_1.default.messageHighlightDark,
    activeComponentBG: colors_1.default.productDark400,
    signInSidebar: colors_1.default.green800,
    sidebar: colors_1.default.productDark100,
    sidebarHover: colors_1.default.productDark300,
    heading: colors_1.default.productDark900,
    textLight: colors_1.default.productDark900,
    textDark: colors_1.default.productDark100,
    textReversed: colors_1.default.productLight900,
    textBackground: colors_1.default.productDark200,
    textMutedReversed: colors_1.default.productDark700,
    textError: colors_1.default.red,
    offline: colors_1.default.productDark700,
    modalBackground: colors_1.default.productDark100,
    cardBG: colors_1.default.productDark200,
    cardBorder: colors_1.default.productDark200,
    spinner: colors_1.default.productDark800,
    unreadIndicator: colors_1.default.green400,
    placeholderText: colors_1.default.productDark700,
    heroCard: colors_1.default.blue400,
    uploadPreviewActivityIndicator: colors_1.default.productDark200,
    dropUIBG: 'rgba(6,27,9,0.92)',
    dropWrapperBG: 'rgba(26, 61, 50, 0.72)',
    fileDropUIBG: 'rgba(3, 212, 124, 0.84)',
    attachmentDropUIBG: 'rgba(90, 176, 255, 0.8)',
    attachmentDropUIBGActive: 'rgba(90, 176, 255, 96)',
    attachmentDropBorderColor: 'rgba(176, 217, 255, 0)',
    attachmentDropBorderColorActive: colors_1.default.blue100,
    receiptDropUIBG: 'rgba(3, 212, 124, 0.8)',
    receiptDropUIBGActive: 'rgba(3, 212, 124, 96)',
    receiptDropBorderColor: 'rgba(177, 242, 214, 0)',
    receiptDropBorderColorActive: colors_1.default.green100,
    checkBox: colors_1.default.green400,
    imageCropBackgroundColor: colors_1.default.productDark700,
    fallbackIconColor: colors_1.default.green700,
    reactionActiveBackground: colors_1.default.green600,
    reactionActiveText: colors_1.default.green100,
    badgeAdHoc: colors_1.default.pink600,
    badgeAdHocHover: colors_1.default.pink700,
    mentionText: colors_1.default.blue100,
    mentionBG: colors_1.default.blue600,
    ourMentionText: colors_1.default.green100,
    ourMentionBG: colors_1.default.green600,
    tooltipHighlightBG: colors_1.default.green100,
    tooltipHighlightText: colors_1.default.green400,
    tooltipSupportingText: colors_1.default.productLight800,
    tooltipPrimaryText: colors_1.default.productLight900,
    trialBannerBackgroundColor: colors_1.default.green700,
    skeletonLHNIn: colors_1.default.productDark400,
    skeletonLHNOut: colors_1.default.productDark600,
    QRLogo: colors_1.default.green400,
    starDefaultBG: 'rgb(254, 228, 94)',
    mapAttributionText: colors_1.default.black,
    white: colors_1.default.white,
    videoPlayerBG: "".concat(colors_1.default.productDark100, "cc"),
    transparentWhite: "".concat(colors_1.default.white, "51"),
    emptyFolderBG: colors_1.default.yellow600,
    travelBG: colors_1.default.blue600,
    todoBG: colors_1.default.blue800,
    trialTimer: colors_1.default.green500,
    // Adding a color here will animate the status bar to the right color when the screen is opened.
    // Note that it needs to be a screen name, not a route url.
    // The route urls from ROUTES.ts are only used for deep linking and configuring URLs on web.
    // The screen name (see SCREENS.ts) is the name of the screen as far as react-navigation is concerned, and the linkingConfig maps screen names to URLs
    PAGE_THEMES: (_a = {},
        _a[SCREENS_1.default.HOME] = {
            backgroundColor: colors_1.default.productDark100,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.REPORT] = {
            backgroundColor: colors_1.default.productDark100,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.SAVE_THE_WORLD.ROOT] = {
            backgroundColor: colors_1.default.tangerine800,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.SETTINGS.PREFERENCES.ROOT] = {
            backgroundColor: colors_1.default.productDark100,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.WORKSPACES_LIST] = {
            backgroundColor: colors_1.default.productDark100,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.SETTINGS.WALLET.ROOT] = {
            backgroundColor: colors_1.default.productDark100,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.SETTINGS.PROFILE.STATUS] = {
            backgroundColor: colors_1.default.productDark100,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.SETTINGS.ROOT] = {
            backgroundColor: colors_1.default.productDark100,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.SETTINGS.TROUBLESHOOT] = {
            backgroundColor: colors_1.default.productDark100,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.REFERRAL_DETAILS] = {
            backgroundColor: colors_1.default.pink800,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a[SCREENS_1.default.RIGHT_MODAL.SIGN_IN] = {
            backgroundColor: colors_1.default.productDark200,
            statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
        },
        _a),
    statusBarStyle: CONST_1.default.STATUS_BAR_STYLE.LIGHT_CONTENT,
    navigationBarButtonsStyle: CONST_1.default.NAVIGATION_BAR_BUTTONS_STYLE.LIGHT,
    translucentNavigationBarBackgroundColor: "".concat(colors_1.default.productDark100, "CD"), // CD is 80% opacity (80% of 0xFF)
    colorScheme: CONST_1.default.COLOR_SCHEME.DARK,
};
exports.default = darkTheme;
