import SCREENS from '@src/SCREENS';

const CENTRAL_PANE_SCREEN_NAMES = [
    SCREENS.SETTINGS.WORKSPACES,
    SCREENS.SETTINGS.PREFERENCES.ROOT,
    SCREENS.SETTINGS.SECURITY,
    SCREENS.SETTINGS.PROFILE.ROOT,
    SCREENS.SETTINGS.WALLET.ROOT,
    SCREENS.SETTINGS.ABOUT,
    SCREENS.SETTINGS.TROUBLESHOOT,
    SCREENS.SETTINGS.SAVE_THE_WORLD,
    SCREENS.REPORT,
    SCREENS.SEARCH.CENTRAL_PANE,
];

export default CENTRAL_PANE_SCREEN_NAMES;
