/* eslint-disable @typescript-eslint/naming-convention */
import Onyx from 'react-native-onyx';
import {handleActionButtonPress} from '@libs/actions/Search';
import ONYXKEYS from '@src/ONYXKEYS';
import waitForBatchedUpdates from '../../utils/waitForBatchedUpdates';

const currentSearchHash = 1;
const mockData = {
    key: `${ONYXKEYS.COLLECTION.SNAPSHOT}${1}`,
    onyxMethod: 'set',
    value: {
        data: {
            report_1350959062018695: {
                accountID: 1206,
                action: 'view',
                chatReportID: '2108006919825366',
                chatType: '',
                created: '2024-12-04 23:18:33',
                currency: 'USD',
                invoiceReceiver: null,
                isOneTransactionReport: false,
                isPolicyExpenseChat: false,
                isWaitingOnBankAccount: false,
                managerID: 1206,
                nonReimbursableTotal: 0,
                ownerAccountID: 1206,
                policyID: '48D7178DE42EE9F9',
                private_isArchived: '',
                reportID: '1350959062018695',
                reportName: 'Expense Report #1350959062018695',
                stateNum: 1,
                statusNum: 1,
                total: -13500,
                type: 'expense',
                unheldTotal: -12300,
            },
            transactions_1049531721038862176: {
                accountID: 1206,
                action: 'view',
                amount: -1200,
                canDelete: true,
                canHold: false,
                canUnhold: true,
                category: '',
                comment: {
                    comment: '',
                    hold: '3042630993757922770',
                },
                created: '2024-12-04',
                currency: 'USD',
                hasEReceipt: false,
                isFromOneTransactionReport: false,
                managerID: 1206,
                merchant: 'qewr',
                modifiedAmount: 0,
                modifiedCreated: '',
                modifiedCurrency: '',
                modifiedMerchant: '',
                parentTransactionID: '',
                policyID: '48D7178DE42EE9F9',
                reportID: '1350959062018695',
                reportType: 'expense',
                tag: '',
                transactionID: '1049531721038862176',
                transactionThreadReportID: '2957345659269055',
                transactionType: 'cash',
            },
            transactions_5345995386715609966: {
                accountID: 1206,
                action: 'view',
                amount: -12300,
                canDelete: true,
                canHold: true,
                canUnhold: false,
                category: '',
                comment: {
                    comment: '',
                },
                created: '2024-12-04',
                currency: 'USD',
                hasEReceipt: false,
                isFromOneTransactionReport: false,
                managerID: 1206,
                merchant: 'fgdfgadfaf',
                modifiedAmount: 0,
                modifiedCreated: '',
                modifiedCurrency: '',
                modifiedMerchant: '',
                parentTransactionID: '',
                policyID: '48D7178DE42EE9F9',
                reportID: '1350959062018695',
                reportType: 'expense',
                tag: '',
                transactionID: '5345995386715609966',
                transactionThreadReportID: '740282333335072',
                transactionType: 'cash',
            },
        },
    },
};

describe('handleActionButtonPress', () => {
    beforeAll(() => {
        Onyx.init({
            keys: ONYXKEYS,
            initialKeyStates: mockData,
        });
        return waitForBatchedUpdates();
    });

    test('returns ', () => {
        const goToItem = () => {};
        const reportItem = {
            shouldAnimateInHighlight: false,
            accountID: 1206,
            action: 'approve',
            chatReportID: '2108006919825366',
            chatType: '',
            created: '2024-12-04 23:18:33',
            currency: 'USD',
            isOneTransactionReport: false,
            isPolicyExpenseChat: false,
            isWaitingOnBankAccount: false,
            managerID: 1206,
            nonReimbursableTotal: 0,
            ownerAccountID: 1206,
            policyID: '48D7178DE42EE9F9',
            private_isArchived: '',
            reportID: '1350959062018695',
            reportName: 'Expense Report #1350959062018695',
            stateNum: 1,
            statusNum: 1,
            total: -13500,
            type: 'expense',
            unheldTotal: -12300,
            keyForList: '1350959062018695',
            from: {
                accountID: 1206,
                avatar: 'https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_7.png',
                displayName: 'aesf',
                firstName: 'aesf',
                lastName: '',
                login: 'apb@apb.com',
                pronouns: '',
                timezone: {
                    automatic: true,
                    selected: 'America/Edmonton',
                },
                phoneNumber: '',
                validated: false,
            },
            to: {
                accountID: 1206,
                avatar: 'https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_7.png',
                displayName: 'aesf',
                firstName: 'aesf',
                lastName: '',
                login: 'apb@apb.com',
                pronouns: '',
                timezone: {
                    automatic: true,
                    selected: 'America/Edmonton',
                },
                phoneNumber: '',
                validated: false,
            },
            transactions: [
                {
                    accountID: 1206,
                    action: 'view',
                    amount: -1200,
                    canDelete: true,
                    canHold: false,
                    canUnhold: true,
                    category: '',
                    comment: {
                        comment: '',
                        hold: '3042630993757922770',
                    },
                    created: '2024-12-04',
                    currency: 'USD',
                    hasEReceipt: false,
                    isFromOneTransactionReport: false,
                    managerID: 1206,
                    merchant: 'qewr',
                    modifiedAmount: 0,
                    modifiedCreated: '',
                    modifiedCurrency: '',
                    modifiedMerchant: '',
                    parentTransactionID: '',
                    policyID: '48D7178DE42EE9F9',
                    reportID: '1350959062018695',
                    reportType: 'expense',
                    tag: '',
                    transactionID: '1049531721038862176',
                    transactionThreadReportID: '2957345659269055',
                    transactionType: 'cash',
                    from: {
                        accountID: 1206,
                        avatar: 'https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_7.png',
                        displayName: 'aesf',
                        firstName: 'aesf',
                        lastName: '',
                        login: 'apb@apb.com',
                        pronouns: '',
                        timezone: {
                            automatic: true,
                            selected: 'America/Edmonton',
                        },
                        phoneNumber: '',
                        validated: false,
                    },
                    to: {
                        accountID: 1206,
                        avatar: 'https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_7.png',
                        displayName: 'aesf',
                        firstName: 'aesf',
                        lastName: '',
                        login: 'apb@apb.com',
                        pronouns: '',
                        timezone: {
                            automatic: true,
                            selected: 'America/Edmonton',
                        },
                        phoneNumber: '',
                        validated: false,
                    },
                    formattedFrom: 'aesf',
                    formattedTo: 'aesf',
                    formattedTotal: 1200,
                    formattedMerchant: 'qewr',
                    date: '2024-12-04',
                    shouldShowMerchant: true,
                    shouldShowCategory: true,
                    shouldShowTag: false,
                    shouldShowTax: false,
                    keyForList: '1049531721038862176',
                    shouldShowYear: false,
                    shouldAnimateInHighlight: false,
                },
                {
                    accountID: 1206,
                    action: 'view',
                    amount: -12300,
                    canDelete: true,
                    canHold: true,
                    canUnhold: false,
                    category: '',
                    comment: {
                        comment: '',
                    },
                    created: '2024-12-04',
                    currency: 'USD',
                    hasEReceipt: false,
                    isFromOneTransactionReport: false,
                    managerID: 1206,
                    merchant: 'fgdfgadfaf',
                    modifiedAmount: 0,
                    modifiedCreated: '',
                    modifiedCurrency: '',
                    modifiedMerchant: '',
                    parentTransactionID: '',
                    policyID: '48D7178DE42EE9F9',
                    reportID: '1350959062018695',
                    reportType: 'expense',
                    tag: '',
                    transactionID: '5345995386715609966',
                    transactionThreadReportID: '740282333335072',
                    transactionType: 'cash',
                    from: {
                        accountID: 1206,
                        avatar: 'https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_7.png',
                        displayName: 'aesf',
                        firstName: 'aesf',
                        lastName: '',
                        login: 'apb@apb.com',
                        pronouns: '',
                        timezone: {
                            automatic: true,
                            selected: 'America/Edmonton',
                        },
                        phoneNumber: '',
                        validated: false,
                    },
                    to: {
                        accountID: 1206,
                        avatar: 'https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_7.png',
                        displayName: 'aesf',
                        firstName: 'aesf',
                        lastName: '',
                        login: 'apb@apb.com',
                        pronouns: '',
                        timezone: {
                            automatic: true,
                            selected: 'America/Edmonton',
                        },
                        phoneNumber: '',
                        validated: false,
                    },
                    formattedFrom: 'aesf',
                    formattedTo: 'aesf',
                    formattedTotal: 12300,
                    formattedMerchant: 'fgdfgadfaf',
                    date: '2024-12-04',
                    shouldShowMerchant: true,
                    shouldShowCategory: true,
                    shouldShowTag: false,
                    shouldShowTax: false,
                    keyForList: '5345995386715609966',
                    shouldShowYear: false,
                    shouldAnimateInHighlight: false,
                },
            ],
            isSelected: false,
        };
        handleActionButtonPress(currentSearchHash, reportItem, goToItem);
    });
});
