/* eslint-disable @typescript-eslint/naming-convention */
// we need "dirty" object key names in these tests
import type {OnyxCollection} from 'react-native-onyx';
import {generatePolicyID} from '@libs/actions/Policy/Policy';
// eslint-disable-next-line no-restricted-syntax
import type * as PersonalDetailsUtils from '@libs/PersonalDetailsUtils';
import CONST from '@src/CONST';
import {
    buildFilterFormValuesFromQuery,
    buildQueryStringFromFilterFormValues,
    buildSearchQueryJSON,
    buildSearchQueryString,
    buildUserReadableQueryString,
    getFilterDisplayValue,
    getQueryWithUpdatedValues,
    shouldHighlight,
    shouldResetSortOrder,
    sortOptionsWithEmptyValue,
} from '@src/libs/SearchQueryUtils';
import ONYXKEYS from '@src/ONYXKEYS';
import type {SearchAdvancedFiltersForm} from '@src/types/form';
import type * as OnyxTypes from '@src/types/onyx';
import {localeCompare, translateLocal} from '../../utils/TestHelper';

const personalDetailsFakeData = {
    'johndoe@example.com': {
        accountID: 12345,
    },
    'janedoe@example.com': {
        accountID: 78901,
    },
} as Record<string, {accountID: number}>;

jest.mock('@libs/SearchParser/searchParser', () => {
    const actual = jest.requireActual<{parse: (...args: unknown[]) => unknown}>('@libs/SearchParser/searchParser');
    return {
        ...actual,
        parse: jest.fn(actual.parse),
    };
});

jest.mock('@libs/PersonalDetailsUtils', () => {
    const actual = jest.requireActual<typeof PersonalDetailsUtils>('@libs/PersonalDetailsUtils');
    return {
        ...actual,
        getPersonalDetailByEmail(email: string) {
            return personalDetailsFakeData[email];
        },
    };
});

// The default query is generated by default values from parser, which are defined in grammar.
// We don't want to test or mock the grammar and the parser, so we're simply defining this string directly here.
// Note: view:table is not included because it's only added when explicitly set by the user.
const defaultQuery = `type:expense sortBy:date sortOrder:desc`;

describe('SearchQueryUtils', () => {
    describe('getQueryWithUpdatedValues', () => {
        test('returns default query for empty value', () => {
            const userQuery = '';

            const result = getQueryWithUpdatedValues(userQuery);

            expect(result).toEqual(defaultQuery);
        });

        test('returns query with updated amounts', () => {
            const userQuery = 'foo test amount:20000';

            const result = getQueryWithUpdatedValues(userQuery);

            expect(result).toEqual(`${defaultQuery} amount:2000000 foo test`);
        });

        test('returns query with user emails substituted', () => {
            const userQuery = 'from:johndoe@example.com hello';

            const result = getQueryWithUpdatedValues(userQuery);

            expect(result).toEqual(`${defaultQuery} from:12345 hello`);
        });

        test('returns query with user emails substituted and preserves user ids', () => {
            const userQuery = 'from:johndoe@example.com to:112233';

            const result = getQueryWithUpdatedValues(userQuery);

            expect(result).toEqual(`${defaultQuery} from:12345 to:112233`);
        });

        test('returns query with all of the fields correctly substituted', () => {
            const userQuery = 'from:9876,87654 to:janedoe@example.com hello amount:150 test';

            const result = getQueryWithUpdatedValues(userQuery);

            expect(result).toEqual(`${defaultQuery} from:9876,87654 to:78901 amount:15000 hello test`);
        });

        test('returns query with updated groupBy', () => {
            const userQuery = 'from:johndoe@example.com groupBy:reports';

            const result = getQueryWithUpdatedValues(userQuery);

            expect(result).toEqual(`${defaultQuery} groupBy:reports from:12345`);
        });

        test('returns query with updated view', () => {
            const userQuery = 'from:johndoe@example.com view:bar';

            const result = getQueryWithUpdatedValues(userQuery);

            expect(result).toEqual('type:expense sortBy:groupCategory sortOrder:asc view:bar groupBy:category from:12345');
        });

        test('returns query with view:line', () => {
            const userQuery = 'type:expense view:line category:travel';

            const result = getQueryWithUpdatedValues(userQuery);

            expect(result).toEqual('type:expense sortBy:groupmonth sortOrder:asc view:line groupBy:month category:travel');
        });

        test('returns query with view:pie', () => {
            const userQuery = 'type:expense view:pie merchant:Amazon';

            const result = getQueryWithUpdatedValues(userQuery);

            expect(result).toEqual('type:expense sortBy:groupCategory sortOrder:asc view:pie groupBy:category merchant:Amazon');
        });

        test('deduplicates conflicting type filters keeping the last occurrence', () => {
            const userQuery = 'type:expense-report action:submit from:me type:expense';

            const result = getQueryWithUpdatedValues(userQuery);
            expect(result).toEqual(`${defaultQuery} action:submit from:me`);

            const queryJSON = buildSearchQueryJSON(result ?? '', userQuery);
            expect(queryJSON?.rawFilterList).toEqual([
                {key: CONST.SEARCH.SYNTAX_FILTER_KEYS.ACTION, operator: CONST.SEARCH.SYNTAX_OPERATORS.EQUAL_TO, value: 'submit', isDefault: false},
                {key: CONST.SEARCH.SYNTAX_FILTER_KEYS.FROM, operator: CONST.SEARCH.SYNTAX_OPERATORS.EQUAL_TO, value: 'me', isDefault: false},
                {key: CONST.SEARCH.SYNTAX_FILTER_KEYS.TYPE, operator: CONST.SEARCH.SYNTAX_OPERATORS.EQUAL_TO, value: CONST.SEARCH.DATA_TYPES.EXPENSE, isDefault: true},
            ]);
        });
    });

    describe('buildQueryStringFromFilterFormValues', () => {
        test('simple filter value', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                policyID: ['12345'],
                amountLessThan: '100',
            };

            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense policyID:12345 amount<100');
        });

        test('with Policy ID', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                policyID: ['12345'],
            };

            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('policyID:12345');
        });

        test('with keywords', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                policyID: ['67890'],
                merchant: 'Amazon',
                description: 'Electronics',
                keyword: 'laptop',
                category: ['electronics', 'gadgets'],
            };

            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense policyID:67890 merchant:Amazon description:Electronics laptop category:electronics,gadgets');
        });

        test('currencies and categories', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                category: ['services', 'consulting'],
                currency: ['USD', 'EUR'],
            };

            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense category:services,consulting currency:USD,EUR');
        });

        test('has empty category values', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                category: ['equipment', 'consulting', 'none,Uncategorized'],
            };

            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense category:equipment,consulting,none,Uncategorized');
        });

        test('empty filter values', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {};

            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('');
        });

        test('array of from', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                from: ['user1@gmail.com', 'user2@gmail.com'],
                to: ['user3@gmail.com'],
            };
            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense from:user1@gmail.com,user2@gmail.com to:user3@gmail.com');
        });

        test('complex filter values', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                from: ['user1@gmail.com', 'user2@gmail.com'],
                to: ['user3@gmail.com'],
                dateAfter: '2025-03-01',
                dateBefore: '2025-03-10',
                amountLessThan: '1000',
                amountGreaterThan: '1',
                category: ['finance', 'insurance'],
            };
            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense from:user1@gmail.com,user2@gmail.com to:user3@gmail.com category:finance,insurance date>2025-03-01 date<2025-03-10 amount>1 amount<1000');
            expect(result).not.toMatch(CONST.VALIDATE_FOR_HTML_TAG_REGEX);
        });

        test('total filter values', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                totalLessThan: '1000',
                totalGreaterThan: '1',
            };
            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense total>1 total<1000');
        });

        test('equal to filter values', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                amountEqualTo: '500',
                totalEqualTo: '750',
            };
            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense amount:500 total:750');
        });

        test('combined equal to and range filter values', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                amountEqualTo: '100',
                totalGreaterThan: '50',
                totalLessThan: '200',
            };
            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense amount:100 total>50 total<200');
        });

        test('with withdrawal type filter', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                withdrawalType: CONST.SEARCH.WITHDRAWAL_TYPE.EXPENSIFY_CARD,
            };

            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense withdrawalType:expensify-card');
        });

        test('with withdrawn filter', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                withdrawnOn: CONST.SEARCH.DATE_PRESETS.LAST_MONTH,
            };

            const result = buildQueryStringFromFilterFormValues(filterValues);

            expect(result).toEqual('type:expense withdrawn:last-month');
        });

        describe('limit option', () => {
            test('includes limit in query string when provided', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                };

                const result = buildQueryStringFromFilterFormValues(filterValues, {limit: 10});

                expect(result).toEqual('type:expense limit:10');
            });

            test('combines limit with sort options', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                    merchant: 'Amazon',
                };

                const result = buildQueryStringFromFilterFormValues(filterValues, {sortBy: 'amount', sortOrder: 'asc', limit: 25});

                expect(result).toEqual('sortBy:amount sortOrder:asc type:expense merchant:Amazon limit:25');
            });

            test('omits limit when not provided', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                };

                const result = buildQueryStringFromFilterFormValues(filterValues);

                expect(result).not.toContain('limit:');
            });

            test('omits limit when form value is empty string (user cleared the field)', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                    limit: '',
                };

                const result = buildQueryStringFromFilterFormValues(filterValues, {limit: 10});

                expect(result).not.toContain('limit:');
            });

            test('quotes limit value containing spaces to prevent keyword contamination', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                    keyword: 'hi',
                    limit: '10 90',
                };

                const result = buildQueryStringFromFilterFormValues(filterValues);

                expect(result).toContain('limit:"10 90"');
                expect(result).toEqual('type:expense hi limit:"10 90"');
            });

            test('limit value with spaces does not leak into keyword when round-tripped through parser', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                    keyword: 'hi',
                    limit: '10 90',
                };

                const queryString = buildQueryStringFromFilterFormValues(filterValues);
                const queryJSON = buildSearchQueryJSON(queryString);

                // "10 90" is not a valid integer, so limit is normalized to undefined
                expect(queryJSON?.limit).toBeUndefined();

                // The keyword must NOT be contaminated with "90" from the limit value
                const keywordFilter = queryJSON?.flatFilters.find((filter) => filter.key === 'keyword');
                expect(keywordFilter?.filters).toHaveLength(1);
                expect(keywordFilter?.filters.at(0)?.value).toBe('hi');
            });
        });

        describe('view parameter', () => {
            test('with view parameter set to bar', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                    groupBy: CONST.SEARCH.GROUP_BY.CATEGORY,
                    view: CONST.SEARCH.VIEW.BAR,
                };

                const result = buildQueryStringFromFilterFormValues(filterValues);

                expect(result).toEqual('type:expense groupBy:category view:bar');
            });

            test('with view parameter set to table', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                    groupBy: CONST.SEARCH.GROUP_BY.CATEGORY,
                    view: CONST.SEARCH.VIEW.TABLE,
                };

                const result = buildQueryStringFromFilterFormValues(filterValues);

                expect(result).toEqual('type:expense groupBy:category view:table');
            });

            test('without view parameter omits view from query', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                    groupBy: CONST.SEARCH.GROUP_BY.CATEGORY,
                };

                const result = buildQueryStringFromFilterFormValues(filterValues);

                expect(result).not.toContain('view:');
            });

            test('view is omitted from query when groupBy is not set', () => {
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                    view: CONST.SEARCH.VIEW.BAR,
                };

                const result = buildQueryStringFromFilterFormValues(filterValues);

                expect(result).not.toContain('view:');
                expect(result).not.toContain('groupBy:');
            });

            test('view is omitted when groupBy is cleared but view remains in form', () => {
                // This simulates the case where groupBy was set (with view), then groupBy was reset
                // but view wasn't explicitly cleared from the form
                const filterValues: Partial<SearchAdvancedFiltersForm> = {
                    type: 'expense',
                    groupBy: undefined,
                    view: CONST.SEARCH.VIEW.BAR,
                };

                const result = buildQueryStringFromFilterFormValues(filterValues);

                expect(result).not.toContain('view:');
                expect(result).toEqual('type:expense');
            });
        });
    });

    describe('buildUserReadableQueryString', () => {
        const emptyReports: OnyxCollection<OnyxTypes.Report> = {};
        const emptyCardList: OnyxTypes.CardList = {};
        const emptyCardFeeds: OnyxCollection<OnyxTypes.CardFeeds> = {};
        const emptyPolicies: OnyxCollection<OnyxTypes.Policy> = {};
        const emptyTaxRates: Record<string, string[]> = {};
        const currentUserAccountID = 0;

        test('preserves manual filter order for raw queries', () => {
            const queryString = 'type:expense date:this-month groupBy:from tag:travel';
            const canonicalQueryString = getQueryWithUpdatedValues(queryString);

            if (!canonicalQueryString) {
                throw new Error('Failed to standardize query string');
            }

            const queryJSON = buildSearchQueryJSON(canonicalQueryString, queryString);

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            const result = buildUserReadableQueryString({
                queryJSON,
                PersonalDetails: undefined,
                reports: emptyReports,
                taxRates: emptyTaxRates,
                cardList: emptyCardList,
                cardFeeds: emptyCardFeeds,
                policies: emptyPolicies,
                currentUserAccountID,
                autoCompleteWithSpace: false,
                translate: translateLocal,
            });

            expect(result).toBe('type:expense date:this-month group-by:from tag:travel');
        });

        test('preserves status all default value from manual query', () => {
            const queryString = 'type:expense status:all merchant:Uber';
            const canonicalQueryString = getQueryWithUpdatedValues(queryString);

            if (!canonicalQueryString) {
                throw new Error('Failed to standardize query string');
            }

            const queryJSON = buildSearchQueryJSON(canonicalQueryString, queryString);

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            const result = buildUserReadableQueryString({
                queryJSON,
                PersonalDetails: undefined,
                reports: emptyReports,
                taxRates: emptyTaxRates,
                cardList: emptyCardList,
                cardFeeds: emptyCardFeeds,
                policies: emptyPolicies,
                currentUserAccountID,
                autoCompleteWithSpace: false,
                translate: translateLocal,
            });

            expect(result).toBe('type:expense status:all merchant:Uber');
        });

        test('maps workspace names and maintains manual order', () => {
            const queryString = 'policyID:123 type:expense merchant:Starbucks';
            const canonicalQueryString = getQueryWithUpdatedValues(queryString);

            if (!canonicalQueryString) {
                throw new Error('Failed to standardize query string');
            }

            const queryJSON = buildSearchQueryJSON(canonicalQueryString, queryString);
            const policies: OnyxCollection<OnyxTypes.Policy> = {
                [`${ONYXKEYS.COLLECTION.POLICY}123`]: {
                    name: 'Team Space',
                } as OnyxTypes.Policy,
            };

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            const result = buildUserReadableQueryString({
                queryJSON,
                PersonalDetails: undefined,
                reports: emptyReports,
                taxRates: emptyTaxRates,
                cardList: emptyCardList,
                cardFeeds: emptyCardFeeds,
                policies,
                currentUserAccountID,
                autoCompleteWithSpace: false,
                translate: translateLocal,
            });

            expect(result).toBe('workspace:"Team Space" type:expense merchant:Starbucks');
        });

        test('rawQuery overrides canonical filter values when provided', () => {
            const queryString = 'type:expense merchant:Uber';
            const canonicalQueryString = getQueryWithUpdatedValues(queryString);

            if (!canonicalQueryString) {
                throw new Error('Failed to standardize query string');
            }

            const overriddenRawQuery = 'type:expense merchant:Lyft';
            const queryJSON = buildSearchQueryJSON(canonicalQueryString, overriddenRawQuery);
            const merchantFilter = queryJSON?.rawFilterList?.find((filter) => filter.key === CONST.SEARCH.SYNTAX_FILTER_KEYS.MERCHANT);

            expect(merchantFilter?.value).toBe('Lyft');
        });

        test('includes limit in readable query string when present', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:25');

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            const result = buildUserReadableQueryString({
                queryJSON,
                PersonalDetails: undefined,
                reports: emptyReports,
                taxRates: emptyTaxRates,
                cardList: emptyCardList,
                cardFeeds: emptyCardFeeds,
                policies: emptyPolicies,
                currentUserAccountID,
                autoCompleteWithSpace: false,
                translate: translateLocal,
            });

            expect(result).toContain('limit:25');
        });

        test('does not include limit in readable query string when not specified', () => {
            const queryJSON = buildSearchQueryJSON('type:expense merchant:Test');

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            const result = buildUserReadableQueryString({
                queryJSON,
                PersonalDetails: undefined,
                reports: emptyReports,
                taxRates: emptyTaxRates,
                cardList: emptyCardList,
                cardFeeds: emptyCardFeeds,
                policies: emptyPolicies,
                currentUserAccountID,
                autoCompleteWithSpace: false,
                translate: translateLocal,
            });

            expect(result).not.toContain('limit:');
        });

        test('includes limit with other root parameters in readable query string', () => {
            const queryJSON = buildSearchQueryJSON('type:expense groupBy:category limit:50');

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            const result = buildUserReadableQueryString({
                queryJSON,
                PersonalDetails: undefined,
                reports: emptyReports,
                taxRates: emptyTaxRates,
                cardList: emptyCardList,
                cardFeeds: emptyCardFeeds,
                policies: emptyPolicies,
                currentUserAccountID,
                autoCompleteWithSpace: false,
                translate: translateLocal,
            });

            expect(result).toContain('limit:50');
            expect(result).toContain('group-by:category');
        });
    });

    describe('buildFilterFormValuesFromQuery', () => {
        test('category filter includes empty values', () => {
            const policyID = generatePolicyID();
            const queryString = 'sortBy:date sortOrder:desc type:expense category:none,Uncategorized,Maintenance';
            const queryJSON = buildSearchQueryJSON(queryString);

            const policyCategories = {
                [`${ONYXKEYS.COLLECTION.POLICY_CATEGORIES}${policyID}`]: {
                    Maintenance: {
                        enabled: true,
                        name: 'Maintenance',
                    },
                    Travel: {
                        enabled: true,
                        name: 'Travel',
                    },
                    Meals: {
                        enabled: true,
                        name: 'Meals',
                    },
                },
            };
            const policyTags = {};
            const currencyList = {};
            const personalDetails = {};
            const cardList = {};
            const reports = {};
            const taxRates = {};

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            const result = buildFilterFormValuesFromQuery(queryJSON, policyCategories, policyTags, currencyList, personalDetails, cardList, reports, taxRates);

            expect(result).toEqual({
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                category: ['Maintenance', 'none'],
            });
        });

        test('action filter should be set to undefined if the input value is invalid', () => {
            const policyCategories = {};
            const policyTags = {};
            const currencyList = {};
            const personalDetails = {};
            const cardList = {};
            const reports = {};
            const taxRates = {};

            let queryString = 'sortBy:date sortOrder:desc type:expense action:submit';
            let queryJSON = buildSearchQueryJSON(queryString);

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            let result = buildFilterFormValuesFromQuery(queryJSON, policyCategories, policyTags, currencyList, personalDetails, cardList, reports, taxRates);

            expect(result).toEqual({
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                action: 'submit',
            });

            // invalid action value
            queryString = 'sortBy:date sortOrder:desc type:expense action:INVALID,submit';
            queryJSON = buildSearchQueryJSON(queryString);

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            result = buildFilterFormValuesFromQuery(queryJSON, policyCategories, policyTags, currencyList, personalDetails, cardList, reports, taxRates);

            expect(result).toEqual({
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                action: undefined,
            });
        });

        test('parses negative backend amounts into filter form values', () => {
            const policyCategories = {};
            const policyTags = {};
            const currencyList = {};
            const personalDetails = {};
            const cardList = {};
            const reports = {};
            const taxRates = {};

            const queryString = 'sortBy:date sortOrder:desc type:expense amount<-12345 amount>-67890 amount:-54321';
            const queryJSON = buildSearchQueryJSON(queryString);

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            const result = buildFilterFormValuesFromQuery(queryJSON, policyCategories, policyTags, currencyList, personalDetails, cardList, reports, taxRates);

            expect(result).toEqual({
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                amountLessThan: '-12345',
                amountGreaterThan: '-67890',
                amountEqualTo: '-54321',
            });
        });

        test('attendee filter preserves name-only attendees without filtering by personalDetails', () => {
            const policyCategories = {};
            const policyTags = {};
            const currencyList = {};
            const personalDetails = {
                12345: {accountID: 12345, login: 'user@example.com'},
            };
            const cardList = {};
            const reports = {};
            const taxRates = {};

            // Test with mix of accountID and name-only attendee
            const queryString = 'sortBy:date sortOrder:desc type:expense attendee:12345,ZZ';
            const queryJSON = buildSearchQueryJSON(queryString);

            if (!queryJSON) {
                throw new Error('Failed to parse query string');
            }

            const result = buildFilterFormValuesFromQuery(queryJSON, policyCategories, policyTags, currencyList, personalDetails, cardList, reports, taxRates);

            // Both values should be preserved - name-only attendees should not be filtered out
            expect(result).toEqual({
                type: 'expense',
                status: CONST.SEARCH.STATUS.EXPENSE.ALL,
                attendee: ['12345', 'ZZ'],
            });
        });

        describe('view parameter', () => {
            const emptyParams = {
                policyCategories: {},
                policyTags: {},
                currencyList: {},
                personalDetails: {},
                cardList: {},
                reports: {},
                taxRates: {},
            };

            test('sets view in form when groupBy is also set', () => {
                const queryString = 'type:expense groupBy:category view:bar';
                const queryJSON = buildSearchQueryJSON(queryString);

                if (!queryJSON) {
                    throw new Error('Failed to parse query string');
                }

                const result = buildFilterFormValuesFromQuery(
                    queryJSON,
                    emptyParams.policyCategories,
                    emptyParams.policyTags,
                    emptyParams.currencyList,
                    emptyParams.personalDetails,
                    emptyParams.cardList,
                    emptyParams.reports,
                    emptyParams.taxRates,
                );

                expect(result.groupBy).toEqual(CONST.SEARCH.GROUP_BY.CATEGORY);
                expect(result.view).toEqual(CONST.SEARCH.VIEW.BAR);
            });

            test('defaults groupBy to category when chart view is specified without groupBy', () => {
                const queryString = 'type:expense view:bar';
                const queryJSON = buildSearchQueryJSON(queryString);

                if (!queryJSON) {
                    throw new Error('Failed to parse query string');
                }

                const result = buildFilterFormValuesFromQuery(
                    queryJSON,
                    emptyParams.policyCategories,
                    emptyParams.policyTags,
                    emptyParams.currencyList,
                    emptyParams.personalDetails,
                    emptyParams.cardList,
                    emptyParams.reports,
                    emptyParams.taxRates,
                );

                // When a chart view is specified without groupBy, groupBy defaults to category
                expect(result.groupBy).toEqual(CONST.SEARCH.GROUP_BY.CATEGORY);
                expect(result.view).toEqual(CONST.SEARCH.VIEW.BAR);
            });
        });
    });

    describe('shouldHighlight', () => {
        it('returns false if either input is empty', () => {
            expect(shouldHighlight('', 'test')).toBe(false);
            expect(shouldHighlight('Some text', '')).toBe(false);
        });

        it('matches exact word at beginning', () => {
            expect(shouldHighlight('Take a 2-minute tour', 'Take')).toBe(true);
        });

        it('matches word with accent', () => {
            expect(shouldHighlight('f200é', 'f200e')).toBe(true);
        });

        it('matches exact word in middle', () => {
            expect(shouldHighlight('Take a 2-minute tour', '2-minute')).toBe(true);
        });

        it('matches phrase with leading space', () => {
            expect(shouldHighlight('Take a 2-minute tour', ' 2-minute tour')).toBe(true);
        });

        it('matches with special characters', () => {
            // cspell:disable-next-line
            expect(shouldHighlight('Explore the #%tự đặc biệt!', '#%tự')).toBe(true);
        });

        it('is case-insensitive', () => {
            expect(shouldHighlight('Take a 2-minute tour', 'TOUR')).toBe(true);
        });

        it('does not match partial word in the middle', () => {
            expect(shouldHighlight('Take a 2-minute tour', 'in')).toBe(false);
        });

        it('does not match incomplete trailing text', () => {
            expect(shouldHighlight('Take a 2-minute tour', '2-minute to')).toBe(false);
        });

        it('matches multi-word phrase exactly', () => {
            expect(shouldHighlight('Take a 2-minute tour', '2-minute tour')).toBe(true);
        });

        it('does not match words out of order', () => {
            expect(shouldHighlight('Take a 2-minute tour', 'tour 2-minute')).toBe(false);
        });
    });

    describe('sortOptionsWithEmptyValue', () => {
        it('should prioritize empty values at the start', () => {
            const options = ['B', 'A', CONST.SEARCH.CATEGORY_EMPTY_VALUE, 'C'];
            const sortedOptions = options.sort((a, b) => sortOptionsWithEmptyValue(a, b, localeCompare));

            expect(sortedOptions).toEqual([CONST.SEARCH.CATEGORY_EMPTY_VALUE, 'A', 'B', 'C']);
        });

        it('should sort non-empty values properly', () => {
            const options = ['B', 'A', 'C'];
            const sortedOptions = options.sort((a, b) => sortOptionsWithEmptyValue(a, b, localeCompare));

            expect(sortedOptions).toEqual(['A', 'B', 'C']);
        });
    });

    describe('similarSearchHash', () => {
        it('should return same similarSearchHash for two queries that are the same but use different sorting', () => {
            const queryJSONa = buildSearchQueryJSON('sortBy:date sortOrder:desc type:expense category:none,Uncategorized,Maintenance');
            const queryJSONb = buildSearchQueryJSON('sortBy:date sortOrder:asc type:expense category:none,Uncategorized,Maintenance');

            expect(queryJSONa?.similarSearchHash).toEqual(queryJSONb?.similarSearchHash);
        });

        it('should return same similarSearchHash for two queries that have same filters but different values', () => {
            const queryJSONa = buildSearchQueryJSON('sortBy:date sortOrder:desc type:expense feed:"oauth.americanexpressfdx.com 1001" posted:last-statement');
            const queryJSONb = buildSearchQueryJSON('sortBy:date sortOrder:desc type:expense feed:"1234_stripe" posted:last-month');

            expect(queryJSONa?.similarSearchHash).toEqual(queryJSONb?.similarSearchHash);
        });

        it('should return same similarSearchHash for queries with a date range', () => {
            const queryJSONa = buildSearchQueryJSON('type:expense withdrawal-type:reimbursement withdrawn:last-month');
            const queryJSONb = buildSearchQueryJSON('type:expense withdrawal-type:reimbursement withdrawn>2025-01-01 withdrawn<2025-01-03');

            expect(queryJSONa?.similarSearchHash).toEqual(queryJSONb?.similarSearchHash);
        });

        it('should return different similarSearchHash for two queries that have different types', () => {
            const queryJSONa = buildSearchQueryJSON('sortBy:date sortOrder:desc type:expense feed:"oauth.americanexpressfdx.com 1001"');
            const queryJSONb = buildSearchQueryJSON('sortBy:date sortOrder:desc type:trip feed:"oauth.americanexpressfdx.com 1001"');

            expect(queryJSONa?.similarSearchHash).not.toEqual(queryJSONb?.similarSearchHash);
        });

        describe('limit filter hashing', () => {
            it('should return same similarSearchHash for queries with different limit values', () => {
                const queryJSONa = buildSearchQueryJSON('type:expense limit:10');
                const queryJSONb = buildSearchQueryJSON('type:expense limit:50');

                expect(queryJSONa?.similarSearchHash).toEqual(queryJSONb?.similarSearchHash);
            });

            it('should return different primaryHash for queries with different limit values', () => {
                const queryJSONa = buildSearchQueryJSON('type:expense limit:10');
                const queryJSONb = buildSearchQueryJSON('type:expense limit:50');

                expect(queryJSONa?.hash).not.toEqual(queryJSONb?.hash);
            });

            it('should return same primaryHash for queries without limit (hash stability)', () => {
                const queryJSONa = buildSearchQueryJSON('type:expense');
                const queryJSONb = buildSearchQueryJSON('type:expense');

                expect(queryJSONa?.hash).toEqual(queryJSONb?.hash);
            });

            it('should return different primaryHash for query with valid limit vs without limit', () => {
                const withoutLimit = buildSearchQueryJSON('type:expense');
                const withLimit = buildSearchQueryJSON('type:expense limit:10');

                expect(withoutLimit?.hash).not.toEqual(withLimit?.hash);
            });

            it('should return same primaryHash for same limit value queried twice', () => {
                const queryJSONa = buildSearchQueryJSON('type:expense limit:25');
                const queryJSONb = buildSearchQueryJSON('type:expense limit:25');

                expect(queryJSONa?.hash).toEqual(queryJSONb?.hash);
            });

            it('should not include limit in hash when limit is not in query string', () => {
                const queryJSON = buildSearchQueryJSON('type:expense merchant:test');

                expect(queryJSON?.limit).toBeUndefined();
                expect(queryJSON?.hash).toBeDefined();
            });

            it('should return same primaryHash for invalid limit as no limit (normalization before hashing)', () => {
                const withoutLimit = buildSearchQueryJSON('type:expense');
                const withZeroLimit = buildSearchQueryJSON('type:expense limit:0');
                const withNegativeLimit = buildSearchQueryJSON('type:expense limit:-5');
                const withDecimalLimit = buildSearchQueryJSON('type:expense limit:10.5');

                // All invalid limits should normalize to undefined and produce same hash as no limit
                expect(withZeroLimit?.hash).toEqual(withoutLimit?.hash);
                expect(withNegativeLimit?.hash).toEqual(withoutLimit?.hash);
                expect(withDecimalLimit?.hash).toEqual(withoutLimit?.hash);
            });
        });
    });

    describe('limit filter parsing', () => {
        it('parses limit value as a number', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:25');

            expect(queryJSON?.limit).toBe(25);
            expect(typeof queryJSON?.limit).toBe('number');
        });

        it('preserves limit when combined with other filters', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:100 merchant:Amazon');

            expect(queryJSON?.limit).toBe(100);
            expect(queryJSON?.type).toBe('expense');
        });

        it('returns undefined limit when not specified in query', () => {
            const queryJSON = buildSearchQueryJSON('type:expense merchant:Amazon');

            expect(queryJSON?.limit).toBeUndefined();
        });

        it('handles large limit values', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:9999');

            expect(queryJSON?.limit).toBe(9999);
        });

        it('converts limit:0 to undefined', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:0');

            expect(queryJSON?.limit).toBeUndefined();
        });

        it('converts negative limit to undefined', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:-10');

            expect(queryJSON?.limit).toBeUndefined();
        });

        it('converts decimal limit to undefined', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:10.5');

            expect(queryJSON?.limit).toBeUndefined();
        });

        it('converts non-numeric limit to undefined', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:abc');

            expect(queryJSON?.limit).toBeUndefined();
        });

        it('converts comma-separated limit to undefined', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:10,20');

            expect(queryJSON?.limit).toBeUndefined();
        });

        it('uses last limit value when multiple limits specified', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:10 limit:20');

            expect(queryJSON?.limit).toBe(20);
        });

        it('treats empty limit as keyword, not limit filter', () => {
            const queryJSON = buildSearchQueryJSON('type:expense limit:');

            expect(queryJSON?.limit).toBeUndefined();
            const keywordFilter = queryJSON?.flatFilters.find((filter) => filter.key === 'keyword');
            expect(keywordFilter?.filters.some((f) => f.value === 'limit:')).toBe(true);
        });

        it('treats negated limit as keyword since limit is non-negatable', () => {
            const queryJSON = buildSearchQueryJSON('type:expense -limit:10');

            expect(queryJSON?.limit).toBeUndefined();
            const keywordFilter = queryJSON?.flatFilters.find((filter) => filter.key === 'keyword');
            expect(keywordFilter?.filters.some((f) => f.value === '-limit:10')).toBe(true);
        });
    });

    describe('getFilterDisplayValue', () => {
        const mockCardList = {};
        const mockCardFeeds = {};
        const mockPolicies = {};
        const mockReports = {};
        const currentUserAccountID = 12345;

        it('should return clean phone number without @expensify.sms for SMS login users', () => {
            const personalDetails = {
                '99999': {
                    accountID: 99999,
                    login: '+15551234567@expensify.sms',
                    displayName: '+15551234567@expensify.sms',
                },
            };

            const result = getFilterDisplayValue(
                CONST.SEARCH.SYNTAX_FILTER_KEYS.FROM,
                '99999',
                personalDetails,
                mockReports,
                mockCardList,
                mockCardFeeds,
                mockPolicies,
                currentUserAccountID,
                translateLocal,
            );

            expect(result).toBe('+15551234567');
            expect(result).not.toContain('@expensify.sms');
        });

        it('should return display name for regular email users', () => {
            const personalDetails = {
                '78901': {
                    accountID: 78901,
                    login: 'janedoe@example.com',
                    displayName: 'Jane Doe',
                },
            };

            const result = getFilterDisplayValue(
                CONST.SEARCH.SYNTAX_FILTER_KEYS.FROM,
                '78901',
                personalDetails,
                mockReports,
                mockCardList,
                mockCardFeeds,
                mockPolicies,
                currentUserAccountID,
                translateLocal,
            );

            expect(result).toBe('Jane Doe');
        });

        it('should return "Me" for current user account ID', () => {
            const personalDetails = {
                '12345': {
                    accountID: 12345,
                    login: 'currentuser@example.com',
                    displayName: 'Current User',
                },
            };

            const result = getFilterDisplayValue(
                CONST.SEARCH.SYNTAX_FILTER_KEYS.FROM,
                '12345',
                personalDetails,
                mockReports,
                mockCardList,
                mockCardFeeds,
                mockPolicies,
                currentUserAccountID,
                translateLocal,
            );

            expect(result).toBe(CONST.SEARCH.ME);
        });

        it('should return fallback value when personal details not found', () => {
            const personalDetails = {};

            const result = getFilterDisplayValue(
                CONST.SEARCH.SYNTAX_FILTER_KEYS.FROM,
                '88888',
                personalDetails,
                mockReports,
                mockCardList,
                mockCardFeeds,
                mockPolicies,
                currentUserAccountID,
                translateLocal,
            );

            expect(result).toBe('88888');
        });

        it('should handle SMS login with custom display name', () => {
            const personalDetails = {
                '77777': {
                    accountID: 77777,
                    login: '+15559876543@expensify.sms',
                    displayName: 'Custom Name',
                },
            };

            const result = getFilterDisplayValue(
                CONST.SEARCH.SYNTAX_FILTER_KEYS.FROM,
                '77777',
                personalDetails,
                mockReports,
                mockCardList,
                mockCardFeeds,
                mockPolicies,
                currentUserAccountID,
                translateLocal,
            );

            expect(result).toBe('Custom Name');
            expect(result).not.toContain('@expensify.sms');
        });

        it('should work with TO filter key', () => {
            const personalDetails = {
                '66666': {
                    accountID: 66666,
                    login: '+15551112222@expensify.sms',
                    displayName: '+15551112222@expensify.sms',
                },
            };

            const result = getFilterDisplayValue(
                CONST.SEARCH.SYNTAX_FILTER_KEYS.TO,
                '66666',
                personalDetails,
                mockReports,
                mockCardList,
                mockCardFeeds,
                mockPolicies,
                currentUserAccountID,
                translateLocal,
            );

            expect(result).toBe('+15551112222');
            expect(result).not.toContain('@expensify.sms');
        });

        it('should work with other user-related filter keys (ASSIGNEE, PAYER, EXPORTER, ATTENDEE)', () => {
            const personalDetails = {
                '55555': {
                    accountID: 55555,
                    login: '+15553334444@expensify.sms',
                    displayName: '+15553334444@expensify.sms',
                },
            };

            const filterKeys = [
                CONST.SEARCH.SYNTAX_FILTER_KEYS.ASSIGNEE,
                CONST.SEARCH.SYNTAX_FILTER_KEYS.PAYER,
                CONST.SEARCH.SYNTAX_FILTER_KEYS.EXPORTER,
                CONST.SEARCH.SYNTAX_FILTER_KEYS.ATTENDEE,
            ];

            for (const filterKey of filterKeys) {
                const result = getFilterDisplayValue(filterKey, '55555', personalDetails, mockReports, mockCardList, mockCardFeeds, mockPolicies, currentUserAccountID, translateLocal);

                expect(result).toBe('+15553334444');
                expect(result).not.toContain('@expensify.sms');
            }
        });
    });

    describe('buildSearchQueryString', () => {
        test('includes view when explicitly set in rawFilterList', () => {
            const queryJSON = buildSearchQueryJSON('type:expense view:line', 'type:expense view:line');

            const result = buildSearchQueryString(queryJSON);

            expect(result).toContain('view:line');
        });

        test('includes view when differs from default even without rawFilterList', () => {
            const queryJSON = buildSearchQueryJSON('type:expense view:pie');

            const result = buildSearchQueryString(queryJSON);

            expect(result).toContain('view:pie');
        });

        test('includes view when set to bar', () => {
            const queryJSON = buildSearchQueryJSON('type:expense view:bar');

            const result = buildSearchQueryString(queryJSON);

            expect(result).toContain('view:bar');
        });

        test('skips view when not explicitly set and matches default', () => {
            const queryJSON = buildSearchQueryJSON('type:expense');

            const result = buildSearchQueryString(queryJSON);

            expect(result).not.toContain('view:table');
        });

        test('includes view when explicitly set to table in rawFilterList', () => {
            const queryJSON = buildSearchQueryJSON('type:expense view:table', 'type:expense view:table');

            const result = buildSearchQueryString(queryJSON);

            expect(result).toContain('view:table');
        });

        test('preserves view along with other filters', () => {
            const queryJSON = buildSearchQueryJSON('type:expense view:line category:travel');

            const result = buildSearchQueryString(queryJSON);

            expect(result).toContain('view:line');
            expect(result).toContain('category:travel');
        });

        test('handles view with rawFilterList containing other filters', () => {
            const queryJSON = buildSearchQueryJSON('type:expense view:pie merchant:Amazon', 'type:expense view:pie merchant:Amazon');

            const result = buildSearchQueryString(queryJSON);

            expect(result).toContain('view:pie');
            expect(result).toContain('merchant:Amazon');
        });
    });

    describe('stale sortBy is overridden on groupBy/view transitions', () => {
        test('switching groupBy from category to month replaces stale sortBy:groupCategory with sortBy:groupmonth', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                groupBy: CONST.SEARCH.GROUP_BY.MONTH,
                view: CONST.SEARCH.VIEW.BAR,
            };

            const queryString = buildQueryStringFromFilterFormValues(filterValues, {
                sortBy: 'groupCategory',
            });
            const queryJSON = buildSearchQueryJSON(queryString);

            expect(queryJSON?.sortBy).toBe(CONST.SEARCH.TABLE_COLUMNS.GROUP_MONTH);
        });

        test('switching groupBy from month to category replaces stale sortBy:groupmonth with sortBy:groupCategory', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                groupBy: CONST.SEARCH.GROUP_BY.CATEGORY,
                view: CONST.SEARCH.VIEW.BAR,
            };

            const queryString = buildQueryStringFromFilterFormValues(filterValues, {
                sortBy: 'groupmonth',
            });
            const queryJSON = buildSearchQueryJSON(queryString);

            expect(queryJSON?.sortBy).toBe(CONST.SEARCH.TABLE_COLUMNS.GROUP_CATEGORY);
        });

        test('switching from table to bar with stale sortBy:date derives correct sortBy from default groupBy', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                groupBy: CONST.SEARCH.GROUP_BY.CATEGORY,
                view: CONST.SEARCH.VIEW.BAR,
            };

            const queryString = buildQueryStringFromFilterFormValues(filterValues, {
                sortBy: 'date',
            });
            const queryJSON = buildSearchQueryJSON(queryString);

            expect(queryJSON?.sortBy).toBe(CONST.SEARCH.TABLE_COLUMNS.GROUP_CATEGORY);
        });

        test('explicit non-default sortBy:amount is preserved across groupBy changes', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                groupBy: CONST.SEARCH.GROUP_BY.WEEK,
                view: CONST.SEARCH.VIEW.BAR,
            };

            const queryString = buildQueryStringFromFilterFormValues(filterValues, {
                sortBy: 'amount',
            });
            const queryJSON = buildSearchQueryJSON(queryString);

            expect(queryJSON?.sortBy).toBe('amount');
        });
    });

    describe('sortOrder is correctly derived when sortBy matches groupBy default (UI loop)', () => {
        test('bar→line with category: sortOrder omitted, sortBy re-fed as groupCategory', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                groupBy: CONST.SEARCH.GROUP_BY.CATEGORY,
                view: CONST.SEARCH.VIEW.LINE,
            };

            const queryString = buildQueryStringFromFilterFormValues(filterValues, {
                sortBy: CONST.SEARCH.TABLE_COLUMNS.GROUP_CATEGORY,
            });
            const rebuilt = getQueryWithUpdatedValues(queryString, true);
            const queryJSON = buildSearchQueryJSON(rebuilt ?? '');

            expect(queryJSON?.sortOrder).toBe('asc');
            expect(queryJSON?.sortBy).toBe(CONST.SEARCH.TABLE_COLUMNS.GROUP_CATEGORY);
        });

        test('bar→table with category: sortOrder omitted, sortBy re-fed as groupCategory', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                groupBy: CONST.SEARCH.GROUP_BY.CATEGORY,
                view: CONST.SEARCH.VIEW.TABLE,
            };

            const queryString = buildQueryStringFromFilterFormValues(filterValues, {
                sortBy: CONST.SEARCH.TABLE_COLUMNS.GROUP_CATEGORY,
            });
            const rebuilt = getQueryWithUpdatedValues(queryString, true);
            const queryJSON = buildSearchQueryJSON(rebuilt ?? '');

            expect(queryJSON?.sortOrder).toBe('asc');
            expect(queryJSON?.sortBy).toBe(CONST.SEARCH.TABLE_COLUMNS.GROUP_CATEGORY);
        });

        test('line→bar with month: sortOrder omitted, sortBy re-fed as groupmonth', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                groupBy: CONST.SEARCH.GROUP_BY.MONTH,
                view: CONST.SEARCH.VIEW.BAR,
            };

            const queryString = buildQueryStringFromFilterFormValues(filterValues, {
                sortBy: CONST.SEARCH.TABLE_COLUMNS.GROUP_MONTH,
            });
            const rebuilt = getQueryWithUpdatedValues(queryString, true);
            const queryJSON = buildSearchQueryJSON(rebuilt ?? '');

            expect(queryJSON?.sortOrder).toBe('asc');
            expect(queryJSON?.sortBy).toBe(CONST.SEARCH.TABLE_COLUMNS.GROUP_MONTH);
        });

        test('rebuilt query string contains sortOrder (visible in URL)', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                groupBy: CONST.SEARCH.GROUP_BY.CATEGORY,
                view: CONST.SEARCH.VIEW.LINE,
            };

            const queryString = buildQueryStringFromFilterFormValues(filterValues, {
                sortBy: CONST.SEARCH.TABLE_COLUMNS.GROUP_CATEGORY,
            });

            expect(queryString).not.toContain('sortOrder');

            const rebuilt = getQueryWithUpdatedValues(queryString, true);

            expect(rebuilt).toContain('sortOrder:asc');
        });

        test('non-time groupBy withdrawal-id gets desc even when sortBy is re-fed', () => {
            const filterValues: Partial<SearchAdvancedFiltersForm> = {
                type: 'expense',
                groupBy: CONST.SEARCH.GROUP_BY.WITHDRAWAL_ID,
                view: CONST.SEARCH.VIEW.BAR,
            };

            const queryString = buildQueryStringFromFilterFormValues(filterValues, {
                sortBy: CONST.SEARCH.TABLE_COLUMNS.GROUP_WITHDRAWN,
            });
            const rebuilt = getQueryWithUpdatedValues(queryString, true);
            const queryJSON = buildSearchQueryJSON(rebuilt ?? '');

            expect(queryJSON?.sortOrder).toBe('desc');
            expect(queryJSON?.sortBy).toBe(CONST.SEARCH.TABLE_COLUMNS.GROUP_WITHDRAWN);
        });
    });

    describe('shouldResetSortOrder', () => {
        // Crossing line/non-line boundary
        test('returns true when switching from table to line view', () => {
            expect(shouldResetSortOrder({newView: 'line', oldView: 'table', newGroupBy: undefined, oldGroupBy: undefined})).toBe(true);
        });

        test('returns true when switching from bar to line view', () => {
            expect(shouldResetSortOrder({newView: 'line', oldView: 'bar', newGroupBy: undefined, oldGroupBy: undefined})).toBe(true);
        });

        test('returns true when switching from line to table view', () => {
            expect(shouldResetSortOrder({newView: 'table', oldView: 'line', newGroupBy: undefined, oldGroupBy: undefined})).toBe(true);
        });

        test('returns true when switching from line to bar view', () => {
            expect(shouldResetSortOrder({newView: 'bar', oldView: 'line', newGroupBy: undefined, oldGroupBy: undefined})).toBe(true);
        });

        // groupBy changes within line view
        test('returns true when groupBy changes while in line view (month -> week)', () => {
            expect(shouldResetSortOrder({newView: 'line', oldView: 'line', newGroupBy: 'week', oldGroupBy: 'month'})).toBe(true);
        });

        test('returns true when groupBy changes while in line view (month -> category)', () => {
            expect(shouldResetSortOrder({newView: 'line', oldView: 'line', newGroupBy: 'category', oldGroupBy: 'month'})).toBe(true);
        });

        test('returns true when groupBy changes while in line view (undefined -> month)', () => {
            expect(shouldResetSortOrder({newView: 'line', oldView: 'line', newGroupBy: 'month', oldGroupBy: undefined})).toBe(true);
        });

        test('returns true when groupBy changes while in line view (month -> undefined)', () => {
            expect(shouldResetSortOrder({newView: 'line', oldView: 'line', newGroupBy: undefined, oldGroupBy: 'month'})).toBe(true);
        });

        // No reset cases
        test('returns false when view stays as table and groupBy does not change', () => {
            expect(shouldResetSortOrder({newView: 'table', oldView: 'table', newGroupBy: 'category', oldGroupBy: 'category'})).toBe(false);
        });

        test('returns false when view stays as bar and groupBy does not change', () => {
            expect(shouldResetSortOrder({newView: 'bar', oldView: 'bar', newGroupBy: 'month', oldGroupBy: 'month'})).toBe(false);
        });

        test('returns false when view stays as line and groupBy does not change', () => {
            expect(shouldResetSortOrder({newView: 'line', oldView: 'line', newGroupBy: 'month', oldGroupBy: 'month'})).toBe(false);
        });

        test('returns true when groupBy changes in table view', () => {
            expect(shouldResetSortOrder({newView: 'table', oldView: 'table', newGroupBy: 'week', oldGroupBy: 'month'})).toBe(true);
        });

        test('returns true when groupBy changes in bar view', () => {
            expect(shouldResetSortOrder({newView: 'bar', oldView: 'bar', newGroupBy: 'category', oldGroupBy: 'month'})).toBe(true);
        });

        // Boundary + groupBy change at the same time (e.g. switching to line with a different groupBy)
        test('returns true when switching to line view and groupBy also changes', () => {
            expect(shouldResetSortOrder({newView: 'line', oldView: 'table', newGroupBy: 'week', oldGroupBy: 'category'})).toBe(true);
        });

        // undefined view handling
        test('returns false when both views are undefined and groupBy does not change', () => {
            expect(shouldResetSortOrder({newView: undefined, oldView: undefined, newGroupBy: undefined, oldGroupBy: undefined})).toBe(false);
        });

        test('returns true when both views are undefined and groupBy changes', () => {
            expect(shouldResetSortOrder({newView: undefined, oldView: undefined, newGroupBy: 'week', oldGroupBy: 'month'})).toBe(true);
        });
    });

    describe('buildSearchQueryJSON cache', () => {
        test('mutating the returned object does not affect subsequent calls for the same query', () => {
            const query = `type:expense groupBy:category view:bar date:last-month merchant:test${Date.now()}`;

            const first = buildSearchQueryJSON(query);
            if (first) {
                first.groupBy = undefined;
                first.view = CONST.SEARCH.VIEW.TABLE;
            }

            const second = buildSearchQueryJSON(query);

            expect(second?.groupBy).toBe('category');
            expect(second?.view).toBe('bar');
        });

        test('returns equal result on repeated calls with the same query', () => {
            const query = 'type:expense status:outstanding';

            const first = buildSearchQueryJSON(query);
            const second = buildSearchQueryJSON(query);

            expect(first).toEqual(second);
        });

        test('returns independent results for the same query with different rawQuery values', () => {
            const query = 'type:expense';
            const rawQueryA = 'type:expense status:drafts';
            const rawQueryB = 'type:expense status:paid';

            const resultA = buildSearchQueryJSON(query, rawQueryA);
            const resultB = buildSearchQueryJSON(query, rawQueryB);

            expect(resultA?.rawFilterList).not.toEqual(resultB?.rawFilterList);
        });

        test('does not cache a failed parse result so subsequent calls retry the parser', () => {
            // Force the parser to throw on the first call only, then succeed on the second.
            // Verifies that a failed parse is not stored in the cache.
            const searchParserModule: {parse: jest.Mock} = jest.requireMock('@libs/SearchParser/searchParser');
            const originalImpl = jest.requireActual<{parse: (...args: unknown[]) => unknown}>('@libs/SearchParser/searchParser').parse;

            const query = `type:expense merchant:cache-err-test${Date.now()}`;
            let callCount = 0;
            searchParserModule.parse.mockImplementation((...args: unknown[]) => {
                callCount++;
                if (callCount === 1) {
                    throw new Error('Simulated parser failure');
                }
                return originalImpl(...args);
            });

            const firstResult = buildSearchQueryJSON(query);
            const secondResult = buildSearchQueryJSON(query);

            expect(firstResult).toBeUndefined();
            expect(secondResult?.type).toBe('expense');

            searchParserModule.parse.mockImplementation(originalImpl);
        });

        test('evicts the oldest entry when the cache exceeds max size', () => {
            // Insert 51 entries (max is 50) to trigger eviction, then verify
            // the evicted entry can still be re-parsed correctly.
            const uniquePrefix = `type:expense merchant:evict${Date.now()}x`;
            for (let i = 0; i < 51; i++) {
                buildSearchQueryJSON(`${uniquePrefix}${i}`);
            }

            const afterEviction = buildSearchQueryJSON(`${uniquePrefix}0`);

            expect(afterEviction).toBeDefined();
            expect(afterEviction?.type).toBe('expense');
        });
    });
});
