import {getEnvironmentURL} from '@libs/Environment/Environment';
import getEnvironment from '@libs/Environment/getEnvironment';

import type {ReactElement, ReactNode} from 'react';

import React, {createContext, useCallback, useContext, useEffect, useMemo, useState} from 'react';

import type {EnvironmentActionsContextType, EnvironmentStateContextType, EnvironmentValue} from './types';

import {defaultEnvironmentActionsContextValue, defaultEnvironmentStateContextValue} from './default';

type EnvironmentProviderProps = {
    /** Actual content wrapped by this component */
    children: ReactNode;
};

/** The production NewDot origin that the backend bakes into the HTML of the report actions it generates. */
const PRODUCTION_NEW_DOT_ORIGIN = 'https://new.expensify.com';

/** Matches an opening anchor tag. Closing tags and every other element are left untouched. */
const ANCHOR_START_TAG_REGEX = /<a\b[^>]*>/gi;

/**
 * Matches an href attribute inside an opening anchor tag, in all three HTML quoting styles.
 * The leading \s is required so that ExpensiMark's `data-raw-href="…"` is not matched.
 */
const HREF_ATTRIBUTE_REGEX = /(\shref\s*=\s*)(?:"([^"]*)"|'([^']*)'|([^\s"'`=<>]+))/i;

/** Characters that may follow an origin, so that a lookalike host such as new.expensify.com.example.com is not rewritten. */
const ORIGIN_BOUNDARY_CHARACTERS = new Set(['/', '?', '#']);

/**
 * Rewrites production NewDot hrefs in anchor tags so they resolve against the current environment.
 *
 * Report action HTML is generated by the backend and stored once in a database that staging and production share,
 * so any absolute origin baked into it is wrong for at least one of those environments. We therefore rewrite the
 * origin at render time instead.
 *
 * This deliberately edits the raw HTML string rather than parsing and re-serializing it: a round trip through an
 * HTML serializer rewrites the App's custom tags (it turns `<mention-user accountID="…"/>` into a wrapper that
 * swallows the rest of the message, lowercases the `accountID` attribute that MentionUserRenderer reads, and
 * converts emoji to numeric character references).
 */
function rewriteProductionNewDotLinks(html: string, environmentURLWithoutTrailingSlash: string): string {
    // Nothing to do when we are already on production, and the substring check skips the messages that hold no NewDot link.
    if (!html || !environmentURLWithoutTrailingSlash || environmentURLWithoutTrailingSlash === PRODUCTION_NEW_DOT_ORIGIN || !html.includes(PRODUCTION_NEW_DOT_ORIGIN)) {
        return html;
    }

    return html.replaceAll(ANCHOR_START_TAG_REGEX, (anchorStartTag) =>
        anchorStartTag.replace(HREF_ATTRIBUTE_REGEX, (hrefAttribute, attributeNameAndEquals: string, doubleQuoted?: string, singleQuoted?: string, unquoted?: string) => {
            const href = doubleQuoted ?? singleQuoted ?? unquoted ?? '';
            if (!href.startsWith(PRODUCTION_NEW_DOT_ORIGIN)) {
                return hrefAttribute;
            }

            const pathAndBeyond = href.slice(PRODUCTION_NEW_DOT_ORIGIN.length);
            if (pathAndBeyond && !ORIGIN_BOUNDARY_CHARACTERS.has(pathAndBeyond.charAt(0))) {
                return hrefAttribute;
            }

            const newHref = `${environmentURLWithoutTrailingSlash}${pathAndBeyond}`;
            if (doubleQuoted !== undefined) {
                return `${attributeNameAndEquals}"${newHref}"`;
            }
            if (singleQuoted !== undefined) {
                return `${attributeNameAndEquals}'${newHref}'`;
            }
            return `${attributeNameAndEquals}${newHref}`;
        }),
    );
}

const EnvironmentStateContext = createContext<EnvironmentStateContextType>(defaultEnvironmentStateContextValue);
const EnvironmentActionsContext = createContext<EnvironmentActionsContextType>(defaultEnvironmentActionsContextValue);

function EnvironmentProvider({children}: EnvironmentProviderProps): ReactElement {
    const [environment, setEnvironment] = useState<EnvironmentValue>(defaultEnvironmentStateContextValue.environment);
    const [environmentURL, setEnvironmentURL] = useState(defaultEnvironmentStateContextValue.environmentURL);
    const environmentURLWithoutTrailingSlash = useMemo(() => environmentURL.replaceAll(/\/+$/g, ''), [environmentURL]);

    useEffect(() => {
        getEnvironment().then(setEnvironment);
        getEnvironmentURL().then(setEnvironmentURL);
    }, []);

    /**
     * Adjusts Expensify links in HTML content to use the current environment URL
     * instead of the production URL (new.expensify.com).
     */
    const adjustExpensifyLinksForEnv = useCallback((html: string): string => rewriteProductionNewDotLinks(html, environmentURLWithoutTrailingSlash), [environmentURLWithoutTrailingSlash]);

    const stateValue = useMemo(
        () => ({
            environment,
            environmentURL,
        }),
        [environment, environmentURL],
    );

    const actionsValue = useMemo(
        () => ({
            adjustExpensifyLinksForEnv,
        }),
        [adjustExpensifyLinksForEnv],
    );

    return (
        <EnvironmentStateContext.Provider value={stateValue}>
            <EnvironmentActionsContext.Provider value={actionsValue}>{children}</EnvironmentActionsContext.Provider>
        </EnvironmentStateContext.Provider>
    );
}

function useEnvironmentState() {
    return useContext(EnvironmentStateContext);
}

function useEnvironmentActions() {
    return useContext(EnvironmentActionsContext);
}

export default EnvironmentProvider;
export {EnvironmentActionsContext, useEnvironmentState, useEnvironmentActions};
export type {EnvironmentStateContextType};
