import {clear, flushQueue, isEmpty, queueOnyxUpdates} from '@libs/actions/QueuedOnyxUpdates';

import CONST from '@src/CONST';
import type {OnyxKey} from '@src/ONYXKEYS';
import ONYXKEYS from '@src/ONYXKEYS';

import type {OnyxUpdate} from 'react-native-onyx';

import Onyx from 'react-native-onyx';

import waitForBatchedUpdates from '../utils/waitForBatchedUpdates';

const queuedOnyxUpdates: Array<
    OnyxUpdate<
        | typeof ONYXKEYS.NVP_TRY_FOCUS_MODE
        | typeof ONYXKEYS.PREFERRED_THEME
        | typeof ONYXKEYS.NVP_PREFERRED_LOCALE
        | typeof ONYXKEYS.SESSION
        | typeof ONYXKEYS.IS_LOADING_APP
        | typeof ONYXKEYS.CREDENTIALS
        | typeof ONYXKEYS.RAM_ONLY_IS_SIDEBAR_LOADED
        | typeof ONYXKEYS.COLLECTION.REPORT
        | typeof ONYXKEYS.COLLECTION.REPORT_ACTIONS
    >
> = [
    {key: ONYXKEYS.NVP_TRY_FOCUS_MODE, value: true, onyxMethod: 'merge'},
    {key: ONYXKEYS.PREFERRED_THEME, value: 'system', onyxMethod: 'merge'},
    {key: ONYXKEYS.NVP_PREFERRED_LOCALE, value: 'en', onyxMethod: 'merge'},
    {
        key: ONYXKEYS.SESSION,
        value: {
            accountID: 18748326,
            authToken: 'testToken',
            email: 'abcd+2342424224@gmail.com',
            encryptedAuthToken: 'testEncryptedAuthToken',
            loading: false,
        },
        onyxMethod: 'merge',
    },
    {key: ONYXKEYS.IS_LOADING_APP, value: false, onyxMethod: 'merge'},
    {
        key: ONYXKEYS.CREDENTIALS,
        value: {
            autoGeneratedLogin: '',
            autoGeneratedPassword: '',
            login: 'abcd+2342424224@gmail.com',
        },
        onyxMethod: 'merge',
    },
    {
        key: ONYXKEYS.RAM_ONLY_IS_SIDEBAR_LOADED,
        value: true,
        onyxMethod: 'merge',
    },
    {
        key: `${ONYXKEYS.COLLECTION.REPORT}2175919089355165`,
        value: {reportID: 'reportID'},
        onyxMethod: 'merge',
    },
    {
        key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}2175919089355165`,
        value: {
            // eslint-disable-next-line @typescript-eslint/naming-convention
            '4135522899867010163': {
                reportActionID: '4135522899867010163',
            },
        },
        onyxMethod: 'merge',
    },
];

jest.mock('@src/CONFIG', () => ({
    IS_TEST_ENV: false,
}));

function getOnyxUpdateValue<T>(key: string): T | undefined {
    return queuedOnyxUpdates.find((item) => item.key === key)?.value as T | undefined;
}

async function testOnyxKeyValue<T>(key: OnyxKey): Promise<void> {
    const expectedValue = getOnyxUpdateValue<T>(key);
    return new Promise<void>((resolve) => {
        const connection = Onyx.connect({
            key,
            waitForCollectionCallback: false,
            callback: (value) => {
                Onyx.disconnect(connection);

                expect(value).toEqual(expectedValue);
                resolve();
            },
        });
    });
}

describe('actions/QueuedOnyxUpdates', () => {
    beforeAll(() => {
        Onyx.init({
            keys: ONYXKEYS,
        });
    });

    beforeEach(() => {
        return Onyx.clear().then(waitForBatchedUpdates);
    });

    describe('flushQueue', () => {
        it('should filter queued updates when currentAccountID is undefined', async () => {
            await queueOnyxUpdates(queuedOnyxUpdates);
            await Onyx.multiSet({
                [ONYXKEYS.SESSION]: null,
            });

            await flushQueue();

            await testOnyxKeyValue(ONYXKEYS.NVP_TRY_FOCUS_MODE);
            await testOnyxKeyValue(ONYXKEYS.PREFERRED_THEME);
            await testOnyxKeyValue(ONYXKEYS.NVP_PREFERRED_LOCALE);
            await testOnyxKeyValue(ONYXKEYS.SESSION);
            await testOnyxKeyValue(ONYXKEYS.IS_LOADING_APP);
            await testOnyxKeyValue(ONYXKEYS.CREDENTIALS);
            await testOnyxKeyValue(ONYXKEYS.RAM_ONLY_IS_SIDEBAR_LOADED);

            await new Promise<void>((resolve) => {
                const connection = Onyx.connect({
                    key: `${ONYXKEYS.COLLECTION.REPORT}2175919089355165`,
                    waitForCollectionCallback: false,
                    callback: (report) => {
                        Onyx.disconnect(connection);
                        expect(report).toBeUndefined();

                        resolve();
                    },
                });
            });

            await new Promise<void>((resolve) => {
                const connection = Onyx.connect({
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}2175919089355165`,
                    waitForCollectionCallback: false,
                    callback: (report) => {
                        Onyx.disconnect(connection);
                        expect(report).toBeUndefined();

                        resolve();
                    },
                });
            });
        });

        it('should not filter updates if currentAccountID is defined', async () => {
            await queueOnyxUpdates(queuedOnyxUpdates);
            await Onyx.multiSet({
                [ONYXKEYS.SESSION]: {
                    accountID: 1,
                },
            });

            await flushQueue();

            await testOnyxKeyValue(ONYXKEYS.NVP_TRY_FOCUS_MODE);
            await testOnyxKeyValue(ONYXKEYS.PREFERRED_THEME);
            await testOnyxKeyValue(ONYXKEYS.NVP_PREFERRED_LOCALE);
            await testOnyxKeyValue(ONYXKEYS.SESSION);
            await testOnyxKeyValue(ONYXKEYS.IS_LOADING_APP);
            await testOnyxKeyValue(ONYXKEYS.CREDENTIALS);
            await testOnyxKeyValue(ONYXKEYS.RAM_ONLY_IS_SIDEBAR_LOADED);

            await new Promise<void>((resolve) => {
                const connection = Onyx.connect({
                    key: `${ONYXKEYS.COLLECTION.REPORT}2175919089355165`,
                    waitForCollectionCallback: false,
                    callback: (report) => {
                        Onyx.disconnect(connection);
                        expect(report).toEqual(getOnyxUpdateValue(`${ONYXKEYS.COLLECTION.REPORT}2175919089355165`));

                        resolve();
                    },
                });
            });

            await new Promise<void>((resolve) => {
                const connection = Onyx.connect({
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}2175919089355165`,
                    waitForCollectionCallback: false,
                    callback: (reportActions) => {
                        Onyx.disconnect(connection);
                        expect(reportActions).toEqual(getOnyxUpdateValue(`${ONYXKEYS.COLLECTION.REPORT_ACTIONS}2175919089355165`));

                        resolve();
                    },
                });
            });
        });

        it('should NOT filter report data when the batch itself establishes an anonymous session (#82013)', async () => {
            // Signed-out public-room deeplink flow: at flush time currentAccountID is still undefined because
            // the anonymous SESSION update that sets it is inside this same batch. The report data belongs to
            // that newly-established anonymous session, so it must be preserved (not dropped by the stale-data
            // filter) — otherwise the deeplink has no report data to navigate to and the flow hangs.
            const reportActionID = '4135522899867010163';
            const anonymousSessionUpdates: Array<OnyxUpdate<typeof ONYXKEYS.SESSION | typeof ONYXKEYS.COLLECTION.REPORT | typeof ONYXKEYS.COLLECTION.REPORT_ACTIONS>> = [
                {
                    key: ONYXKEYS.SESSION,
                    value: {
                        accountID: 18748326,
                        authToken: 'anonymousAuthToken',
                        authTokenType: CONST.AUTH_TOKEN_TYPES.ANONYMOUS,
                        encryptedAuthToken: 'testEncryptedAuthToken',
                    },
                    onyxMethod: 'merge',
                },
                {
                    key: `${ONYXKEYS.COLLECTION.REPORT}2175919089355165`,
                    value: {reportID: 'reportID'},
                    onyxMethod: 'merge',
                },
                {
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}2175919089355165`,
                    value: {[reportActionID]: {reportActionID}},
                    onyxMethod: 'merge',
                },
            ];

            await queueOnyxUpdates(anonymousSessionUpdates);
            // Clear the session so currentAccountID is undefined at flush time, reproducing the signed-out state.
            await Onyx.multiSet({
                [ONYXKEYS.SESSION]: null,
            });

            await flushQueue();

            await new Promise<void>((resolve) => {
                const connection = Onyx.connect({
                    key: `${ONYXKEYS.COLLECTION.REPORT}2175919089355165`,
                    waitForCollectionCallback: false,
                    callback: (report) => {
                        Onyx.disconnect(connection);
                        expect(report).toEqual({reportID: 'reportID'});

                        resolve();
                    },
                });
            });

            await new Promise<void>((resolve) => {
                const connection = Onyx.connect({
                    key: `${ONYXKEYS.COLLECTION.REPORT_ACTIONS}2175919089355165`,
                    waitForCollectionCallback: false,
                    callback: (reportActions) => {
                        Onyx.disconnect(connection);
                        expect(reportActions).toEqual({
                            [reportActionID]: {reportActionID},
                        });

                        resolve();
                    },
                });
            });
        });
    });

    describe('clear', () => {
        it('empties the queue so buffered old-account updates are dropped on sign-out (#82013)', async () => {
            // Given old-account updates buffered before sign-out
            const oldUpdates: Array<OnyxUpdate<typeof ONYXKEYS.COLLECTION.REPORT>> = [
                {
                    key: `${ONYXKEYS.COLLECTION.REPORT}9999999999999999`,
                    value: {reportID: 'oldReport'},
                    onyxMethod: 'merge',
                },
            ];
            await queueOnyxUpdates(oldUpdates);
            expect(isEmpty()).toBe(false);

            // When the session is cleaned up on sign-out (cleanupSession() calls QueuedOnyxUpdates.clear())
            clear();

            // Then the buffer is empty, so the old-account update can never ride through the anonymous-session
            // stale-data-filter bypass in flushQueue() during a later signed-out deeplink flow.
            expect(isEmpty()).toBe(true);
        });
    });
});
