// cspell:ignore SOMESECRETKEY
import {beforeEach, jest, test} from '@jest/globals';
import {openAuthSessionAsync} from 'expo-web-browser';
import Onyx from 'react-native-onyx';
import type {OnyxEntry} from 'react-native-onyx';
import {confirmReadyToOpenApp, openApp, reconnectApp} from '@libs/actions/App';
import {buildOldDotURL, openExternalLink} from '@libs/actions/Link';
import OnyxUpdateManager from '@libs/actions/OnyxUpdateManager';
import {getAll as getAllPersistedRequests} from '@libs/actions/PersistedRequests';
// eslint-disable-next-line no-restricted-syntax
import * as SignInRedirect from '@libs/actions/SignInRedirect';
import {SIDE_EFFECT_REQUEST_COMMANDS, WRITE_COMMANDS} from '@libs/API/types';
import asyncOpenURL from '@libs/asyncOpenURL';
import getPlatform from '@libs/getPlatform';
import HttpUtils from '@libs/HttpUtils';
import {setHasRadio} from '@libs/NetworkState';
import PushNotification from '@libs/Notification/PushNotification';
// This lib needs to be imported, but it has nothing to export since all it contains is an Onyx connection
import '@libs/Notification/PushNotification/subscribeToPushNotifications';
import CONFIG from '@src/CONFIG';
import CONST from '@src/CONST';
import * as SessionUtil from '@src/libs/actions/Session';
import {KEYS_TO_PRESERVE_SUPPORTAL, signOutAndRedirectToSignIn} from '@src/libs/actions/Session';
import * as API from '@src/libs/API';
import ONYXKEYS from '@src/ONYXKEYS';
import type {Credentials, Session} from '@src/types/onyx';
import * as TestHelper from '../utils/TestHelper';
import waitForBatchedUpdates from '../utils/waitForBatchedUpdates';

// We are mocking this method so that we can later test to see if it was called and what arguments it was called with.
// We test HttpUtils.xhr() since this means that our API command turned into a network request and isn't only queued.
HttpUtils.xhr = jest.fn<typeof HttpUtils.xhr<never>>();

// Mocked to ensure push notifications are subscribed/unsubscribed as the session changes
jest.mock('@libs/Notification/PushNotification');

// Mocked to check SignOutAndRedirectToSignIn behavior
jest.mock('@libs/asyncOpenURL');

jest.mock('expo-web-browser', () => ({
    openAuthSessionAsync: jest.fn(() => Promise.resolve({type: 'success'})),
}));

jest.mock('@libs/actions/Link', () => {
    return {
        buildOldDotURL: jest.fn(() => Promise.resolve('mockOldDotURL')),
        openExternalLink: jest.fn(),
    };
});

jest.mock('@libs/getPlatform', () => jest.fn());

const mockedGetPlatform = jest.mocked(getPlatform);

Onyx.init({
    keys: ONYXKEYS,
});

OnyxUpdateManager();
beforeEach(() => {
    setHasRadio(true);
    return Onyx.clear().then(waitForBatchedUpdates);
});

describe('Session', () => {
    test('Authenticate is called with saved credentials when a session expires', async () => {
        // Given a test user and set of authToken with subscriptions to session and credentials
        const TEST_USER_LOGIN = 'test@testguy.com';
        const TEST_USER_ACCOUNT_ID = 1;
        const TEST_INITIAL_AUTH_TOKEN = 'initialAuthToken';
        const TEST_REFRESHED_AUTH_TOKEN = 'refreshedAuthToken';

        let credentials: OnyxEntry<Credentials>;
        Onyx.connect({
            key: ONYXKEYS.CREDENTIALS,
            callback: (val) => (credentials = val),
        });

        let session: OnyxEntry<Session>;
        Onyx.connect({
            key: ONYXKEYS.SESSION,
            callback: (val) => (session = val),
        });

        // When we sign in with the test user
        await TestHelper.signInWithTestUser(TEST_USER_ACCOUNT_ID, TEST_USER_LOGIN, 'Password1', TEST_INITIAL_AUTH_TOKEN);
        await waitForBatchedUpdates();

        // Then our re-authentication credentials should be generated and our session data
        // have the correct information + initial authToken.
        expect(credentials?.login).toBe(TEST_USER_LOGIN);
        expect(credentials?.autoGeneratedLogin).not.toBeUndefined();
        expect(credentials?.autoGeneratedPassword).not.toBeUndefined();
        expect(session?.authToken).toBe(TEST_INITIAL_AUTH_TOKEN);
        expect(session?.accountID).toBe(TEST_USER_ACCOUNT_ID);
        expect(session?.email).toBe(TEST_USER_LOGIN);

        // At this point we have an authToken. To simulate it expiring we'll just make another
        // request and mock the response so it returns 407. Once this happens we should attempt
        // to Re-Authenticate with the stored credentials. Our next call will be to Authenticate
        // so we will mock that response with a new authToken and then verify that Onyx has our
        // data.
        (HttpUtils.xhr as jest.MockedFunction<typeof HttpUtils.xhr>)

            // This will make the call to OpenApp below return with an expired session code
            .mockImplementationOnce(() =>
                Promise.resolve({
                    jsonCode: CONST.JSON_CODE.NOT_AUTHENTICATED,
                }),
            )

            // The next call should be Authenticate since we are re-authenticating
            .mockImplementationOnce(() =>
                Promise.resolve({
                    jsonCode: CONST.JSON_CODE.SUCCESS,
                    accountID: TEST_USER_ACCOUNT_ID,
                    authToken: TEST_REFRESHED_AUTH_TOKEN,
                    email: TEST_USER_LOGIN,
                }),
            );

        // When we attempt to fetch the initial app data via the API
        confirmReadyToOpenApp();
        openApp();
        await waitForBatchedUpdates();

        // Then it should fail and reauthenticate the user adding the new authToken to the session
        // data in Onyx
        expect(session?.authToken).toBe(TEST_REFRESHED_AUTH_TOKEN);
    });

    test('Push notifications are subscribed after signing in', async () => {
        await TestHelper.signInWithTestUser();
        await waitForBatchedUpdates();
        expect(PushNotification.register).toHaveBeenCalled();
    });

    test('Push notifications are unsubscribed after signing out', async () => {
        await TestHelper.signInWithTestUser();
        await TestHelper.signOutTestUser();
        expect(PushNotification.deregister).toHaveBeenCalled();
    });

    test('ReconnectApp should push request to the queue', async () => {
        await TestHelper.signInWithTestUser();
        await Onyx.set(ONYXKEYS.HAS_LOADED_APP, true);
        setHasRadio(false);
        await waitForBatchedUpdates();

        confirmReadyToOpenApp();
        reconnectApp();

        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(1);
        expect(getAllPersistedRequests().at(0)?.command).toBe(WRITE_COMMANDS.RECONNECT_APP);

        setHasRadio(true);
        await waitForBatchedUpdates();

        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(0);
    });

    test('ReconnectApp should open if app is not loaded', async () => {
        await TestHelper.signInWithTestUser();
        await Onyx.set(ONYXKEYS.HAS_LOADED_APP, false);
        setHasRadio(false);
        await waitForBatchedUpdates();

        confirmReadyToOpenApp();
        reconnectApp();

        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(1);
        expect(getAllPersistedRequests().at(0)?.command).toBe(WRITE_COMMANDS.OPEN_APP);

        setHasRadio(true);
        await waitForBatchedUpdates();

        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(0);
    });

    test('ReconnectApp should replace same requests from the queue', async () => {
        await TestHelper.signInWithTestUser();
        await Onyx.set(ONYXKEYS.HAS_LOADED_APP, true);
        setHasRadio(false);
        await waitForBatchedUpdates();

        confirmReadyToOpenApp();
        reconnectApp();
        reconnectApp();
        reconnectApp();
        reconnectApp();

        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(1);
        expect(getAllPersistedRequests().at(0)?.command).toBe(WRITE_COMMANDS.RECONNECT_APP);

        setHasRadio(true);
        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(0);
    });

    test('OpenApp should push request to the queue', async () => {
        await TestHelper.signInWithTestUser();
        setHasRadio(false);
        await waitForBatchedUpdates();

        openApp();

        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(1);
        expect(getAllPersistedRequests().at(0)?.command).toBe(WRITE_COMMANDS.OPEN_APP);

        setHasRadio(true);
        await waitForBatchedUpdates();

        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(0);
    });

    test('OpenApp should replace same requests from the queue', async () => {
        await TestHelper.signInWithTestUser();
        setHasRadio(false);
        await waitForBatchedUpdates();

        openApp();
        openApp();
        openApp();
        openApp();

        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(1);
        expect(getAllPersistedRequests().at(0)?.command).toBe(WRITE_COMMANDS.OPEN_APP);

        setHasRadio(true);
        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(0);
    });

    test('SignOut should return a promise with response containing hasOldDotAuthCookies', async () => {
        await TestHelper.signInWithTestUser();
        setHasRadio(false);
        await waitForBatchedUpdates();

        (HttpUtils.xhr as jest.MockedFunction<typeof HttpUtils.xhr>)
            // This will make the call to OpenApp below return with an expired session code
            .mockImplementationOnce(() =>
                Promise.resolve({
                    jsonCode: CONST.JSON_CODE.SUCCESS,
                    hasOldDotAuthCookies: true,
                }),
            );

        const signOutPromise = SessionUtil.signOut({authToken: 'testAuthToken'});

        expect(signOutPromise).toBeInstanceOf(Promise);

        expect(await signOutPromise).toStrictEqual({
            jsonCode: CONST.JSON_CODE.SUCCESS,
            hasOldDotAuthCookies: true,
        });

        setHasRadio(true);
        await waitForBatchedUpdates();

        expect(getAllPersistedRequests().length).toBe(0);
    });

    describe('SignOutAndRedirectToSignIn', () => {
        test('SignOutAndRedirectToSignIn should redirect to OldDot when LogOut returns truthy hasOldDotAuthCookies', async () => {
            await TestHelper.signInWithTestUser();
            setHasRadio(false);
            await waitForBatchedUpdates();

            (HttpUtils.xhr as jest.MockedFunction<typeof HttpUtils.xhr>)
                // This will make the call to OpenApp below return with an expired session code
                .mockImplementationOnce(() =>
                    Promise.resolve({
                        jsonCode: CONST.JSON_CODE.SUCCESS,
                        hasOldDotAuthCookies: true,
                    }),
                );

            const redirectToSignInSpy = jest.spyOn(SignInRedirect, 'default').mockImplementation(() => Promise.resolve());

            signOutAndRedirectToSignIn();

            await waitForBatchedUpdates();

            expect(asyncOpenURL).toHaveBeenCalledWith(expect.any(Promise), `${CONFIG.EXPENSIFY.EXPENSIFY_URL}${CONST.OLDDOT_URLS.SIGN_OUT}`, true, true);
            expect(redirectToSignInSpy).toHaveBeenCalled();
            jest.clearAllMocks();
        });

        test('SignOutAndRedirectToSignIn should not redirect to OldDot when LogOut return falsy hasOldDotAuthCookies', async () => {
            await TestHelper.signInWithTestUser();
            setHasRadio(false);
            await waitForBatchedUpdates();

            (HttpUtils.xhr as jest.MockedFunction<typeof HttpUtils.xhr>)
                // This will make the call to OpenApp below return with an expired session code
                .mockImplementationOnce(() =>
                    Promise.resolve({
                        jsonCode: CONST.JSON_CODE.SUCCESS,
                    }),
                );

            const redirectToSignInSpy = jest.spyOn(SignInRedirect, 'default').mockImplementation(() => Promise.resolve());

            signOutAndRedirectToSignIn();

            await waitForBatchedUpdates();

            expect(asyncOpenURL).not.toHaveBeenCalled();
            expect(redirectToSignInSpy).toHaveBeenCalled();
            jest.clearAllMocks();
        });

        test('SignOutAndRedirectToSignIn should restore stashed session and redirect to OldDot supportal of supportal agent', async () => {
            jest.spyOn(SessionUtil, 'isSupportAuthToken').mockReturnValue(true);
            jest.spyOn(SessionUtil, 'hasStashedSession').mockReturnValue(true);
            jest.spyOn(SessionUtil, 'signOut').mockResolvedValue(undefined);
            jest.spyOn(Onyx, 'clear').mockResolvedValue(undefined);
            jest.spyOn(Onyx, 'multiSet').mockResolvedValue(undefined);

            const testStashedCredentials = {login: 'stashed@expensify.com', autoGeneratedLogin: 'stashedAutoLogin', autoGeneratedPassword: 'stashedAutoPassword'};
            const testStashedSession = {authToken: 'stashedAuthToken', email: 'stashed@expensify.com', accountID: 123, creationDate: new Date().getTime()};

            await Onyx.set(ONYXKEYS.STASHED_CREDENTIALS, testStashedCredentials);
            await Onyx.set(ONYXKEYS.STASHED_SESSION, testStashedSession);
            await Onyx.merge(ONYXKEYS.SESSION, {authTokenType: CONST.AUTH_TOKEN_TYPES.SUPPORT});

            await waitForBatchedUpdates();

            const onyxClearSpy = Onyx.clear as jest.Mock;
            const onyxMultiSetSpy = Onyx.multiSet as jest.Mock;

            signOutAndRedirectToSignIn(false, false, true, true);

            await waitForBatchedUpdates();

            expect(SessionUtil.signOut).not.toHaveBeenCalled();

            expect(onyxClearSpy).toHaveBeenCalledWith(KEYS_TO_PRESERVE_SUPPORTAL);

            expect(onyxMultiSetSpy).toHaveBeenCalledWith({
                [ONYXKEYS.CREDENTIALS]: testStashedCredentials,
                [ONYXKEYS.SESSION]: testStashedSession,
            });

            expect(buildOldDotURL).toHaveBeenCalledWith(CONST.OLDDOT_URLS.SUPPORTAL_RESTORE_STASHED_LOGIN);
            expect(openExternalLink).toHaveBeenCalledWith('mockOldDotURL', undefined, true);
        });

        test('SignOutAndRedirectToSignIn should preserve SESSION and restore stashed session when shouldForceUseStashedSession is true', async () => {
            jest.spyOn(SessionUtil, 'isSupportAuthToken').mockReturnValue(false);
            jest.spyOn(SessionUtil, 'hasStashedSession').mockReturnValue(true);
            jest.spyOn(SessionUtil, 'signOut').mockResolvedValue(undefined);
            jest.spyOn(Onyx, 'clear').mockResolvedValue(undefined);
            jest.spyOn(Onyx, 'multiSet').mockResolvedValue(undefined);

            const testStashedCredentials = {login: 'delegate@expensify.com', autoGeneratedLogin: 'delegateAutoLogin', autoGeneratedPassword: 'delegateAutoPassword'};
            const testStashedSession = {authToken: 'delegateAuthToken', email: 'delegate@expensify.com', accountID: 456, creationDate: new Date().getTime()};

            await Onyx.set(ONYXKEYS.STASHED_CREDENTIALS, testStashedCredentials);
            await Onyx.set(ONYXKEYS.STASHED_SESSION, testStashedSession);

            await waitForBatchedUpdates();

            const onyxClearSpy = Onyx.clear as jest.Mock;
            const onyxMultiSetSpy = Onyx.multiSet as jest.Mock;
            const redirectToSignInSpy = jest.spyOn(SignInRedirect, 'default').mockImplementation(() => Promise.resolve());

            signOutAndRedirectToSignIn(true, false, true, true);

            await waitForBatchedUpdates();

            expect(SessionUtil.signOut).not.toHaveBeenCalled();

            // Should use Onyx.clear with KEYS_TO_PRESERVE_SUPPORTAL (preserving SESSION) instead of redirectToSignIn
            expect(onyxClearSpy).toHaveBeenCalledWith(KEYS_TO_PRESERVE_SUPPORTAL);
            expect(redirectToSignInSpy).not.toHaveBeenCalled();

            expect(onyxMultiSetSpy).toHaveBeenCalledWith({
                [ONYXKEYS.CREDENTIALS]: testStashedCredentials,
                [ONYXKEYS.SESSION]: testStashedSession,
            });
        });
    });

    describe('hasStashedSession', () => {
        // Clear any mocks from previous tests that might have mocked hasStashedSession
        beforeEach(() => {
            jest.restoreAllMocks();
        });

        test('returns true when both stashedSession has authToken and stashedCredentials has valid autoGeneratedLogin', () => {
            const stashedSession = {authToken: 'testAuthToken', email: 'test@expensify.com', accountID: 123, creationDate: new Date().getTime()};
            const stashedCredentials = {login: 'test@expensify.com', autoGeneratedLogin: 'autoLogin', autoGeneratedPassword: 'autoPassword'};

            const result = SessionUtil.hasStashedSession(stashedSession, stashedCredentials);

            expect(result).toBe(true);
        });

        test('returns false when stashedSession authToken is missing', () => {
            const stashedSession = {email: 'test@expensify.com', accountID: 123, creationDate: new Date().getTime()};
            const stashedCredentials = {login: 'test@expensify.com', autoGeneratedLogin: 'autoLogin', autoGeneratedPassword: 'autoPassword'};

            const result = SessionUtil.hasStashedSession(stashedSession, stashedCredentials);

            expect(result).toBe(false);
        });

        test('returns false when autoGeneratedLogin is missing', () => {
            const stashedSession = {authToken: 'testAuthToken', email: 'test@expensify.com', accountID: 123, creationDate: new Date().getTime()};
            const stashedCredentials = {login: 'test@expensify.com', autoGeneratedPassword: 'autoPassword'};

            const result = SessionUtil.hasStashedSession(stashedSession, stashedCredentials);

            expect(result).toBe(false);
        });

        test('returns false when stashedSessionParam is undefined', () => {
            const stashedCredentials = {login: 'test@expensify.com', autoGeneratedLogin: 'autoLogin', autoGeneratedPassword: 'autoPassword'};

            const result = SessionUtil.hasStashedSession(undefined, stashedCredentials);

            expect(result).toBe(false);
        });

        test('returns false when stashedCredentialsParam is undefined', () => {
            const stashedSession = {authToken: 'testAuthToken', email: 'test@expensify.com', accountID: 123, creationDate: new Date().getTime()};

            const result = SessionUtil.hasStashedSession(stashedSession, undefined);

            expect(result).toBe(false);
        });
    });

    describe('SAML sign out', () => {
        const mockedOpenAuthSessionAsync = jest.mocked(openAuthSessionAsync);

        // The supportal test above spies on SessionUtil.signOut and mocks it.
        // We need to restore it so our tests call the real implementation.
        beforeEach(() => {
            jest.restoreAllMocks();
        });

        test('SignOut should call openAuthSessionAsync without appversion when signedInWithSAML is true on web', async () => {
            await TestHelper.signInWithTestUser();
            await waitForBatchedUpdates();

            mockedOpenAuthSessionAsync.mockClear();

            mockedGetPlatform.mockReturnValue(CONST.PLATFORM.WEB);

            // eslint-disable-next-line rulesdir/no-multiple-api-calls
            const makeRequestSpy = jest.spyOn(API, 'makeRequestWithSideEffects').mockResolvedValue(undefined);

            await SessionUtil.signOut({signedInWithSAML: true, authToken: 'testAuthToken', autoGeneratedLogin: 'testLogin'});
            await waitForBatchedUpdates();

            expect(mockedOpenAuthSessionAsync).toHaveBeenCalledWith(expect.stringContaining('referer=ecash&authToken=testAuthToken'), CONFIG.EXPENSIFY.NEW_EXPENSIFY_URL);
            expect(mockedOpenAuthSessionAsync).toHaveBeenCalledWith(expect.not.stringContaining('appversion='), CONFIG.EXPENSIFY.NEW_EXPENSIFY_URL);
            expect(makeRequestSpy).toHaveBeenCalledWith(SIDE_EFFECT_REQUEST_COMMANDS.LOG_OUT, expect.objectContaining({authToken: 'testAuthToken', partnerUserID: 'testLogin'}), {});

            makeRequestSpy.mockRestore();
        });

        test('SignOut should call openAuthSessionAsync with appversion when signedInWithSAML is true on mobile', async () => {
            await TestHelper.signInWithTestUser();
            await waitForBatchedUpdates();

            mockedOpenAuthSessionAsync.mockClear();
            // eslint-disable-next-line rulesdir/no-multiple-api-calls
            const makeRequestSpy = jest.spyOn(API, 'makeRequestWithSideEffects').mockResolvedValue(undefined);
            mockedGetPlatform.mockReturnValue(CONST.PLATFORM.ANDROID);

            await SessionUtil.signOut({signedInWithSAML: true, authToken: 'testAuthToken', autoGeneratedLogin: 'testLogin'});
            await waitForBatchedUpdates();

            expect(mockedOpenAuthSessionAsync).toHaveBeenCalledWith(expect.stringContaining('appversion='), CONST.SAML_REDIRECT_URL);
            expect(mockedOpenAuthSessionAsync).toHaveBeenCalledWith(expect.stringContaining('authToken=testAuthToken'), CONST.SAML_REDIRECT_URL);
            expect(makeRequestSpy).toHaveBeenCalledWith(SIDE_EFFECT_REQUEST_COMMANDS.LOG_OUT, expect.objectContaining({authToken: 'testAuthToken', partnerUserID: 'testLogin'}), {});
            makeRequestSpy.mockRestore();
        });

        test('SignOut should still call LOG_OUT when SAML browser session fails', async () => {
            await TestHelper.signInWithTestUser();
            await waitForBatchedUpdates();

            mockedOpenAuthSessionAsync.mockImplementationOnce(() => Promise.reject(new Error('Browser session failed')));
            // eslint-disable-next-line rulesdir/no-multiple-api-calls
            const makeRequestSpy = jest.spyOn(API, 'makeRequestWithSideEffects').mockResolvedValue(undefined);

            await SessionUtil.signOut({signedInWithSAML: true, authToken: 'testAuthToken', autoGeneratedLogin: 'testLogin'});
            await waitForBatchedUpdates();

            expect(makeRequestSpy).toHaveBeenCalledWith(SIDE_EFFECT_REQUEST_COMMANDS.LOG_OUT, expect.objectContaining({authToken: 'testAuthToken', partnerUserID: 'testLogin'}), {});
            makeRequestSpy.mockRestore();
        });

        test('SignOut should follow normal LOG_OUT path when signedInWithSAML is false', async () => {
            await TestHelper.signInWithTestUser();
            await waitForBatchedUpdates();

            mockedOpenAuthSessionAsync.mockClear();
            // eslint-disable-next-line rulesdir/no-multiple-api-calls
            const makeRequestSpy = jest.spyOn(API, 'makeRequestWithSideEffects').mockResolvedValue(undefined);

            await SessionUtil.signOut({authToken: 'testAuthToken', autoGeneratedLogin: 'testLogin'});
            await waitForBatchedUpdates();

            expect(mockedOpenAuthSessionAsync).not.toHaveBeenCalled();
            expect(makeRequestSpy).toHaveBeenCalledWith(SIDE_EFFECT_REQUEST_COMMANDS.LOG_OUT, expect.objectContaining({authToken: 'testAuthToken', partnerUserID: 'testLogin'}), {});
            makeRequestSpy.mockRestore();
        });
    });

    describe('replaceTwoFactorDevice', () => {
        test('sets isLoading and clears errors optimistically for both steps', () => {
            // eslint-disable-next-line rulesdir/no-multiple-api-calls
            const writeSpy = jest.spyOn(API, 'write').mockResolvedValue(undefined);

            SessionUtil.replaceTwoFactorDevice('verify_old', '123456');

            const onyxData = writeSpy.mock.calls.at(0)?.at(2) as {optimisticData: Array<{key: string; value: unknown}>};
            const accountOptimistic = onyxData.optimisticData.find((d) => d.key === ONYXKEYS.ACCOUNT);
            expect(accountOptimistic?.value).toStrictEqual({isLoading: true, errors: null});

            writeSpy.mockRestore();
        });

        test('verify_old success data does not clear twoFactorAuthSecretKey', () => {
            // eslint-disable-next-line rulesdir/no-multiple-api-calls
            const writeSpy = jest.spyOn(API, 'write').mockResolvedValue(undefined);

            SessionUtil.replaceTwoFactorDevice('verify_old', '123456');

            const onyxData = writeSpy.mock.calls.at(0)?.at(2) as {successData: Array<{key: string; value: Record<string, unknown>}>};
            const accountSuccess = onyxData.successData.find((d) => d.key === ONYXKEYS.ACCOUNT);
            expect(accountSuccess?.value).not.toHaveProperty('twoFactorAuthSecretKey');

            writeSpy.mockRestore();
        });

        test('verify_new success data clears twoFactorAuthSecretKey to signal step completion', () => {
            // eslint-disable-next-line rulesdir/no-multiple-api-calls
            const writeSpy = jest.spyOn(API, 'write').mockResolvedValue(undefined);

            SessionUtil.replaceTwoFactorDevice('verify_new', '654321');

            const onyxData = writeSpy.mock.calls.at(0)?.at(2) as {successData: Array<{key: string; value: Record<string, unknown>}>};
            const accountSuccess = onyxData.successData.find((d) => d.key === ONYXKEYS.ACCOUNT);
            expect(accountSuccess?.value.twoFactorAuthSecretKey).toBeNull();

            writeSpy.mockRestore();
        });
    });

    describe('clearTwoFactorAuthSecretKey', () => {
        test('removes twoFactorAuthSecretKey from account state', async () => {
            await Onyx.merge(ONYXKEYS.ACCOUNT, {twoFactorAuthSecretKey: 'SOMESECRETKEY123'});
            await waitForBatchedUpdates();

            let account: Record<string, unknown> | null | undefined;
            Onyx.connect({
                key: ONYXKEYS.ACCOUNT,
                callback: (val) => {
                    account = val as Record<string, unknown> | null | undefined;
                },
            });
            await waitForBatchedUpdates();
            expect(account?.twoFactorAuthSecretKey).toBe('SOMESECRETKEY123');

            SessionUtil.clearTwoFactorAuthSecretKey();
            await waitForBatchedUpdates();

            expect(account).not.toHaveProperty('twoFactorAuthSecretKey');
        });
    });

    describe('SAML sign in', () => {
        test('signInWithShortLivedAuthToken with isSAML=true should set signedInWithSAML in session', async () => {
            let session: OnyxEntry<Session>;
            Onyx.connect({
                key: ONYXKEYS.SESSION,
                callback: (val) => (session = val),
            });

            SessionUtil.signInWithShortLivedAuthToken('testAuthToken', true);
            await waitForBatchedUpdates();

            expect(session?.signedInWithSAML).toBe(true);
        });

        test('signInWithShortLivedAuthToken with isSAML=false should not set signedInWithSAML', async () => {
            let session: OnyxEntry<Session>;
            Onyx.connect({
                key: ONYXKEYS.SESSION,
                callback: (val) => (session = val),
            });

            SessionUtil.signInWithShortLivedAuthToken('testAuthToken', false);
            await waitForBatchedUpdates();

            expect(session?.signedInWithSAML).toBe(false);
        });
    });
});
