source "https://rubygems.org"

# Manage Jekyll version
gem "jekyll", "~> 4.3.4"

# Default theme for new Jekyll sites
gem "minima", "~> 2.5"

# Plugins for Jekyll
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# For development on macOS and Linux (add webrick for Jekyll 4.3+)
gem "webrick", "~> 1.8"

# Nokogiri for HTML editing
gem "nokogiri", "~> 1.12"

# Optional: Add tzinfo for timezone support (mainly for Windows/JRuby environments)
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Lock http_parser.rb gem to v0.6.x for JRuby
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]

