"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.openRouteInDesktopApp = exports.isChromeIOS = exports.isMobileChrome = exports.isModernSafari = exports.isSafari = exports.isMobileWebKit = exports.isMobileSafari = exports.isMobileIOS = exports.isMobile = exports.getBrowser = void 0;
var getBrowser = function () { return ''; };
exports.getBrowser = getBrowser;
var isMobile = function () { return false; };
exports.isMobile = isMobile;
var isMobileIOS = function () { return false; };
exports.isMobileIOS = isMobileIOS;
var isMobileSafari = function () { return false; };
exports.isMobileSafari = isMobileSafari;
var isMobileChrome = function () { return false; };
exports.isMobileChrome = isMobileChrome;
var isMobileWebKit = function () { return false; };
exports.isMobileWebKit = isMobileWebKit;
var isChromeIOS = function () { return false; };
exports.isChromeIOS = isChromeIOS;
var isSafari = function () { return false; };
exports.isSafari = isSafari;
var isModernSafari = function () { return false; };
exports.isModernSafari = isModernSafari;
var openRouteInDesktopApp = function () { };
exports.openRouteInDesktopApp = openRouteInDesktopApp;
