import colors from '../colors';

export default {
    name: 'darkGreen',
    shadow: colors.black,
    link: colors.darkLink,
    linkHover: colors.blueHover,
    componentBG: colors.darkAppBackground,
    hoverComponentBG: colors.darkHighlightBackground,
    activeComponentBG: colors.darkBorders,
    appBG: colors.darkAppBackground,
    heading: colors.darkText,
    sidebar: colors.darkHighlightBackground,
    sidebarHover: colors.darkAppBackground,
    border: colors.darkBorders,
    borderFocus: colors.darkLink,
    icon: colors.darkIcons,
    iconHovered: colors.darkText,
    iconSuccessFill: colors.darkSuccessButton,
    iconReversed: colors.darkAppBackground,
    textSupporting: colors.darkSupportingText,
    text: colors.darkText,
    textError: colors.darkDangerButton,
    textSuccess: colors.darkSuccessButton,
    textBackground: colors.darkHighlightBackground,
    textReversed: colors.darkAppBackground,
    textMutedReversed: colors.darkIcons,
    buttonDefaultBG: colors.darkBorders,
    buttonSuccessBG: colors.darkSuccessButton,
    buttonSuccessHoveredBG: colors.greenHover,
    buttonDangerBG: colors.darkDangerButton,
    buttonDangerPressedBG: colors.redHover,
    buttonDangerDisabledBG: colors.redDisabled,
    online: colors.darkSuccessButton,
    offline: colors.darkIcons,
    sidebarButtonBG: 'rgba(139, 156, 143, 0.25)', // Icons color at 25% opacity
    modalBackdrop: colors.darkIcons,
    modalBackground: colors.darkBorders,
    badgeDangerBG: colors.darkDangerButton,
    badgeDangerPressedBG: colors.redHover,
    badgeDefaultBG: colors.darkBorders,
    badgeSuccessBG: colors.darkSuccessButton,
    badgeSuccessPressedBG: colors.greenHover,
    buttonDisabledBG: colors.darkBorders,
    buttonHoveredBG: colors.darkHighlightBackground,
    buttonPressedBG: colors.darkBorders,
    spinner: colors.darkSupportingText,
    unreadIndicator: colors.darkSuccessButton,
    placeholderText: colors.darkIcons,
    heroCard: colors.darkLink,
    uploadPreviewActivityIndicator: colors.darkHighlightBackground,
};
