import colors from '../colors';

export default {
    shadow: colors.black,
    link: colors.darkerLink,
    linkHover: colors.blueHover,
    componentBG: colors.darkerAppBackground,
    hoverComponentBG: colors.darkerHighlightBackground,
    activeComponentBG: colors.darkerBorders,
    appBG: colors.darkerAppBackground,
    heading: colors.darkerText,
    sidebar: colors.darkerHighlightBackground,
    sidebarHover: colors.darkerAppBackground,
    border: colors.darkerBorders,
    borderFocus: colors.darkerLink,
    icon: colors.darkerIcons,
    iconHovered: colors.darkerText,
    iconSuccessFill: colors.darkerSuccessButton,
    iconReversed: colors.darkerAppBackground,
    textSupporting: colors.darkerSupportingText,
    text: colors.darkerText,
    textError: colors.darkerDangerButton,
    textSuccess: colors.darkerSuccessButton,
    textBackground: colors.darkerHighlightBackground,
    textReversed: colors.darkerAppBackground,
    textMutedReversed: colors.darkerIcons,
    buttonDefaultBG: colors.darkerBorders,
    buttonSuccessBG: colors.darkerSuccessButton,
    buttonSuccessHoveredBG: colors.greenHover,
    buttonDangerBG: colors.darkerDangerButton,
    buttonDangerPressedBG: colors.redHover,
    buttonDangerDisabledBG: colors.redDisabled,
    online: colors.darkerSuccessButton,
    offline: colors.darkerIcons,
    sidebarButtonBG: 'rgba(198, 201, 202, 0.25)', // Icons color at 25% opacity
    modalBackdrop: colors.darkerIcons,
    modalBackground: colors.darkerBorders,
    badgeDangerBG: colors.darkerDangerButton,
    badgeDangerPressedBG: colors.redHover,
    badgeDefaultBG: colors.darkerBorders,
    badgeSuccessBG: colors.darkerSuccessButton,
    badgeSuccessPressedBG: colors.greenHover,
    buttonDisabledBG: colors.darkerBorders,
    buttonHoveredBG: colors.darkerHighlightBackground,
    buttonPressedBG: colors.darkerBorders,
    spinner: colors.darkerSupportingText,
    unreadIndicator: colors.darkerSuccessButton,
    placeholderText: colors.darkerIcons,
    heroCard: colors.darkerLink,
    uploadPreviewActivityIndicator: colors.darkerHighlightBackground,
};
