import colors from '../colors';

export default {
    shadow: colors.black,
    link: colors.blue,
    componentBG: colors.darkmodeDark,
    appBG: colors.darkmodeDark,
    heading: colors.white,
    sidebar: colors.darkmodeDarkest,
    border: colors.charcoal,
    borderFocus: colors.blue,
    icon: colors.gray4,
    iconSuccessFill: colors.green,
    textSupporting: colors.gray3,
    text: colors.white,
    textError: colors.red,
    textSuccess: colors.green,
    textBackground: colors.gray4,
    textReversed: colors.charcoal,
    textMutedReversed: colors.gray3,
    buttonDefaultBG: colors.gray4,
    buttonSuccessBG: colors.green,
    buttonSuccessText: colors.white,
    buttonSuccessHoveredBG: colors.greenHover,
    online: colors.green,
    offline: colors.gray3,
    sidebarButtonBG: 'rgba(198, 201, 202, 0.25)',
    modalBackdrop: colors.darkmodeDarkest,
    pillBG: colors.gray2,
    buttonDisabledBG: colors.gray4,
    buttonHoveredBG: colors.charcoal,
};
