import colors from '../colors';

export default {
    shadow: colors.black,
    link: colors.blue,
    componentBG: colors.white,
    appBG: colors.white,
    heading: colors.charcoal,
    sidebar: colors.gray1,
    border: colors.gray2,
    borderFocus: colors.blue,
    icon: colors.gray3,
    iconSuccessFill: colors.green1,
    textSupporting: colors.gray4,
    text: colors.gray5,
    textError: colors.red,
    textSuccess: colors.green1,
    textBackground: colors.gray1,
    textReversed: colors.white,
    textMutedReversed: colors.gray3,
    buttonDefaultBG: colors.gray2,
    buttonSuccessBG: colors.green1,
    buttonSuccessHoveredBG: colors.green2,
    online: colors.green1,
    offline: colors.gray3,
    sidebarButtonBG: 'rgba(198, 201, 202, 0.25)',
    modalBackdrop: colors.gray3,
    pillBG: colors.gray2,
    buttonDisabledBG: colors.gray2,
    buttonHoveredBG: colors.gray1,
};
