import colors from '../colors';

export default {
    shadow: colors.black,
    link: colors.lightLink,
    linkHover: colors.blueHover,
    componentBG: colors.lightAppBackground,
    hoverComponentBG: colors.lightHighlightBackground,
    activeComponentBG: colors.lightBorders,
    appBG: colors.lightAppBackground,
    heading: colors.lightText,
    sidebar: colors.lightHighlightBackground,
    sidebarHover: colors.lightAppBackground,
    border: colors.lightBorders,
    borderFocus: colors.lightLink,
    icon: colors.lightIcons,
    iconHovered: colors.lightText,
    iconSuccessFill: colors.lightSuccessButton,
    iconReversed: colors.lightAppBackground,
    textSupporting: colors.lightSupportingText,
    text: colors.lightText,
    textError: colors.lightDangerButton,
    textSuccess: colors.lightSuccessButton,
    textBackground: colors.lightHighlightBackground,
    textReversed: colors.lightAppBackground,
    textMutedReversed: colors.lightIcons,
    buttonDefaultBG: colors.lightBorders,
    buttonSuccessBG: colors.lightSuccessButton,
    buttonSuccessHoveredBG: colors.greenHover,
    buttonDangerBG: colors.lightDangerButton,
    buttonDangerPressedBG: colors.redHover,
    buttonDangerDisabledBG: colors.redDisabled,
    online: colors.lightSuccessButton,
    offline: colors.lightIcons,
    sidebarButtonBG: 'rgba(198, 201, 202, 0.25)', // Icons color at 25% opacity
    modalBackdrop: colors.lightIcons,
    modalBackground: colors.lightBorders,
    badgeDangerBG: colors.lightDangerButton,
    badgeDangerPressedBG: colors.redHover,
    badgeDefaultBG: colors.lightBorders,
    badgeSuccessBG: colors.lightSuccessButton,
    badgeSuccessPressedBG: colors.greenHover,
    buttonDisabledBG: colors.lightBorders,
    buttonHoveredBG: colors.lightHighlightBackground,
    buttonPressedBG: colors.lightBorders,
    spinner: colors.lightSupportingText,
    unreadIndicator: colors.lightSuccessButton,
    placeholderText: colors.lightIcons,
    heroCard: colors.lightLink,
    uploadPreviewActivityIndicator: colors.lightHighlightBackground,
};
