import {PixelRatio} from 'react-native';
import variables from './variables';

const styles = () => {
    if (PixelRatio.getFontScale() > 1) {
        return {
            contentHeaderHeight: 100,
            componentSizeSmall: 28,
            componentSizeNormal: 40,
            inputComponentSizeNormal: 42,
            componentSizeLarge: 52,
            componentBorderRadius: 8,
            componentBorderRadiusSmall: 4,
            componentBorderRadiusNormal: 8,
            componentBorderRadiusCard: 12,
            avatarSizeLarge: 80,
            avatarSizeNormal: 40,
            avatarSizeSmall: 28,
            avatarSizeSubscript: 20,
            avatarSizeSmallSubscript: 14,
            fontSizeSingleEmoji: 30,
            fontSizeSingleEmojiHeight: 35,
            fontSizeSmall: 17,
            fontSizeExtraSmall: 9,
            fontSizeLabel: 19,
            fontSizeNormal: 21,
            fontSizeLarge: 19,
            fontSizeHero: 36,
            fontSizeh1: 19,
            fontSizeXXLarge: 28,
            fontSizeXXXLarge: 32,
            fontSizeXXXXXLarge: 48,
            fontSizeNormalHeight: 28,
            lineHeightHero: 40,
            iconSizeXXXSmall: 4,
            iconSizeXXSmall: 8,
            iconSizeExtraSmall: 12,
            iconSizeSmall: 16,
            iconSizeNormal: 20,
            iconSizeLarge: 24,
            iconSizeXLarge: 28,
            iconSizeExtraLarge: 40,
            emojiSize: 20,
            iouAmountTextSize: 40,
            mobileResponsiveWidthBreakpoint: 800,
            tabletResponsiveWidthBreakpoint: 1024,
            safeInsertPercentage: 0.7,
            sideBarWidth: 375,
            pdfPageMaxWidth: 992,
            tooltipzIndex: 10050,
            gutterWidth: 16,
            popoverMenuShadow: '0px 4px 12px 0px rgba(0, 0, 0, 0.06)',
            lineHeightSmall: 16,
            lineHeightNormal: 21,
            lineHeightLarge: 18,
            lineHeightXLarge: 22,
            
            baseTextInputPaddingTop: 18,
            baseTextInputPaddingBottom: 5,
            inputHeight: 72,
            pickerIconTop: 26,
            formErrorLineHeight: 23,
            communicationsLinkHeight: 30,
            alternateTextHeight: 22,

        };
    }

    return {
        contentHeaderHeight: variables.contentHeaderHeight,
        componentSizeSmall: variables.componentSizeSmall,
        componentSizeNormal: variables.componentSizeNormal,
        inputComponentSizeNormal: variables.inputComponentSizeNormal,
        componentSizeLarge: variables.componentSizeLarge,
        componentBorderRadius: variables.componentBorderRadius,
        componentBorderRadiusSmall: variables.componentBorderRadiusSmall,
        componentBorderRadiusNormal: variables.componentBorderRadiusNormal,
        componentBorderRadiusCard: variables.componentBorderRadiusCard,
        avatarSizeLarge: variables.avatarSizeLarge,
        avatarSizeNormal: variables.avatarSizeNormal,
        avatarSizeSmall: variables.avatarSizeSmall,
        avatarSizeSubscript: variables.avatarSizeSubscript,
        avatarSizeSmallSubscript: variables.avatarSizeSmallSubscript,
        fontSizeSingleEmoji: variables.fontSizeSingleEmoji,
        fontSizeSingleEmojiHeight: variables.fontSizeSingleEmojiHeight,
        fontSizeSmall: variables.fontSizeSmall,
        fontSizeExtraSmall: variables.fontSizeExtraSmall,
        fontSizeLabel: variables.fontSizeLabel,
        fontSizeNormal: variables.fontSizeNormal,
        fontSizeLarge: variables.fontSizeLarge,
        fontSizeHero: variables.fontSizeHero,
        fontSizeh1: variables.fontSizeh1,
        fontSizeXXLarge: variables.fontSizeXXLarge,
        fontSizeXXXLarge: variables.fontSizeXXXLarge,
        fontSizeXXXXXLarge: variables.fontSizeXXXXXLarge,
        fontSizeNormalHeight: variables.fontSizeNormalHeight,
        lineHeightHero: variables.lineHeightHero,
        iconSizeXXXSmall: variables.iconSizeXXXSmall,
        iconSizeXXSmall: variables.iconSizeXXSmall,
        iconSizeExtraSmall: variables.iconSizeExtraSmall,
        iconSizeSmall: variables.iconSizeSmall,
        iconSizeNormal: variables.iconSizeNormal,
        iconSizeLarge: variables.iconSizeLarge,
        iconSizeXLarge: variables.iconSizeXLarge,
        iconSizeExtraLarge: variables.iconSizeExtraLarge,
        emojiSize: variables.emojiSize,
        iouAmountTextSize: variables.iouAmountTextSize,
        mobileResponsiveWidthBreakpoint: variables.mobileResponsiveWidthBreakpoint,
        tabletResponsiveWidthBreakpoint: variables.tabletResponsiveWidthBreakpoint,
        safeInsertPercentage: variables.safeInsertPercentage,
        sideBarWidth: variables.sideBarWidth,
        pdfPageMaxWidth: variables.pdfPageMaxWidth,
        tooltipzIndex: variables.tooltipzIndex,
        gutterWidth: variables.gutterWidth,
        popoverMenuShadow: variables.popoverMenuShadow,
        lineHeightSmall: variables.lineHeightSmall,
        lineHeightNormal: variables.lineHeightNormal,
        lineHeightLarge: variables.lineHeightLarge,
        baseTextInputPaddingTop: variables.baseTextInputPaddingTop,
        baseTextInputPaddingBottom: variables.baseTextInputPaddingBottom,
        inputHeight: variables.inputHeight,
        pickerIconTop: variables.pickerIconTop,
        formErrorLineHeight: variables.formErrorLineHeight,
        communicationsLinkHeight: variables.communicationsLinkHeight,
        alternateTextHeight: variables.alternateTextHeight,
    };
};
export default styles;
