export default {
    contentHeaderHeight: 65,
    componentSizeSmall: 28,
    componentSizeNormal: 40,
    componentSizeLarge: 52,
    componentBorderRadius: 8,
    fontSizeSmall: 11,
    fontSizeLabel: 13,
    fontSizeNormal: 15,
    fontSizeLarge: 17,
    fontSizeh1: 19,
    iconSizeSmall: 12,
    iconSizeNormal: 20,
    mobileResponsiveWidthBreakpoint: 800,
    safeInsertPercentage: 0.7,
    sideBarWidth: 375,
};
