import {act, cleanup, render, waitFor} from '@testing-library/react-native';

import * as AppActions from '@libs/actions/App';
import {hasAuthToken} from '@libs/actions/Session';
import * as Session from '@libs/actions/Session';
import Navigation from '@libs/Navigation/Navigation';
import {getCurrentUserEmail, setLastShortAuthToken} from '@libs/Network/NetworkStore';

import App from '@src/App';
import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';
import ROUTES from '@src/ROUTES';

import type {OnyxEntry, OnyxMultiSetInput} from 'react-native-onyx';

import {Str} from 'expensify-common';
import {Linking} from 'react-native';
import Onyx from 'react-native-onyx';

import {createRandomReport} from '../utils/collections/reports';
import PusherHelper from '../utils/PusherHelper';
import * as TestHelper from '../utils/TestHelper';
import waitForBatchedUpdatesWithAct from '../utils/waitForBatchedUpdatesWithAct';
import waitForNetworkPromises from '../utils/waitForNetworkPromises';
import wrapOnyxWithWaitForBatchedUpdates from '../utils/wrapOnyxWithWaitForBatchedUpdates';

jest.mock('@libs/BootSplash', () => ({
    hide: jest.fn().mockResolvedValue(undefined),
}));

const TEST_USER_ACCOUNT_ID_1 = 123;
const TEST_USER_LOGIN_1 = 'test@test.com';
// cspell:disable-next-line
const TEST_AUTH_TOKEN_1 = 'asdfghjkl';

const TEST_USER_ACCOUNT_ID_2 = 456;
const TEST_USER_LOGIN_2 = 'test2@test.com';
// cspell:disable-next-line
const TEST_AUTH_TOKEN_2 = 'zxcvbnm';

// We need a large timeout here as we are lazy loading React Navigation screens and this test is running against the entire mounted App
jest.setTimeout(120000);

// Full-App integration tests below render <App /> and drain the entire React/Onyx work queue via act().
// With coverage enabled and other tests in the same CI shard competing for CPU, they can exceed 4 minutes.
const FULL_APP_UI_TEST_TIMEOUT_MS = 6 * 60 * 1000;
TestHelper.setupApp();
TestHelper.setupGlobalFetchMock();

const report = createRandomReport(7, undefined);

function getInitialURL() {
    const params = new URLSearchParams();

    params.set('exitTo', `${ROUTES.REPORT}/${report.reportID}`);
    params.set('email', TEST_USER_LOGIN_1);
    params.set('shortLivedAuthToken', TEST_AUTH_TOKEN_1);

    const deeplinkUrl = `${CONST.DEEPLINK_BASE_URL}/transition?${params.toString()}`;
    return deeplinkUrl;
}

// cspell:disable-next-line
const TEST_SUPPORT_AUTH_TOKEN = 'supporttoken123';

function getSupportAuthURL() {
    const params = new URLSearchParams();

    params.set('email', TEST_USER_LOGIN_1);
    params.set('delegatorEmail', TEST_USER_LOGIN_2);
    params.set('shortLivedAuthToken', TEST_SUPPORT_AUTH_TOKEN);
    params.set('authTokenType', CONST.AUTH_TOKEN_TYPES.SUPPORT);

    return `${CONST.DEEPLINK_BASE_URL}/transition?${params.toString()}`;
}

describe('Deep linking', () => {
    let lastVisitedPath: string | undefined;
    let lastVisitedPathConnectionID: ReturnType<typeof Onyx.connect> | undefined;
    let originalSignInWithShortLivedAuthToken: typeof Session.signInWithShortLivedAuthToken;

    beforeAll(() => {
        originalSignInWithShortLivedAuthToken = Session.signInWithShortLivedAuthToken;
    });

    beforeEach(() => {
        jest.restoreAllMocks();
        wrapOnyxWithWaitForBatchedUpdates(Onyx);

        lastVisitedPathConnectionID = Onyx.connect({
            key: ONYXKEYS.LAST_VISITED_PATH,
            callback: (val: OnyxEntry<string>) => (lastVisitedPath = val),
        });

        // Set session state directly via multiSet rather than waiting for the API.read response
        // (optimistic→network→finally Onyx cycle) to keep the test fast. Then call through to
        // the real signInWithShortLivedAuthToken so it sets NetworkStore.lastShortAuthToken —
        // the token-cache guard in LogInWithShortLivedAuthTokenPage reads that value to skip
        // re-authentication after sign-out, which is exactly what the second test asserts.
        jest.spyOn(Session, 'signInWithShortLivedAuthToken').mockImplementation(() => {
            Onyx.multiSet({
                [ONYXKEYS.CREDENTIALS]: {
                    login: TEST_USER_LOGIN_1,
                    autoGeneratedLogin: Str.guid('expensify.cash-'),
                    autoGeneratedPassword: Str.guid(),
                },
                [ONYXKEYS.ACCOUNT]: {validated: true, isUsingExpensifyCard: false},
                [ONYXKEYS.PERSONAL_DETAILS_LIST]: {
                    [TEST_USER_ACCOUNT_ID_1]: TestHelper.buildPersonalDetails(TEST_USER_LOGIN_1, TEST_USER_ACCOUNT_ID_1, 'Test'),
                },
                [ONYXKEYS.SESSION]: {
                    authToken: TEST_AUTH_TOKEN_1,
                    accountID: TEST_USER_ACCOUNT_ID_1,
                    email: TEST_USER_LOGIN_1,
                    encryptedAuthToken: TEST_AUTH_TOKEN_1,
                },
                [ONYXKEYS.NVP_PRIVATE_PUSH_NOTIFICATION_ID]: 'randomID',
            });
            return originalSignInWithShortLivedAuthToken(TEST_AUTH_TOKEN_1);
        });

        // Set the keys the app needs to finish loading rather than going through
        // getPolicyParamsForOpenOrReconnect + writeWithNoDuplicatesConflictAction(OPEN_APP),
        // which adds a policy-collection read, and a full
        // request-queue round-trip with optimistic→network→finally Onyx data.
        // NVP_ONBOARDING suppresses the onboarding flow that would otherwise render
        // extra screens and inflate the React work queue drained by act().
        // Single multiSet keeps this to one batched-update cycle. The report collection key
        // is cast because multiSet's type only covers non-computed keys.
        jest.spyOn(AppActions, 'openApp').mockImplementation(() =>
            Onyx.multiSet({
                [`${ONYXKEYS.COLLECTION.REPORT}${report.reportID}`]: report,
                [ONYXKEYS.IS_LOADING_APP]: false,
                [ONYXKEYS.IS_LOADING_REPORT_DATA]: false,
                [ONYXKEYS.HAS_LOADED_APP]: true,
                [ONYXKEYS.NVP_ONBOARDING]: {hasCompletedGuidedSetupFlow: true},
            } as unknown as OnyxMultiSetInput),
        );
    });

    afterEach(async () => {
        if (lastVisitedPathConnectionID) {
            Onyx.disconnect(lastVisitedPathConnectionID);
            lastVisitedPathConnectionID = undefined;
        }
        cleanup();
        await act(async () => {
            await Onyx.clear();
        });
        await waitForBatchedUpdatesWithAct();
        PusherHelper.teardown();
        jest.clearAllMocks();
        lastVisitedPath = undefined;
        Linking.setInitialURL('');
        setLastShortAuthToken(null);
    });

    // This test renders the full App and processes a deep-link sign-in flow, so it runs
    // significantly longer than the suite default on loaded CI runners (see FULL_APP_UI_TEST_TIMEOUT_MS).
    it(
        'should not remember the report path of the last deep link login after signing out and in again',
        async () => {
            expect(hasAuthToken()).toBe(false);

            const url = getInitialURL();
            // User signs in automatically when the app is rendered because of the deep link
            Linking.setInitialURL(url);
            const {unmount} = render(<App />);

            await waitForBatchedUpdatesWithAct();

            const reportPath = `/${ROUTES.REPORT}/${report.reportID}`;
            expect(decodeURIComponent(lastVisitedPath ?? '')).toContain(reportPath);

            expect(hasAuthToken()).toBe(true);

            await TestHelper.signOutTestUser();
            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();

            expect(hasAuthToken()).toBe(false);

            await TestHelper.signInWithTestUser(TEST_USER_ACCOUNT_ID_2, TEST_USER_LOGIN_2, undefined, TEST_AUTH_TOKEN_2);

            await waitForBatchedUpdatesWithAct();

            expect(lastVisitedPath).toBeDefined();
            expect(decodeURIComponent(lastVisitedPath ?? '')).not.toContain(reportPath);

            unmount();
            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();
        },
        FULL_APP_UI_TEST_TIMEOUT_MS,
    );

    // This test renders the full App three times, so it runs significantly longer than
    // the suite default on loaded CI runners (see FULL_APP_UI_TEST_TIMEOUT_MS).
    it(
        'should not reuse the last deep link and log in again when signing out',
        async () => {
            expect(hasAuthToken()).toBe(false);

            const {unmount: unmount1} = render(<App />);
            await TestHelper.signInWithTestUser(TEST_USER_ACCOUNT_ID_2, TEST_USER_LOGIN_2, undefined, TEST_AUTH_TOKEN_2);

            await waitForBatchedUpdatesWithAct();

            expect(hasAuthToken()).toBe(true);
            expect(getCurrentUserEmail()).toBe(TEST_USER_LOGIN_2);
            // Unmount so we can prepare the deep link login
            unmount1();

            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();

            const url = getInitialURL();
            // User signs in automatically when the app is remounted because of the deep link.
            // This overrides the previous sign-in.
            Linking.setInitialURL(url);
            const {unmount: unmount2} = render(<App />);

            await waitForBatchedUpdatesWithAct();

            expect(getCurrentUserEmail()).toBe(TEST_USER_LOGIN_1);

            await TestHelper.signOutTestUser();
            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();

            // In a failing scenario, remounting triggers the sign-in with the deep link again because it still remembers it.
            // However, we've implemented a fix so that it does not reuse the last deep link.
            unmount2();
            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();

            const {unmount: unmount3} = render(<App />);

            await waitForBatchedUpdatesWithAct();

            expect(hasAuthToken()).toBe(false);

            unmount3();
            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();
        },
        FULL_APP_UI_TEST_TIMEOUT_MS,
    );
});

describe('Support auth token login', () => {
    beforeEach(() => {
        jest.restoreAllMocks();
        wrapOnyxWithWaitForBatchedUpdates(Onyx);

        jest.spyOn(Session, 'signInWithSupportAuthToken').mockImplementation(() => {});

        // Set the keys the app needs to finish loading rather than going through a full OpenApp round-trip.
        jest.spyOn(AppActions, 'openApp').mockImplementation(() =>
            Onyx.multiSet({
                [ONYXKEYS.IS_LOADING_APP]: false,
                [ONYXKEYS.IS_LOADING_REPORT_DATA]: false,
                [ONYXKEYS.HAS_LOADED_APP]: true,
                [ONYXKEYS.NVP_ONBOARDING]: {hasCompletedGuidedSetupFlow: true},
            }),
        );
    });

    afterEach(async () => {
        cleanup();
        await act(async () => {
            await Onyx.clear();
        });
        await waitForBatchedUpdatesWithAct();
        await waitForNetworkPromises();
        PusherHelper.teardown();
        jest.clearAllMocks();
        Linking.setInitialURL('');
        setLastShortAuthToken(null);
    });

    // Renders the full App and processes a supportal transition, so it runs longer than the suite default (see FULL_APP_UI_TEST_TIMEOUT_MS).
    it(
        'does not fire the support sign-in again when LogOutPreviousUserPage re-processes an already-handled token',
        async () => {
            expect(hasAuthToken()).toBe(false);

            // Sign in so the app is on AuthScreens, where LogOutPreviousUserPage owns the /transition route.
            const {unmount: unmount1} = render(<App />);
            await TestHelper.signInWithTestUser(TEST_USER_ACCOUNT_ID_2, TEST_USER_LOGIN_2, undefined, TEST_AUTH_TOKEN_2);

            await waitForBatchedUpdatesWithAct();

            expect(hasAuthToken()).toBe(true);
            unmount1();

            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();

            // The public transition page (LogInWithShortLivedAuthTokenPage) records the support token when it
            // fires the sign-in. Simulate that, then re-process the SAME support deep link, which lands on
            // LogOutPreviousUserPage. It must skip the duplicate sign-in; before the fix it fired
            // unconditionally and tripped the support-token rate limit.
            setLastShortAuthToken(TEST_SUPPORT_AUTH_TOKEN);
            Linking.setInitialURL(getSupportAuthURL());
            const {unmount: unmount2} = render(<App />);

            await waitForBatchedUpdatesWithAct();

            expect(Session.signInWithSupportAuthToken).not.toHaveBeenCalled();

            unmount2();
            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();
        },
        FULL_APP_UI_TEST_TIMEOUT_MS,
    );
});

describe('SAML required sign-in loop', () => {
    beforeEach(() => {
        jest.restoreAllMocks();
        wrapOnyxWithWaitForBatchedUpdates(Onyx);
    });

    afterEach(async () => {
        cleanup();
        await act(async () => {
            await Onyx.clear();
        });
        await waitForBatchedUpdatesWithAct();
        await waitForNetworkPromises();
        PusherHelper.teardown();
        jest.clearAllMocks();
        Linking.setInitialURL('');
        setLastShortAuthToken(null);
    });

    // Regression test for the global New Expensify SAML web login loop (https://github.com/Expensify/Expensify/issues/657345).
    // A SAML redirect-back short-lived token exchange sets account.isLoading, which is the same signal that drives
    // SignInPage's shouldInitiateSAMLLogin. Re-initiating SAML while that exchange is in flight tears the page down
    // before the token can be consumed, so the user loops back to their IdP forever. The RAM_ONLY_IS_AUTHENTICATING_WITH_SHORT_LIVED_TOKEN
    // flag lets SignInPage tell the two apart, so it must not re-initiate SAML while the flag is set.
    it(
        'does not re-initiate SAML while a short-lived token exchange is in flight',
        async () => {
            const navigateSpy = jest.spyOn(Navigation, 'navigate');

            await act(async () => {
                await Onyx.multiSet({
                    [ONYXKEYS.CREDENTIALS]: {login: TEST_USER_LOGIN_1},
                    [ONYXKEYS.ACCOUNT]: {isSAMLRequired: true, isLoading: true, validated: true},
                    [ONYXKEYS.RAM_ONLY_IS_AUTHENTICATING_WITH_SHORT_LIVED_TOKEN]: true,
                });
            });

            const {unmount} = render(<App />);
            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();

            // The exchange is in flight, so SAML must not be re-initiated.
            expect(navigateSpy).not.toHaveBeenCalledWith(ROUTES.SAML_SIGN_IN);

            // Positive control: once the exchange is no longer in flight, SAML re-initiates as usual. This proves the
            // guard (and not the harness never reaching the decision) is what suppressed the navigation above.
            navigateSpy.mockClear();
            await act(async () => {
                await Onyx.set(ONYXKEYS.RAM_ONLY_IS_AUTHENTICATING_WITH_SHORT_LIVED_TOKEN, false);
            });
            await waitForBatchedUpdatesWithAct();

            await waitFor(() => expect(navigateSpy).toHaveBeenCalledWith(ROUTES.SAML_SIGN_IN));

            unmount();
            await waitForBatchedUpdatesWithAct();
            await waitForNetworkPromises();
        },
        FULL_APP_UI_TEST_TIMEOUT_MS,
    );
});
