import {cleanup, render} from '@testing-library/react-native';
import type {OnyxEntry} from 'react-native-onyx';
import Onyx from 'react-native-onyx';
import redirectToSignIn from '@userActions/SignInRedirect';
import {signInWithShortLivedAuthToken} from '@userActions/Session';
import {setLastShortAuthToken} from '@libs/Network/NetworkStore';
import LogInWithShortLivedAuthTokenPage from '@pages/LogInWithShortLivedAuthTokenPage';
import ONYXKEYS from '@src/ONYXKEYS';
import ROUTES from '@src/ROUTES';
import {createRandomReport} from '../utils/collections/reports';
import waitForBatchedUpdatesWithAct from '../utils/waitForBatchedUpdatesWithAct';

jest.mock('@libs/BootSplash', () => ({
    hide: jest.fn().mockResolvedValue(undefined),
}));

jest.mock('@components/FullscreenLoadingIndicator', () => 'FullScreenLoadingIndicator');

jest.mock('@userActions/Session', () => ({
    setAccountError: jest.fn(),
    signInWithShortLivedAuthToken: jest.fn(),
    signInWithSupportAuthToken: jest.fn(),
}));

Onyx.init({
    keys: ONYXKEYS,
});

const TEST_USER_ACCOUNT_ID_1 = 123;
const TEST_USER_LOGIN_1 = 'test@test.com';
// cspell:disable-next-line
const TEST_AUTH_TOKEN_1 = 'asdfghjkl';

const TEST_USER_ACCOUNT_ID_2 = 456;
const TEST_USER_LOGIN_2 = 'test2@test.com';
// cspell:disable-next-line
const TEST_AUTH_TOKEN_2 = 'zxcvbnm';

const report = createRandomReport(7, undefined);
const reportPath = `/${ROUTES.REPORT}/${report.reportID}`;

function signInTestUser(accountID: number, login: string, authToken: string) {
    return Onyx.multiSet({
        [ONYXKEYS.CREDENTIALS]: {
            login,
            autoGeneratedLogin: `expensify.cash-${accountID}`,
            autoGeneratedPassword: 'password',
        },
        [ONYXKEYS.ACCOUNT]: {
            validated: true,
            isUsingExpensifyCard: false,
        },
        [ONYXKEYS.SESSION]: {
            authToken,
            accountID,
            email: login,
            encryptedAuthToken: authToken,
        },
        [ONYXKEYS.NVP_PRIVATE_PUSH_NOTIFICATION_ID]: 'randomID',
    });
}

function renderTransitionPage(shortLivedAuthToken: string) {
    return render(
        <LogInWithShortLivedAuthTokenPage
            route={{params: {shortLivedAuthToken}} as never}
            navigation={{} as never}
        />,
    );
}

describe('Deep linking', () => {
    let lastVisitedPath: string | undefined;
    let lastVisitedPathConnectionID: ReturnType<typeof Onyx.connect> | undefined;
    let authToken: string | undefined;
    let sessionConnectionID: ReturnType<typeof Onyx.connect> | undefined;

    beforeEach(() => {
        lastVisitedPathConnectionID = Onyx.connect({
            key: ONYXKEYS.LAST_VISITED_PATH,
            callback: (val: OnyxEntry<string>) => (lastVisitedPath = val),
        });
        sessionConnectionID = Onyx.connect({
            key: ONYXKEYS.SESSION,
            callback: (val) => (authToken = val?.authToken),
        });
    });

    afterEach(async () => {
        if (lastVisitedPathConnectionID) {
            Onyx.disconnect(lastVisitedPathConnectionID);
            lastVisitedPathConnectionID = undefined;
        }
        if (sessionConnectionID) {
            Onyx.disconnect(sessionConnectionID);
            sessionConnectionID = undefined;
        }
        cleanup();
        await Onyx.clear();
        await waitForBatchedUpdatesWithAct();
        jest.clearAllMocks();
        lastVisitedPath = undefined;
        authToken = undefined;
        setLastShortAuthToken(null);
    });

    it('should not remember the report path of the last deep link login after signing out and in again', async () => {
        expect(authToken).toBeUndefined();

        await signInTestUser(TEST_USER_ACCOUNT_ID_1, TEST_USER_LOGIN_1, TEST_AUTH_TOKEN_1);
        await Onyx.merge(ONYXKEYS.LAST_VISITED_PATH, reportPath);

        await waitForBatchedUpdatesWithAct();

        expect(decodeURIComponent(lastVisitedPath ?? '')).toContain(reportPath);
        expect(authToken).toBe(TEST_AUTH_TOKEN_1);

        await redirectToSignIn();
        await waitForBatchedUpdatesWithAct();

        expect(authToken).toBeUndefined();
        expect(decodeURIComponent(lastVisitedPath ?? '')).not.toContain(reportPath);

        await signInTestUser(TEST_USER_ACCOUNT_ID_2, TEST_USER_LOGIN_2, TEST_AUTH_TOKEN_2);

        await waitForBatchedUpdatesWithAct();

        expect(decodeURIComponent(lastVisitedPath ?? '')).not.toContain(reportPath);
    });

    it('should not reuse the last deep link and log in again when signing out', async () => {
        expect(authToken).toBeUndefined();

        renderTransitionPage(TEST_AUTH_TOKEN_2);
        await waitForBatchedUpdatesWithAct();

        expect(signInWithShortLivedAuthToken).toHaveBeenCalledWith(TEST_AUTH_TOKEN_2, false);

        cleanup();
        jest.clearAllMocks();
        setLastShortAuthToken(TEST_AUTH_TOKEN_1);

        renderTransitionPage(TEST_AUTH_TOKEN_1);
        await waitForBatchedUpdatesWithAct();

        expect(signInWithShortLivedAuthToken).not.toHaveBeenCalled();
        expect(authToken).toBeUndefined();
    });
});
