const DEFAULT_MIN_ZOOM_SCALE = 1;
const DEFAULT_MAX_ZOOM_SCALE = 20;

const MIN_ZOOM_SCALE_BOUNCE = 0.7;
const MAX_ZOOM_SCALE_BOUNCE = 1.5;

export {DEFAULT_MIN_ZOOM_SCALE, DEFAULT_MAX_ZOOM_SCALE, MIN_ZOOM_SCALE_BOUNCE, MAX_ZOOM_SCALE_BOUNCE};
