import type React from 'react';
import CONST from '@src/CONST';
import type * as OnyxTypes from '@src/types/onyx';
import PolicyChangeLogRenderer from './renderers/PolicyChangeLogRenderer';
import SystemMessageRenderer from './renderers/SystemMessageRenderer';
import type ActionRendererProps from './types';

const PCL = CONST.REPORT.ACTIONS.TYPE.POLICY_CHANGE_LOG;

const actionRendererMap: Partial<Record<string, React.ComponentType<ActionRendererProps>>> = {
    // System messages
    [CONST.REPORT.ACTIONS.TYPE.HOLD]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.HOLD_COMMENT]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.UNHOLD]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.REJECTED]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.RETRACTED]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.REOPENED]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.REJECTEDTRANSACTION_THREAD]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.REJECTED_TRANSACTION_MARKASRESOLVED]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.MERGED_WITH_CASH_TRANSACTION]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.RECEIPT_SCAN_FAILED]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.CHANGE_POLICY]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.DELETED_TRANSACTION]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.UNAPPROVED]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.DISMISSED_VIOLATION]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.RESOLVED_DUPLICATES]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.MARKED_REIMBURSED]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.REMOVED_FROM_APPROVAL_CHAIN]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.DEMOTED_FROM_WORKSPACE]: SystemMessageRenderer,
    [CONST.REPORT.ACTIONS.TYPE.ROOM_CHANGE_LOG.LEAVE_ROOM]: SystemMessageRenderer,

    // Policy change log types (no policy dependency)
    [PCL.LEAVE_ROOM]: PolicyChangeLogRenderer,
    [PCL.UPDATE_NAME]: PolicyChangeLogRenderer,
    [PCL.UPDATE_CURRENCY]: PolicyChangeLogRenderer,
    [PCL.UPDATE_AUTO_REPORTING_FREQUENCY]: PolicyChangeLogRenderer,
    [PCL.UPDATE_CATEGORIES]: PolicyChangeLogRenderer,
    [PCL.IMPORT_TAGS]: PolicyChangeLogRenderer,
    [PCL.DELETE_ALL_TAGS]: PolicyChangeLogRenderer,
    [PCL.ADD_TAX]: PolicyChangeLogRenderer,
    [PCL.DELETE_TAX]: PolicyChangeLogRenderer,
    [PCL.UPDATE_TAX]: PolicyChangeLogRenderer,
    [PCL.UPDATE_TAG_LIST_NAME]: PolicyChangeLogRenderer,
    [PCL.UPDATE_TAG_LIST]: PolicyChangeLogRenderer,
    [PCL.UPDATE_TAG_LIST_REQUIRED]: PolicyChangeLogRenderer,
    [PCL.ADD_TAG]: PolicyChangeLogRenderer,
    [PCL.DELETE_TAG]: PolicyChangeLogRenderer,
    [PCL.UPDATE_TAG]: PolicyChangeLogRenderer,
    [PCL.UPDATE_TAG_ENABLED]: PolicyChangeLogRenderer,
    [PCL.UPDATE_TAG_NAME]: PolicyChangeLogRenderer,
    [PCL.DELETE_MULTIPLE_TAGS]: PolicyChangeLogRenderer,
    [PCL.UPDATE_CUSTOM_UNIT]: PolicyChangeLogRenderer,
    [PCL.IMPORT_CUSTOM_UNIT_RATES]: PolicyChangeLogRenderer,
    [PCL.ADD_CUSTOM_UNIT_RATE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_CUSTOM_UNIT_RATE]: PolicyChangeLogRenderer,
    [PCL.DELETE_CUSTOM_UNIT_RATE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_CUSTOM_UNIT_SUB_RATE]: PolicyChangeLogRenderer,
    [PCL.DELETE_CUSTOM_UNIT_SUB_RATE]: PolicyChangeLogRenderer,
    [PCL.ADD_REPORT_FIELD]: PolicyChangeLogRenderer,
    [PCL.UPDATE_REPORT_FIELD]: PolicyChangeLogRenderer,
    [PCL.DELETE_REPORT_FIELD]: PolicyChangeLogRenderer,
    [PCL.UPDATE_FIELD]: PolicyChangeLogRenderer,
    [PCL.UPDATE_FEATURE_ENABLED]: PolicyChangeLogRenderer,
    [PCL.UPDATE_IS_ATTENDEE_TRACKING_ENABLED]: PolicyChangeLogRenderer,
    [PCL.UPDATE_DEFAULT_APPROVER]: PolicyChangeLogRenderer,
    [PCL.UPDATE_SUBMITS_TO]: PolicyChangeLogRenderer,
    [PCL.UPDATE_FORWARDS_TO]: PolicyChangeLogRenderer,
    [PCL.UPDATE_AUTO_PAY_APPROVED_REPORTS_ENABLED]: PolicyChangeLogRenderer,
    [PCL.UPDATE_AUTO_REIMBURSEMENT]: PolicyChangeLogRenderer,
    [PCL.UPDATE_INVOICE_COMPANY_NAME]: PolicyChangeLogRenderer,
    [PCL.UPDATE_INVOICE_COMPANY_WEBSITE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_REIMBURSER]: PolicyChangeLogRenderer,
    [PCL.UPDATE_REIMBURSEMENT_ENABLED]: PolicyChangeLogRenderer,
    [PCL.UPDATE_ACH_ACCOUNT]: PolicyChangeLogRenderer,
    [PCL.UPDATE_ADDRESS]: PolicyChangeLogRenderer,
    [PCL.UPDATE_MAX_EXPENSE_AMOUNT_NO_RECEIPT]: PolicyChangeLogRenderer,
    [PCL.UPDATE_MAX_EXPENSE_AMOUNT]: PolicyChangeLogRenderer,
    [PCL.UPDATE_MAX_EXPENSE_AGE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_DEFAULT_BILLABLE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_DEFAULT_REIMBURSABLE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_DEFAULT_TITLE_ENFORCED]: PolicyChangeLogRenderer,
    [PCL.ADD_EMPLOYEE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_EMPLOYEE]: PolicyChangeLogRenderer,
    [PCL.DELETE_EMPLOYEE]: PolicyChangeLogRenderer,
    [PCL.ADD_APPROVER_RULE]: PolicyChangeLogRenderer,
    [PCL.DELETE_APPROVER_RULE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_APPROVER_RULE]: PolicyChangeLogRenderer,
    [PCL.ADD_INTEGRATION]: PolicyChangeLogRenderer,
    [PCL.DELETE_INTEGRATION]: PolicyChangeLogRenderer,
    [PCL.UPDATE_AUDIT_RATE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_MANUAL_APPROVAL_THRESHOLD]: PolicyChangeLogRenderer,
    [PCL.UPDATE_TIME_ENABLED]: PolicyChangeLogRenderer,
    [PCL.UPDATE_TIME_RATE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_PROHIBITED_EXPENSES]: PolicyChangeLogRenderer,
    [PCL.UPDATE_REIMBURSEMENT_CHOICE]: PolicyChangeLogRenderer,
    [PCL.SET_AUTO_JOIN]: PolicyChangeLogRenderer,
    [PCL.UPDATE_DEFAULT_TITLE]: PolicyChangeLogRenderer,
    [PCL.UPDATE_AUTO_HARVESTING]: PolicyChangeLogRenderer,
    [PCL.INDIVIDUAL_BUDGET_NOTIFICATION]: PolicyChangeLogRenderer,
    [PCL.SHARED_BUDGET_NOTIFICATION]: PolicyChangeLogRenderer,
    [PCL.CORPORATE_UPGRADE]: PolicyChangeLogRenderer,
    [PCL.CORPORATE_FORCE_UPGRADE]: PolicyChangeLogRenderer,
    [PCL.TEAM_DOWNGRADE]: PolicyChangeLogRenderer,
};

function getActionRenderer(action: OnyxTypes.ReportAction): React.ComponentType<ActionRendererProps> | null {
    return actionRendererMap[action.actionName] ?? null;
}

export default getActionRenderer;
