import Avatar1 from '@assets/images/avatars/group/default-avatar_1.svg';
import Avatar2 from '@assets/images/avatars/group/default-avatar_2.svg';
import Avatar3 from '@assets/images/avatars/group/default-avatar_3.svg';
import Avatar4 from '@assets/images/avatars/group/default-avatar_4.svg';
import Avatar5 from '@assets/images/avatars/group/default-avatar_5.svg';
import Avatar6 from '@assets/images/avatars/group/default-avatar_6.svg';
import Avatar7 from '@assets/images/avatars/group/default-avatar_7.svg';
import Avatar8 from '@assets/images/avatars/group/default-avatar_8.svg';
import Avatar9 from '@assets/images/avatars/group/default-avatar_9.svg';
import Avatar10 from '@assets/images/avatars/group/default-avatar_10.svg';
import Avatar11 from '@assets/images/avatars/group/default-avatar_11.svg';
import Avatar12 from '@assets/images/avatars/group/default-avatar_12.svg';
import Avatar13 from '@assets/images/avatars/group/default-avatar_13.svg';
import Avatar14 from '@assets/images/avatars/group/default-avatar_14.svg';
import Avatar15 from '@assets/images/avatars/group/default-avatar_15.svg';
import Avatar16 from '@assets/images/avatars/group/default-avatar_16.svg';
import Avatar17 from '@assets/images/avatars/group/default-avatar_17.svg';
import Avatar18 from '@assets/images/avatars/group/default-avatar_18.svg';

export {Avatar1, Avatar2, Avatar3, Avatar4, Avatar5, Avatar6, Avatar7, Avatar8, Avatar9, Avatar10, Avatar11, Avatar12, Avatar13, Avatar14, Avatar15, Avatar16, Avatar17, Avatar18};
