"use strict";
exports.__esModule = true;
var CONST_1 = require("@src/CONST");
var _a = CONST_1["default"].PRODUCT_TRAINING_TOOLTIP_NAMES, CONCEIRGE_LHN_GBR = _a.CONCEIRGE_LHN_GBR, RENAME_SAVED_SEARCH = _a.RENAME_SAVED_SEARCH, BOTTOM_NAV_INBOX_TOOLTIP = _a.BOTTOM_NAV_INBOX_TOOLTIP, LHN_WORKSPACE_CHAT_TOOLTIP = _a.LHN_WORKSPACE_CHAT_TOOLTIP, GLOBAL_CREATE_TOOLTIP = _a.GLOBAL_CREATE_TOOLTIP, SCAN_TEST_TOOLTIP = _a.SCAN_TEST_TOOLTIP, SCAN_TEST_TOOLTIP_MANAGER = _a.SCAN_TEST_TOOLTIP_MANAGER, SCAN_TEST_CONFIRMATION = _a.SCAN_TEST_CONFIRMATION;
