
exports.__esModule = true;
const CONST_1 = require('@src/CONST');

const _a = CONST_1['default'].PRODUCT_TRAINING_TOOLTIP_NAMES;
    const CONCEIRGE_LHN_GBR = _a.CONCEIRGE_LHN_GBR;
    const RENAME_SAVED_SEARCH = _a.RENAME_SAVED_SEARCH;
    const BOTTOM_NAV_INBOX_TOOLTIP = _a.BOTTOM_NAV_INBOX_TOOLTIP;
    const LHN_WORKSPACE_CHAT_TOOLTIP = _a.LHN_WORKSPACE_CHAT_TOOLTIP;
    const GLOBAL_CREATE_TOOLTIP = _a.GLOBAL_CREATE_TOOLTIP;
    const SCAN_TEST_TOOLTIP = _a.SCAN_TEST_TOOLTIP;
    const SCAN_TEST_TOOLTIP_MANAGER = _a.SCAN_TEST_TOOLTIP_MANAGER;
    const SCAN_TEST_CONFIRMATION = _a.SCAN_TEST_CONFIRMATION;
