const NAVIGATION_FOCUS_ROUTE_DATASET_KEY = 'navigationFocusRouteKey' as const;
const NAVIGATION_FOCUS_ROUTE_DATA_ATTRIBUTE = 'data-navigation-focus-route-key' as const;
const NAVIGATION_FOCUS_ROUTE_SELECTOR = `[${NAVIGATION_FOCUS_ROUTE_DATA_ATTRIBUTE}]` as const;

export {NAVIGATION_FOCUS_ROUTE_DATASET_KEY, NAVIGATION_FOCUS_ROUTE_DATA_ATTRIBUTE, NAVIGATION_FOCUS_ROUTE_SELECTOR};
