import HybridAppModule from '@expensify/react-native-hybrid-app';
import Onyx from 'react-native-onyx';
import type {OnyxEntry} from 'react-native-onyx';
import CONFIG from '@src/CONFIG';
import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';
import type {Credentials, HybridApp, Session, TryNewDot} from '@src/types/onyx';
import {isEmptyObject} from '@src/types/utils/EmptyObject';
import {closeReactNativeApp, setReadyToShowAuthScreens, setUseNewDotSignInPage} from './actions/HybridApp';
import Log from './Log';
import {getCurrentUserEmail} from './Network/NetworkStore';

function isAnonymousUser(sessionParam: OnyxEntry<Session>): boolean {
    return sessionParam?.authTokenType === CONST.AUTH_TOKEN_TYPES.ANONYMOUS;
}

let currentHybridApp: OnyxEntry<HybridApp>;
let currentTryNewDot: OnyxEntry<TryNewDot>;
let currentCredentials: OnyxEntry<Credentials>;
let currentSession: OnyxEntry<Session>;

Onyx.connect({
    key: ONYXKEYS.HYBRID_APP,
    callback: (hybridApp) => {
        currentHybridApp = hybridApp;
        handleChangeInHybridAppSignInFlow(hybridApp, currentTryNewDot, currentCredentials, currentSession);
    },
});

Onyx.connect({
    key: ONYXKEYS.NVP_TRY_NEW_DOT,
    callback: (tryNewDot) => {
        currentTryNewDot = tryNewDot;
        handleChangeInHybridAppSignInFlow(currentHybridApp, tryNewDot, currentCredentials, currentSession);
    },
});

Onyx.connect({
    key: ONYXKEYS.CREDENTIALS,
    callback: (credentials) => {
        currentCredentials = credentials;
        handleChangeInHybridAppSignInFlow(currentHybridApp, currentTryNewDot, credentials, currentSession);
    },
});

Onyx.connect({
    key: ONYXKEYS.SESSION,
    callback: (session: OnyxEntry<Session>) => {
        currentSession = session;
        handleChangeInHybridAppSignInFlow(currentHybridApp, currentTryNewDot, currentCredentials, session);
    },
});

let activePolicyID: OnyxEntry<string>;
Onyx.connect({
    key: ONYXKEYS.NVP_ACTIVE_POLICY_ID,
    callback: (newActivePolicyID) => {
        activePolicyID = newActivePolicyID;
    },
});

function shouldUseOldApp(tryNewDot: TryNewDot) {
    if (isEmptyObject(tryNewDot) || isEmptyObject(tryNewDot.classicRedirect)) {
        return true;
    }
    return tryNewDot.classicRedirect.dismissed;
}

function handleChangeInHybridAppSignInFlow(hybridApp: OnyxEntry<HybridApp>, tryNewDot: OnyxEntry<TryNewDot>, credentials: OnyxEntry<Credentials>, session: OnyxEntry<Session>) {
    if (!CONFIG.IS_HYBRID_APP) {
        return;
    }

    if (!session?.authToken || !hybridApp?.useNewDotSignInPage) {
        return;
    }

    if (isAnonymousUser(session)) {
        setReadyToShowAuthScreens(true);
        return;
    }

    if (!credentials?.autoGeneratedLogin || !credentials?.autoGeneratedPassword) {
        return;
    }

    Log.info(`[HybridApp] Performing sign-in on OldDot side`);
    HybridAppModule.signInToOldDot({
        autoGeneratedLogin: credentials.autoGeneratedLogin,
        autoGeneratedPassword: credentials.autoGeneratedPassword,
        authToken: session.authToken,
        email: getCurrentUserEmail() ?? '',
        // eslint-disable-next-line rulesdir/no-default-id-values
        policyID: activePolicyID ?? '',
    });

    if (tryNewDot !== undefined) {
        setUseNewDotSignInPage(false).then(() => {
            if (shouldUseOldApp(tryNewDot)) {
                closeReactNativeApp({shouldSignOut: false, shouldSetNVP: false});
            } else {
                Log.info('[HybridApp] The user should see NewDot. There is no need to block the user on the `SignInPage` until the sign-in process is completed on the OldDot side.');
                setReadyToShowAuthScreens(true);
            }
        });
    }
}
