import ROUTES from '@src/ROUTES';

import isPublicScreenRoute from './isPublicScreenRoute';
import normalizePath from './Navigation/helpers/normalizePath';

/**
 * Tracks whether a logged-out user opened a /concierge deep link so the app can
 * route them to Concierge after sign-up/onboarding. sessionStorage keeps the
 * tab-scoped intent across page reloads while sign-out/consume paths clear it.
 */
const PENDING_CONCIERGE_DEEP_LINK_STORAGE_KEY = 'PENDING_CONCIERGE_DEEP_LINK';
const LEGACY_PERFORMANCE_NAVIGATION_KEY = 'navigation';
const LEGACY_PERFORMANCE_NAVIGATION_TYPE_KEY = 'type';
const LEGACY_PERFORMANCE_NAVIGATION_TYPE_RELOAD = 1;
let hasPendingConciergeDeepLink = false;

function getSessionStorage() {
    try {
        return typeof window === 'undefined' ? undefined : window.sessionStorage;
    } catch {
        return undefined;
    }
}

function getStoredValue(key: string, getStorage: () => Storage | undefined) {
    try {
        return getStorage()?.getItem(key);
    } catch {
        return undefined;
    }
}

function setStoredValue(key: string, value: string, getStorage: () => Storage | undefined) {
    try {
        getStorage()?.setItem(key, value);
    } catch {
        // Ignore storage failures and keep the in-memory intent for the current page lifecycle.
    }
}

function clearStoredValue(key: string, getStorage: () => Storage | undefined) {
    try {
        getStorage()?.removeItem(key);
    } catch {
        // Ignore storage failures since clearing the in-memory flag is still enough for this page lifecycle.
    }
}

function hasStoredFlag(key: string) {
    return getStoredValue(key, getSessionStorage) === 'true';
}

function setStoredFlag(key: string) {
    setStoredValue(key, 'true', getSessionStorage);
}

function clearStoredFlag(key: string) {
    clearStoredValue(key, getSessionStorage);
}

function hasPendingConciergeDeepLinkFlag() {
    return hasPendingConciergeDeepLink || hasStoredFlag(PENDING_CONCIERGE_DEEP_LINK_STORAGE_KEY);
}

function clearPendingConciergeDeepLink() {
    hasPendingConciergeDeepLink = false;
    clearStoredFlag(PENDING_CONCIERGE_DEEP_LINK_STORAGE_KEY);
}

function setPendingConciergeDeepLink() {
    hasPendingConciergeDeepLink = true;
    setStoredFlag(PENDING_CONCIERGE_DEEP_LINK_STORAGE_KEY);
}

function isRecord(value: unknown): value is Record<string, unknown> {
    return typeof value === 'object' && value !== null;
}

function isBrowserReload() {
    try {
        // A browser refresh during signup can replay root/home even though the stored Concierge intent is still valid.
        const performance = typeof window === 'undefined' ? undefined : window.performance;
        const navigationEntries = performance?.getEntriesByType?.('navigation') ?? [];
        if (navigationEntries.some((entry) => 'type' in entry && entry.type === 'reload')) {
            return true;
        }

        // Some web runtimes only expose the deprecated navigation API, so read it indirectly to keep the fallback without triggering deprecated API lint.
        const legacyNavigation: unknown = performance ? Reflect.get(performance, LEGACY_PERFORMANCE_NAVIGATION_KEY) : undefined;
        return isRecord(legacyNavigation) && legacyNavigation[LEGACY_PERFORMANCE_NAVIGATION_TYPE_KEY] === LEGACY_PERFORMANCE_NAVIGATION_TYPE_RELOAD;
    } catch {
        return false;
    }
}

function isCurrentBrowserPathOnboarding() {
    try {
        if (typeof window === 'undefined') {
            return false;
        }

        const normalizedPath = getNormalizedRouteWithoutParams(window.location.pathname);
        return isOnboardingRoute(normalizedPath);
    } catch {
        return false;
    }
}

function getNormalizedRouteWithoutParams(route: string) {
    const [routeWithoutParams] = normalizePath(route).split(/[?#]/, 1);
    return routeWithoutParams.replace(/\/$/, '') || '/';
}

function isOnboardingRoute(normalizedRoute: string) {
    // Onboarding URLs are generated by the guided setup flow, so they should not replace the original signup deep-link intent.
    return normalizedRoute === normalizePath(ROUTES.ONBOARDING_ROOT.route) || normalizedRoute.startsWith(`${normalizePath(ROUTES.ONBOARDING_ROOT.route)}/`);
}

function setPendingHomeDeepLinkIfNoPendingConcierge() {
    // Startup/linking can emit ambiguous root/home signals, so avoid replacing an explicit /concierge intent.
    if (hasPendingConciergeDeepLinkFlag()) {
        return;
    }
    clearPendingConciergeDeepLink();
}

function isAmbiguousStartupOrOnboardingReplay(normalizedRoute: string) {
    return isOnboardingRoute(normalizedRoute) || (normalizedRoute === '/' && (isBrowserReload() || isCurrentBrowserPathOnboarding()));
}

// Keep pending signup deep-link intent consistent across initial URL handling and later Linking URL events.
function updatePendingConciergeDeepLinkForRoute(route: string, isAuthenticated: boolean) {
    const normalizedRoute = getNormalizedRouteWithoutParams(route);
    const routeForPublicScreen = normalizedRoute === '/' ? '' : normalizedRoute.slice(1);

    if (hasPendingConciergeDeepLinkFlag() && isAmbiguousStartupOrOnboardingReplay(normalizedRoute)) {
        return;
    }

    if (isAuthenticated) {
        if (normalizedRoute === '/') {
            clearPendingConciergeDeepLink();
            return;
        }
        if (normalizedRoute === normalizePath(ROUTES.HOME) || isOnboardingRoute(normalizedRoute)) {
            return;
        }
        if (normalizedRoute !== normalizePath(ROUTES.CONCIERGE) && !isPublicScreenRoute(routeForPublicScreen)) {
            clearPendingConciergeDeepLink();
        }
        return;
    }

    if (normalizedRoute === normalizePath(ROUTES.CONCIERGE)) {
        setPendingConciergeDeepLink();
    } else if (normalizedRoute === '/') {
        clearPendingConciergeDeepLink();
    } else if (normalizedRoute === normalizePath(ROUTES.HOME)) {
        setPendingHomeDeepLinkIfNoPendingConcierge();
    } else if (!isPublicScreenRoute(routeForPublicScreen)) {
        clearPendingConciergeDeepLink();
    }
}

function consumePendingConciergeDeepLink() {
    const shouldNavigateToConcierge = hasPendingConciergeDeepLinkFlag();
    clearPendingConciergeDeepLink();
    return shouldNavigateToConcierge;
}

export {setPendingConciergeDeepLink, setPendingHomeDeepLinkIfNoPendingConcierge, updatePendingConciergeDeepLinkForRoute, consumePendingConciergeDeepLink, clearPendingConciergeDeepLink};
