import CONST from '@src/CONST';

import type {ValueOf} from 'type-fest';

type PolicyFeature = ValueOf<typeof CONST.POLICY.POLICY_FEATURE>;
type PolicyFeatureAccess = ValueOf<typeof CONST.POLICY.POLICY_FEATURE_ACCESS>;

const ALL_POLICY_FEATURES = Object.values(CONST.POLICY.POLICY_FEATURE);

const WRITE_ALL_POLICY_FEATURES = ALL_POLICY_FEATURES.reduce<Partial<Record<PolicyFeature, PolicyFeatureAccess>>>(
    (features, feature) => ({...features, [feature]: CONST.POLICY.POLICY_FEATURE_ACCESS.WRITE}),
    {},
);

const READ_ALL_POLICY_FEATURES = ALL_POLICY_FEATURES.reduce<Partial<Record<PolicyFeature, PolicyFeatureAccess>>>(
    (features, feature) => ({...features, [feature]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ}),
    {},
);

const EDITOR_POLICY_FEATURES = ALL_POLICY_FEATURES.filter((feature) => feature !== CONST.POLICY.POLICY_FEATURE.ASSIGN_ELEVATED_ROLES).reduce<
    Partial<Record<PolicyFeature, PolicyFeatureAccess>>
>((features, feature) => ({...features, [feature]: CONST.POLICY.POLICY_FEATURE_ACCESS.WRITE}), {});

const ROLE_PERMISSION_BUNDLES: Record<string, Partial<Record<PolicyFeature, PolicyFeatureAccess>>> = {
    [CONST.POLICY.ROLE.ADMIN]: WRITE_ALL_POLICY_FEATURES,
    [CONST.POLICY.ROLE.EDITOR]: EDITOR_POLICY_FEATURES,
    [CONST.POLICY.ROLE.AUDITOR]: READ_ALL_POLICY_FEATURES,
    [CONST.POLICY.ROLE.USER]: {
        [CONST.POLICY.POLICY_FEATURE.OVERVIEW]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
        [CONST.POLICY.POLICY_FEATURE.MEMBERS]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
    },
    [CONST.POLICY.ROLE.GUEST]: {
        [CONST.POLICY.POLICY_FEATURE.OVERVIEW]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
    },
    [CONST.POLICY.ROLE.CARD_ADMIN]: {
        [CONST.POLICY.POLICY_FEATURE.OVERVIEW]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
        [CONST.POLICY.POLICY_FEATURE.MEMBERS]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
        [CONST.POLICY.POLICY_FEATURE.EXPENSIFY_CARD]: CONST.POLICY.POLICY_FEATURE_ACCESS.WRITE,
        [CONST.POLICY.POLICY_FEATURE.COMPANY_CARDS]: CONST.POLICY.POLICY_FEATURE_ACCESS.WRITE,
    },
    [CONST.POLICY.ROLE.PEOPLE_ADMIN]: {
        [CONST.POLICY.POLICY_FEATURE.OVERVIEW]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
        [CONST.POLICY.POLICY_FEATURE.MEMBERS]: CONST.POLICY.POLICY_FEATURE_ACCESS.WRITE,
        [CONST.POLICY.POLICY_FEATURE.WORKFLOWS]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
        [CONST.POLICY.POLICY_FEATURE.WORKFLOWS_APPROVALS]: CONST.POLICY.POLICY_FEATURE_ACCESS.WRITE,
    },
    [CONST.POLICY.ROLE.PAYMENTS_ADMIN]: {
        [CONST.POLICY.POLICY_FEATURE.OVERVIEW]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
        [CONST.POLICY.POLICY_FEATURE.MEMBERS]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
        [CONST.POLICY.POLICY_FEATURE.WORKFLOWS]: CONST.POLICY.POLICY_FEATURE_ACCESS.READ,
        [CONST.POLICY.POLICY_FEATURE.WORKFLOWS_PAYMENTS]: CONST.POLICY.POLICY_FEATURE_ACCESS.WRITE,
    },
};

const CONTROL_POLICY_ONLY_ROLES = [CONST.POLICY.ROLE.AUDITOR, CONST.POLICY.ROLE.GUEST, CONST.POLICY.ROLE.CARD_ADMIN, CONST.POLICY.ROLE.PEOPLE_ADMIN, CONST.POLICY.ROLE.PAYMENTS_ADMIN];

function isControlPolicyOnlyRole(role: string | undefined): boolean {
    return CONTROL_POLICY_ONLY_ROLES.some((controlPolicyOnlyRole) => controlPolicyOnlyRole === role);
}

export type {PolicyFeature, PolicyFeatureAccess};
export {ROLE_PERMISSION_BUNDLES, isControlPolicyOnlyRole};
