const PASSWORD_AUTOCOMPLETE_TYPE = 'password';
const NEW_PASSWORD_AUTOCOMPLETE_TYPE = 'password-new';
const ACCESSIBILITY_ROLE_FORM = 'none';

export {
    PASSWORD_AUTOCOMPLETE_TYPE,
    ACCESSIBILITY_ROLE_FORM,
    NEW_PASSWORD_AUTOCOMPLETE_TYPE,
};
