export default () => ({
    onyxData: [
        {
            onyxMethod: 'merge',
            key: 'report_98345625',
            value: {
                reportID: '98345625',
                reportName: 'Chat Report',
                chatType: '',
                ownerEmail: '__fake__',
                policyID: '_FAKE_',
                participants: [
                    'fake1@gmail.com',
                    'fake2@gmail.com',
                    'fake3@gmail.com',
                    'fake4@gmail.com',
                    'fake5@gmail.com',
                    'fake6@gmail.com',
                    'fake7@gmail.com',
                    'fake8@gmail.com',
                ],
                isPinned: false,
                lastReadTimestamp: 1671470568415,
                lastReadCreated: '1980-01-01 00:00:00.000',
                lastActionCreated: '2022-08-01 20:49:11',
                lastMessageTimestamp: 1659386951000,
                lastMessageText: 'Say hello\ud83d\ude10',
                lastActorEmail: 'fake3@gmail.com',
                notificationPreference: 'always',
                stateNum: 0,
                statusNum: 0,
                oldPolicyName: '',
                visibility: null,
                isOwnPolicyExpenseChat: false,
                lastMessageHtml: 'Say hello\ud83d\ude10',
                hasOutstandingIOU: false,
            },
        },
        {
            onyxMethod: 'merge',
            key: 'reportActions_98345625',
            value: {
                226245034: {
                    reportActionID: '226245034',
                    actionName: 'CREATED',
                    created: '2022-08-01 20:48:58',
                    timestamp: 1659386938,
                    reportActionTimestamp: 0,
                    avatar: 'https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_3.png',
                    message: [
                        {
                            type: 'TEXT',
                            style: 'strong',
                            text: '__fake__',
                        },
                        {
                            type: 'TEXT',
                            style: 'normal',
                            text: ' created this report',
                        },
                    ],
                    person: [
                        {
                            type: 'TEXT',
                            style: 'strong',
                            text: '__fake__',
                        },
                    ],
                    automatic: false,
                    shouldShow: true,
                },
                1082059149: {
                    person: [
                        {
                            type: 'TEXT',
                            style: 'strong',
                            text: '123 Ios',
                        },
                    ],
                    actorEmail: 'fake3@gmail.com',
                    actorAccountID: 10773236,
                    message: [
                        {
                            type: 'COMMENT',
                            html: 'Say hello\ud83d\ude10',
                            text: 'Say hello\ud83d\ude10',
                            isEdited: false,
                        },
                    ],
                    originalMessage: {
                        html: 'Say hello\ud83d\ude10',
                    },
                    avatar: 'https://d1wpcgnaa73g0y.cloudfront.net/301e37631eca9e3127d6b668822e3a53771551f6_128.jpeg',
                    created: '2022-08-01 20:49:11',
                    timestamp: 1659386951,
                    reportActionTimestamp: 1659386951000,
                    automatic: false,
                    actionName: 'ADDCOMMENT',
                    shouldShow: true,
                    reportActionID: '1082059149',
                },
            },
        },
    ],
    jsonCode: 200,
    requestID: '783ef80a3fc5969a-SJC',
});
