const NAVIGATION_TABS = {
    HOME: 'HOME',
    INBOX: 'INBOX',
    SEARCH: 'SEARCH',
    INSIGHTS: 'INSIGHTS',
    ASK_CONCIERGE: 'ASK_CONCIERGE',
    MORE: 'MORE',
    WORKSPACES: 'WORKSPACES',
    SETTINGS: 'SETTINGS',
} as const;

export default NAVIGATION_TABS;
