const NAVIGATION_TABS = {
    NEW_DOT_HOME: 'NEW_DOT_HOME',
    HOME: 'HOME',
    SEARCH: 'SEARCH',
    WORKSPACES: 'WORKSPACES',
    SETTINGS: 'SETTINGS',
} as const;

export default NAVIGATION_TABS;
