# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

skip_docs
opt_out_usage

platform :android do
  desc "Generate a new local APK"
  lane :build do
    ENV["ENVFILE"]=".env.production"

    gradle(
      project_dir: './android',
      task: 'assemble',
      build_type: 'Release',
    )
  end

  desc "Build and upload app to Google Play"
  lane :beta do
    ENV["ENVFILE"]=".env.production"

    gradle(
        project_dir: './android',
        task: 'bundle',
        build_type: 'Release',
    )

    upload_to_play_store(
        package_name: "com.expensify.chat",
        json_key: './android/app/android-fastlane-json-key.json',
        aab: './android/app/build/outputs/bundle/release/app-release.aab',
        track: 'internal',
        rollout: '1.0'
    )
  end
end

platform :ios do
  desc "Generate a local iOS production build"
  lane :build do
    ENV["ENVFILE"]=".env.production"

    build_app(
        workspace: "./ios/ExpensifyCash.xcworkspace",
        scheme: "ExpensifyCash"
    )
  end

  desc "Build and upload app to TestFlight"
  lane :beta do
    require 'securerandom'
    ENV["ENVFILE"]=".env.production"

    keychain_password = SecureRandom.uuid

    create_keychain(
        name: "ios-build.keychain",
        password: keychain_password,
        default_keychain: "true",
        unlock: "true",
        timeout: "3600",
        add_to_search_list: "true"
    )

    import_certificate(
        certificate_path: "./ios/Certificates.p12",
        keychain_name: "ios-build.keychain",
        keychain_password: keychain_password
    )

    install_provisioning_profile(
        path: "./ios/chat_expensify_appstore.mobileprovision"
    )

    build_app(
        workspace: "./ios/ExpensifyCash.xcworkspace",
        scheme: "ExpensifyCash"
    )

    upload_to_testflight(
        distribute_external: true,
        reject_build_waiting_for_review: true,
        changelog: "Thank you for beta testing the Expensify Chat, this version includes bug fixes and improvements.",
        groups: ["Beta"],
        demo_account_required: true,
        beta_app_review_info: {
            contact_email: "mobile@expensify.com",
            contact_first_name: "Andrew",
            contact_last_name: "Gable",
            contact_phone: "+1 916 698 2582",
            demo_account_name: "andrew+empty@expensifail.com",
            demo_account_password: "asdfASDF00",
            notes: "Use the account provided. Thank you for the review."
        }
    )


    upload_symbols_to_crashlytics(
      dsym_path: lane_context[SharedValues::DSYM_OUTPUT_PATH],
      gsp_path: "./ios/GoogleService-Info.plist",
      binary_path: "./ios/Pods/FirebaseCrashlytics/upload-symbols"
    )
  end
end
