# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

skip_docs
opt_out_usage

default_platform(:ios)

platform :ios do
  desc "Build and upload app to TestFlight"
  lane :beta do
    update_code_signing_settings(
        use_automatic_signing: true,
        path: "ReactNativeChat.xcodeproj"
    )
    build_app(scheme: "ReactNativeChat", export_xcargs: "-allowProvisioningUpdates")
    upload_to_testflight
  end
end

