import {getMicroSecondOnyxErrorWithMessage} from '@libs/ErrorUtils';
import {clearSessionStorage} from '@libs/Navigation/helpers/lastVisitedTabPathUtils';
import {getIsOffline} from '@libs/NetworkState';
import clearPrefetchOnAppStart from '@libs/Prefetch/clearPrefetchOnAppStart';
import type {SignOutReason} from '@libs/telemetry/ReceiptObservability';
import {logReceiptQueueSnapshot} from '@libs/telemetry/ReceiptObservability';

import CONFIG from '@src/CONFIG';
import CONST from '@src/CONST';
import type {OnyxKey} from '@src/ONYXKEYS';
import ONYXKEYS from '@src/ONYXKEYS';

import HybridAppModule from '@expensify/react-native-hybrid-app';
import Onyx from 'react-native-onyx';

import {resetSignInFlow} from './HybridApp';

let currentShouldForceOffline: boolean | undefined;
let currentIsUsingImportedState: boolean | undefined;
let currentSessionAuthToken: string | undefined;
let currentSessionEmail: string | undefined;
let currentCredentialsValidateCode: string | undefined;

Onyx.connectWithoutView({
    key: ONYXKEYS.NETWORK,
    callback: (network) => {
        currentShouldForceOffline = network?.shouldForceOffline;
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.IS_USING_IMPORTED_STATE,
    callback: (value) => {
        currentIsUsingImportedState = value;
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.SESSION,
    callback: (session) => {
        currentSessionAuthToken = session?.authToken;
        currentSessionEmail = session?.email;
    },
});

Onyx.connectWithoutView({
    key: ONYXKEYS.CREDENTIALS,
    callback: (credentials) => {
        currentCredentialsValidateCode = credentials?.validateCode;
    },
});

function clearStorageAndRedirect(signOutReason: SignOutReason, errorMessage?: string): Promise<void> {
    logReceiptQueueSnapshot('signOut', signOutReason);

    // Under certain conditions, there are key-values we'd like to keep in storage even when a user is logged out.
    // We pass these into the clear() method in order to avoid having to reset them on a delayed tick and getting
    // flashes of unwanted default state.
    const keysToPreserve: OnyxKey[] = [];
    keysToPreserve.push(ONYXKEYS.NVP_PREFERRED_LOCALE);
    keysToPreserve.push(ONYXKEYS.RAM_ONLY_ARE_TRANSLATIONS_LOADING);
    keysToPreserve.push(ONYXKEYS.PREFERRED_THEME);
    keysToPreserve.push(ONYXKEYS.NVP_SEARCH_SIDEBAR);
    keysToPreserve.push(ONYXKEYS.ACTIVE_CLIENTS);
    keysToPreserve.push(ONYXKEYS.DEVICE_ID);
    keysToPreserve.push(ONYXKEYS.SHOULD_USE_STAGING_SERVER);
    keysToPreserve.push(ONYXKEYS.IS_DEBUG_MODE_ENABLED);
    keysToPreserve.push(ONYXKEYS.COLLECTION.PASSKEY_CREDENTIALS);
    keysToPreserve.push(ONYXKEYS.COLLECTION.DEVICE_BIOMETRICS);

    // After signing out, set ourselves as offline if we were offline before logging out and we are not forcing it.
    // If we are forcing offline, ignore it while signed out, otherwise it would require a refresh because there's no way to toggle the switch to go back online while signed out.
    if (getIsOffline() && !currentShouldForceOffline) {
        keysToPreserve.push(ONYXKEYS.NETWORK);
    }

    // When using imported state, preserve both the flag and the network state (which has shouldForceOffline=true).
    // This prevents the app from getting stuck in infinite loading when HybridApp transitions from OldDot to NewDot.
    if (currentIsUsingImportedState) {
        keysToPreserve.push(ONYXKEYS.IS_USING_IMPORTED_STATE);
        keysToPreserve.push(ONYXKEYS.NETWORK);
    }

    // When the user is in the middle of a 2FA sign-in flow (they've entered their validateCode but not yet completed
    // 2FA), we want to preserve their credentials and account state so that after a page refresh they are still
    // prompted to enter their 2FA code rather than being sent back to the initial sign-in page.
    const isIncompleteSignIn = !currentSessionAuthToken && !!currentCredentialsValidateCode;
    if (isIncompleteSignIn) {
        keysToPreserve.push(ONYXKEYS.CREDENTIALS);
        keysToPreserve.push(ONYXKEYS.ACCOUNT);
    }

    // SAML accounts must keep CREDENTIALS/ACCOUNT through the clear so SignInPage can re-initiate the IdP handshake.
    const shouldPreserveCredentialsForSAML = signOutReason === CONST.SIGN_OUT_REASON.SAML_REQUIRED;

    // Mark the account as loading and set the login in credentials to trigger the `SAML_SIGN_IN` transition
    if (shouldPreserveCredentialsForSAML) {
        keysToPreserve.push(ONYXKEYS.CREDENTIALS);
        keysToPreserve.push(ONYXKEYS.ACCOUNT);
        Onyx.merge(ONYXKEYS.CREDENTIALS, {login: currentSessionEmail, autoGeneratedLogin: null, autoGeneratedPassword: null});
        Onyx.merge(ONYXKEYS.ACCOUNT, {isLoading: true});
    }

    return Onyx.clear(keysToPreserve).then(async () => {
        // Requests may be processed while sign-out is in progress. Clear again after credentials have been removed so none of those requests remain queued for the next startup.
        await clearPrefetchOnAppStart();

        if (CONFIG.IS_HYBRID_APP) {
            resetSignInFlow();
            HybridAppModule.signOutFromOldDot();
        }

        // When logging out from imported state, reset shouldForceOffline to false and clear the imported state flag
        // so the user can log back in
        if (currentIsUsingImportedState) {
            Onyx.merge(ONYXKEYS.NETWORK, {shouldForceOffline: false});
            Onyx.merge(ONYXKEYS.IS_USING_IMPORTED_STATE, false);
        }

        if (!errorMessage) {
            return;
        }

        // `Onyx.clear` reinitializes the Onyx instance with initial values so use `Onyx.merge` instead of `Onyx.set`
        Onyx.merge(ONYXKEYS.SESSION, {errors: getMicroSecondOnyxErrorWithMessage(errorMessage)});
    });
}

/**
 * Cleanup actions resulting in the user being redirected to the Sign-in page
 * - Clears the Onyx store - removing the authToken redirects the user to the Sign-in page
 *
 * Normally this method would live in Session.js, but that would cause a circular dependency with Network.js.
 *
 * @param signOutReason Which path tore down the session. Reported on the receipt queue snapshot, and the SAML path
 *                      additionally preserves the credentials needed to re-initiate the IdP handshake.
 * @param errorMessage Error message to be displayed on the sign in page
 */
function redirectToSignIn(signOutReason: SignOutReason, errorMessage?: string): Promise<void> {
    return clearStorageAndRedirect(signOutReason, errorMessage).then(() => {
        clearSessionStorage();
    });
}

export default redirectToSignIn;
