import type {NumericEditingKeyPressEvent, NumericEditingSelection} from '@components/NumericEditingController/types';
import {clampSelection, collapseSelection, getNewSelection, getSelectionAtOffset, isForwardDeleteKeyPress} from '@components/NumericEditingController/utils';

import shouldIgnoreSelectionWhenUpdatedManually from '@libs/shouldIgnoreSelectionWhenUpdatedManually';

import {useIsFocused} from '@react-navigation/native';
import {useLayoutEffect, useRef, useState} from 'react';

type UseNumericSelectionParams = {
    /** Displayed text used to clamp native selections. */
    displayText: string;
};

type NumericSelectionEdit = {
    previousText: string;

    nextText: string;
};

/** Manages the caret and guards against stale native selection events. */
function useNumericSelection({displayText}: UseNumericSelectionParams) {
    const isFocused = useIsFocused();

    const [selection, setSelection] = useState<NumericEditingSelection>(() => getSelectionAtOffset(displayText.length));
    const [previousIsFocused, setPreviousIsFocused] = useState(isFocused);

    // Native events can arrive before the pending text renders.
    const pendingDisplayTextRef = useRef<string | undefined>(undefined);
    // Native echoes one stale event after a controlled selection update; consume it once.
    const willSelectionBeUpdatedManually = useRef(false);
    // Ignore the selection event generated by rejected input.
    const willSelectionBeRestoredAfterInvalidInput = useRef(false);
    // Forward-delete removes the next character, so the caret offset stays.
    const forwardDeletePressedRef = useRef(false);

    // Reset selection when returning to the screen.
    if (previousIsFocused !== isFocused) {
        setPreviousIsFocused(isFocused);
        if (isFocused && !previousIsFocused) {
            setSelection(collapseSelection);
        }
    }

    // Prepare guards for a manual selection update.
    const prepareSelectionUpdate = (nextText: string) => {
        willSelectionBeUpdatedManually.current = true;
        pendingDisplayTextRef.current = nextText;
    };

    const collapse = () => {
        setSelection(collapseSelection);
    };

    // Moves the caret to the start after an external clear.
    const reset = () => {
        setSelection(getSelectionAtOffset(0));
    };

    const moveToEnd = (nextText: string) => {
        prepareSelectionUpdate(nextText);
        setSelection(getSelectionAtOffset(nextText.length));
    };

    // Tracks whether the next edit follows a forward-delete key press.
    const handleKeyPress = (event: NumericEditingKeyPressEvent) => {
        forwardDeletePressedRef.current = isForwardDeleteKeyPress(event);
    };

    // Adjusts the caret for a text-length change.
    const syncAfterEdit = ({previousText, nextText}: NumericSelectionEdit) => {
        prepareSelectionUpdate(nextText);
        const isForwardDelete = forwardDeletePressedRef.current && previousText.length > nextText.length;
        const previousLength = isForwardDelete ? nextText.length : previousText.length;
        setSelection((currentSelection) => getNewSelection(currentSelection, previousLength, nextText.length));
    };

    // Restores the last valid caret after a rejected edit.
    const rejectEdit = () => {
        // React Native syncs against its last reported position, so ignore this event.
        willSelectionBeRestoredAfterInvalidInput.current = true;
        // Shallow copy forces native selection reset: https://github.com/Expensify/App/issues/16385
        setSelection((currentSelection) => ({...currentSelection}));
    };

    const handleNativeSelectionChange = (selectionStart: number, selectionEnd: number) => {
        if (willSelectionBeRestoredAfterInvalidInput.current) {
            willSelectionBeRestoredAfterInvalidInput.current = false;
            return;
        }

        if (shouldIgnoreSelectionWhenUpdatedManually && willSelectionBeUpdatedManually.current) {
            willSelectionBeUpdatedManually.current = false;
            return;
        }

        // iOS may report selection before the text renders, so use pending bounds.
        const maxSelection = pendingDisplayTextRef.current?.length ?? displayText.length;
        pendingDisplayTextRef.current = undefined;
        setSelection(clampSelection({start: selectionStart, end: selectionEnd}, maxSelection));
    };

    useLayoutEffect(() => {
        // Clear the rejected-input guard after the selection commits. Keep the manual-update guard until its native
        // echo is handled, because that event can arrive after the commit.
        willSelectionBeRestoredAfterInvalidInput.current = false;
    }, [selection]);

    return {
        selection,
        collapse,
        reset,
        moveToEnd,
        syncAfterEdit,
        handleKeyPress,
        rejectEdit,
        handleNativeSelectionChange,
    };
}

export default useNumericSelection;
