import CONST from '@src/CONST';
import {getCurrentUserEmail} from '@src/libs/CurrentUserStore';
import Log from '@src/libs/Log';
import ONYXKEYS from '@src/ONYXKEYS';
import type Credentials from '@src/types/onyx/Credentials';

import type {ValueOf} from 'type-fest';

// TODO: Rename this module to AuthStore in a follow-up PR — it only manages auth/credentials state now.
import Onyx from 'react-native-onyx';

let credentials: Credentials | null | undefined;
let lastShortAuthToken: string | null | undefined;
let authToken: string | null | undefined;
let authTokenType: ValueOf<typeof CONST.AUTH_TOKEN_TYPES> | null;
let accountID: number | null | undefined;
let authenticating = false;
let authenticatingStartTime = 0;

let resolveIsReadyPromise: (args?: unknown[]) => void;
let isReadyPromise = new Promise((resolve) => {
    resolveIsReadyPromise = resolve;
});

/**
 * This is a hack to workaround the fact that Onyx may not yet have read these values from storage by the time Network starts processing requests.
 * If the values are undefined we haven't read them yet. If they are null or have a value then we have and the network is "ready".
 */
function checkRequiredData() {
    if (authToken === undefined || credentials === undefined) {
        return;
    }

    resolveIsReadyPromise();
}

function resetHasReadRequiredDataFromStorage() {
    // Create a new promise and a new resolve function
    isReadyPromise = new Promise((resolve) => {
        resolveIsReadyPromise = resolve;
    });
}

// Use connectWithoutView since this doesn't affect to any UI
Onyx.connectWithoutView({
    key: ONYXKEYS.SESSION,
    callback: (val) => {
        authToken = val?.authToken ?? null;
        authTokenType = val?.authTokenType ?? null;
        accountID = val?.accountID ?? null;
        checkRequiredData();
    },
});

// Use connectWithoutView since this doesn't affect to any UI
Onyx.connectWithoutView({
    key: ONYXKEYS.CREDENTIALS,
    callback: (val) => {
        Log.info('[NetworkStore] Updating credentials', false, {autoGeneratedLogin: !!val?.autoGeneratedLogin, autoGeneratedPassword: !!val?.autoGeneratedPassword});
        credentials = val ?? null;
        checkRequiredData();
    },
});

function getCredentials(): Credentials | null | undefined {
    return credentials;
}

function getAuthToken(): string | null | undefined {
    return authToken;
}

function getAccountID(): number | null | undefined {
    return accountID;
}

function getLastShortAuthToken(): string | null | undefined {
    return lastShortAuthToken;
}

function setLastShortAuthToken(newLastAuthToken: string | null) {
    lastShortAuthToken = newLastAuthToken;
}

function isSupportAuthToken(): boolean {
    return authTokenType === CONST.AUTH_TOKEN_TYPES.SUPPORT;
}

function setAuthToken(newAuthToken: string | null) {
    authToken = newAuthToken;
}

function hasReadRequiredDataFromStorage(): Promise<unknown> {
    return isReadyPromise;
}

function isAuthenticating(): boolean {
    // Self-heal a stuck flag: an authentication that never settles (e.g. an interrupted SAML sign-in) would otherwise
    // leave this true forever, freezing the main queue (see MainQueue.canMakeRequest) and short-circuiting the 407
    // reauthentication path so the session never recovers without a page refresh.
    if (authenticating && Date.now() - authenticatingStartTime > CONST.NETWORK.MAX_AUTHENTICATION_PENDING_TIME_MS) {
        Log.hmmm('[NetworkStore] Authentication has been pending for too long. Clearing the isAuthenticating flag so requests can flow and reauthentication can restart.', {
            elapsedTime: Date.now() - authenticatingStartTime,
        });
        authenticating = false;
    }
    return authenticating;
}

function setIsAuthenticating(val: boolean) {
    if (val) {
        // Stamp each new authentication attempt so a hung one can be detected as stale in isAuthenticating().
        authenticatingStartTime = Date.now();
    }
    authenticating = val;
}

export {
    getAuthToken,
    getAccountID,
    setAuthToken,
    getCurrentUserEmail,
    hasReadRequiredDataFromStorage,
    resetHasReadRequiredDataFromStorage,
    isAuthenticating,
    setIsAuthenticating,
    getCredentials,
    checkRequiredData,
    isSupportAuthToken,
    getLastShortAuthToken,
    setLastShortAuthToken,
};
