import {renderHook} from '@testing-library/react-native';

import useSwitchToDelegator from '@hooks/useSwitchToDelegator';

import {connect, disconnect} from '@libs/actions/Delegate';
import {stopGpsTrip} from '@libs/GPSDraftDetailsUtils';

import CONST from '@src/CONST';
import ONYXKEYS from '@src/ONYXKEYS';
import type {GpsDraftDetails} from '@src/types/onyx';

import Onyx from 'react-native-onyx';

import waitForBatchedUpdates from '../../utils/waitForBatchedUpdates';

const DELEGATOR_EMAIL = 'delegator@example.com';
const ORIGINAL_EMAIL = 'original@example.com';
const ACTIVE_POLICY_ID = 'policy1';

const DELEGATED_ACCESS = {delegators: [{email: DELEGATOR_EMAIL, role: CONST.DELEGATE_ROLE.ALL}]};
const CREDENTIALS = {login: ORIGINAL_EMAIL, autoGeneratedLogin: 'auto', autoGeneratedPassword: 'pass'};
const STASHED_CREDENTIALS = {login: ORIGINAL_EMAIL, autoGeneratedLogin: 'stashedAuto', autoGeneratedPassword: 'stashedPass'};
const SESSION = {email: DELEGATOR_EMAIL, accountID: 2};
const STASHED_SESSION = {email: ORIGINAL_EMAIL, accountID: 1};

const GPS_POINTS = [[{lat: 1, long: 2}]];
const GPS_DRAFT_DETAILS: GpsDraftDetails = {gpsPoints: GPS_POINTS, distanceInMeters: 10, isTracking: true, reportID: 'report1', unit: 'mi'};

let mockIsOffline = false;
let mockIsActingAsDelegate = false;
let mockConfirmAction: 'CONFIRM' | 'CLOSE' = 'CONFIRM';

const mockShowConfirmModal = jest.fn(() => Promise.resolve({action: mockConfirmAction}));
const mockShowDelegateNoAccessModal = jest.fn();

jest.mock('@hooks/useLocalize', () => ({
    __esModule: true,
    default: () => ({translate: (key: string) => key}),
}));

jest.mock('@hooks/useNetwork', () => ({
    __esModule: true,
    default: () => ({isOffline: mockIsOffline}),
}));

jest.mock('@hooks/useConfirmModal', () => ({
    __esModule: true,
    default: () => ({showConfirmModal: mockShowConfirmModal}),
}));

jest.mock('@components/DelegateNoAccessModalProvider', () => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    const actual = jest.requireActual('@components/DelegateNoAccessModalProvider');
    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    return {
        ...actual,
        useDelegateNoAccessState: () => ({isActingAsDelegate: mockIsActingAsDelegate, isDelegateAccessRestricted: false}),
        useDelegateNoAccessActions: () => ({showDelegateNoAccessModal: mockShowDelegateNoAccessModal}),
    };
});

jest.mock('@libs/actions/Delegate', () => ({
    connect: jest.fn(),
    disconnect: jest.fn(),
}));

jest.mock('@libs/actions/Modal', () => ({
    close: (onModalCloseCallback?: () => void) => onModalCloseCallback?.(),
}));

jest.mock('@libs/GPSDraftDetailsUtils', () => {
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    const actual = jest.requireActual('@libs/GPSDraftDetailsUtils');
    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    return {...actual, stopGpsTrip: jest.fn()};
});

async function seedOnyx(overrides: {isTracking?: boolean; withStashedCredentials?: boolean} = {}) {
    await Onyx.merge(ONYXKEYS.ACCOUNT, {delegatedAccess: DELEGATED_ACCESS});
    await Onyx.merge(ONYXKEYS.CREDENTIALS, CREDENTIALS);
    await Onyx.merge(ONYXKEYS.SESSION, SESSION);
    await Onyx.merge(ONYXKEYS.STASHED_SESSION, STASHED_SESSION);
    await Onyx.merge(ONYXKEYS.NVP_ACTIVE_POLICY_ID, ACTIVE_POLICY_ID);
    if (overrides.withStashedCredentials ?? true) {
        await Onyx.merge(ONYXKEYS.STASHED_CREDENTIALS, STASHED_CREDENTIALS);
    }
    if (overrides.isTracking) {
        await Onyx.merge(ONYXKEYS.GPS_DRAFT_DETAILS, GPS_DRAFT_DETAILS);
    }
    await waitForBatchedUpdates();
}

describe('useSwitchToDelegator', () => {
    beforeAll(() => {
        Onyx.init({keys: ONYXKEYS});
    });

    beforeEach(async () => {
        mockIsOffline = false;
        mockIsActingAsDelegate = false;
        mockConfirmAction = 'CONFIRM';
        mockShowConfirmModal.mockClear();
        mockShowDelegateNoAccessModal.mockClear();
        jest.mocked(connect).mockClear();
        jest.mocked(disconnect).mockClear();
        jest.mocked(stopGpsTrip).mockClear();
        await Onyx.clear();
        await waitForBatchedUpdates();
    });

    it('connects to the delegator with every value it read from Onyx', async () => {
        await seedOnyx();

        const {result} = renderHook(() => useSwitchToDelegator());
        result.current(DELEGATOR_EMAIL);

        expect(connect).toHaveBeenCalledWith({
            email: DELEGATOR_EMAIL,
            delegatedAccess: DELEGATED_ACCESS,
            credentials: CREDENTIALS,
            session: expect.objectContaining(SESSION),
            activePolicyID: ACTIVE_POLICY_ID,
        });
        expect(disconnect).not.toHaveBeenCalled();
        expect(mockShowConfirmModal).not.toHaveBeenCalled();
    });

    it('blocks the switch and shows the offline modal when offline', async () => {
        await seedOnyx();
        mockIsOffline = true;

        const {result} = renderHook(() => useSwitchToDelegator());
        result.current(DELEGATOR_EMAIL);

        expect(mockShowConfirmModal).toHaveBeenCalledWith(
            expect.objectContaining({
                title: 'common.youAppearToBeOffline',
                prompt: 'common.offlinePrompt',
                shouldShowCancelButton: false,
            }),
        );
        expect(connect).not.toHaveBeenCalled();
        expect(disconnect).not.toHaveBeenCalled();
    });

    it('disconnects back to the original user, reading the stashed pair from Onyx', async () => {
        await seedOnyx();
        mockIsActingAsDelegate = true;

        const {result} = renderHook(() => useSwitchToDelegator());
        result.current(ORIGINAL_EMAIL);

        expect(disconnect).toHaveBeenCalledWith({stashedCredentials: STASHED_CREDENTIALS, stashedSession: STASHED_SESSION});
        expect(connect).not.toHaveBeenCalled();
        expect(mockShowDelegateNoAccessModal).not.toHaveBeenCalled();
    });

    it('passes an empty object as the stashed credentials when the key has no value', async () => {
        await seedOnyx({withStashedCredentials: false});
        mockIsActingAsDelegate = true;

        const {result} = renderHook(() => useSwitchToDelegator());
        result.current(ORIGINAL_EMAIL);

        expect(disconnect).toHaveBeenCalledWith({stashedCredentials: {}, stashedSession: STASHED_SESSION});
    });

    it('refuses a chained delegation, comparing the email against the stashed session', async () => {
        await seedOnyx();
        mockIsActingAsDelegate = true;

        const {result} = renderHook(() => useSwitchToDelegator());
        result.current('someone.else@example.com');

        expect(mockShowDelegateNoAccessModal).toHaveBeenCalledTimes(1);
        expect(connect).not.toHaveBeenCalled();
        expect(disconnect).not.toHaveBeenCalled();
    });

    it('stops the tracked trip with the points it read, then switches, when the user confirms', async () => {
        await seedOnyx({isTracking: true});

        const {result} = renderHook(() => useSwitchToDelegator());
        result.current(DELEGATOR_EMAIL);
        await waitForBatchedUpdates();

        expect(mockShowConfirmModal).toHaveBeenCalledWith(
            expect.objectContaining({
                title: 'gps.switchAccountWarningTripInProgress.title',
                confirmText: 'gps.switchAccountWarningTripInProgress.confirm',
            }),
        );
        expect(stopGpsTrip).toHaveBeenCalledWith(false, GPS_POINTS, true);
        expect(connect).toHaveBeenCalledTimes(1);
    });

    it('leaves the trip running and does not switch when the user dismisses the trip warning', async () => {
        await seedOnyx({isTracking: true});
        mockConfirmAction = 'CLOSE';

        const {result} = renderHook(() => useSwitchToDelegator());
        result.current(DELEGATOR_EMAIL);
        await waitForBatchedUpdates();

        expect(mockShowConfirmModal).toHaveBeenCalledTimes(1);
        expect(stopGpsTrip).not.toHaveBeenCalled();
        expect(connect).not.toHaveBeenCalled();
        expect(disconnect).not.toHaveBeenCalled();
    });

    it('ignores the trip warning entirely when nothing is being tracked', async () => {
        await seedOnyx();
        await Onyx.merge(ONYXKEYS.GPS_DRAFT_DETAILS, {...GPS_DRAFT_DETAILS, isTracking: false});
        await waitForBatchedUpdates();

        const {result} = renderHook(() => useSwitchToDelegator());
        result.current(DELEGATOR_EMAIL);

        expect(mockShowConfirmModal).not.toHaveBeenCalled();
        expect(stopGpsTrip).not.toHaveBeenCalled();
        expect(connect).toHaveBeenCalledTimes(1);
    });
});
