const ANIMATED_TRANSITION = 300;
const MENU_ANIMATION_DURATION = 300;
const DEFAULT_IN = 300;
const DEFAULT_OUT = 200;
const DEFAULT_RIGHT_DOCKED_IOS_IN = 500;
const DEFAULT_RIGHT_DOCKED_IOS_OUT = 400;
const FAB_IN = 350;
const FAB_OUT = 200;

export {ANIMATED_TRANSITION, MENU_ANIMATION_DURATION, DEFAULT_IN, DEFAULT_OUT, DEFAULT_RIGHT_DOCKED_IOS_IN, DEFAULT_RIGHT_DOCKED_IOS_OUT, FAB_IN, FAB_OUT};
