const oldRoutes: Record<string, string> = {
    /* eslint-disable @typescript-eslint/naming-convention */
    '/settings/*/category/*/edit': '/settings/$1/category/$2/category-edit',
    '/settings/*/tags/*/edit': '/settings/$1/tags/settings/edit/$2',
    '/settings/*/tags/new': '/settings/$1/tags/tag-new',
    '/settings/*/tag/*/*/edit': '/settings/$1/tags/tag-settings/$2/$3/tag-edit/$2/$3',
    '/settings/*/tag/*/*/gl-code': '/settings/$1/tags/tag-settings/$2/$3/gl-code/$2/$3',
    '/settings/*/tag/*/*': '/settings/$1/tags/tag-settings/$2/$3',
    '/workspaces/*/category/*/payroll-code': '/workspaces/$1/categories/category/$2/payroll-code',
    '/workspaces/*/category/*/gl-code': '/workspaces/$1/categories/category/$2/gl-code',
    '/workspaces/*/category/*/edit': '/workspaces/$1/categories/category/$2/edit',
    '/workspaces/*/category/*': '/workspaces/$1/categories/category/$2',
    '/settings/workspaces/*': '/workspaces/$1',
    '/settings/workspaces': '/workspaces',
    '/r/*/settings/name': '/r/$1/details/settings/name',
    '/r/*/title': '/r/$1/title',
    '/r/*/description': '/r/$1/description',
    '/r/*/assignee': '/r/$1/assignee',
    '/r/*/notes/*/edit': '/r/$1/notes-edit/$2',
    '/r/*/notes': '/r/$1/details/notes',
    '/workspaces/*/overview/address': '/workspaces/$1/overview/workspace-address',
    '/workspaces/*/categories/settings': '/workspaces/$1/categories/categories-settings',
    '/workspaces/*/categories/new': '/workspaces/$1/categories/category-new',
    '/settings/*/categories/settings': '/settings/$1/categories/manage-settings',
    '/settings/*/categories/new': '/settings/$1/categories/category-create',
    '/workspaces/*/accounting/*/card-reconciliation/account': '/workspaces/$1/accounting/$2/card-reconciliation/account-reconciliation-settings',
    '/workspaces/*/connections/netsuite/export/invoice-item-preference/invoice-item/select': '/workspaces/$1/connections/netsuite/export/invoice-item-preference/select/invoice-item/select',
    '/workspaces/*/connections/xero/export/preferred-exporter/select': '/workspaces/$1/accounting/xero/export/xero-preferred-exporter/select',
    '/workspaces/*/connections/quickbooks-online/advanced/autosync/accounting-method':
        '/workspaces/$1/accounting/quickbooks-online/advanced/quickbooks-online-autosync/quickbooks-online-accounting-method',
    '/workspaces/*/connections/quickbooks-online/advanced/autosync': '/workspaces/$1/accounting/quickbooks-online/advanced/quickbooks-online-autosync',
    '/travel/upgrade': '/travel/travel-upgrade',
    '/workspaces/*/accounting/quickbooks-desktop/export/company-card-expense-account': '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-company-card-expense-account',
    '/workspaces/*/accounting/quickbooks-desktop/export/company-card-expense-account-select': '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-company-card-expense-account-select',
    '/workspaces/*/accounting/quickbooks-desktop/export/company-card-expense-account/account-select':
        '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-company-card-expense-account-select',
    '/workspaces/*/accounting/quickbooks-desktop/export/out-of-pocket-expense/account-select':
        '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-out-of-pocket-expense/qbd-account-select',
    '/workspaces/*/accounting/quickbooks-desktop/export/out-of-pocket-expense/entity-select':
        '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-out-of-pocket-expense/qbd-entity-select',
    '/flag/*/*': '/r/$1/flag/$1/$2',
    '/r/*/details/shareCode': '/r/$1/share-code',
    '/e/*/details/shareCode': '/e/$1/share-code',
    '/referral/*': '/home/referral/$1',
    '/a/*/avatar': '/avatar/$1',
    '/settings/profile/contact-methods/verify': '/settings/profile/contact-methods/verify-account',
    '/home-page': '/home',
    '/settings/wallet/enable-payments/plaid*': '/settings/wallet/enable-payments/add-bank-account/plaid$1',
    '/settings/wallet/enable-payments/bank-account-confirmation*': '/settings/wallet/enable-payments/add-bank-account/bank-account-confirmation$1',
    '/settings/wallet/enable-payments/legal-name*': '/settings/wallet/enable-payments/personal-info/legal-name$1',
    '/settings/wallet/enable-payments/date-of-birth*': '/settings/wallet/enable-payments/personal-info/date-of-birth$1',
    '/settings/wallet/enable-payments/address*': '/settings/wallet/enable-payments/personal-info/address$1',
    '/settings/wallet/enable-payments/phone-number*': '/settings/wallet/enable-payments/personal-info/phone-number$1',
    '/settings/wallet/enable-payments/ssn*': '/settings/wallet/enable-payments/personal-info/ssn$1',
    '/settings/wallet/enable-payments/personal-info-confirmation*': '/settings/wallet/enable-payments/personal-info/personal-info-confirmation$1',
    // 'fees*' must not use a bare wildcard - it would also match the new 'fees-and-terms' page and append a duplicate segment on every navigation
    '/settings/wallet/enable-payments/fees': '/settings/wallet/enable-payments/fees-and-terms/fees',
    '/settings/wallet/enable-payments/fees/*': '/settings/wallet/enable-payments/fees-and-terms/fees/$1',
    '/settings/wallet/enable-payments/terms*': '/settings/wallet/enable-payments/fees-and-terms/terms$1',
    /* eslint-enable @typescript-eslint/naming-convention */
};

export default oldRoutes;
