const oldRoutes: Record<string, string> = {
    /* eslint-disable @typescript-eslint/naming-convention */
    '/settings/*/category/*/edit': '/settings/$1/categories/category-settings/$2/category-edit',
    '/settings/*/category/*': '/settings/$1/categories/category-settings/$2',
    '/settings/*/tags/*/edit': '/settings/$1/tags/settings-tags-edit/$2',
    '/settings/*/tags/settings/edit/*': '/settings/$1/tags/settings/settings-tags-edit/$2',
    '/settings/*/tags/tag-list/*/edit/*': '/settings/$1/tags/tag-list/$2/settings-tags-edit/$3',
    '/settings/*/tags/new': '/settings/$1/tags/tag-new',
    '/settings/*/tag/*/*/edit': '/settings/$1/tags/tag-settings/$2/$3/tag-edit/$2/$3',
    '/settings/*/tag/*/*/gl-code': '/settings/$1/tags/tag-settings/$2/$3/gl-code/$2/$3',
    '/settings/*/tag/*/*': '/settings/$1/tags/tag-settings/$2/$3',
    '/workspaces/*/category/*/payroll-code': '/workspaces/$1/categories/category/$2/payroll-code',
    '/workspaces/*/category/*/gl-code': '/workspaces/$1/categories/category/$2/gl-code',
    '/workspaces/*/category/*/edit': '/workspaces/$1/categories/category/$2/edit',
    '/workspaces/*/category/*': '/workspaces/$1/categories/category/$2',
    '/settings/workspaces/*': '/workspaces/$1',
    '/settings/workspaces': '/workspaces',
    '/r/*/settings': '/r/$1/details/report-settings',
    '/r/*/settings/name': '/r/$1/details/settings/name',
    '/r/*/participants/invite': '/r/$1/participants/participants-invite',
    '/r/*/participants/*/role': '/r/$1/participants/participants-details/$2/participants-role',
    '/r/*/title': '/r/$1/title',
    '/r/*/description': '/r/$1/description',
    '/r/*/assignee': '/r/$1/assignee',
    '/r/*/members': '/r/$1/details/members',
    '/r/*/members/*': '/r/$1/details/members/room-member-details/$2',
    '/r/*/invite': '/r/$1/details/room-invite',
    '/r/*/notes/*/edit': '/r/$1/notes-edit/$2',
    '/r/*/notes': '/r/$1/details/notes',
    '/workspaces/*/overview/address': '/workspaces/$1/overview/workspace-address',
    '/workspaces/*/categories/settings': '/workspaces/$1/categories/categories-settings',
    '/workspaces/*/categories/new': '/workspaces/$1/categories/category-new',
    '/workspaces/*/tags/settings': '/workspaces/$1/tags/tags-settings',
    '/workspaces/*/tags/new': '/workspaces/$1/tags/tag-create',
    '/workspaces/*/tags/*/edit': '/workspaces/$1/tags/tags-settings/workspace-edit-tags/$2',
    '/workspaces/*/tags/tags-settings/edit/*': '/workspaces/$1/tags/tags-settings/workspace-edit-tags/$2',
    '/workspaces/*/tag/*/*/edit': '/workspaces/$1/tags/workspace-tag-settings/$2/$3/workspace-tag-edit',
    '/workspaces/*/tag/*/*/gl-code': '/workspaces/$1/tags/workspace-tag-settings/$2/$3/workspace-tag-gl-code',
    '/workspaces/*/tag/*/*/approver': '/workspaces/$1/tags/workspace-tag-settings/$2/$3/workspace-tag-approver',
    '/workspaces/*/tag/*/*/workspace-tag-edit': '/workspaces/$1/tags/workspace-tag-settings/$2/$3/workspace-tag-edit',
    '/workspaces/*/tag/*/*/workspace-tag-gl-code': '/workspaces/$1/tags/workspace-tag-settings/$2/$3/workspace-tag-gl-code',
    '/workspaces/*/tag/*/*/workspace-tag-approver': '/workspaces/$1/tags/workspace-tag-settings/$2/$3/workspace-tag-approver',
    '/workspaces/*/tag/*/*': '/workspaces/$1/tags/workspace-tag-settings/$2/$3',
    '/settings/*/categories/settings': '/settings/$1/categories/manage-settings',
    '/settings/*/categories/new': '/settings/$1/categories/category-create',
    '/workspaces/*/accounting/*/card-reconciliation/account': '/workspaces/$1/accounting/$2/card-reconciliation/account-reconciliation-settings',
    '/workspaces/*/connections/netsuite/export/invoice-item-preference/invoice-item/select': '/workspaces/$1/connections/netsuite/export/invoice-item-preference/select/invoice-item/select',
    '/workspaces/*/connections/xero/export/preferred-exporter/select': '/workspaces/$1/accounting/xero/export/xero-preferred-exporter/select',
    '/workspaces/*/connections/quickbooks-online/advanced/autosync/accounting-method':
        '/workspaces/$1/accounting/quickbooks-online/advanced/quickbooks-online-autosync/quickbooks-online-accounting-method',
    '/workspaces/*/connections/quickbooks-online/advanced/autosync': '/workspaces/$1/accounting/quickbooks-online/advanced/quickbooks-online-autosync',
    '/travel/upgrade': '/travel/travel-upgrade',
    '/workspaces/*/accounting/quickbooks-desktop/export/company-card-expense-account': '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-company-card-expense-account',
    '/workspaces/*/accounting/quickbooks-desktop/export/company-card-expense-account-select': '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-company-card-expense-account-select',
    '/workspaces/*/accounting/quickbooks-desktop/export/company-card-expense-account/account-select':
        '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-company-card-expense-account-select',
    '/workspaces/*/accounting/quickbooks-desktop/export/out-of-pocket-expense/account-select':
        '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-out-of-pocket-expense/qbd-account-select',
    '/workspaces/*/accounting/quickbooks-desktop/export/out-of-pocket-expense/entity-select':
        '/workspaces/$1/accounting/quickbooks-desktop/export/qbd-out-of-pocket-expense/qbd-entity-select',
    '/flag/*/*': '/r/$1/flag/$1/$2',
    '/r/*/details/shareCode': '/r/$1/share-code',
    '/e/*/details/shareCode': '/e/$1/share-code',
    '/referral/*': '/home/referral/$1',
    '/a/*/avatar': '/avatar/$1',
    '/settings/profile/contact-methods/verify': '/settings/profile/contact-methods/verify-account',
    '/home-page': '/home',
    '/workspaces/*/company-cards/company-card-details/*/*/edit/export': '/workspaces/$1/company-cards/company-card-details/$2/$3/edit/export',
    '/workspaces/*/company-cards/company-card-details/*/*/edit/transaction-start-date': '/workspaces/$1/company-cards/company-card-details/$2/$3/edit/transaction-start-date',
    '/workspaces/*/company-cards/company-card-details/*/*/edit/name': '/workspaces/$1/company-cards/company-card-details/$2/$3/edit/name',
    '/workspaces/*/company-cards/company-card-details/assign-card/*': '/workspaces/$1/company-cards/assign-card/$2',
    '/workspaces/*/company-cards/company-card-details/*/*': '/workspaces/$1/company-cards/company-card-details/$2/$3',
    '/workspaces/*/company-cards/*/*/edit/export': '/workspaces/$1/company-cards/company-card-details/$2/$3/edit/export',
    '/workspaces/*/company-cards/assign-card/*': '/workspaces/$1/company-cards/assign-card/$2',
    '/workspaces/*/company-cards/*/*/edit/transaction-start-date': '/workspaces/$1/company-cards/$2/$3/edit/transaction-start-date',
    '/workspaces/*/company-cards/*/*/edit/name': '/workspaces/$1/company-cards/$2/$3/edit/name',
    '/workspaces/*/company-cards/*/assign-card/*': '/workspaces/$1/company-cards/$2/assign-card/$3',
    '/workspaces/*/company-cards/*/broken-card-feed-connection': '/workspaces/$1/company-cards/$2/broken-card-feed-connection',
    '/workspaces/*/company-cards/*/refresh-card-feed-connection': '/workspaces/$1/company-cards/$2/refresh-card-feed-connection',
    '/workspaces/*/company-cards/*/work-email': '/workspaces/$1/company-cards/$2/work-email',
    '/workspaces/*/company-cards/*/verify-work-email': '/workspaces/$1/company-cards/$2/verify-work-email',
    '/workspaces/*/company-cards/settings/*': '/workspaces/$1/company-cards/settings/$2',
    '/workspaces/*/company-cards/add-card-feed/*': '/workspaces/$1/company-cards/add-card-feed/$2',
    '/workspaces/*/company-cards/select-feed/*': '/workspaces/$1/company-cards/select-feed/$2',
    '/workspaces/*/company-cards/*/*': '/workspaces/$1/company-cards/company-card-details/$2/$3',
    '/workspace/confirmation/currency': '/workspaces/workspace/confirmation/currency',
    '/workspace/confirmation': '/workspaces/workspace/confirmation',
    '/settings/wallet/enable-payments/plaid*': '/settings/wallet/enable-payments/add-bank-account/plaid$1',
    '/settings/wallet/enable-payments/bank-account-confirmation*': '/settings/wallet/enable-payments/add-bank-account/confirmation$1',
    '/settings/wallet/enable-payments/legal-name*': '/settings/wallet/enable-payments/personal-info/legal-name$1',
    '/settings/wallet/enable-payments/date-of-birth*': '/settings/wallet/enable-payments/personal-info/date-of-birth$1',
    '/settings/wallet/enable-payments/address*': '/settings/wallet/enable-payments/personal-info/address$1',
    '/settings/wallet/enable-payments/phone-number*': '/settings/wallet/enable-payments/personal-info/phone-number$1',
    '/settings/wallet/enable-payments/ssn*': '/settings/wallet/enable-payments/personal-info/ssn$1',
    '/settings/wallet/enable-payments/personal-info-confirmation*': '/settings/wallet/enable-payments/personal-info/confirmation$1',
    // 'fees*' must not use a bare wildcard - it would also match the new 'fees-and-terms' page and append a duplicate segment on every navigation
    '/settings/wallet/enable-payments/fees': '/settings/wallet/enable-payments/fees-and-terms/fees',
    '/settings/wallet/enable-payments/fees/*': '/settings/wallet/enable-payments/fees-and-terms/fees/$1',
    '/settings/wallet/enable-payments/terms*': '/settings/wallet/enable-payments/fees-and-terms/terms$1',
    '/workspaces/*/workflows/approvals/expenses-from': '/workspaces/$1/workflows/approvals/new/expenses-from',
    /* eslint-enable @typescript-eslint/naming-convention */
};

export default oldRoutes;
