import hasDifferentSplitScope from '@libs/Navigation/helpers/hasDifferentSplitScope';
import {isRecord} from '@libs/ObjectUtils';

import type {NavigationRoute, State} from '@navigation/types';

import type {NavigationAction, NavigationState} from '@react-navigation/native';
import type {Writable} from 'type-fest';

import type {ActionPayload} from './types';

type MinimalAction = {
    action: Writable<NavigationAction>;
    /** The state of the navigator the minimal action is addressed at, which is the root state when the descent stops on it */
    targetState: State;
    /**
     * True when the descent stopped on a split navigator that has the requested name but holds another scope
     * (another workspace or domain). Callers decide what that means: forward navigation pushes a sibling split
     * instead of reusing this one, backward navigation looks for the matching split among its siblings.
     */
    isFocusedRouteInDifferentScope: boolean;
};

function isNamedActionPayload(payload: unknown): payload is ActionPayload & {name: string} {
    return isRecord(payload) && typeof payload.name === 'string';
}

/**
 * One step of the descent: the same action addressed at `nestedState`, the state of the route the given action names.
 * Its payload has no name when the action addresses nothing below that route, which is where a descent stops.
 */
function getNestedAction(action: NavigationAction, nestedState: State): Writable<NavigationAction> {
    const params = isNamedActionPayload(action.payload) ? action.payload.params : undefined;
    return {
        type: action.type,
        payload: {
            name: params?.screen,
            params: params?.params,
            path: params?.path,
        },
        target: nestedState.key,
    };
}

/**
 * Motivation for this function is described in NAVIGATION.md
 *
 * @param action action generated by getActionFromState
 * @param state The root state
 * @returns minimalAction minimal action is the action that we should dispatch
 */
function getMinimalAction(action: NavigationAction, state: NavigationState): MinimalAction {
    let currentAction: Writable<NavigationAction> = action;
    let currentState: State = state;
    let isFocusedRouteInDifferentScope = false;

    while (isNamedActionPayload(currentAction.payload)) {
        const currentRoute: NavigationRoute | undefined = currentState.routes.at(currentState.index ?? -1);
        if (!currentRoute || currentRoute.name !== currentAction.payload.name) {
            break;
        }

        // Descending into a split of another scope would reuse its sidebar for a different workspace or domain.
        isFocusedRouteInDifferentScope = hasDifferentSplitScope(currentRoute, currentAction.payload);
        if (!currentRoute.state || isFocusedRouteInDifferentScope) {
            break;
        }

        currentAction = getNestedAction(currentAction, currentRoute.state);
        currentState = currentRoute.state;
    }
    return {action: currentAction, targetState: currentState, isFocusedRouteInDifferentScope};
}

export default getMinimalAction;
export {getNestedAction};
