/**
 * Barrel file that merges shared, NativeBiometrics, and Passkeys VALUES
 * into a single object matching the original Biometrics/VALUES shape.
 * This ensures CONST.MULTIFACTOR_AUTHENTICATION continues working everywhere.
 */
import NATIVE_BIOMETRICS_VALUES from './NativeBiometrics/VALUES';
import PASSKEY_VALUES from './Passkeys/VALUES';
import SHARED_VALUES from './shared/VALUES';

const MULTIFACTOR_AUTHENTICATION_VALUES = {
    ...SHARED_VALUES,

    // NativeBiometrics-specific
    KEYCHAIN_SERVICE: NATIVE_BIOMETRICS_VALUES.KEYCHAIN_SERVICE,
    ED25519_TYPE: NATIVE_BIOMETRICS_VALUES.ED25519_TYPE,
    KEY_ALIASES: NATIVE_BIOMETRICS_VALUES.KEY_ALIASES,
    EXPO_ERRORS: NATIVE_BIOMETRICS_VALUES.EXPO_ERRORS,
    EXPO_ERROR_MAPPINGS: NATIVE_BIOMETRICS_VALUES.EXPO_ERROR_MAPPINGS,

    // Passkeys-specific
    WEBAUTHN_ERRORS: PASSKEY_VALUES.WEBAUTHN_ERRORS,
    WEBAUTHN_ERROR_MAPPINGS: PASSKEY_VALUES.WEBAUTHN_ERROR_MAPPINGS,
} as const;

export default MULTIFACTOR_AUTHENTICATION_VALUES;
