import {getDrivingJourneyPaths, getMfaShortestPaths} from 'tests/utils/mfa/flowPaths';
import {getStableLeafStates} from 'tests/utils/mfa/leafStates';
import {matchesState} from 'xstate';
import mfaMachine from '@components/MultifactorAuthentication/machine/mfaMachine';

// Both suites in this file are generated by traversing the mfaMachine graph, so a state added to the
// machine gets a test here automatically. Nothing renders in this file. `leafStates.ts` excludes
// only transient leaves that XState resolves before emitting a snapshot.

// Reachability is asserted on the unfiltered shortest paths, so it also covers routes the UI walk in
// `viewMatchesMachine.test.tsx` cannot drive (a delayed transition, for example). A failure here means
// the machine itself lost the state, not that the UI harness broke.
describe('every stable MFA state is reachable in the machine chart', () => {
    const reachableSnapshots = getMfaShortestPaths().map((path) => path.state);

    it.each(getStableLeafStates(mfaMachine.root))('$description can be reached from the initial state', ({description}) => {
        expect(reachableSnapshots.some((snapshot) => matchesState(description, snapshot.value))).toBe(true);
    });
});

// The journey endpoints are the only hand-written expectations, so a transition that points at the
// wrong target can only surface here, and only when a journey drives it. The `DRIVING_JOURNEYS` doc
// explains why.
describe('every driving journey ends in its pinned state', () => {
    it.each(getDrivingJourneyPaths())('$description', ({paths, endState}) => {
        expect(paths.length).toBeGreaterThan(0);
        for (const path of paths) {
            expect(matchesState(endState, path.state.value)).toBe(true);
        }
    });
});
