import {AUTHENTICATION_COMMAND} from '@libs/API/types';
import {getApiRoot} from '@libs/ApiUtils';
import Log from '@libs/Log';
import {getBaseRequestParameters} from '@libs/Network/enhanceParameters';
import {getCredentials} from '@libs/Network/NetworkStore';
import {getPartnerCredentials} from '@libs/SessionUtils';

import CONST from '@src/CONST';
import type Credentials from '@src/types/onyx/Credentials';

import {clearTokenRefresh, prefetchOnAppStart, registerTokenRefresh} from 'react-native-nitro-fetch';

import type RegisterPrefetchOnAppStart from './types';

const NITRO_FETCH_TARGET = 'fetch';
const CONTENT_TYPE_HEADER = 'Content-Type';

function buildAuthenticateBody(credentials: Credentials): string {
    // NitroFetch token refresh runs outside the JS request pipeline, so we must serialize the
    // Authenticate body here instead of going through Request.post() and enhanceParameters().
    const {partnerName, partnerPassword} = getPartnerCredentials(credentials.autoGeneratedLogin);
    // eslint-disable-next-line @typescript-eslint/naming-convention
    const {referer, platform, api_setCookie, isFromDevEnv} = getBaseRequestParameters();

    const body = new URLSearchParams();
    body.append('useExpensifyLogin', 'false');
    body.append('partnerName', partnerName);
    body.append('partnerPassword', partnerPassword);
    body.append('partnerUserID', credentials.autoGeneratedLogin ?? '');
    body.append('partnerUserSecret', credentials.autoGeneratedPassword ?? '');
    body.append('shouldRetry', 'false');
    body.append('forceNetworkRequest', 'true');
    body.append('email', credentials.login ?? '');
    body.append('referer', referer);
    body.append('platform', platform);
    body.append('api_setCookie', String(api_setCookie));
    body.append('isFromDevEnv', String(isFromDevEnv));

    return body.toString();
}

function registerPrefetchTokenRefresh(): void {
    const credentials = getCredentials();

    clearTokenRefresh(NITRO_FETCH_TARGET);

    if (!credentials?.autoGeneratedLogin || !credentials.autoGeneratedPassword) {
        return;
    }

    const authenticateURL = `${getApiRoot()}api/${AUTHENTICATION_COMMAND}?`;

    registerTokenRefresh({
        target: NITRO_FETCH_TARGET,
        url: authenticateURL,
        method: 'POST',
        headers: {
            [CONTENT_TYPE_HEADER]: 'application/x-www-form-urlencoded',
        },
        body: buildAuthenticateBody(credentials),
        responseType: 'json',
        formDataMappings: [{jsonPath: CONST.HTTP_HEADER_NAMES.AUTH_TOKEN, field: CONST.HTTP_HEADER_NAMES.AUTH_TOKEN}],
        onFailure: 'useStoredHeaders',
    });

    Log.info('[NitroFetchTokenRefresh] Registered token refresh for startup prefetch', false);
}

const registerPrefetchOnAppStart: RegisterPrefetchOnAppStart = ({prefetchKey, fetchParams, command, url}) => {
    if (!prefetchKey) {
        return;
    }

    registerPrefetchTokenRefresh();
    prefetchOnAppStart(url, fetchParams).catch((error) => {
        Log.warn(`[HttpUtils] prefetchOnAppStart failed for ${command}`, {error, fetchParams, url});
    });
};

export default registerPrefetchOnAppStart;
