/**
 * This is a file containing constants for all of the screen names. In most cases, we should use the routes for
 * navigation. But there are situations where we may need to access screen names directly.
 */
import type DeepValueOf from './types/utils/DeepValueOf';

const PROTECTED_SCREENS = {
    HOME: 'Home',
    CONCIERGE: 'Concierge',
    ATTACHMENTS: 'Attachments',
    TRACK_EXPENSE: 'Track Expense',
    SUBMIT_EXPENSE: 'Submit Expense',
} as const;

const SCREENS = {
    ...PROTECTED_SCREENS,
    REPORT: 'Report',
    PROFILE_AVATAR: 'Profile Avatar',
    WORKSPACE_AVATAR: 'Workspace Avatar',
    REPORT_AVATAR: 'Report Avatar',
    NOT_FOUND: 'Not Found',
    TRANSITION_BETWEEN_APPS: 'Transition Between Apps',
    VALIDATE_LOGIN: 'Validate Login',
    CONNECTION_COMPLETE: 'Connection Complete',
    UNLINK_LOGIN: 'Unlink Login',
    SETTINGS_CENTRAL_PANE: 'Settings',
    TRAVEL: {
        MY_TRIPS: 'My Trips',
        TCS: 'Travel Concierge Services',
    },
    SEARCH: {
        CENTRAL_PANE: 'Search',
        REPORT: 'Search Report',
        ADVANCED_FILTERS: 'Search Advanced Filters',
        ADVANCED_FILTERS_DATE: 'Search Advanced Filters Date',
        ADVANCED_FILTERS_TYPE: 'Search Advanced Filters Type',
        ADVANCED_FILTERS_STATUS: 'Search Advanced Filters Status',
        ADVANCED_FILTERS_CURRENCY: 'Search Advanced Filters Currency',
        ADVANCED_FILTERS_DESCRIPTION: 'Search Advanced Filters Description',
        ADVANCED_FILTERS_MERCHANT: 'Search Advanced Filters Merchant',
        ADVANCED_FILTERS_REPORT_ID: 'Search Advanced Filters ReportID',
        ADVANCED_FILTERS_CATEGORY: 'Search Advanced Filters Category',
        ADVANCED_FILTERS_CARD: 'Search Advanced Filters Card',
        TRANSACTION_HOLD_REASON: 'Search Transaction Hold Reason',
        BOTTOM_TAB: 'Search',
    },
    SETTINGS: {
        ROOT: 'Settings',
        SHARE_CODE: 'Share Code',
        WORKSPACES: 'Workspaces',
        SECURITY: 'Security',
        ABOUT: 'About',
        SAVE_THE_WORLD: 'Teachers Unite',
        APP_DOWNLOAD_LINKS: 'App Download Links',
        ADD_DEBIT_CARD: 'Add Debit Card',
        ADD_PAYMENT_CARD_CHANGE_CURRENCY: 'Add Payment Card Change Currency',
        ADD_BANK_ACCOUNT: 'Add Bank Account',
        CLOSE: 'Close Settings',
        TWO_FACTOR_AUTH: 'Two-Factor Authentication',
        REPORT_CARD_LOST_OR_DAMAGED: 'Report Lost or Damaged Card',
        TROUBLESHOOT: 'Troubleshoot',
        CONSOLE: 'Console',
        SHARE_LOG: 'Share Log',

        PROFILE: {
            ROOT: 'Profile',
            DISPLAY_NAME: 'Display Name',
            CONTACT_METHODS: 'Contact Methods',
            CONTACT_METHOD_DETAILS: 'Contact Method Details',
            NEW_CONTACT_METHOD: 'New Contact Method',
            STATUS_CLEAR_AFTER: 'Clear Status After',
            STATUS_CLEAR_AFTER_DATE: 'Clear Status After Date',
            STATUS_CLEAR_AFTER_TIME: 'Clear Status After Time',
            STATUS: 'Status',
            PRONOUNS: 'Pronouns',
            TIMEZONE: 'Timezone',
            TIMEZONE_SELECT: 'Select Timezone',
            LEGAL_NAME: 'Legal Name',
            DATE_OF_BIRTH: 'Date of Birth',
            ADDRESS: 'Address',
            ADDRESS_COUNTRY: 'Country',
            ADDRESS_STATE: 'State',
        },

        PREFERENCES: {
            ROOT: 'Preferences',
            PRIORITY_MODE: 'Priority Mode',
            LANGUAGE: 'Language',
            THEME: 'Theme',
        },

        WALLET: {
            ROOT: 'Wallet',
            DOMAIN_CARD: 'Domain Card',
            CARD_GET_PHYSICAL: {
                NAME: 'Get Physical Card - Name',
                PHONE: 'Get Physical Card - Phone',
                ADDRESS: 'Get Physical Card - Address',
                CONFIRM: 'Get Physical Card - Confirm',
            },
            TRANSFER_BALANCE: 'Transfer Balance',
            CHOOSE_TRANSFER_ACCOUNT: 'Choose Transfer Account',
            ENABLE_PAYMENTS: 'Enable Payments',
            CARD_ACTIVATE: 'Activate Card',
            REPORT_VIRTUAL_CARD_FRAUD: 'Report Virtual Card Fraud',
            CARDS_DIGITAL_DETAILS_UPDATE_ADDRESS: 'Update Card Address',
        },

        EXIT_SURVEY: {
            REASON: 'Exit Survey - Reason',
            RESPONSE: 'Exit Survey - Response',
            CONFIRM: 'Exit Survey - Confirm',
        },

        SUBSCRIPTION: {
            ROOT: 'Subscription',
            SIZE: 'Subscription Size',
            ADD_PAYMENT_CARD: 'Add Payment Card',
            DISABLE_AUTO_RENEW_SURVEY: 'Disable Auto-Renew Survey',
            CHANGE_BILLING_CURRENCY: 'Change Billing Currency',
            CHANGE_PAYMENT_CURRENCY: 'Change Payment Currency',
            REQUEST_EARLY_CANCELLATION: 'Request Early Cancellation',
        },
    },
    SAVE_THE_WORLD: {
        ROOT: 'Save the World',
    },
    LEFT_MODAL: {
        CHAT_FINDER: 'Chat Finder',
        WORKSPACE_SWITCHER: 'Workspace Switcher',
    },
    RIGHT_MODAL: {
        SETTINGS: 'Settings',
        NEW_CHAT: 'New Chat',
        DETAILS: 'Details',
        PROFILE: 'Profile',
        REPORT_DETAILS: 'Report Details',
        REPORT_SETTINGS: 'Report Settings',
        REPORT_DESCRIPTION: 'Report Description',
        PARTICIPANTS: 'Participants',
        MONEY_REQUEST: 'Money Request',
        NEW_TASK: 'New Task',
        TEACHERS_UNITE: 'Teachers Unite',
        TASK_DETAILS: 'Task Details',
        ENABLE_PAYMENTS: 'Enable Payments',
        SPLIT_DETAILS: 'Split Details',
        ADD_PERSONAL_BANK_ACCOUNT: 'Add Personal Bank Account',
        WALLET_STATEMENT: 'Wallet Statement',
        FLAG_COMMENT: 'Flag Comment',
        EDIT_REQUEST: 'Edit Request',
        SIGN_IN: 'Sign In',
        PRIVATE_NOTES: 'Private Notes',
        ROOM_MEMBERS: 'Room Members',
        ROOM_INVITE: 'Room Invite',
        REFERRAL: 'Referral',
        PROCESS_MONEY_REQUEST_HOLD: 'Process Money Request Hold',
        TRANSACTION_DUPLICATE: 'Transaction Duplicate',
        TRAVEL: 'Travel',
        SEARCH_REPORT: 'Search Report',
        SEARCH_ADVANCED_FILTERS: 'Search Advanced Filters',
        SETTINGS_CATEGORIES: 'Settings Categories',
        RESTRICTED_ACTION: 'Restricted Action',
        REPORT_EXPORT: 'Export Report',
    },
    ONBOARDING_MODAL: {
        ONBOARDING: 'Onboarding',
    },
    SIGN_IN_WITH_APPLE_DESKTOP: 'Sign In with Apple Desktop',
    SIGN_IN_WITH_GOOGLE_DESKTOP: 'Sign In with Google Desktop',
    DESKTOP_SIGN_IN_REDIRECT: 'Desktop Sign In Redirect',
    SAML_SIGN_IN: 'SAML Sign In',
    WORKSPACE_JOIN_USER: 'Join Workspace',

    MONEY_REQUEST: {
        CREATE: 'Create Money Request',
        HOLD: 'Money Request Hold Reason',
        STEP_CONFIRMATION: 'Money Request Confirmation',
        START: 'Start Money Request',
        STEP_AMOUNT: 'Money Request Amount',
        STEP_CATEGORY: 'Money Request Category',
        STEP_CURRENCY: 'Money Request Currency',
        STEP_DATE: 'Money Request Date',
        STEP_DESCRIPTION: 'Money Request Description',
        STEP_DISTANCE: 'Money Request Distance',
        STEP_DISTANCE_RATE: 'Money Request Distance Rate',
        STEP_MERCHANT: 'Money Request Merchant',
        STEP_PARTICIPANTS: 'Money Request Participants',
        STEP_SCAN: 'Money Request Scan',
        STEP_TAG: 'Money Request Tag',
        STEP_WAYPOINT: 'Money Request Waypoint',
        STEP_TAX_AMOUNT: 'Money Request Tax Amount',
        STEP_TAX_RATE: 'Money Request Tax Rate',
        STEP_SPLIT_PAYER: 'Money Request Split Payer',
        STEP_SEND_FROM: 'Money Request Send From',
        CURRENCY: 'Money Request Currency',
        WAYPOINT: 'Money Request Waypoint',
        EDIT_WAYPOINT: 'Edit Money Request Waypoint',
        RECEIPT: 'Money Request Receipt',
        STATE_SELECTOR: 'Money Request State Selector',
    },

    TRANSACTION_DUPLICATE: {
        REVIEW: 'Review Duplicate Transaction',
        MERCHANT: 'Duplicate Transaction Merchant',
        CATEGORY: 'Duplicate Transaction Category',
        TAG: 'Duplicate Transaction Tag',
        DESCRIPTION: 'Duplicate Transaction Description',
        TAX_CODE: 'Duplicate Transaction Tax Code',
        REIMBURSABLE: 'Duplicate Transaction Reimbursable',
        BILLABLE: 'Duplicate Transaction Billable',
        CONFIRMATION: 'Duplicate Transaction Confirmation',
    },

    IOU_SEND: {
        ADD_BANK_ACCOUNT: 'Add Bank Account',
        ADD_DEBIT_CARD: 'Add Debit Card',
        ENABLE_PAYMENTS: 'Enable Payments',
    },

    SETTINGS_CATEGORIES: {
        SETTINGS_CATEGORY_SETTINGS: 'Category Settings',
        SETTINGS_CATEGORIES_SETTINGS: 'Categories Settings',
        SETTINGS_CATEGORY_CREATE: 'Create Category',
        SETTINGS_CATEGORY_EDIT: 'Edit Category',
        SETTINGS_CATEGORIES_ROOT: 'Categories',
    },

    REPORT_SETTINGS: {
        ROOT: 'Report Settings',
        NAME: 'Report Settings Name',
        NOTIFICATION_PREFERENCES: 'Notification Preferences',
        WRITE_CAPABILITY: 'Write Capability',
        VISIBILITY: 'Visibility',
    },

    NEW_TASK: {
        ROOT: 'New Task',
        TASK_ASSIGNEE_SELECTOR: 'Task Assignee Selector',
        TASK_SHARE_DESTINATION_SELECTOR: 'Task Share Destination Selector',
        DETAILS: 'Task Details',
        TITLE: 'Task Title',
        DESCRIPTION: 'Task Description',
    },

    TASK: {
        TITLE: 'Task Title',
        ASSIGNEE: 'Task Assignee',
    },

    PRIVATE_NOTES: {
        LIST: 'Private Notes List',
        EDIT: 'Edit Private Notes',
    },

    REPORT_DETAILS: {
        ROOT: 'Report Details',
        SHARE_CODE: 'Report Share Code',
        EXPORT: 'Export Report',
    },

    WORKSPACE: {
        ACCOUNTING: {
            ROOT: 'Accounting',
            QUICKBOOKS_ONLINE_IMPORT: 'QuickBooks Online Import',
            QUICKBOOKS_ONLINE_CHART_OF_ACCOUNTS: 'QuickBooks Online Chart of Accounts',
            QUICKBOOKS_ONLINE_CLASSES: 'QuickBooks Online Classes',
            QUICKBOOKS_ONLINE_CUSTOMERS: 'QuickBooks Online Customers',
            QUICKBOOKS_ONLINE_LOCATIONS: 'QuickBooks Online Locations',
            QUICKBOOKS_ONLINE_TAXES: 'QuickBooks Online Taxes',
            QUICKBOOKS_ONLINE_EXPORT: 'QuickBooks Online Export',
            QUICKBOOKS_ONLINE_EXPORT_DATE_SELECT: 'QuickBooks Online Export Date Select',
            QUICKBOOKS_ONLINE_EXPORT_INVOICE_ACCOUNT_SELECT: 'QuickBooks Online Export Invoice Account Select',
            QUICKBOOKS_ONLINE_COMPANY_CARD_EXPENSE_ACCOUNT: 'QuickBooks Online Company Card Expense',
            QUICKBOOKS_ONLINE_COMPANY_CARD_EXPENSE_ACCOUNT_SELECT: 'QuickBooks Online Company Card Expense Account Select',
            QUICKBOOKS_ONLINE_NON_REIMBURSABLE_DEFAULT_VENDOR_SELECT: 'QuickBooks Online Non-Reimbursable Default Vendor Select',
            QUICKBOOKS_ONLINE_COMPANY_CARD_EXPENSE_ACCOUNT_COMPANY_CARD_SELECT: 'QuickBooks Online Company Card Select',
            QUICKBOOKS_ONLINE_EXPORT_PREFERRED_EXPORTER: 'QuickBooks Online Preferred Exporter',
            QUICKBOOKS_ONLINE_EXPORT_OUT_OF_POCKET_EXPENSES: 'QuickBooks Online Export Out-of-Pocket Expenses',
            QUICKBOOKS_ONLINE_EXPORT_OUT_OF_POCKET_EXPENSES_SELECT: 'QuickBooks Online Export Out-of-Pocket Expenses Select',
            QUICKBOOKS_ONLINE_EXPORT_OUT_OF_POCKET_EXPENSES_ACCOUNT_SELECT: 'QuickBooks Online Export Out-of-Pocket Expenses Account Select',
            QUICKBOOKS_ONLINE_ADVANCED: 'QuickBooks Online Advanced',
            QUICKBOOKS_ONLINE_ACCOUNT_SELECTOR: 'QuickBooks Online Account Selector',
            QUICKBOOKS_ONLINE_INVOICE_ACCOUNT_SELECTOR: 'QuickBooks Online Invoice Account Selector',
            XERO_IMPORT: 'Xero Import',
            XERO_ORGANIZATION: 'Xero Organization',
            XERO_CHART_OF_ACCOUNTS: 'Xero Chart of Accounts',
            XERO_CUSTOMER: 'Xero Customer',
            XERO_TAXES: 'Xero Taxes',
            XERO_TRACKING_CATEGORIES: 'Xero Tracking Categories',
            XERO_MAP_TRACKING_CATEGORY: 'Xero Map Tracking Category',
            XERO_EXPORT: 'Xero Export',
            XERO_EXPORT_PURCHASE_BILL_DATE_SELECT: 'Xero Export Purchase Bill Date Select',
            XERO_ADVANCED: 'Xero Advanced',
            XERO_BILL_STATUS_SELECTOR: 'Xero Bill Status Selector',
            XERO_INVOICE_ACCOUNT_SELECTOR: 'Xero Invoice Account Selector',
            XERO_EXPORT_PREFERRED_EXPORTER_SELECT: 'Xero Export Preferred Exporter Select',
            XERO_BILL_PAYMENT_ACCOUNT_SELECTOR: 'Xero Bill Payment Account Selector',
            XERO_EXPORT_BANK_ACCOUNT_SELECT: 'Xero Export Bank Account Select',
            NETSUITE_IMPORT_MAPPING: 'NetSuite Import Mapping',
            NETSUITE_IMPORT_CUSTOM_FIELD: 'NetSuite Import Custom Field',
            NETSUITE_IMPORT_CUSTOM_FIELD_VIEW: 'NetSuite Import Custom Field View',
            NETSUITE_IMPORT_CUSTOM_FIELD_EDIT: 'NetSuite Import Custom Field Edit',
            NETSUITE_IMPORT_CUSTOM_LIST_ADD: 'NetSuite Import Custom List Add',
            NETSUITE_IMPORT_CUSTOM_SEGMENT_ADD: 'NetSuite Import Custom Segment Add',
            NETSUITE_IMPORT_CUSTOMERS_OR_PROJECTS: 'NetSuite Import Customers or Projects',
            NETSUITE_IMPORT_CUSTOMERS_OR_PROJECTS_SELECT: 'NetSuite Import Customers or Projects Select',
            NETSUITE_REUSE_EXISTING_CONNECTIONS: 'NetSuite Reuse Existing Connections',
            NETSUITE_TOKEN_INPUT: 'NetSuite Token Input',
            NETSUITE_SUBSIDIARY_SELECTOR: 'NetSuite Subsidiary Selector',
            NETSUITE_IMPORT: 'NetSuite Import',
            NETSUITE_EXPORT: 'NetSuite Export',
            NETSUITE_PREFERRED_EXPORTER_SELECT: 'NetSuite Preferred Exporter Select',
            NETSUITE_DATE_SELECT: 'NetSuite Date Select',
            NETSUITE_EXPORT_EXPENSES: 'NetSuite Export Expenses',
            NETSUITE_EXPORT_EXPENSES_DESTINATION_SELECT: 'NetSuite Export Expenses Destination Select',
            NETSUITE_EXPORT_EXPENSES_VENDOR_SELECT: 'NetSuite Export Expenses Vendor Select',
            NETSUITE_EXPORT_EXPENSES_PAYABLE_ACCOUNT_SELECT: 'NetSuite Export Expenses Payable Account Select',
            NETSUITE_EXPORT_EXPENSES_JOURNAL_POSTING_PREFERENCE_SELECT: 'NetSuite Export Expenses Journal Posting Preference Select',
            NETSUITE_RECEIVABLE_ACCOUNT_SELECT: 'NetSuite Receivable Account Select',
            NETSUITE_INVOICE_ITEM_PREFERENCE_SELECT: 'NetSuite Invoice Item Preference Select',
            NETSUITE_INVOICE_ITEM_SELECT: 'NetSuite Invoice Item Select',
            NETSUITE_TAX_POSTING_ACCOUNT_SELECT: 'NetSuite Tax Posting Account Select',
            NETSUITE_PROVINCIAL_TAX_POSTING_ACCOUNT_SELECT: 'NetSuite Provincial Tax Posting Account Select',
            NETSUITE_ADVANCED: 'NetSuite Advanced',
            NETSUITE_REIMBURSEMENT_ACCOUNT_SELECT: 'NetSuite Reimbursement Account Select',
            NETSUITE_COLLECTION_ACCOUNT_SELECT: 'NetSuite Collection Account Select',
            NETSUITE_EXPENSE_REPORT_APPROVAL_LEVEL_SELECT: 'NetSuite Expense Report Approval Level Select',
            NETSUITE_VENDOR_BILL_APPROVAL_LEVEL_SELECT: 'NetSuite Vendor Bill Approval Level Select',
            NETSUITE_JOURNAL_ENTRY_APPROVAL_LEVEL_SELECT: 'NetSuite Journal Entry Approval Level Select',
            NETSUITE_APPROVAL_ACCOUNT_SELECT: 'NetSuite Approval Account Select',
            NETSUITE_CUSTOM_FORM_ID: 'NetSuite Custom Form ID',
            SAGE_INTACCT_PREREQUISITES: 'Sage Intacct Prerequisites',
            ENTER_SAGE_INTACCT_CREDENTIALS: 'Enter Sage Intacct Credentials',
            EXISTING_SAGE_INTACCT_CONNECTIONS: 'Existing Sage Intacct Connections',
            SAGE_INTACCT_ENTITY: 'Sage Intacct Entity',
            SAGE_INTACCT_IMPORT: 'Sage Intacct Import',
            SAGE_INTACCT_TOGGLE_MAPPING: 'Sage Intacct Toggle Mapping',
            SAGE_INTACCT_MAPPING_TYPE: 'Sage Intacct Mapping Type',
            SAGE_INTACCT_USER_DIMENSIONS: 'Sage Intacct User Dimensions',
            SAGE_INTACCT_ADD_USER_DIMENSION: 'Add Sage Intacct User Dimension',
            SAGE_INTACCT_EDIT_USER_DIMENSION: 'Edit Sage Intacct User Dimension',
            SAGE_INTACCT_EXPORT: 'Sage Intacct Export',
            SAGE_INTACCT_PREFERRED_EXPORTER: 'Sage Intacct Preferred Exporter',
            SAGE_INTACCT_EXPORT_DATE: 'Sage Intacct Export Date',
            SAGE_INTACCT_REIMBURSABLE_EXPENSES: 'Sage Intacct Reimbursable Expenses',
            SAGE_INTACCT_NON_REIMBURSABLE_EXPENSES: 'Sage Intacct Non-Reimbursable Expenses',
            SAGE_INTACCT_DEFAULT_VENDOR: 'Sage Intacct Default Vendor',
            SAGE_INTACCT_NON_REIMBURSABLE_CREDIT_CARD_ACCOUNT: 'Sage Intacct Non-Reimbursable Credit Card Account',
            SAGE_INTACCT_ADVANCED: 'Sage Intacct Advanced',
            SAGE_INTACCT_PAYMENT_ACCOUNT: 'Sage Intacct Payment Account',
            CARD_RECONCILIATION: 'Card Reconciliation',
            RECONCILIATION_ACCOUNT_SETTINGS: 'Reconciliation Account Settings',
        },
        INITIAL: 'Workspace Initial',
        PROFILE: 'Workspace Profile',
        CARD: 'Workspace Card',
        REIMBURSE: 'Reimburse',
        RATE_AND_UNIT: 'Rate and Unit',
        RATE_AND_UNIT_RATE: 'Rate and Unit Rate',
        RATE_AND_UNIT_UNIT: 'Rate and Unit Unit',
        EXPENSIFY_CARD: 'Expensify Card',
        EXPENSIFY_CARD_DETAILS: 'Expensify Card Details',
        EXPENSIFY_CARD_LIMIT: 'Expensify Card Limit',
        EXPENSIFY_CARD_ISSUE_NEW: 'Issue New Expensify Card',
        EXPENSIFY_CARD_NAME: 'Expensify Card Name',
        EXPENSIFY_CARD_LIMIT_TYPE: 'Expensify Card Limit Type',
        EXPENSIFY_CARD_BANK_ACCOUNT: 'Expensify Card Bank Account',
        EXPENSIFY_CARD_SETTINGS: 'Expensify Card Settings',
        EXPENSIFY_CARD_SETTINGS_ACCOUNT: 'Expensify Card Settings Account',
        EXPENSIFY_CARD_SETTINGS_FREQUENCY: 'Expensify Card Settings Frequency',
        BILLS: 'Bills',
        INVOICES: 'Invoices',
        TRAVEL: 'Travel',
        MEMBERS: 'Members',
        INVITE: 'Invite',
        INVITE_MESSAGE: 'Invite Message',
        CATEGORIES: 'Categories',
        TAGS: 'Tags',
        TAGS_SETTINGS: 'Tags Settings',
        TAGS_EDIT: 'Edit Tags',
        TAG_EDIT: 'Edit Tag',
        TAXES: 'Taxes',
        REPORT_FIELDS: 'Report Fields',
        REPORT_FIELDS_SETTINGS: 'Report Fields Settings',
        REPORT_FIELDS_CREATE: 'Create Report Fields',
        REPORT_FIELDS_LIST_VALUES: 'Report Fields List Values',
        REPORT_FIELDS_ADD_VALUE: 'Add Report Field Value',
        REPORT_FIELDS_VALUE_SETTINGS: 'Report Field Value Settings',
        REPORT_FIELDS_EDIT_VALUE: 'Edit Report Field Value',
        REPORT_FIELDS_EDIT_INITIAL_VALUE: 'Edit Initial Report Field Value',
        TAX_EDIT: 'Edit Tax',
        TAX_NAME: 'Tax Name',
        TAX_VALUE: 'Tax Value',
        TAX_CODE: 'Tax Code',
        TAXES_SETTINGS: 'Taxes Settings',
        TAXES_SETTINGS_CUSTOM_TAX_NAME: 'Custom Tax Name',
        TAXES_SETTINGS_WORKSPACE_CURRENCY_DEFAULT: 'Workspace Currency Default',
        TAXES_SETTINGS_FOREIGN_CURRENCY_DEFAULT: 'Foreign Currency Default',
        TAX_CREATE: 'Create Tax',
        TAG_CREATE: 'Create Tag',
        TAG_SETTINGS: 'Tag Settings',
        TAG_LIST_VIEW: 'Tag List View',
        TAG_GL_CODE: 'Tag GL Code',
        CURRENCY: 'Workspace Currency',
        ADDRESS: 'Workspace Address',
        WORKFLOWS: 'Workflows',
        WORKFLOWS_PAYER: 'Workflows Payer',
        WORKFLOWS_APPROVALS_NEW: 'New Approvals Workflow',
        WORKFLOWS_APPROVALS_EDIT: 'Edit Approvals Workflow',
        WORKFLOWS_APPROVALS_EXPENSES_FROM: 'Approvals Expenses From',
        WORKFLOWS_APPROVALS_APPROVER: 'Approvals Approver',
        WORKFLOWS_AUTO_REPORTING_FREQUENCY: 'Auto Reporting Frequency',
        WORKFLOWS_AUTO_REPORTING_MONTHLY_OFFSET: 'Auto Reporting Monthly Offset',
        DESCRIPTION: 'Workspace Description',
        SHARE: 'Share Workspace',
        NAME: 'Workspace Name',
        CATEGORY_CREATE: 'Create Category',
        CATEGORY_EDIT: 'Edit Category',
        CATEGORY_PAYROLL_CODE: 'Category Payroll Code',
        CATEGORY_GL_CODE: 'Category GL Code',
        CATEGORY_SETTINGS: 'Category Settings',
        CATEGORIES_SETTINGS: 'Categories Settings',
        MORE_FEATURES: 'More Features',
        MEMBER_DETAILS: 'Member Details',
        OWNER_CHANGE_CHECK: 'Owner Change Check',
        OWNER_CHANGE_SUCCESS: 'Owner Change Success',
        OWNER_CHANGE_ERROR: 'Owner Change Error',
        DISTANCE_RATES: 'Distance Rates',
        CREATE_DISTANCE_RATE: 'Create Distance Rate',
        DISTANCE_RATES_SETTINGS: 'Distance Rates Settings',
        DISTANCE_RATE_DETAILS: 'Distance Rate Details',
        DISTANCE_RATE_EDIT: 'Edit Distance Rate',
        DISTANCE_RATE_TAX_RECLAIMABLE_ON_EDIT: 'Edit Distance Rate Tax Reclaimable',
        DISTANCE_RATE_TAX_RATE_EDIT: 'Edit Distance Rate Tax Rate',
        UPGRADE: 'Workspace Upgrade',
    },

    EDIT_REQUEST: {
        CURRENCY: 'Edit Request Currency',
        REPORT_FIELD: 'Edit Request Report Field',
    },

    NEW_CHAT: {
        ROOT: 'New Chat',
        NEW_CHAT: 'Chat',
        NEW_CHAT_CONFIRM: 'Confirm New Chat',
        NEW_CHAT_EDIT_NAME: 'Edit New Chat Name',
        NEW_ROOM: 'Room',
    },

    SPLIT_DETAILS: {
        ROOT: 'Split Details',
        EDIT_REQUEST: 'Edit Split Details Request',
        EDIT_CURRENCY: 'Edit Split Details Currency',
    },

    ONBOARDING: {
        PERSONAL_DETAILS: 'Personal Details',
        PURPOSE: 'Purpose',
        WORK: 'Work',
    },

    WELCOME_VIDEO: {
        ROOT: 'Welcome Video',
    },

    EXPLANATION_MODAL: {
        ROOT: 'Explanation Modal',
    },

    I_KNOW_A_TEACHER: 'I Know a Teacher',
    INTRO_SCHOOL_PRINCIPAL: 'Introduction to School Principal',
    I_AM_A_TEACHER: 'I Am a Teacher',
    ENABLE_PAYMENTS_ROOT: 'Enable Payments',
    ADD_PERSONAL_BANK_ACCOUNT_ROOT: 'Add Personal Bank Account',
    REIMBURSEMENT_ACCOUNT_ROOT: 'Reimbursement Account',
    WALLET_STATEMENT_ROOT: 'Wallet Statement',
    SIGN_IN_ROOT: 'Sign In',
    DETAILS_ROOT: 'Details',
    PROFILE_ROOT: 'Profile',
    PROCESS_MONEY_REQUEST_HOLD_ROOT: 'Process Money Request Hold',
    REPORT_DESCRIPTION_ROOT: 'Report Description',
    REPORT_PARTICIPANTS: {
        ROOT: 'Report Participants',
        INVITE: 'Invite Participants',
        DETAILS: 'Participant Details',
        ROLE: 'Participant Role',
    },
    ROOM_MEMBERS_ROOT: 'Room Members',
    ROOM_INVITE_ROOT: 'Room Invite',
    FLAG_COMMENT_ROOT: 'Flag Comment',
    REIMBURSEMENT_ACCOUNT: 'Reimbursement Account',
    GET_ASSISTANCE: 'Get Assistance',
    REFERRAL_DETAILS: 'Referral Details',
    KEYBOARD_SHORTCUTS: 'Keyboard Shortcuts',
    TRANSACTION_RECEIPT: 'Transaction Receipt',
    FEATURE_TRAINING_ROOT: 'Feature Training',
    RESTRICTED_ACTION_ROOT: 'Restricted Action',
} as const;

type Screen = DeepValueOf<typeof SCREENS>;

export default SCREENS;
export {PROTECTED_SCREENS};
export type {Screen};
