import CONST from './CONST';
import SCREENS from './SCREENS';

export default {
    [CONST.SUB_NAVIGATION_MENU.HOME]: [SCREENS.HOME_OLDDOT],
    [CONST.SUB_NAVIGATION_MENU.CHATS]: [SCREENS.REPORT],
    [CONST.SUB_NAVIGATION_MENU.MONEY]: [SCREENS.EXPENSES_OLDDOT, SCREENS.REPORTS_OLDDOT, SCREENS.INSIGHTS_OLDDOT],
    [CONST.SUB_NAVIGATION_MENU.WORKSPACES]: [SCREENS.INDIVIDUAL_WORKSPACE_OLDDOT, SCREENS.GROUPS_WORKSPACES_OLDDOT, SCREENS.DOMAINS_OLDDOT],
    // Breadcrumbs menus
    [CONST.SUB_NAVIGATION_MENU.DOMAINS]: [SCREENS.DOMAIN_OLDDOT_TEST],
} as const;
