// Auto-generated SVG assets file
// Generated by: npx ts-node scripts/listFiles.ts --type svg --prepareSvgArray

/* eslint-disable rulesdir/no-inline-named-export */
// Total SVG files: 610
import AddReaction419 from '@assets/images/add-reaction.svg';
import All488 from '@assets/images/all.svg';
import Android350 from '@assets/images/android.svg';
import Apple369 from '@assets/images/apple.svg';
import ArrowCircleClockwise522 from '@assets/images/arrow-circle-clockwise.svg';
import ArrowCollapse561 from '@assets/images/arrow-collapse.svg';
import ArrowDownLong553 from '@assets/images/arrow-down-long.svg';
import ArrowRightLong554 from '@assets/images/arrow-right-long.svg';
import ArrowRight577 from '@assets/images/arrow-right.svg';
import ArrowSplit242 from '@assets/images/arrow-split.svg';
import ArrowUpLong555 from '@assets/images/arrow-up-long.svg';
import ArrowUp580 from '@assets/images/arrow-up.svg';
import ArrowsLeftright573 from '@assets/images/arrows-leftright.svg';
import ArrowsUpdown526 from '@assets/images/arrows-updown.svg';
import AttachmentNotFound428 from '@assets/images/attachment-not-found.svg';
import AdminRoom337 from '@assets/images/avatars/admin-room.svg';
import AnnounceRoom355 from '@assets/images/avatars/announce-room.svg';
import ConciergeAvatar241 from '@assets/images/avatars/concierge-avatar.svg';
import DeletedRoom382 from '@assets/images/avatars/deleted-room.svg';
import DomainRoom318 from '@assets/images/avatars/domain-room.svg';
import FallbackAvatar578 from '@assets/images/avatars/fallback-avatar.svg';
import FallbackWorkspaceAvatar360 from '@assets/images/avatars/fallback-workspace-avatar.svg';
import DefaultAvatar1407 from '@assets/images/avatars/group/default-avatar_1.svg';
import DefaultAvatar2396 from '@assets/images/avatars/group/default-avatar_2.svg';
import DefaultAvatar3398 from '@assets/images/avatars/group/default-avatar_3.svg';
import DefaultAvatar4395 from '@assets/images/avatars/group/default-avatar_4.svg';
import DefaultAvatar5394 from '@assets/images/avatars/group/default-avatar_5.svg';
import DefaultAvatar6391 from '@assets/images/avatars/group/default-avatar_6.svg';
import DefaultAvatar7390 from '@assets/images/avatars/group/default-avatar_7.svg';
import DefaultAvatar8393 from '@assets/images/avatars/group/default-avatar_8.svg';
import DefaultAvatar9392 from '@assets/images/avatars/group/default-avatar_9.svg';
import DefaultAvatar10406 from '@assets/images/avatars/group/default-avatar_10.svg';
import DefaultAvatar11405 from '@assets/images/avatars/group/default-avatar_11.svg';
import DefaultAvatar12403 from '@assets/images/avatars/group/default-avatar_12.svg';
import DefaultAvatar13404 from '@assets/images/avatars/group/default-avatar_13.svg';
import DefaultAvatar14402 from '@assets/images/avatars/group/default-avatar_14.svg';
import DefaultAvatar15401 from '@assets/images/avatars/group/default-avatar_15.svg';
import DefaultAvatar16400 from '@assets/images/avatars/group/default-avatar_16.svg';
import DefaultAvatar17397 from '@assets/images/avatars/group/default-avatar_17.svg';
import DefaultAvatar18399 from '@assets/images/avatars/group/default-avatar_18.svg';
import NotificationsAvatar284 from '@assets/images/avatars/notifications-avatar.svg';
import Room378 from '@assets/images/avatars/room.svg';
import DefaultAvatar181 from '@assets/images/avatars/user/default-avatar_1.svg';
import DefaultAvatar2110 from '@assets/images/avatars/user/default-avatar_2.svg';
import DefaultAvatar356 from '@assets/images/avatars/user/default-avatar_3.svg';
import DefaultAvatar460 from '@assets/images/avatars/user/default-avatar_4.svg';
import DefaultAvatar566 from '@assets/images/avatars/user/default-avatar_5.svg';
import DefaultAvatar672 from '@assets/images/avatars/user/default-avatar_6.svg';
import DefaultAvatar763 from '@assets/images/avatars/user/default-avatar_7.svg';
import DefaultAvatar870 from '@assets/images/avatars/user/default-avatar_8.svg';
import DefaultAvatar9115 from '@assets/images/avatars/user/default-avatar_9.svg';
import DefaultAvatar1069 from '@assets/images/avatars/user/default-avatar_10.svg';
import DefaultAvatar1188 from '@assets/images/avatars/user/default-avatar_11.svg';
import DefaultAvatar1289 from '@assets/images/avatars/user/default-avatar_12.svg';
import DefaultAvatar1364 from '@assets/images/avatars/user/default-avatar_13.svg';
import DefaultAvatar1461 from '@assets/images/avatars/user/default-avatar_14.svg';
import DefaultAvatar1573 from '@assets/images/avatars/user/default-avatar_15.svg';
import DefaultAvatar1654 from '@assets/images/avatars/user/default-avatar_16.svg';
import DefaultAvatar1791 from '@assets/images/avatars/user/default-avatar_17.svg';
import DefaultAvatar1896 from '@assets/images/avatars/user/default-avatar_18.svg';
import DefaultAvatar1977 from '@assets/images/avatars/user/default-avatar_19.svg';
import DefaultAvatar2068 from '@assets/images/avatars/user/default-avatar_20.svg';
import DefaultAvatar2183 from '@assets/images/avatars/user/default-avatar_21.svg';
import DefaultAvatar2262 from '@assets/images/avatars/user/default-avatar_22.svg';
import DefaultAvatar2367 from '@assets/images/avatars/user/default-avatar_23.svg';
import DefaultAvatar2458 from '@assets/images/avatars/user/default-avatar_24.svg';
import DefaultAvatar0566 from '@assets/images/avatars/workspace/default-avatar_0.svg';
import DefaultAvatar1517 from '@assets/images/avatars/workspace/default-avatar_1.svg';
import DefaultAvatar2423 from '@assets/images/avatars/workspace/default-avatar_2.svg';
import DefaultAvatar3429 from '@assets/images/avatars/workspace/default-avatar_3.svg';
import DefaultAvatar4533 from '@assets/images/avatars/workspace/default-avatar_4.svg';
import DefaultAvatar5489 from '@assets/images/avatars/workspace/default-avatar_5.svg';
import DefaultAvatar6484 from '@assets/images/avatars/workspace/default-avatar_6.svg';
import DefaultAvatar7504 from '@assets/images/avatars/workspace/default-avatar_7.svg';
import DefaultAvatar8462 from '@assets/images/avatars/workspace/default-avatar_8.svg';
import DefaultAvatar9475 from '@assets/images/avatars/workspace/default-avatar_9.svg';
import DefaultAvatarA367 from '@assets/images/avatars/workspace/default-avatar_a.svg';
import DefaultAvatarB376 from '@assets/images/avatars/workspace/default-avatar_b.svg';
import DefaultAvatarBuilding387 from '@assets/images/avatars/workspace/default-avatar_building.svg';
import DefaultAvatarC451 from '@assets/images/avatars/workspace/default-avatar_c.svg';
import DefaultAvatarD466 from '@assets/images/avatars/workspace/default-avatar_d.svg';
import DefaultAvatarE361 from '@assets/images/avatars/workspace/default-avatar_e.svg';
import DefaultAvatarF412 from '@assets/images/avatars/workspace/default-avatar_f.svg';
import DefaultAvatarG434 from '@assets/images/avatars/workspace/default-avatar_g.svg';
import DefaultAvatarH352 from '@assets/images/avatars/workspace/default-avatar_h.svg';
import DefaultAvatarI545 from '@assets/images/avatars/workspace/default-avatar_i.svg';
import DefaultAvatarJ523 from '@assets/images/avatars/workspace/default-avatar_j.svg';
import DefaultAvatarK354 from '@assets/images/avatars/workspace/default-avatar_k.svg';
import DefaultAvatarL470 from '@assets/images/avatars/workspace/default-avatar_l.svg';
import DefaultAvatarM351 from '@assets/images/avatars/workspace/default-avatar_m.svg';
import DefaultAvatarN379 from '@assets/images/avatars/workspace/default-avatar_n.svg';
import DefaultAvatarO562 from '@assets/images/avatars/workspace/default-avatar_o.svg';
import DefaultAvatarP441 from '@assets/images/avatars/workspace/default-avatar_p.svg';
import DefaultAvatarQ440 from '@assets/images/avatars/workspace/default-avatar_q.svg';
import DefaultAvatarR362 from '@assets/images/avatars/workspace/default-avatar_r.svg';
import DefaultAvatarS409 from '@assets/images/avatars/workspace/default-avatar_s.svg';
import DefaultAvatarT432 from '@assets/images/avatars/workspace/default-avatar_t.svg';
import DefaultAvatarU480 from '@assets/images/avatars/workspace/default-avatar_u.svg';
import DefaultAvatarV460 from '@assets/images/avatars/workspace/default-avatar_v.svg';
import DefaultAvatarW332 from '@assets/images/avatars/workspace/default-avatar_w.svg';
import DefaultAvatarX327 from '@assets/images/avatars/workspace/default-avatar_x.svg';
import DefaultAvatarY389 from '@assets/images/avatars/workspace/default-avatar_y.svg';
import DefaultAvatarZ418 from '@assets/images/avatars/workspace/default-avatar_z.svg';
import BackLeft582 from '@assets/images/back-left.svg';
import AmericanExpress324 from '@assets/images/bank-icons/american-express.svg';
import BankOfAmerica309 from '@assets/images/bank-icons/bank-of-america.svg';
import BbT249 from '@assets/images/bank-icons/bb-t.svg';
import CapitalOne124 from '@assets/images/bank-icons/capital-one.svg';
import CharlesSchwab136 from '@assets/images/bank-icons/charles-schwab.svg';
import Chase445 from '@assets/images/bank-icons/chase.svg';
import Citibank317 from '@assets/images/bank-icons/citibank.svg';
import CitizensBank210 from '@assets/images/bank-icons/citizens-bank.svg';
import Discover174 from '@assets/images/bank-icons/discover.svg';
import Expensify330 from '@assets/images/bank-icons/expensify.svg';
import Fidelity311 from '@assets/images/bank-icons/fidelity.svg';
import GenericBankAccount381 from '@assets/images/bank-icons/generic-bank-account.svg';
import HuntingtonBank368 from '@assets/images/bank-icons/huntington-bank.svg';
import NavyFederalCreditUnion131 from '@assets/images/bank-icons/navy-federal-credit-union.svg';
import Pnc365 from '@assets/images/bank-icons/pnc.svg';
import RegionsBank208 from '@assets/images/bank-icons/regions-bank.svg';
import Suntrust48 from '@assets/images/bank-icons/suntrust.svg';
import TdBank506 from '@assets/images/bank-icons/td-bank.svg';
import UsBank261 from '@assets/images/bank-icons/us-bank.svg';
import Usaa222 from '@assets/images/bank-icons/usaa.svg';
import Bank447 from '@assets/images/bank.svg';
import Bed442 from '@assets/images/bed.svg';
import Bell570 from '@assets/images/bell.svg';
import Bellslash487 from '@assets/images/bellSlash.svg';
import Bill499 from '@assets/images/bill.svg';
import Binoculars347 from '@assets/images/binoculars.svg';
import BoltSlash490 from '@assets/images/bolt-slash.svg';
import Bolt581 from '@assets/images/bolt.svg';
import Bookmark606 from '@assets/images/bookmark.svg';
import Box560 from '@assets/images/box.svg';
import Briefcase531 from '@assets/images/briefcase.svg';
import Bug341 from '@assets/images/bug.svg';
import Building426 from '@assets/images/building.svg';
import Buildings349 from '@assets/images/buildings.svg';
import CalendarSolid559 from '@assets/images/calendar-solid.svg';
import Calendar458 from '@assets/images/calendar.svg';
import Camera514 from '@assets/images/camera.svg';
import CarWithKey279 from '@assets/images/car-with-key.svg';
import Car320 from '@assets/images/car.svg';
import AmericanExpress293 from '@assets/images/cardicons/american-express.svg';
import BankOfAmerica290 from '@assets/images/cardicons/bank-of-america.svg';
import BbT211 from '@assets/images/cardicons/bb-t.svg';
import CapitalOne126 from '@assets/images/cardicons/capital-one.svg';
import CharlesSchwab114 from '@assets/images/cardicons/charles-schwab.svg';
import Chase450 from '@assets/images/cardicons/chase.svg';
import Citibank296 from '@assets/images/cardicons/citibank.svg';
import Citizens169 from '@assets/images/cardicons/citizens.svg';
import Discover159 from '@assets/images/cardicons/discover.svg';
import ExpensifyCardDark113 from '@assets/images/cardicons/expensify-card-dark.svg';
import Fidelity287 from '@assets/images/cardicons/fidelity.svg';
import GenericBankCard608 from '@assets/images/cardicons/generic-bank-card.svg';
import HuntingtonBank333 from '@assets/images/cardicons/huntington-bank.svg';
import NavyFederalCreditUnion103 from '@assets/images/cardicons/navy-federal-credit-union.svg';
import Pnc322 from '@assets/images/cardicons/pnc.svg';
import RegionsBank173 from '@assets/images/cardicons/regions-bank.svg';
import Suntrust46 from '@assets/images/cardicons/suntrust.svg';
import TdBank473 from '@assets/images/cardicons/td-bank.svg';
import UsBank218 from '@assets/images/cardicons/us-bank.svg';
import Usaa193 from '@assets/images/cardicons/usaa.svg';
import CaretUpDown516 from '@assets/images/caret-up-down.svg';
import Cash587 from '@assets/images/cash.svg';
import Chair503 from '@assets/images/chair.svg';
import ChatbubbleAdd456 from '@assets/images/chatbubble-add.svg';
import ChatbubbleCounter563 from '@assets/images/chatbubble-counter.svg';
import ChatbubbleReply448 from '@assets/images/chatbubble-reply.svg';
import ChatbubbleSlash463 from '@assets/images/chatbubble-slash.svg';
import ChatbubbleUnread482 from '@assets/images/chatbubble-unread.svg';
import Chatbubble598 from '@assets/images/chatbubble.svg';
import Chatbubbles444 from '@assets/images/chatbubbles.svg';
import CheckCircle528 from '@assets/images/check-circle.svg';
import CheckSquare527 from '@assets/images/check-square.svg';
import Checkbox510 from '@assets/images/checkbox.svg';
import CheckmarkCircle572 from '@assets/images/checkmark-circle.svg';
import Checkmark568 from '@assets/images/checkmark.svg';
import CircularArrowBackwards507 from '@assets/images/circular-arrow-backwards.svg';
import Close589 from '@assets/images/close.svg';
import ClosedSign455 from '@assets/images/closed-sign.svg';
import Coins314 from '@assets/images/coins.svg';
import Collapse535 from '@assets/images/collapse.svg';
import CommentBubbles343 from '@assets/images/comment-bubbles.svg';
import Amex205 from '@assets/images/companyCards/amex.svg';
import CardAmex231 from '@assets/images/companyCards/card-amex.svg';
import CardBofa221 from '@assets/images/companyCards/card-bofa.svg';
import CardBrex258 from '@assets/images/companyCards/card-brex.svg';
import CardCapitalOne248 from '@assets/images/companyCards/card-capital_one.svg';
import CardCapitalone244 from '@assets/images/companyCards/card-capitalone.svg';
import CardChase269 from '@assets/images/companyCards/card-chase.svg';
import CardCiti213 from '@assets/images/companyCards/card-citi.svg';
import CardExpensify94 from '@assets/images/companyCards/card-expensify.svg';
import CardMastercard260 from '@assets/images/companyCards/card-mastercard.svg';
import CardPlaid289 from '@assets/images/companyCards/card-plaid.svg';
import CardStripe185 from '@assets/images/companyCards/card-stripe.svg';
import CardVisa119 from '@assets/images/companyCards/card-visa.svg';
import CardWellsFargo150 from '@assets/images/companyCards/card-wells_fargo.svg';
import CardWellsfargo120 from '@assets/images/companyCards/card-wellsfargo.svg';
import EmptystateCardPos23 from '@assets/images/companyCards/emptystate__card-pos.svg';
import GenericCsvDark282 from '@assets/images/companyCards/generic-csv-dark.svg';
import GenericCsvLight281 from '@assets/images/companyCards/generic-csv-light.svg';
import GenericDark253 from '@assets/images/companyCards/generic-dark.svg';
import GenericLight254 from '@assets/images/companyCards/generic-light.svg';
import CardAmexLarge206 from '@assets/images/companyCards/large/card-amex-large.svg';
import CardBofaLarge200 from '@assets/images/companyCards/large/card-bofa-large.svg';
import CardBrexLarge245 from '@assets/images/companyCards/large/card-brex-large.svg';
import CardCapitalOneLarge217 from '@assets/images/companyCards/large/card-capital_one-large.svg';
import CardChaseLarge250 from '@assets/images/companyCards/large/card-chase-large.svg';
import CardCitiLarge203 from '@assets/images/companyCards/large/card-citi-large.svg';
import CardExpensifyLarge82 from '@assets/images/companyCards/large/card-expensify-large.svg';
import CardMastercardLarge228 from '@assets/images/companyCards/large/card-mastercard-large.svg';
import CardPlaidLarge263 from '@assets/images/companyCards/large/card-plaid-large.svg';
import CardStripeLarge170 from '@assets/images/companyCards/large/card-stripe-large.svg';
import CardVisaLarge108 from '@assets/images/companyCards/large/card-visa-large.svg';
import CardWellsfargoLarge105 from '@assets/images/companyCards/large/card-wellsfargo-large.svg';
import GenericCsvDarkLarge252 from '@assets/images/companyCards/large/generic-csv-dark-large.svg';
import GenericCsvLightLarge251 from '@assets/images/companyCards/large/generic-csv-light-large.svg';
import GenericDarkLarge220 from '@assets/images/companyCards/large/generic-dark-large.svg';
import GenericLightLarge219 from '@assets/images/companyCards/large/generic-light-large.svg';
import Mastercard225 from '@assets/images/companyCards/mastercard.svg';
import PendingBank31 from '@assets/images/companyCards/pending-bank.svg';
import PendingstateLaptopWithHourglassAndCards37 from '@assets/images/companyCards/pendingstate_laptop-with-hourglass-and-cards.svg';
import Visa118 from '@assets/images/companyCards/visa.svg';
import Computer41 from '@assets/images/computer.svg';
import Concierge422 from '@assets/images/concierge.svg';
import Connect431 from '@assets/images/connect.svg';
import ConnectionComplete42 from '@assets/images/connection-complete.svg';
import Copy585 from '@assets/images/copy.svg';
import CreditCardExclamation425 from '@assets/images/credit-card-exclamation.svg';
import CreditCardHourglass297 from '@assets/images/credit-card-hourglass.svg';
import Creditcard590 from '@assets/images/creditcard.svg';
import Crosshair308 from '@assets/images/crosshair.svg';
import DocumentMerge316 from '@assets/images/document-merge.svg';
import DocumentPlus492 from '@assets/images/document-plus.svg';
import DocumentSlash547 from '@assets/images/document-slash.svg';
import Document591 from '@assets/images/document.svg';
import DotIndicatorUnfilled550 from '@assets/images/dot-indicator-unfilled.svg';
import DotIndicator6 from '@assets/images/dot-indicator.svg';
import Down579 from '@assets/images/down.svg';
import Download532 from '@assets/images/download.svg';
import DragAndDrop313 from '@assets/images/drag-and-drop.svg';
import DragHandles601 from '@assets/images/drag-handles.svg';
import EducationalIllustrationMultiScan36 from '@assets/images/educational-illustration__multi-scan.svg';
import Emoji502 from '@assets/images/emoji.svg';
import AddEmoji291 from '@assets/images/emojiCategoryIcons/add-emoji.svg';
import Calendar459 from '@assets/images/emojiCategoryIcons/calendar.svg';
import Car321 from '@assets/images/emojiCategoryIcons/car.svg';
import Flag586 from '@assets/images/emojiCategoryIcons/flag.svg';
import Hamburger548 from '@assets/images/emojiCategoryIcons/hamburger.svg';
import Heart596 from '@assets/images/emojiCategoryIcons/heart.svg';
import LightBulb436 from '@assets/images/emojiCategoryIcons/light-bulb.svg';
import PeaceSign498 from '@assets/images/emojiCategoryIcons/peace-sign.svg';
import Plane542 from '@assets/images/emojiCategoryIcons/plane.svg';
import Plant546 from '@assets/images/emojiCategoryIcons/plant.svg';
import SoccerBall520 from '@assets/images/emojiCategoryIcons/soccer-ball.svg';
import EmptySquare594 from '@assets/images/empty-square.svg';
import EmptyStateAttachReceipt195 from '@assets/images/empty-state__attach-receipt.svg';
import EmptystateExpensifycard12 from '@assets/images/emptystate__expensifycard.svg';
import EmptystateRoutepending346 from '@assets/images/emptystate__routepending.svg';
import EmptystateSpyPigeon71 from '@assets/images/emptystate__spy-pigeon.svg';
import EreceiptBgimage24 from '@assets/images/eReceipt-BGImage.svg';
import EreceiptBackground9 from '@assets/images/eReceipt_background.svg';
import EreceiptbgBlue28 from '@assets/images/eReceiptBGs/eReceiptBG_blue.svg';
import EreceiptbgGreen26 from '@assets/images/eReceiptBGs/eReceiptBG_green.svg';
import EreceiptbgIce21 from '@assets/images/eReceiptBGs/eReceiptBG_ice.svg';
import EreceiptbgPink15 from '@assets/images/eReceiptBGs/eReceiptBG_pink.svg';
import EreceiptbgTangerine14 from '@assets/images/eReceiptBGs/eReceiptBG_tangerine.svg';
import EreceiptbgYellow18 from '@assets/images/eReceiptBGs/eReceiptBG_yellow.svg';
import Ereceipticon306 from '@assets/images/eReceiptIcon.svg';
import Exclamation576 from '@assets/images/exclamation.svg';
import Exit364 from '@assets/images/exit.svg';
import Expand539 from '@assets/images/expand.svg';
import ExpensifyAppIcon304 from '@assets/images/expensify-app-icon.svg';
import ExpensifyCardIcon557 from '@assets/images/expensify-card-icon.svg';
import ExpensifyCard123 from '@assets/images/expensify-card.svg';
import ExpensifyFooterLogoVertical229 from '@assets/images/expensify-footer-logo-vertical.svg';
import ExpensifyFooterLogo233 from '@assets/images/expensify-footer-logo.svg';
import ExpensifyLogoAdhoc181 from '@assets/images/expensify-logo--adhoc.svg';
import ExpensifyLogoDev194 from '@assets/images/expensify-logo--dev.svg';
import ExpensifyLogoProd257 from '@assets/images/expensify-logo--prod.svg';
import ExpensifyLogoStaging184 from '@assets/images/expensify-logo--staging.svg';
import ExpensifyLogoNew273 from '@assets/images/expensify-logo-new.svg';
import ExpensifyWordmark264 from '@assets/images/expensify-wordmark.svg';
import ExpensifyWordmarkWhite246 from '@assets/images/expensify_wordmark_white.svg';
import Cardillustration30 from '@assets/images/expensifyCard/cardIllustration.svg';
import Export544 from '@assets/images/export.svg';
import EyeDisabled415 from '@assets/images/eye-disabled.svg';
import Eye433 from '@assets/images/eye.svg';
import Feed538 from '@assets/images/feed.svg';
import Filter485 from '@assets/images/filter.svg';
import Filters493 from '@assets/images/filters.svg';
import Flag584 from '@assets/images/flag.svg';
import FlagLevel01454 from '@assets/images/flag_level_01.svg';
import FlagLevel02453 from '@assets/images/flag_level_02.svg';
import FlagLevel03452 from '@assets/images/flag_level_03.svg';
import Folder607 from '@assets/images/folder.svg';
import Fullscreen380 from '@assets/images/fullscreen.svg';
import GalleryNotFound427 from '@assets/images/gallery-not-found.svg';
import Gallery468 from '@assets/images/gallery.svg';
import Gear307 from '@assets/images/gear.svg';
import Globe348 from '@assets/images/globe.svg';
import Hand52 from '@assets/images/hand.svg';
import Hashtag303 from '@assets/images/hashtag.svg';
import Heart595 from '@assets/images/heart.svg';
import History469 from '@assets/images/history.svg';
import HomeBackgroundAndroid4 from '@assets/images/home-background--android.svg';
import HomeBackgroundDesktop2 from '@assets/images/home-background--desktop.svg';
import HomeBackgroundIos1 from '@assets/images/home-background--ios.svg';
import HomeBackgroundMobile3 from '@assets/images/home-background--mobile.svg';
import HomeFadeGradientMobile471 from '@assets/images/home-fade-gradient--mobile.svg';
import HomeFadeGradient472 from '@assets/images/home-fade-gradient.svg';
import Home571 from '@assets/images/home.svg';
import Hourglass439 from '@assets/images/hourglass.svg';
import ImageCropCircleMask325 from '@assets/images/image-crop-circle-mask.svg';
import ImageCropSquareMask302 from '@assets/images/image-crop-square-mask.svg';
import Inbox515 from '@assets/images/inbox.svg';
import Info519 from '@assets/images/info.svg';
import CircleSlash575 from '@assets/images/integrationicons/circle-slash.svg';
import MicrosoftDynamicsIcon305 from '@assets/images/integrationicons/export/microsoft-dynamics-icon.svg';
import NetsuiteIcon182 from '@assets/images/integrationicons/export/netsuite-icon.svg';
import NetsuiteOracleIcon148 from '@assets/images/integrationicons/export/netsuite-oracle-icon.svg';
import OracleIcon259 from '@assets/images/integrationicons/export/oracle-icon.svg';
import QboIcon339 from '@assets/images/integrationicons/export/qbo-icon.svg';
import SageIntacctIcon207 from '@assets/images/integrationicons/export/sage-intacct-icon.svg';
import SapIcon280 from '@assets/images/integrationicons/export/sap-icon.svg';
import XeroIcon232 from '@assets/images/integrationicons/export/xero-icon.svg';
import MicrosoftDynamicsIconSquare270 from '@assets/images/integrationicons/microsoft-dynamics-icon-square.svg';
import NetsuiteIconSquare137 from '@assets/images/integrationicons/netsuite-icon-square.svg';
import OracleIconSquare235 from '@assets/images/integrationicons/oracle-icon-square.svg';
import QbdIconSquare373 from '@assets/images/integrationicons/qbd-icon-square.svg';
import QboIconCircle366 from '@assets/images/integrationicons/qbo-icon-circle.svg';
import QboIconSquare372 from '@assets/images/integrationicons/qbo-icon-square.svg';
import SageIntacctIconSquare204 from '@assets/images/integrationicons/sage-intacct-icon-square.svg';
import SapIconSquare295 from '@assets/images/integrationicons/sap-icon-square.svg';
import Uber90 from '@assets/images/integrationicons/uber.svg';
import XeroIconCircle236 from '@assets/images/integrationicons/xero-icon-circle.svg';
import XeroIconSquare237 from '@assets/images/integrationicons/xero-icon-square.svg';
import InvoiceGeneric357 from '@assets/images/invoice-generic.svg';
import Invoice495 from '@assets/images/invoice.svg';
import Key497 from '@assets/images/key.svg';
import Keyboard271 from '@assets/images/keyboard.svg';
import LaptopWithSecondScreenAndHourglass34 from '@assets/images/laptop-with-second-screen-and-hourglass.svg';
import LaptopWithSecondScreenSync38 from '@assets/images/laptop-with-second-screen-sync.svg';
import LaptopWithSecondScreenX40 from '@assets/images/laptop-with-second-screen-x.svg';
import LinkCopy344 from '@assets/images/link-copy.svg';
import Link465 from '@assets/images/link.svg';
import Location574 from '@assets/images/location.svg';
import Lock549 from '@assets/images/lock.svg';
import Luggage388 from '@assets/images/luggage.svg';
import MagnifyingGlassSpyMouthClosed43 from '@assets/images/magnifying-glass-spy-mouth-closed.svg';
import MagnifyingGlass521 from '@assets/images/magnifying-glass.svg';
import Mail564 from '@assets/images/mail.svg';
import MakeAdmin413 from '@assets/images/make-admin.svg';
import Map592 from '@assets/images/map.svg';
import MccAirlines479 from '@assets/images/MCCGroupIcons/MCC-Airlines.svg';
import MccCommuter336 from '@assets/images/MCCGroupIcons/MCC-Commuter.svg';
import MccGas386 from '@assets/images/MCCGroupIcons/MCC-Gas.svg';
import MccGoods543 from '@assets/images/MCCGroupIcons/MCC-Goods.svg';
import MccGroceries340 from '@assets/images/MCCGroupIcons/MCC-Groceries.svg';
import MccHotel443 from '@assets/images/MCCGroupIcons/MCC-Hotel.svg';
import MccMail481 from '@assets/images/MCCGroupIcons/MCC-Mail.svg';
import MccMeals329 from '@assets/images/MCCGroupIcons/MCC-Meals.svg';
import MccMisc363 from '@assets/images/MCCGroupIcons/MCC-Misc.svg';
import MccRentalcar268 from '@assets/images/MCCGroupIcons/MCC-RentalCar.svg';
import MccServices421 from '@assets/images/MCCGroupIcons/MCC-Services.svg';
import MccTaxi292 from '@assets/images/MCCGroupIcons/MCC-Taxi.svg';
import MccUtilities335 from '@assets/images/MCCGroupIcons/MCC-Utilities.svg';
import Megaphone457 from '@assets/images/megaphone.svg';
import Menu599 from '@assets/images/menu.svg';
import Meter541 from '@assets/images/meter.svg';
import Minus605 from '@assets/images/minus.svg';
import MoneyBag467 from '@assets/images/money-bag.svg';
import MoneyCircle408 from '@assets/images/money-circle.svg';
import MoneyHourglass331 from '@assets/images/money-hourglass.svg';
import MoneySearch417 from '@assets/images/money-search.svg';
import MoneyStack45 from '@assets/images/money-stack.svg';
import MoneyWaving55 from '@assets/images/money-waving.svg';
import Monitor449 from '@assets/images/monitor.svg';
import MultiTag410 from '@assets/images/multi-tag.svg';
import Mute461 from '@assets/images/mute.svg';
import NewExpensifyAdhoc239 from '@assets/images/new-expensify-adhoc.svg';
import NewExpensifyDark285 from '@assets/images/new-expensify-dark.svg';
import NewExpensifyDev274 from '@assets/images/new-expensify-dev.svg';
import NewExpensifyStg243 from '@assets/images/new-expensify-stg.svg';
import NewExpensify275 from '@assets/images/new-expensify.svg';
import NewWindow483 from '@assets/images/new-window.svg';
import NewWorkspace294 from '@assets/images/new-workspace.svg';
import OfflineCloud552 from '@assets/images/offline-cloud.svg';
import Offline530 from '@assets/images/offline.svg';
import Paperclip491 from '@assets/images/paperclip.svg';
import Pause569 from '@assets/images/pause.svg';
import Paycheck342 from '@assets/images/paycheck.svg';
import Paypal513 from '@assets/images/paypal.svg';
import Pencil588 from '@assets/images/pencil.svg';
import Phone565 from '@assets/images/phone.svg';
import Pin496 from '@assets/images/pin.svg';
import Plane518 from '@assets/images/plane.svg';
import Play5 from '@assets/images/play.svg';
import Plus602 from '@assets/images/plus.svg';
import Printer438 from '@assets/images/printer.svg';
import Abracadabra25 from '@assets/images/product-illustrations/abracadabra.svg';
import BankArrowPink172 from '@assets/images/product-illustrations/bank-arrow--pink.svg';
import BankMouseGreen158 from '@assets/images/product-illustrations/bank-mouse--green.svg';
import BankUserGreen156 from '@assets/images/product-illustrations/bank-user--green.svg';
import BrokenMagnifyingGlass112 from '@assets/images/product-illustrations/broken-magnifying-glass.svg';
import ConciergeBlue319 from '@assets/images/product-illustrations/concierge--blue.svg';
import ConciergeExclamation283 from '@assets/images/product-illustrations/concierge--exclamation.svg';
import CreditCardsBlue226 from '@assets/images/product-illustrations/credit-cards--blue.svg';
import EmptystateExpenses93 from '@assets/images/product-illustrations/emptystate__expenses.svg';
import EmptystateHoldexpense20 from '@assets/images/product-illustrations/emptystate__holdexpense.svg';
import EmptystateReceiptfairy32 from '@assets/images/product-illustrations/emptystate__receiptfairy.svg';
import EmptystateTravel27 from '@assets/images/product-illustrations/emptystate__travel.svg';
import FolderWithPapers135 from '@assets/images/product-illustrations/folder-with-papers.svg';
import GpsTrackOrange256 from '@assets/images/product-illustrations/gps-track--orange.svg';
import HomeIllustrationHands29 from '@assets/images/product-illustrations/home-illustration-hands.svg';
import IllustrationCardReplacementSuccess11 from '@assets/images/product-illustrations/illustration__card-replacement-success.svg';
import InvoiceOrange277 from '@assets/images/product-illustrations/invoice--orange.svg';
import JewelBoxBlue180 from '@assets/images/product-illustrations/jewel-box--blue.svg';
import JewelBoxGreen179 from '@assets/images/product-illustrations/jewel-box--green.svg';
import JewelBoxPink178 from '@assets/images/product-illustrations/jewel-box--pink.svg';
import JewelBoxYellow177 from '@assets/images/product-illustrations/jewel-box--yellow.svg';
import MagicCode22 from '@assets/images/product-illustrations/magic-code.svg';
import ModalHoldOrReject13 from '@assets/images/product-illustrations/modal-hold-or-reject.svg';
import MoneyEnvelopeBlue227 from '@assets/images/product-illustrations/money-envelope--blue.svg';
import MoneyMousePink234 from '@assets/images/product-illustrations/money-mouse--pink.svg';
import MushroomTopHat59 from '@assets/images/product-illustrations/mushroom-top-hat.svg';
import PaymentHands35 from '@assets/images/product-illustrations/payment-hands.svg';
import ReceiptYellow312 from '@assets/images/product-illustrations/receipt--yellow.svg';
import ReceiptsSearchYellow155 from '@assets/images/product-illustrations/receipts-search--yellow.svg';
import ReceiptsStackedOnPin65 from '@assets/images/product-illustrations/receipts-stacked-on-pin.svg';
import RocketBlue49 from '@assets/images/product-illustrations/rocket--blue.svg';
import RocketOrange98 from '@assets/images/product-illustrations/rocket--orange.svg';
import RocketDude33 from '@assets/images/product-illustrations/rocket-dude.svg';
import Safe87 from '@assets/images/product-illustrations/safe.svg';
import SimpleIllustrationSmartscan167 from '@assets/images/product-illustrations/simple-illustration__smartscan.svg';
import TadaBlue140 from '@assets/images/product-illustrations/tada--blue.svg';
import TadaYellow139 from '@assets/images/product-illustrations/tada--yellow.svg';
import Telescope128 from '@assets/images/product-illustrations/telescope.svg';
import ThreeLeggedLaptopWoman50 from '@assets/images/product-illustrations/three_legged_laptop_woman.svg';
import ToddBehindCloud132 from '@assets/images/product-illustrations/todd-behind-cloud.svg';
import ToddInCar19 from '@assets/images/product-illustrations/todd-in-car.svg';
import ToddWithPhones17 from '@assets/images/product-illustrations/todd-with-phones.svg';
import Profile583 from '@assets/images/profile.svg';
import Qrcode508 from '@assets/images/qrcode.svg';
import QuestionMarkCircle474 from '@assets/images/question-mark-circle.svg';
import ReceiptBody198 from '@assets/images/receipt-body.svg';
import ReceiptMultiple272 from '@assets/images/receipt-multiple.svg';
import ReceiptPlaceholderPlus529 from '@assets/images/receipt-placeholder-plus.svg';
import ReceiptPlus359 from '@assets/images/receipt-plus.svg';
import ReceiptScan328 from '@assets/images/receipt-scan.svg';
import ReceiptSearch334 from '@assets/images/receipt-search.svg';
import ReceiptSlash323 from '@assets/images/receipt-slash.svg';
import ReceiptUpload86 from '@assets/images/receipt-upload.svg';
import Receipt338 from '@assets/images/receipt.svg';
import RemoveMembers556 from '@assets/images/remove-members.svg';
import RotateImage414 from '@assets/images/rotate-image.svg';
import RotateLeft525 from '@assets/images/rotate-left.svg';
import Rotate476 from '@assets/images/rotate.svg';
import RunningTurtle47 from '@assets/images/running-turtle.svg';
import Scan551 from '@assets/images/scan.svg';
import Send597 from '@assets/images/send.svg';
import Shield384 from '@assets/images/shield.svg';
import Shutter536 from '@assets/images/shutter.svg';
import AppleLogo326 from '@assets/images/signIn/apple-logo.svg';
import GoogleLogo298 from '@assets/images/signIn/google-logo.svg';
import AdvancedApprovalsIconSquare84 from '@assets/images/simple-illustrations/advanced-approvals-icon-square.svg';
import EmptystateBigVault39 from '@assets/images/simple-illustrations/emptystate__big-vault.svg';
import EmptystatePuzzlepieces76 from '@assets/images/simple-illustrations/emptystate__puzzlepieces.svg';
import SimpleIllustrationAbacus201 from '@assets/images/simple-illustrations/simple-illustration__abacus.svg';
import SimpleIllustrationAccounting106 from '@assets/images/simple-illustrations/simple-illustration__accounting.svg';
import SimpleIllustrationAlert215 from '@assets/images/simple-illustrations/simple-illustration__alert.svg';
import SimpleIllustrationApproval161 from '@assets/images/simple-illustrations/simple-illustration__approval.svg';
import SimpleIllustrationBankArrow107 from '@assets/images/simple-illustrations/simple-illustration__bank-arrow.svg';
import SimpleIllustrationBigrocket53 from '@assets/images/simple-illustrations/simple-illustration__bigrocket.svg';
import SimpleIllustrationBill130 from '@assets/images/simple-illustrations/simple-illustration__bill.svg';
import SimpleIllustrationBinoculars168 from '@assets/images/simple-illustrations/simple-illustration__binoculars.svg';
import SimpleIllustrationBuilding301 from '@assets/images/simple-illustrations/simple-illustration__building.svg';
import SimpleIllustrationBuildings262 from '@assets/images/simple-illustrations/simple-illustration__buildings.svg';
import SimpleIllustrationCarIce144 from '@assets/images/simple-illustrations/simple-illustration__car-ice.svg';
import SimpleIllustrationCar145 from '@assets/images/simple-illustrations/simple-illustration__car.svg';
import SimpleIllustrationCarPink143 from '@assets/images/simple-illustrations/simple-illustration__car_pink.svg';
import SimpleIllustrationChatbubbles276 from '@assets/images/simple-illustrations/simple-illustration__chatbubbles.svg';
import SimpleIllustrationCheckmarkcircle265 from '@assets/images/simple-illustrations/simple-illustration__checkmarkcircle.svg';
import SimpleIllustrationCoffeemug188 from '@assets/images/simple-illustrations/simple-illustration__coffeemug.svg';
import SimpleIllustrationCoins134 from '@assets/images/simple-illustrations/simple-illustration__coins.svg';
import SimpleIllustrationCommentbubbles266 from '@assets/images/simple-illustrations/simple-illustration__commentbubbles.svg';
import SimpleIllustrationCommentbubblesBlue267 from '@assets/images/simple-illustrations/simple-illustration__commentbubbles_blue.svg';
import SimpleIllustrationCompanyCard214 from '@assets/images/simple-illustrations/simple-illustration__company-card.svg';
import SimpleIllustrationConciergeBubble151 from '@assets/images/simple-illustrations/simple-illustration__concierge-bubble.svg';
import SimpleIllustrationConcierge154 from '@assets/images/simple-illustrations/simple-illustration__concierge.svg';
import SimpleIllustrationCreditCards160 from '@assets/images/simple-illustrations/simple-illustration__credit-cards.svg';
import SimpleIllustrationCreditcardeyes164 from '@assets/images/simple-illustrations/simple-illustration__creditcardeyes.svg';
import SimpleIllustrationCreditcardsGreen152 from '@assets/images/simple-illustrations/simple-illustration__creditcards--green.svg';
import SimpleIllustrationEmailAddress209 from '@assets/images/simple-illustrations/simple-illustration__email-address.svg';
import SimpleIllustrationEmptyShelves16 from '@assets/images/simple-illustrations/simple-illustration__empty-shelves.svg';
import SimpleIllustrationEmptyState95 from '@assets/images/simple-illustrations/simple-illustration__empty-state.svg';
import SimpleIllustrationEncryption99 from '@assets/images/simple-illustrations/simple-illustration__encryption.svg';
import SimpleIllustrationEnvelopereceipt117 from '@assets/images/simple-illustrations/simple-illustration__envelopereceipt.svg';
import SimpleIllustrationFilters121 from '@assets/images/simple-illustrations/simple-illustration__filters.svg';
import SimpleIllustrationFlash190 from '@assets/images/simple-illustrations/simple-illustration__flash.svg';
import SimpleIllustrationFolderOpen286 from '@assets/images/simple-illustrations/simple-illustration__folder-open.svg';
import SimpleIllustrationGears57 from '@assets/images/simple-illustrations/simple-illustration__gears.svg';
import SimpleIllustrationHandcard196 from '@assets/images/simple-illustrations/simple-illustration__handcard.svg';
import SimpleIllustrationHandearth212 from '@assets/images/simple-illustrations/simple-illustration__handearth.svg';
import SimpleIllustrationHeadset141 from '@assets/images/simple-illustrations/simple-illustration__headset.svg';
import SimpleIllustrationHotdogstand85 from '@assets/images/simple-illustrations/simple-illustration__hotdogstand.svg';
import SimpleIllustrationHourglass149 from '@assets/images/simple-illustrations/simple-illustration__hourglass.svg';
import SimpleIllustrationHouse247 from '@assets/images/simple-illustrations/simple-illustration__house.svg';
import SimpleIllustrationInvoice162 from '@assets/images/simple-illustrations/simple-illustration__invoice.svg';
import SimpleIllustrationLightbulb223 from '@assets/images/simple-illustrations/simple-illustration__lightbulb.svg';
import SimpleIllustrationLockclosed192 from '@assets/images/simple-illustrations/simple-illustration__lockclosed.svg';
import SimpleIllustrationLockclosedOrange186 from '@assets/images/simple-illustrations/simple-illustration__lockclosed_orange.svg';
import SimpleIllustrationLockopen165 from '@assets/images/simple-illustrations/simple-illustration__lockopen.svg';
import SimpleIllustrationLuggage189 from '@assets/images/simple-illustrations/simple-illustration__luggage.svg';
import SimpleIllustrationMagnifyingglassMoney175 from '@assets/images/simple-illustrations/simple-illustration__magnifyingglass-money.svg';
import SimpleIllustrationMailbox183 from '@assets/images/simple-illustrations/simple-illustration__mailbox.svg';
import SimpleIllustrationMessageinabottle104 from '@assets/images/simple-illustrations/simple-illustration__messageinabottle.svg';
import SimpleIllustrationMobileapp142 from '@assets/images/simple-illustrations/simple-illustration__mobileapp.svg';
import SimpleIllustrationMoneyReceipts102 from '@assets/images/simple-illustrations/simple-illustration__money-receipts.svg';
import SimpleIllustrationMoneybadge153 from '@assets/images/simple-illustrations/simple-illustration__moneybadge.svg';
import SimpleIllustrationMoneyintowallet122 from '@assets/images/simple-illustrations/simple-illustration__moneyintowallet.svg';
import SimpleIllustrationMoneywings97 from '@assets/images/simple-illustrations/simple-illustration__moneywings.svg';
import SimpleIllustrationOpensafe80 from '@assets/images/simple-illustrations/simple-illustration__opensafe.svg';
import SimpleIllustrationPalmtree240 from '@assets/images/simple-illustrations/simple-illustration__palmtree.svg';
import SimpleIllustrationPaperairplane133 from '@assets/images/simple-illustrations/simple-illustration__paperairplane.svg';
import SimpleIllustrationPencil146 from '@assets/images/simple-illustrations/simple-illustration__pencil.svg';
import SimpleIllustrationPerdiem100 from '@assets/images/simple-illustrations/simple-illustration__perdiem.svg';
import SimpleIllustrationPiggybank92 from '@assets/images/simple-illustrations/simple-illustration__piggybank.svg';
import SimpleIllustrationPillow127 from '@assets/images/simple-illustrations/simple-illustration__pillow.svg';
import SimpleIllustrationProfile416 from '@assets/images/simple-illustrations/simple-illustration__profile.svg';
import SimpleIllustrationQrCode411 from '@assets/images/simple-illustrations/simple-illustration__qr-code.svg';
import SimpleIllustrationRealtimereports109 from '@assets/images/simple-illustrations/simple-illustration__realtimereports.svg';
import SimpleIllustrationReceiptEnvelope370 from '@assets/images/simple-illustrations/simple-illustration__receipt-envelope.svg';
import SimpleIllustrationReceiptLocationMarker51 from '@assets/images/simple-illustrations/simple-illustration__receipt-location-marker.svg';
import SimpleIllustrationReceiptWrangler116 from '@assets/images/simple-illustrations/simple-illustration__receipt-wrangler.svg';
import SimpleIllustrationReceipt288 from '@assets/images/simple-illustrations/simple-illustration__receipt.svg';
import SimpleIllustrationReceiptupload278 from '@assets/images/simple-illustrations/simple-illustration__receiptupload.svg';
import SimpleIllustrationReplaceReceipt157 from '@assets/images/simple-illustrations/simple-illustration__replace-receipt.svg';
import SimpleIllustrationReportReceipt345 from '@assets/images/simple-illustrations/simple-illustration__report-receipt.svg';
import SimpleIllustrationRules299 from '@assets/images/simple-illustrations/simple-illustration__rules.svg';
import SimpleIllustrationSanfrancisco202 from '@assets/images/simple-illustrations/simple-illustration__sanfrancisco.svg';
import SimpleIllustrationSendmoney191 from '@assets/images/simple-illustrations/simple-illustration__sendmoney.svg';
import SimpleIllustrationShield147 from '@assets/images/simple-illustrations/simple-illustration__shield.svg';
import SimpleIllustrationSmallrocket129 from '@assets/images/simple-illustrations/simple-illustration__smallrocket.svg';
import SimpleIllustrationSmartscan230 from '@assets/images/simple-illustrations/simple-illustration__smartscan.svg';
import SimpleIllustrationSplitbill166 from '@assets/images/simple-illustrations/simple-illustration__splitbill.svg';
import SimpleIllustrationStopwatch199 from '@assets/images/simple-illustrations/simple-illustration__stopwatch.svg';
import SimpleIllustrationSubscriptionAnnual101 from '@assets/images/simple-illustrations/simple-illustration__subscription-annual.svg';
import SimpleIllustrationSubscriptionPpu255 from '@assets/images/simple-illustrations/simple-illustration__subscription-ppu.svg';
import SimpleIllustrationTag216 from '@assets/images/simple-illustrations/simple-illustration__tag.svg';
import SimpleIllustrationTeachersUnite176 from '@assets/images/simple-illustrations/simple-illustration__teachers-unite.svg';
import SimpleIllustrationThumbsdown224 from '@assets/images/simple-illustrations/simple-illustration__thumbsdown.svg';
import SimpleIllustrationThumbsupstars111 from '@assets/images/simple-illustrations/simple-illustration__thumbsupstars.svg';
import SimpleIllustrationTire197 from '@assets/images/simple-illustrations/simple-illustration__tire.svg';
import SimpleIllustrationTrackShoe125 from '@assets/images/simple-illustrations/simple-illustration__track-shoe.svg';
import SimpleIllustrationTrashcan171 from '@assets/images/simple-illustrations/simple-illustration__trashcan.svg';
import SimpleIllustrationTreasurechest138 from '@assets/images/simple-illustrations/simple-illustration__treasurechest.svg';
import SimpleIllustrationTwocardsHorizontal238 from '@assets/images/simple-illustrations/simple-illustration__twocards-horizontal.svg';
import SimpleIllustrationVirtualcard163 from '@assets/images/simple-illustrations/simple-illustration__virtualcard.svg';
import SimpleIllustrationWalletAlt187 from '@assets/images/simple-illustrations/simple-illustration__wallet-alt.svg';
import SimpleIllustrationWorkflows79 from '@assets/images/simple-illustrations/simple-illustration__workflows.svg';
import SocialFacebook603 from '@assets/images/social-facebook.svg';
import SocialInstagram300 from '@assets/images/social-instagram.svg';
import SocialLinkedin567 from '@assets/images/social-linkedin.svg';
import SocialPodcast315 from '@assets/images/social-podcast.svg';
import SocialTwitter512 from '@assets/images/social-twitter.svg';
import SocialYoutube478 from '@assets/images/social-youtube.svg';
import SpreadsheetComputer44 from '@assets/images/spreadsheet-computer.svg';
import Star437 from '@assets/images/Star.svg';
import Stopwatch486 from '@assets/images/stopwatch.svg';
import SubscriptionDetailsApprovedlogoLight75 from '@assets/images/subscription-details__approvedlogo--light.svg';
import SubscriptionDetailsApprovedlogo74 from '@assets/images/subscription-details__approvedlogo.svg';
import Suitcase494 from '@assets/images/suitcase.svg';
import Sync424 from '@assets/images/sync.svg';
import Table593 from '@assets/images/table.svg';
import Tag501 from '@assets/images/tag.svg';
import Task356 from '@assets/images/task.svg';
import TestDrive10 from '@assets/images/test-drive.svg';
import EmptyStateBackgroundFadeDark8 from '@assets/images/themeDependent/empty-state_background-fade-dark.svg';
import EmptyStateBackgroundFadeLight7 from '@assets/images/themeDependent/empty-state_background-fade-light.svg';
import Thread377 from '@assets/images/thread.svg';
import ThreeDots558 from '@assets/images/three-dots.svg';
import ThumbsDown371 from '@assets/images/thumbs-down.svg';
import ThumbsUp505 from '@assets/images/thumbs-up.svg';
import Train358 from '@assets/images/train.svg';
import Transfer524 from '@assets/images/transfer.svg';
import Trashcan477 from '@assets/images/trashcan.svg';
import TreasureChest375 from '@assets/images/treasure-chest.svg';
import TurtleInShell78 from '@assets/images/turtle-in-shell.svg';
import Unlock600 from '@assets/images/unlock.svg';
import UploadAlt534 from '@assets/images/upload-alt.svg';
import Upload540 from '@assets/images/upload.svg';
import UserCheck464 from '@assets/images/user-check.svg';
import UserEye310 from '@assets/images/user-eye.svg';
import UserLock383 from '@assets/images/user-lock.svg';
import UserPlus509 from '@assets/images/user-plus.svg';
import User604 from '@assets/images/user.svg';
import Users500 from '@assets/images/users.svg';
import VideoSlash353 from '@assets/images/video-slash.svg';
import VolumeHigh420 from '@assets/images/volume-high.svg';
import VolumeLow537 from '@assets/images/volume-low.svg';
import Wallet511 from '@assets/images/wallet.svg';
import Workflows446 from '@assets/images/workflows.svg';
import WorkspaceDefaultAvatar374 from '@assets/images/workspace-default-avatar.svg';
import Wrench385 from '@assets/images/wrench.svg';
import XCircle435 from '@assets/images/x-circle.svg';
import Zoom430 from '@assets/images/zoom.svg';

export type SVGItem = {
    position: number;
    name: string;
    component: React.ComponentType;
};

// Complete SVG items array (610 total)
export const svgItems: SVGItem[] = [
    {position: 1, name: 'home-background--ios.svg', component: HomeBackgroundIos1},
    {position: 2, name: 'home-background--desktop.svg', component: HomeBackgroundDesktop2},
    {position: 3, name: 'home-background--mobile.svg', component: HomeBackgroundMobile3},
    {position: 4, name: 'home-background--android.svg', component: HomeBackgroundAndroid4},
    {position: 5, name: 'play.svg', component: Play5},
    {position: 6, name: 'dot-indicator.svg', component: DotIndicator6},
    {position: 7, name: 'empty-state_background-fade-light.svg', component: EmptyStateBackgroundFadeLight7},
    {position: 8, name: 'empty-state_background-fade-dark.svg', component: EmptyStateBackgroundFadeDark8},
    {position: 9, name: 'eReceipt_background.svg', component: EreceiptBackground9},
    {position: 10, name: 'test-drive.svg', component: TestDrive10},
    {position: 11, name: 'illustration__card-replacement-success.svg', component: IllustrationCardReplacementSuccess11},
    {position: 12, name: 'emptystate__expensifycard.svg', component: EmptystateExpensifycard12},
    {position: 13, name: 'modal-hold-or-reject.svg', component: ModalHoldOrReject13},
    {position: 14, name: 'eReceiptBG_tangerine.svg', component: EreceiptbgTangerine14},
    {position: 15, name: 'eReceiptBG_pink.svg', component: EreceiptbgPink15},
    {position: 16, name: 'simple-illustration__empty-shelves.svg', component: SimpleIllustrationEmptyShelves16},
    {position: 17, name: 'todd-with-phones.svg', component: ToddWithPhones17},
    {position: 18, name: 'eReceiptBG_yellow.svg', component: EreceiptbgYellow18},
    {position: 19, name: 'todd-in-car.svg', component: ToddInCar19},
    {position: 20, name: 'emptystate__holdexpense.svg', component: EmptystateHoldexpense20},
    {position: 21, name: 'eReceiptBG_ice.svg', component: EreceiptbgIce21},
    {position: 22, name: 'magic-code.svg', component: MagicCode22},
    {position: 23, name: 'emptystate__card-pos.svg', component: EmptystateCardPos23},
    {position: 24, name: 'eReceipt-BGImage.svg', component: EreceiptBgimage24},
    {position: 25, name: 'abracadabra.svg', component: Abracadabra25},
    {position: 26, name: 'eReceiptBG_green.svg', component: EreceiptbgGreen26},
    {position: 27, name: 'emptystate__travel.svg', component: EmptystateTravel27},
    {position: 28, name: 'eReceiptBG_blue.svg', component: EreceiptbgBlue28},
    {position: 29, name: 'home-illustration-hands.svg', component: HomeIllustrationHands29},
    {position: 30, name: 'cardIllustration.svg', component: Cardillustration30},
    {position: 31, name: 'pending-bank.svg', component: PendingBank31},
    {position: 32, name: 'emptystate__receiptfairy.svg', component: EmptystateReceiptfairy32},
    {position: 33, name: 'rocket-dude.svg', component: RocketDude33},
    {position: 34, name: 'laptop-with-second-screen-and-hourglass.svg', component: LaptopWithSecondScreenAndHourglass34},
    {position: 35, name: 'payment-hands.svg', component: PaymentHands35},
    {position: 36, name: 'educational-illustration__multi-scan.svg', component: EducationalIllustrationMultiScan36},
    {position: 37, name: 'pendingstate_laptop-with-hourglass-and-cards.svg', component: PendingstateLaptopWithHourglassAndCards37},
    {position: 38, name: 'laptop-with-second-screen-sync.svg', component: LaptopWithSecondScreenSync38},
    {position: 39, name: 'emptystate__big-vault.svg', component: EmptystateBigVault39},
    {position: 40, name: 'laptop-with-second-screen-x.svg', component: LaptopWithSecondScreenX40},
    {position: 41, name: 'computer.svg', component: Computer41},
    {position: 42, name: 'connection-complete.svg', component: ConnectionComplete42},
    {position: 43, name: 'magnifying-glass-spy-mouth-closed.svg', component: MagnifyingGlassSpyMouthClosed43},
    {position: 44, name: 'spreadsheet-computer.svg', component: SpreadsheetComputer44},
    {position: 45, name: 'money-stack.svg', component: MoneyStack45},
    {position: 46, name: 'suntrust.svg', component: Suntrust46},
    {position: 47, name: 'running-turtle.svg', component: RunningTurtle47},
    {position: 48, name: 'suntrust.svg', component: Suntrust48},
    {position: 49, name: 'rocket--blue.svg', component: RocketBlue49},
    {position: 50, name: 'three_legged_laptop_woman.svg', component: ThreeLeggedLaptopWoman50},
    {position: 51, name: 'simple-illustration__receipt-location-marker.svg', component: SimpleIllustrationReceiptLocationMarker51},
    {position: 52, name: 'hand.svg', component: Hand52},
    {position: 53, name: 'simple-illustration__bigrocket.svg', component: SimpleIllustrationBigrocket53},
    {position: 54, name: 'default-avatar_16.svg', component: DefaultAvatar1654},
    {position: 55, name: 'money-waving.svg', component: MoneyWaving55},
    {position: 56, name: 'default-avatar_3.svg', component: DefaultAvatar356},
    {position: 57, name: 'simple-illustration__gears.svg', component: SimpleIllustrationGears57},
    {position: 58, name: 'default-avatar_24.svg', component: DefaultAvatar2458},
    {position: 59, name: 'mushroom-top-hat.svg', component: MushroomTopHat59},
    {position: 60, name: 'default-avatar_4.svg', component: DefaultAvatar460},
    {position: 61, name: 'default-avatar_14.svg', component: DefaultAvatar1461},
    {position: 62, name: 'default-avatar_22.svg', component: DefaultAvatar2262},
    {position: 63, name: 'default-avatar_7.svg', component: DefaultAvatar763},
    {position: 64, name: 'default-avatar_13.svg', component: DefaultAvatar1364},
    {position: 65, name: 'receipts-stacked-on-pin.svg', component: ReceiptsStackedOnPin65},
    {position: 66, name: 'default-avatar_5.svg', component: DefaultAvatar566},
    {position: 67, name: 'default-avatar_23.svg', component: DefaultAvatar2367},
    {position: 68, name: 'default-avatar_20.svg', component: DefaultAvatar2068},
    {position: 69, name: 'default-avatar_10.svg', component: DefaultAvatar1069},
    {position: 70, name: 'default-avatar_8.svg', component: DefaultAvatar870},
    {position: 71, name: 'emptystate__spy-pigeon.svg', component: EmptystateSpyPigeon71},
    {position: 72, name: 'default-avatar_6.svg', component: DefaultAvatar672},
    {position: 73, name: 'default-avatar_15.svg', component: DefaultAvatar1573},
    {position: 74, name: 'subscription-details__approvedlogo.svg', component: SubscriptionDetailsApprovedlogo74},
    {position: 75, name: 'subscription-details__approvedlogo--light.svg', component: SubscriptionDetailsApprovedlogoLight75},
    {position: 76, name: 'emptystate__puzzlepieces.svg', component: EmptystatePuzzlepieces76},
    {position: 77, name: 'default-avatar_19.svg', component: DefaultAvatar1977},
    {position: 78, name: 'turtle-in-shell.svg', component: TurtleInShell78},
    {position: 79, name: 'simple-illustration__workflows.svg', component: SimpleIllustrationWorkflows79},
    {position: 80, name: 'simple-illustration__opensafe.svg', component: SimpleIllustrationOpensafe80},
    {position: 81, name: 'default-avatar_1.svg', component: DefaultAvatar181},
    {position: 82, name: 'card-expensify-large.svg', component: CardExpensifyLarge82},
    {position: 83, name: 'default-avatar_21.svg', component: DefaultAvatar2183},
    {position: 84, name: 'advanced-approvals-icon-square.svg', component: AdvancedApprovalsIconSquare84},
    {position: 85, name: 'simple-illustration__hotdogstand.svg', component: SimpleIllustrationHotdogstand85},
    {position: 86, name: 'receipt-upload.svg', component: ReceiptUpload86},
    {position: 87, name: 'safe.svg', component: Safe87},
    {position: 88, name: 'default-avatar_11.svg', component: DefaultAvatar1188},
    {position: 89, name: 'default-avatar_12.svg', component: DefaultAvatar1289},
    {position: 90, name: 'uber.svg', component: Uber90},
    {position: 91, name: 'default-avatar_17.svg', component: DefaultAvatar1791},
    {position: 92, name: 'simple-illustration__piggybank.svg', component: SimpleIllustrationPiggybank92},
    {position: 93, name: 'emptystate__expenses.svg', component: EmptystateExpenses93},
    {position: 94, name: 'card-expensify.svg', component: CardExpensify94},
    {position: 95, name: 'simple-illustration__empty-state.svg', component: SimpleIllustrationEmptyState95},
    {position: 96, name: 'default-avatar_18.svg', component: DefaultAvatar1896},
    {position: 97, name: 'simple-illustration__moneywings.svg', component: SimpleIllustrationMoneywings97},
    {position: 98, name: 'rocket--orange.svg', component: RocketOrange98},
    {position: 99, name: 'simple-illustration__encryption.svg', component: SimpleIllustrationEncryption99},
    {position: 100, name: 'simple-illustration__perdiem.svg', component: SimpleIllustrationPerdiem100},
    {position: 101, name: 'simple-illustration__subscription-annual.svg', component: SimpleIllustrationSubscriptionAnnual101},
    {position: 102, name: 'simple-illustration__money-receipts.svg', component: SimpleIllustrationMoneyReceipts102},
    {position: 103, name: 'navy-federal-credit-union.svg', component: NavyFederalCreditUnion103},
    {position: 104, name: 'simple-illustration__messageinabottle.svg', component: SimpleIllustrationMessageinabottle104},
    {position: 105, name: 'card-wellsfargo-large.svg', component: CardWellsfargoLarge105},
    {position: 106, name: 'simple-illustration__accounting.svg', component: SimpleIllustrationAccounting106},
    {position: 107, name: 'simple-illustration__bank-arrow.svg', component: SimpleIllustrationBankArrow107},
    {position: 108, name: 'card-visa-large.svg', component: CardVisaLarge108},
    {position: 109, name: 'simple-illustration__realtimereports.svg', component: SimpleIllustrationRealtimereports109},
    {position: 110, name: 'default-avatar_2.svg', component: DefaultAvatar2110},
    {position: 111, name: 'simple-illustration__thumbsupstars.svg', component: SimpleIllustrationThumbsupstars111},
    {position: 112, name: 'broken-magnifying-glass.svg', component: BrokenMagnifyingGlass112},
    {position: 113, name: 'expensify-card-dark.svg', component: ExpensifyCardDark113},
    {position: 114, name: 'charles-schwab.svg', component: CharlesSchwab114},
    {position: 115, name: 'default-avatar_9.svg', component: DefaultAvatar9115},
    {position: 116, name: 'simple-illustration__receipt-wrangler.svg', component: SimpleIllustrationReceiptWrangler116},
    {position: 117, name: 'simple-illustration__envelopereceipt.svg', component: SimpleIllustrationEnvelopereceipt117},
    {position: 118, name: 'visa.svg', component: Visa118},
    {position: 119, name: 'card-visa.svg', component: CardVisa119},
    {position: 120, name: 'card-wellsfargo.svg', component: CardWellsfargo120},
    {position: 121, name: 'simple-illustration__filters.svg', component: SimpleIllustrationFilters121},
    {position: 122, name: 'simple-illustration__moneyintowallet.svg', component: SimpleIllustrationMoneyintowallet122},
    {position: 123, name: 'expensify-card.svg', component: ExpensifyCard123},
    {position: 124, name: 'capital-one.svg', component: CapitalOne124},
    {position: 125, name: 'simple-illustration__track-shoe.svg', component: SimpleIllustrationTrackShoe125},
    {position: 126, name: 'capital-one.svg', component: CapitalOne126},
    {position: 127, name: 'simple-illustration__pillow.svg', component: SimpleIllustrationPillow127},
    {position: 128, name: 'telescope.svg', component: Telescope128},
    {position: 129, name: 'simple-illustration__smallrocket.svg', component: SimpleIllustrationSmallrocket129},
    {position: 130, name: 'simple-illustration__bill.svg', component: SimpleIllustrationBill130},
    {position: 131, name: 'navy-federal-credit-union.svg', component: NavyFederalCreditUnion131},
    {position: 132, name: 'todd-behind-cloud.svg', component: ToddBehindCloud132},
    {position: 133, name: 'simple-illustration__paperairplane.svg', component: SimpleIllustrationPaperairplane133},
    {position: 134, name: 'simple-illustration__coins.svg', component: SimpleIllustrationCoins134},
    {position: 135, name: 'folder-with-papers.svg', component: FolderWithPapers135},
    {position: 136, name: 'charles-schwab.svg', component: CharlesSchwab136},
    {position: 137, name: 'netsuite-icon-square.svg', component: NetsuiteIconSquare137},
    {position: 138, name: 'simple-illustration__treasurechest.svg', component: SimpleIllustrationTreasurechest138},
    {position: 139, name: 'tada--yellow.svg', component: TadaYellow139},
    {position: 140, name: 'tada--blue.svg', component: TadaBlue140},
    {position: 141, name: 'simple-illustration__headset.svg', component: SimpleIllustrationHeadset141},
    {position: 142, name: 'simple-illustration__mobileapp.svg', component: SimpleIllustrationMobileapp142},
    {position: 143, name: 'simple-illustration__car_pink.svg', component: SimpleIllustrationCarPink143},
    {position: 144, name: 'simple-illustration__car-ice.svg', component: SimpleIllustrationCarIce144},
    {position: 145, name: 'simple-illustration__car.svg', component: SimpleIllustrationCar145},
    {position: 146, name: 'simple-illustration__pencil.svg', component: SimpleIllustrationPencil146},
    {position: 147, name: 'simple-illustration__shield.svg', component: SimpleIllustrationShield147},
    {position: 148, name: 'netsuite-oracle-icon.svg', component: NetsuiteOracleIcon148},
    {position: 149, name: 'simple-illustration__hourglass.svg', component: SimpleIllustrationHourglass149},
    {position: 150, name: 'card-wells_fargo.svg', component: CardWellsFargo150},
    {position: 151, name: 'simple-illustration__concierge-bubble.svg', component: SimpleIllustrationConciergeBubble151},
    {position: 152, name: 'simple-illustration__creditcards--green.svg', component: SimpleIllustrationCreditcardsGreen152},
    {position: 153, name: 'simple-illustration__moneybadge.svg', component: SimpleIllustrationMoneybadge153},
    {position: 154, name: 'simple-illustration__concierge.svg', component: SimpleIllustrationConcierge154},
    {position: 155, name: 'receipts-search--yellow.svg', component: ReceiptsSearchYellow155},
    {position: 156, name: 'bank-user--green.svg', component: BankUserGreen156},
    {position: 157, name: 'simple-illustration__replace-receipt.svg', component: SimpleIllustrationReplaceReceipt157},
    {position: 158, name: 'bank-mouse--green.svg', component: BankMouseGreen158},
    {position: 159, name: 'discover.svg', component: Discover159},
    {position: 160, name: 'simple-illustration__credit-cards.svg', component: SimpleIllustrationCreditCards160},
    {position: 161, name: 'simple-illustration__approval.svg', component: SimpleIllustrationApproval161},
    {position: 162, name: 'simple-illustration__invoice.svg', component: SimpleIllustrationInvoice162},
    {position: 163, name: 'simple-illustration__virtualcard.svg', component: SimpleIllustrationVirtualcard163},
    {position: 164, name: 'simple-illustration__creditcardeyes.svg', component: SimpleIllustrationCreditcardeyes164},
    {position: 165, name: 'simple-illustration__lockopen.svg', component: SimpleIllustrationLockopen165},
    {position: 166, name: 'simple-illustration__splitbill.svg', component: SimpleIllustrationSplitbill166},
    {position: 167, name: 'simple-illustration__smartscan.svg', component: SimpleIllustrationSmartscan167},
    {position: 168, name: 'simple-illustration__binoculars.svg', component: SimpleIllustrationBinoculars168},
    {position: 169, name: 'citizens.svg', component: Citizens169},
    {position: 170, name: 'card-stripe-large.svg', component: CardStripeLarge170},
    {position: 171, name: 'simple-illustration__trashcan.svg', component: SimpleIllustrationTrashcan171},
    {position: 172, name: 'bank-arrow--pink.svg', component: BankArrowPink172},
    {position: 173, name: 'regions-bank.svg', component: RegionsBank173},
    {position: 174, name: 'discover.svg', component: Discover174},
    {position: 175, name: 'simple-illustration__magnifyingglass-money.svg', component: SimpleIllustrationMagnifyingglassMoney175},
    {position: 176, name: 'simple-illustration__teachers-unite.svg', component: SimpleIllustrationTeachersUnite176},
    {position: 177, name: 'jewel-box--yellow.svg', component: JewelBoxYellow177},
    {position: 178, name: 'jewel-box--pink.svg', component: JewelBoxPink178},
    {position: 179, name: 'jewel-box--green.svg', component: JewelBoxGreen179},
    {position: 180, name: 'jewel-box--blue.svg', component: JewelBoxBlue180},
    {position: 181, name: 'expensify-logo--adhoc.svg', component: ExpensifyLogoAdhoc181},
    {position: 182, name: 'netsuite-icon.svg', component: NetsuiteIcon182},
    {position: 183, name: 'simple-illustration__mailbox.svg', component: SimpleIllustrationMailbox183},
    {position: 184, name: 'expensify-logo--staging.svg', component: ExpensifyLogoStaging184},
    {position: 185, name: 'card-stripe.svg', component: CardStripe185},
    {position: 186, name: 'simple-illustration__lockclosed_orange.svg', component: SimpleIllustrationLockclosedOrange186},
    {position: 187, name: 'simple-illustration__wallet-alt.svg', component: SimpleIllustrationWalletAlt187},
    {position: 188, name: 'simple-illustration__coffeemug.svg', component: SimpleIllustrationCoffeemug188},
    {position: 189, name: 'simple-illustration__luggage.svg', component: SimpleIllustrationLuggage189},
    {position: 190, name: 'simple-illustration__flash.svg', component: SimpleIllustrationFlash190},
    {position: 191, name: 'simple-illustration__sendmoney.svg', component: SimpleIllustrationSendmoney191},
    {position: 192, name: 'simple-illustration__lockclosed.svg', component: SimpleIllustrationLockclosed192},
    {position: 193, name: 'usaa.svg', component: Usaa193},
    {position: 194, name: 'expensify-logo--dev.svg', component: ExpensifyLogoDev194},
    {position: 195, name: 'empty-state__attach-receipt.svg', component: EmptyStateAttachReceipt195},
    {position: 196, name: 'simple-illustration__handcard.svg', component: SimpleIllustrationHandcard196},
    {position: 197, name: 'simple-illustration__tire.svg', component: SimpleIllustrationTire197},
    {position: 198, name: 'receipt-body.svg', component: ReceiptBody198},
    {position: 199, name: 'simple-illustration__stopwatch.svg', component: SimpleIllustrationStopwatch199},
    {position: 200, name: 'card-bofa-large.svg', component: CardBofaLarge200},
    {position: 201, name: 'simple-illustration__abacus.svg', component: SimpleIllustrationAbacus201},
    {position: 202, name: 'simple-illustration__sanfrancisco.svg', component: SimpleIllustrationSanfrancisco202},
    {position: 203, name: 'card-citi-large.svg', component: CardCitiLarge203},
    {position: 204, name: 'sage-intacct-icon-square.svg', component: SageIntacctIconSquare204},
    {position: 205, name: 'amex.svg', component: Amex205},
    {position: 206, name: 'card-amex-large.svg', component: CardAmexLarge206},
    {position: 207, name: 'sage-intacct-icon.svg', component: SageIntacctIcon207},
    {position: 208, name: 'regions-bank.svg', component: RegionsBank208},
    {position: 209, name: 'simple-illustration__email-address.svg', component: SimpleIllustrationEmailAddress209},
    {position: 210, name: 'citizens-bank.svg', component: CitizensBank210},
    {position: 211, name: 'bb-t.svg', component: BbT211},
    {position: 212, name: 'simple-illustration__handearth.svg', component: SimpleIllustrationHandearth212},
    {position: 213, name: 'card-citi.svg', component: CardCiti213},
    {position: 214, name: 'simple-illustration__company-card.svg', component: SimpleIllustrationCompanyCard214},
    {position: 215, name: 'simple-illustration__alert.svg', component: SimpleIllustrationAlert215},
    {position: 216, name: 'simple-illustration__tag.svg', component: SimpleIllustrationTag216},
    {position: 217, name: 'card-capital_one-large.svg', component: CardCapitalOneLarge217},
    {position: 218, name: 'us-bank.svg', component: UsBank218},
    {position: 219, name: 'generic-light-large.svg', component: GenericLightLarge219},
    {position: 220, name: 'generic-dark-large.svg', component: GenericDarkLarge220},
    {position: 221, name: 'card-bofa.svg', component: CardBofa221},
    {position: 222, name: 'usaa.svg', component: Usaa222},
    {position: 223, name: 'simple-illustration__lightbulb.svg', component: SimpleIllustrationLightbulb223},
    {position: 224, name: 'simple-illustration__thumbsdown.svg', component: SimpleIllustrationThumbsdown224},
    {position: 225, name: 'mastercard.svg', component: Mastercard225},
    {position: 226, name: 'credit-cards--blue.svg', component: CreditCardsBlue226},
    {position: 227, name: 'money-envelope--blue.svg', component: MoneyEnvelopeBlue227},
    {position: 228, name: 'card-mastercard-large.svg', component: CardMastercardLarge228},
    {position: 229, name: 'expensify-footer-logo-vertical.svg', component: ExpensifyFooterLogoVertical229},
    {position: 230, name: 'simple-illustration__smartscan.svg', component: SimpleIllustrationSmartscan230},
    {position: 231, name: 'card-amex.svg', component: CardAmex231},
    {position: 232, name: 'xero-icon.svg', component: XeroIcon232},
    {position: 233, name: 'expensify-footer-logo.svg', component: ExpensifyFooterLogo233},
    {position: 234, name: 'money-mouse--pink.svg', component: MoneyMousePink234},
    {position: 235, name: 'oracle-icon-square.svg', component: OracleIconSquare235},
    {position: 236, name: 'xero-icon-circle.svg', component: XeroIconCircle236},
    {position: 237, name: 'xero-icon-square.svg', component: XeroIconSquare237},
    {position: 238, name: 'simple-illustration__twocards-horizontal.svg', component: SimpleIllustrationTwocardsHorizontal238},
    {position: 239, name: 'new-expensify-adhoc.svg', component: NewExpensifyAdhoc239},
    {position: 240, name: 'simple-illustration__palmtree.svg', component: SimpleIllustrationPalmtree240},
    {position: 241, name: 'concierge-avatar.svg', component: ConciergeAvatar241},
    {position: 242, name: 'arrow-split.svg', component: ArrowSplit242},
    {position: 243, name: 'new-expensify-stg.svg', component: NewExpensifyStg243},
    {position: 244, name: 'card-capitalone.svg', component: CardCapitalone244},
    {position: 245, name: 'card-brex-large.svg', component: CardBrexLarge245},
    {position: 246, name: 'expensify_wordmark_white.svg', component: ExpensifyWordmarkWhite246},
    {position: 247, name: 'simple-illustration__house.svg', component: SimpleIllustrationHouse247},
    {position: 248, name: 'card-capital_one.svg', component: CardCapitalOne248},
    {position: 249, name: 'bb-t.svg', component: BbT249},
    {position: 250, name: 'card-chase-large.svg', component: CardChaseLarge250},
    {position: 251, name: 'generic-csv-light-large.svg', component: GenericCsvLightLarge251},
    {position: 252, name: 'generic-csv-dark-large.svg', component: GenericCsvDarkLarge252},
    {position: 253, name: 'generic-dark.svg', component: GenericDark253},
    {position: 254, name: 'generic-light.svg', component: GenericLight254},
    {position: 255, name: 'simple-illustration__subscription-ppu.svg', component: SimpleIllustrationSubscriptionPpu255},
    {position: 256, name: 'gps-track--orange.svg', component: GpsTrackOrange256},
    {position: 257, name: 'expensify-logo--prod.svg', component: ExpensifyLogoProd257},
    {position: 258, name: 'card-brex.svg', component: CardBrex258},
    {position: 259, name: 'oracle-icon.svg', component: OracleIcon259},
    {position: 260, name: 'card-mastercard.svg', component: CardMastercard260},
    {position: 261, name: 'us-bank.svg', component: UsBank261},
    {position: 262, name: 'simple-illustration__buildings.svg', component: SimpleIllustrationBuildings262},
    {position: 263, name: 'card-plaid-large.svg', component: CardPlaidLarge263},
    {position: 264, name: 'expensify-wordmark.svg', component: ExpensifyWordmark264},
    {position: 265, name: 'simple-illustration__checkmarkcircle.svg', component: SimpleIllustrationCheckmarkcircle265},
    {position: 266, name: 'simple-illustration__commentbubbles.svg', component: SimpleIllustrationCommentbubbles266},
    {position: 267, name: 'simple-illustration__commentbubbles_blue.svg', component: SimpleIllustrationCommentbubblesBlue267},
    {position: 268, name: 'MCC-RentalCar.svg', component: MccRentalcar268},
    {position: 269, name: 'card-chase.svg', component: CardChase269},
    {position: 270, name: 'microsoft-dynamics-icon-square.svg', component: MicrosoftDynamicsIconSquare270},
    {position: 271, name: 'keyboard.svg', component: Keyboard271},
    {position: 272, name: 'receipt-multiple.svg', component: ReceiptMultiple272},
    {position: 273, name: 'expensify-logo-new.svg', component: ExpensifyLogoNew273},
    {position: 274, name: 'new-expensify-dev.svg', component: NewExpensifyDev274},
    {position: 275, name: 'new-expensify.svg', component: NewExpensify275},
    {position: 276, name: 'simple-illustration__chatbubbles.svg', component: SimpleIllustrationChatbubbles276},
    {position: 277, name: 'invoice--orange.svg', component: InvoiceOrange277},
    {position: 278, name: 'simple-illustration__receiptupload.svg', component: SimpleIllustrationReceiptupload278},
    {position: 279, name: 'car-with-key.svg', component: CarWithKey279},
    {position: 280, name: 'sap-icon.svg', component: SapIcon280},
    {position: 281, name: 'generic-csv-light.svg', component: GenericCsvLight281},
    {position: 282, name: 'generic-csv-dark.svg', component: GenericCsvDark282},
    {position: 283, name: 'concierge--exclamation.svg', component: ConciergeExclamation283},
    {position: 284, name: 'notifications-avatar.svg', component: NotificationsAvatar284},
    {position: 285, name: 'new-expensify-dark.svg', component: NewExpensifyDark285},
    {position: 286, name: 'simple-illustration__folder-open.svg', component: SimpleIllustrationFolderOpen286},
    {position: 287, name: 'fidelity.svg', component: Fidelity287},
    {position: 288, name: 'simple-illustration__receipt.svg', component: SimpleIllustrationReceipt288},
    {position: 289, name: 'card-plaid.svg', component: CardPlaid289},
    {position: 290, name: 'bank-of-america.svg', component: BankOfAmerica290},
    {position: 291, name: 'add-emoji.svg', component: AddEmoji291},
    {position: 292, name: 'MCC-Taxi.svg', component: MccTaxi292},
    {position: 293, name: 'american-express.svg', component: AmericanExpress293},
    {position: 294, name: 'new-workspace.svg', component: NewWorkspace294},
    {position: 295, name: 'sap-icon-square.svg', component: SapIconSquare295},
    {position: 296, name: 'citibank.svg', component: Citibank296},
    {position: 297, name: 'credit-card-hourglass.svg', component: CreditCardHourglass297},
    {position: 298, name: 'google-logo.svg', component: GoogleLogo298},
    {position: 299, name: 'simple-illustration__rules.svg', component: SimpleIllustrationRules299},
    {position: 300, name: 'social-instagram.svg', component: SocialInstagram300},
    {position: 301, name: 'simple-illustration__building.svg', component: SimpleIllustrationBuilding301},
    {position: 302, name: 'image-crop-square-mask.svg', component: ImageCropSquareMask302},
    {position: 303, name: 'hashtag.svg', component: Hashtag303},
    {position: 304, name: 'expensify-app-icon.svg', component: ExpensifyAppIcon304},
    {position: 305, name: 'microsoft-dynamics-icon.svg', component: MicrosoftDynamicsIcon305},
    {position: 306, name: 'eReceiptIcon.svg', component: Ereceipticon306},
    {position: 307, name: 'gear.svg', component: Gear307},
    {position: 308, name: 'crosshair.svg', component: Crosshair308},
    {position: 309, name: 'bank-of-america.svg', component: BankOfAmerica309},
    {position: 310, name: 'user-eye.svg', component: UserEye310},
    {position: 311, name: 'fidelity.svg', component: Fidelity311},
    {position: 312, name: 'receipt--yellow.svg', component: ReceiptYellow312},
    {position: 313, name: 'drag-and-drop.svg', component: DragAndDrop313},
    {position: 314, name: 'coins.svg', component: Coins314},
    {position: 315, name: 'social-podcast.svg', component: SocialPodcast315},
    {position: 316, name: 'document-merge.svg', component: DocumentMerge316},
    {position: 317, name: 'citibank.svg', component: Citibank317},
    {position: 318, name: 'domain-room.svg', component: DomainRoom318},
    {position: 319, name: 'concierge--blue.svg', component: ConciergeBlue319},
    {position: 320, name: 'car.svg', component: Car320},
    {position: 321, name: 'car.svg', component: Car321},
    {position: 322, name: 'pnc.svg', component: Pnc322},
    {position: 323, name: 'receipt-slash.svg', component: ReceiptSlash323},
    {position: 324, name: 'american-express.svg', component: AmericanExpress324},
    {position: 325, name: 'image-crop-circle-mask.svg', component: ImageCropCircleMask325},
    {position: 326, name: 'apple-logo.svg', component: AppleLogo326},
    {position: 327, name: 'default-avatar_x.svg', component: DefaultAvatarX327},
    {position: 328, name: 'receipt-scan.svg', component: ReceiptScan328},
    {position: 329, name: 'MCC-Meals.svg', component: MccMeals329},
    {position: 330, name: 'expensify.svg', component: Expensify330},
    {position: 331, name: 'money-hourglass.svg', component: MoneyHourglass331},
    {position: 332, name: 'default-avatar_w.svg', component: DefaultAvatarW332},
    {position: 333, name: 'huntington-bank.svg', component: HuntingtonBank333},
    {position: 334, name: 'receipt-search.svg', component: ReceiptSearch334},
    {position: 335, name: 'MCC-Utilities.svg', component: MccUtilities335},
    {position: 336, name: 'MCC-Commuter.svg', component: MccCommuter336},
    {position: 337, name: 'admin-room.svg', component: AdminRoom337},
    {position: 338, name: 'receipt.svg', component: Receipt338},
    {position: 339, name: 'qbo-icon.svg', component: QboIcon339},
    {position: 340, name: 'MCC-Groceries.svg', component: MccGroceries340},
    {position: 341, name: 'bug.svg', component: Bug341},
    {position: 342, name: 'paycheck.svg', component: Paycheck342},
    {position: 343, name: 'comment-bubbles.svg', component: CommentBubbles343},
    {position: 344, name: 'link-copy.svg', component: LinkCopy344},
    {position: 345, name: 'simple-illustration__report-receipt.svg', component: SimpleIllustrationReportReceipt345},
    {position: 346, name: 'emptystate__routepending.svg', component: EmptystateRoutepending346},
    {position: 347, name: 'binoculars.svg', component: Binoculars347},
    {position: 348, name: 'globe.svg', component: Globe348},
    {position: 349, name: 'buildings.svg', component: Buildings349},
    {position: 350, name: 'android.svg', component: Android350},
    {position: 351, name: 'default-avatar_m.svg', component: DefaultAvatarM351},
    {position: 352, name: 'default-avatar_h.svg', component: DefaultAvatarH352},
    {position: 353, name: 'video-slash.svg', component: VideoSlash353},
    {position: 354, name: 'default-avatar_k.svg', component: DefaultAvatarK354},
    {position: 355, name: 'announce-room.svg', component: AnnounceRoom355},
    {position: 356, name: 'task.svg', component: Task356},
    {position: 357, name: 'invoice-generic.svg', component: InvoiceGeneric357},
    {position: 358, name: 'train.svg', component: Train358},
    {position: 359, name: 'receipt-plus.svg', component: ReceiptPlus359},
    {position: 360, name: 'fallback-workspace-avatar.svg', component: FallbackWorkspaceAvatar360},
    {position: 361, name: 'default-avatar_e.svg', component: DefaultAvatarE361},
    {position: 362, name: 'default-avatar_r.svg', component: DefaultAvatarR362},
    {position: 363, name: 'MCC-Misc.svg', component: MccMisc363},
    {position: 364, name: 'exit.svg', component: Exit364},
    {position: 365, name: 'pnc.svg', component: Pnc365},
    {position: 366, name: 'qbo-icon-circle.svg', component: QboIconCircle366},
    {position: 367, name: 'default-avatar_a.svg', component: DefaultAvatarA367},
    {position: 368, name: 'huntington-bank.svg', component: HuntingtonBank368},
    {position: 369, name: 'apple.svg', component: Apple369},
    {position: 370, name: 'simple-illustration__receipt-envelope.svg', component: SimpleIllustrationReceiptEnvelope370},
    {position: 371, name: 'thumbs-down.svg', component: ThumbsDown371},
    {position: 372, name: 'qbo-icon-square.svg', component: QboIconSquare372},
    {position: 373, name: 'qbd-icon-square.svg', component: QbdIconSquare373},
    {position: 374, name: 'workspace-default-avatar.svg', component: WorkspaceDefaultAvatar374},
    {position: 375, name: 'treasure-chest.svg', component: TreasureChest375},
    {position: 376, name: 'default-avatar_b.svg', component: DefaultAvatarB376},
    {position: 377, name: 'thread.svg', component: Thread377},
    {position: 378, name: 'room.svg', component: Room378},
    {position: 379, name: 'default-avatar_n.svg', component: DefaultAvatarN379},
    {position: 380, name: 'fullscreen.svg', component: Fullscreen380},
    {position: 381, name: 'generic-bank-account.svg', component: GenericBankAccount381},
    {position: 382, name: 'deleted-room.svg', component: DeletedRoom382},
    {position: 383, name: 'user-lock.svg', component: UserLock383},
    {position: 384, name: 'shield.svg', component: Shield384},
    {position: 385, name: 'wrench.svg', component: Wrench385},
    {position: 386, name: 'MCC-Gas.svg', component: MccGas386},
    {position: 387, name: 'default-avatar_building.svg', component: DefaultAvatarBuilding387},
    {position: 388, name: 'luggage.svg', component: Luggage388},
    {position: 389, name: 'default-avatar_y.svg', component: DefaultAvatarY389},
    {position: 390, name: 'default-avatar_7.svg', component: DefaultAvatar7390},
    {position: 391, name: 'default-avatar_6.svg', component: DefaultAvatar6391},
    {position: 392, name: 'default-avatar_9.svg', component: DefaultAvatar9392},
    {position: 393, name: 'default-avatar_8.svg', component: DefaultAvatar8393},
    {position: 394, name: 'default-avatar_5.svg', component: DefaultAvatar5394},
    {position: 395, name: 'default-avatar_4.svg', component: DefaultAvatar4395},
    {position: 396, name: 'default-avatar_2.svg', component: DefaultAvatar2396},
    {position: 397, name: 'default-avatar_17.svg', component: DefaultAvatar17397},
    {position: 398, name: 'default-avatar_3.svg', component: DefaultAvatar3398},
    {position: 399, name: 'default-avatar_18.svg', component: DefaultAvatar18399},
    {position: 400, name: 'default-avatar_16.svg', component: DefaultAvatar16400},
    {position: 401, name: 'default-avatar_15.svg', component: DefaultAvatar15401},
    {position: 402, name: 'default-avatar_14.svg', component: DefaultAvatar14402},
    {position: 403, name: 'default-avatar_12.svg', component: DefaultAvatar12403},
    {position: 404, name: 'default-avatar_13.svg', component: DefaultAvatar13404},
    {position: 405, name: 'default-avatar_11.svg', component: DefaultAvatar11405},
    {position: 406, name: 'default-avatar_10.svg', component: DefaultAvatar10406},
    {position: 407, name: 'default-avatar_1.svg', component: DefaultAvatar1407},
    {position: 408, name: 'money-circle.svg', component: MoneyCircle408},
    {position: 409, name: 'default-avatar_s.svg', component: DefaultAvatarS409},
    {position: 410, name: 'multi-tag.svg', component: MultiTag410},
    {position: 411, name: 'simple-illustration__qr-code.svg', component: SimpleIllustrationQrCode411},
    {position: 412, name: 'default-avatar_f.svg', component: DefaultAvatarF412},
    {position: 413, name: 'make-admin.svg', component: MakeAdmin413},
    {position: 414, name: 'rotate-image.svg', component: RotateImage414},
    {position: 415, name: 'eye-disabled.svg', component: EyeDisabled415},
    {position: 416, name: 'simple-illustration__profile.svg', component: SimpleIllustrationProfile416},
    {position: 417, name: 'money-search.svg', component: MoneySearch417},
    {position: 418, name: 'default-avatar_z.svg', component: DefaultAvatarZ418},
    {position: 419, name: 'add-reaction.svg', component: AddReaction419},
    {position: 420, name: 'volume-high.svg', component: VolumeHigh420},
    {position: 421, name: 'MCC-Services.svg', component: MccServices421},
    {position: 422, name: 'concierge.svg', component: Concierge422},
    {position: 423, name: 'default-avatar_2.svg', component: DefaultAvatar2423},
    {position: 424, name: 'sync.svg', component: Sync424},
    {position: 425, name: 'credit-card-exclamation.svg', component: CreditCardExclamation425},
    {position: 426, name: 'building.svg', component: Building426},
    {position: 427, name: 'gallery-not-found.svg', component: GalleryNotFound427},
    {position: 428, name: 'attachment-not-found.svg', component: AttachmentNotFound428},
    {position: 429, name: 'default-avatar_3.svg', component: DefaultAvatar3429},
    {position: 430, name: 'zoom.svg', component: Zoom430},
    {position: 431, name: 'connect.svg', component: Connect431},
    {position: 432, name: 'default-avatar_t.svg', component: DefaultAvatarT432},
    {position: 433, name: 'eye.svg', component: Eye433},
    {position: 434, name: 'default-avatar_g.svg', component: DefaultAvatarG434},
    {position: 435, name: 'x-circle.svg', component: XCircle435},
    {position: 436, name: 'light-bulb.svg', component: LightBulb436},
    {position: 437, name: 'Star.svg', component: Star437},
    {position: 438, name: 'printer.svg', component: Printer438},
    {position: 439, name: 'hourglass.svg', component: Hourglass439},
    {position: 440, name: 'default-avatar_q.svg', component: DefaultAvatarQ440},
    {position: 441, name: 'default-avatar_p.svg', component: DefaultAvatarP441},
    {position: 442, name: 'bed.svg', component: Bed442},
    {position: 443, name: 'MCC-Hotel.svg', component: MccHotel443},
    {position: 444, name: 'chatbubbles.svg', component: Chatbubbles444},
    {position: 445, name: 'chase.svg', component: Chase445},
    {position: 446, name: 'workflows.svg', component: Workflows446},
    {position: 447, name: 'bank.svg', component: Bank447},
    {position: 448, name: 'chatbubble-reply.svg', component: ChatbubbleReply448},
    {position: 449, name: 'monitor.svg', component: Monitor449},
    {position: 450, name: 'chase.svg', component: Chase450},
    {position: 451, name: 'default-avatar_c.svg', component: DefaultAvatarC451},
    {position: 452, name: 'flag_level_03.svg', component: FlagLevel03452},
    {position: 453, name: 'flag_level_02.svg', component: FlagLevel02453},
    {position: 454, name: 'flag_level_01.svg', component: FlagLevel01454},
    {position: 455, name: 'closed-sign.svg', component: ClosedSign455},
    {position: 456, name: 'chatbubble-add.svg', component: ChatbubbleAdd456},
    {position: 457, name: 'megaphone.svg', component: Megaphone457},
    {position: 458, name: 'calendar.svg', component: Calendar458},
    {position: 459, name: 'calendar.svg', component: Calendar459},
    {position: 460, name: 'default-avatar_v.svg', component: DefaultAvatarV460},
    {position: 461, name: 'mute.svg', component: Mute461},
    {position: 462, name: 'default-avatar_8.svg', component: DefaultAvatar8462},
    {position: 463, name: 'chatbubble-slash.svg', component: ChatbubbleSlash463},
    {position: 464, name: 'user-check.svg', component: UserCheck464},
    {position: 465, name: 'link.svg', component: Link465},
    {position: 466, name: 'default-avatar_d.svg', component: DefaultAvatarD466},
    {position: 467, name: 'money-bag.svg', component: MoneyBag467},
    {position: 468, name: 'gallery.svg', component: Gallery468},
    {position: 469, name: 'history.svg', component: History469},
    {position: 470, name: 'default-avatar_l.svg', component: DefaultAvatarL470},
    {position: 471, name: 'home-fade-gradient--mobile.svg', component: HomeFadeGradientMobile471},
    {position: 472, name: 'home-fade-gradient.svg', component: HomeFadeGradient472},
    {position: 473, name: 'td-bank.svg', component: TdBank473},
    {position: 474, name: 'question-mark-circle.svg', component: QuestionMarkCircle474},
    {position: 475, name: 'default-avatar_9.svg', component: DefaultAvatar9475},
    {position: 476, name: 'rotate.svg', component: Rotate476},
    {position: 477, name: 'trashcan.svg', component: Trashcan477},
    {position: 478, name: 'social-youtube.svg', component: SocialYoutube478},
    {position: 479, name: 'MCC-Airlines.svg', component: MccAirlines479},
    {position: 480, name: 'default-avatar_u.svg', component: DefaultAvatarU480},
    {position: 481, name: 'MCC-Mail.svg', component: MccMail481},
    {position: 482, name: 'chatbubble-unread.svg', component: ChatbubbleUnread482},
    {position: 483, name: 'new-window.svg', component: NewWindow483},
    {position: 484, name: 'default-avatar_6.svg', component: DefaultAvatar6484},
    {position: 485, name: 'filter.svg', component: Filter485},
    {position: 486, name: 'stopwatch.svg', component: Stopwatch486},
    {position: 487, name: 'bellSlash.svg', component: Bellslash487},
    {position: 488, name: 'all.svg', component: All488},
    {position: 489, name: 'default-avatar_5.svg', component: DefaultAvatar5489},
    {position: 490, name: 'bolt-slash.svg', component: BoltSlash490},
    {position: 491, name: 'paperclip.svg', component: Paperclip491},
    {position: 492, name: 'document-plus.svg', component: DocumentPlus492},
    {position: 493, name: 'filters.svg', component: Filters493},
    {position: 494, name: 'suitcase.svg', component: Suitcase494},
    {position: 495, name: 'invoice.svg', component: Invoice495},
    {position: 496, name: 'pin.svg', component: Pin496},
    {position: 497, name: 'key.svg', component: Key497},
    {position: 498, name: 'peace-sign.svg', component: PeaceSign498},
    {position: 499, name: 'bill.svg', component: Bill499},
    {position: 500, name: 'users.svg', component: Users500},
    {position: 501, name: 'tag.svg', component: Tag501},
    {position: 502, name: 'emoji.svg', component: Emoji502},
    {position: 503, name: 'chair.svg', component: Chair503},
    {position: 504, name: 'default-avatar_7.svg', component: DefaultAvatar7504},
    {position: 505, name: 'thumbs-up.svg', component: ThumbsUp505},
    {position: 506, name: 'td-bank.svg', component: TdBank506},
    {position: 507, name: 'circular-arrow-backwards.svg', component: CircularArrowBackwards507},
    {position: 508, name: 'qrcode.svg', component: Qrcode508},
    {position: 509, name: 'user-plus.svg', component: UserPlus509},
    {position: 510, name: 'checkbox.svg', component: Checkbox510},
    {position: 511, name: 'wallet.svg', component: Wallet511},
    {position: 512, name: 'social-twitter.svg', component: SocialTwitter512},
    {position: 513, name: 'paypal.svg', component: Paypal513},
    {position: 514, name: 'camera.svg', component: Camera514},
    {position: 515, name: 'inbox.svg', component: Inbox515},
    {position: 516, name: 'caret-up-down.svg', component: CaretUpDown516},
    {position: 517, name: 'default-avatar_1.svg', component: DefaultAvatar1517},
    {position: 518, name: 'plane.svg', component: Plane518},
    {position: 519, name: 'info.svg', component: Info519},
    {position: 520, name: 'soccer-ball.svg', component: SoccerBall520},
    {position: 521, name: 'magnifying-glass.svg', component: MagnifyingGlass521},
    {position: 522, name: 'arrow-circle-clockwise.svg', component: ArrowCircleClockwise522},
    {position: 523, name: 'default-avatar_j.svg', component: DefaultAvatarJ523},
    {position: 524, name: 'transfer.svg', component: Transfer524},
    {position: 525, name: 'rotate-left.svg', component: RotateLeft525},
    {position: 526, name: 'arrows-updown.svg', component: ArrowsUpdown526},
    {position: 527, name: 'check-square.svg', component: CheckSquare527},
    {position: 528, name: 'check-circle.svg', component: CheckCircle528},
    {position: 529, name: 'receipt-placeholder-plus.svg', component: ReceiptPlaceholderPlus529},
    {position: 530, name: 'offline.svg', component: Offline530},
    {position: 531, name: 'briefcase.svg', component: Briefcase531},
    {position: 532, name: 'download.svg', component: Download532},
    {position: 533, name: 'default-avatar_4.svg', component: DefaultAvatar4533},
    {position: 534, name: 'upload-alt.svg', component: UploadAlt534},
    {position: 535, name: 'collapse.svg', component: Collapse535},
    {position: 536, name: 'shutter.svg', component: Shutter536},
    {position: 537, name: 'volume-low.svg', component: VolumeLow537},
    {position: 538, name: 'feed.svg', component: Feed538},
    {position: 539, name: 'expand.svg', component: Expand539},
    {position: 540, name: 'upload.svg', component: Upload540},
    {position: 541, name: 'meter.svg', component: Meter541},
    {position: 542, name: 'plane.svg', component: Plane542},
    {position: 543, name: 'MCC-Goods.svg', component: MccGoods543},
    {position: 544, name: 'export.svg', component: Export544},
    {position: 545, name: 'default-avatar_i.svg', component: DefaultAvatarI545},
    {position: 546, name: 'plant.svg', component: Plant546},
    {position: 547, name: 'document-slash.svg', component: DocumentSlash547},
    {position: 548, name: 'hamburger.svg', component: Hamburger548},
    {position: 549, name: 'lock.svg', component: Lock549},
    {position: 550, name: 'dot-indicator-unfilled.svg', component: DotIndicatorUnfilled550},
    {position: 551, name: 'scan.svg', component: Scan551},
    {position: 552, name: 'offline-cloud.svg', component: OfflineCloud552},
    {position: 553, name: 'arrow-down-long.svg', component: ArrowDownLong553},
    {position: 554, name: 'arrow-right-long.svg', component: ArrowRightLong554},
    {position: 555, name: 'arrow-up-long.svg', component: ArrowUpLong555},
    {position: 556, name: 'remove-members.svg', component: RemoveMembers556},
    {position: 557, name: 'expensify-card-icon.svg', component: ExpensifyCardIcon557},
    {position: 558, name: 'three-dots.svg', component: ThreeDots558},
    {position: 559, name: 'calendar-solid.svg', component: CalendarSolid559},
    {position: 560, name: 'box.svg', component: Box560},
    {position: 561, name: 'arrow-collapse.svg', component: ArrowCollapse561},
    {position: 562, name: 'default-avatar_o.svg', component: DefaultAvatarO562},
    {position: 563, name: 'chatbubble-counter.svg', component: ChatbubbleCounter563},
    {position: 564, name: 'mail.svg', component: Mail564},
    {position: 565, name: 'phone.svg', component: Phone565},
    {position: 566, name: 'default-avatar_0.svg', component: DefaultAvatar0566},
    {position: 567, name: 'social-linkedin.svg', component: SocialLinkedin567},
    {position: 568, name: 'checkmark.svg', component: Checkmark568},
    {position: 569, name: 'pause.svg', component: Pause569},
    {position: 570, name: 'bell.svg', component: Bell570},
    {position: 571, name: 'home.svg', component: Home571},
    {position: 572, name: 'checkmark-circle.svg', component: CheckmarkCircle572},
    {position: 573, name: 'arrows-leftright.svg', component: ArrowsLeftright573},
    {position: 574, name: 'location.svg', component: Location574},
    {position: 575, name: 'circle-slash.svg', component: CircleSlash575},
    {position: 576, name: 'exclamation.svg', component: Exclamation576},
    {position: 577, name: 'arrow-right.svg', component: ArrowRight577},
    {position: 578, name: 'fallback-avatar.svg', component: FallbackAvatar578},
    {position: 579, name: 'down.svg', component: Down579},
    {position: 580, name: 'arrow-up.svg', component: ArrowUp580},
    {position: 581, name: 'bolt.svg', component: Bolt581},
    {position: 582, name: 'back-left.svg', component: BackLeft582},
    {position: 583, name: 'profile.svg', component: Profile583},
    {position: 584, name: 'flag.svg', component: Flag584},
    {position: 585, name: 'copy.svg', component: Copy585},
    {position: 586, name: 'flag.svg', component: Flag586},
    {position: 587, name: 'cash.svg', component: Cash587},
    {position: 588, name: 'pencil.svg', component: Pencil588},
    {position: 589, name: 'close.svg', component: Close589},
    {position: 590, name: 'creditcard.svg', component: Creditcard590},
    {position: 591, name: 'document.svg', component: Document591},
    {position: 592, name: 'map.svg', component: Map592},
    {position: 593, name: 'table.svg', component: Table593},
    {position: 594, name: 'empty-square.svg', component: EmptySquare594},
    {position: 595, name: 'heart.svg', component: Heart595},
    {position: 596, name: 'heart.svg', component: Heart596},
    {position: 597, name: 'send.svg', component: Send597},
    {position: 598, name: 'chatbubble.svg', component: Chatbubble598},
    {position: 599, name: 'menu.svg', component: Menu599},
    {position: 600, name: 'unlock.svg', component: Unlock600},
    {position: 601, name: 'drag-handles.svg', component: DragHandles601},
    {position: 602, name: 'plus.svg', component: Plus602},
    {position: 603, name: 'social-facebook.svg', component: SocialFacebook603},
    {position: 604, name: 'user.svg', component: User604},
    {position: 605, name: 'minus.svg', component: Minus605},
    {position: 606, name: 'bookmark.svg', component: Bookmark606},
    {position: 607, name: 'folder.svg', component: Folder607},
    {position: 608, name: 'generic-bank-card.svg', component: GenericBankCard608},
];

export default svgItems;
