# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

skip_docs
opt_out_usage

default_platform(:android)

platform :android do
  desc "Deploy a new version to Github"
  lane :beta do
    ENV["ENVFILE"]=".env.production"

    version = `node -pe "require('../../package.json').version"`.strip

    gradle(task: "clean assembleRelease")

    set_github_release(
        repository_name: "AndrewGable/ReactNativeChat",
        api_token: ENV["GITHUB_TOKEN"],
        name: version,
        description: ("Release version " + version),
        tag_name: version,
        upload_assets: ["./app/build/outputs/apk/release/app-release.apk"]
    )
  end
end
