# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

skip_docs
opt_out_usage

default_platform(:android)

platform :android do
  desc "Deploy a new version to Github"
  lane :beta do
    ENV["ENVFILE"]=".env.production"

    gradle(task: "clean assembleRelease")

    aws_s3(
        access_key: ENV['AWS_SECRET_ACCESS_KEY'],
        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
        aws_profile: ENV['AWS_ACCESS_KEY_ID'],
        bucket: 's3://chat-test-expensify-com/',
        region: 'us-east-1',
        apk: './app/build/outputs/apk/release/app-release.apk',
        path: '/',
        upload_metadata: false,
    )
  end
end
