import {READ_COMMANDS, WRITE_COMMANDS} from '@libs/API/types';

import CONST from '@src/CONST';
import * as PersistedRequests from '@src/libs/actions/PersistedRequests';
import * as API from '@src/libs/API';
import HttpUtils from '@src/libs/HttpUtils';
import * as MainQueue from '@src/libs/Network/MainQueue';
import * as NetworkStore from '@src/libs/Network/NetworkStore';
import * as SequentialQueue from '@src/libs/Network/SequentialQueue';
import {setHasRadio} from '@src/libs/NetworkState';
import ONYXKEYS from '@src/ONYXKEYS';
import type Response from '@src/types/onyx/Response';

import type {OnyxKey, OnyxUpdate} from 'react-native-onyx';

import Onyx from '../../__mocks__/react-native-onyx';
import getOnyxValue from '../utils/getOnyxValue';
import waitForBatchedUpdates from '../utils/waitForBatchedUpdates';

const WRITE_COMMAND = WRITE_COMMANDS.UPDATE_SPLIT_TRANSACTION;
const SPLIT_AMOUNT_PARAM = 'splits[0][amount]';

// SearchForTodos response payload. The key is arbitrary — it only has to be something we can read back.
const TODOS_ONYX_DATA: Array<OnyxUpdate<OnyxKey>> = [{onyxMethod: Onyx.METHOD.MERGE, key: ONYXKEYS.NVP_PRIORITY_MODE, value: CONST.PRIORITY_MODE.GSD}];

/**
 * Replaces xhr with a version that lets each command's response be resolved by hand.
 * Returns the map of in-flight commands to their resolvers.
 */
function mockControllableXhr() {
    const pending = new Map<string, (response: Response<OnyxKey>) => void>();
    jest.spyOn(HttpUtils, 'xhr').mockImplementation((command: string) => {
        // Log requests are noise here and would otherwise hang forever.
        if (command === 'Log') {
            return Promise.resolve({jsonCode: CONST.JSON_CODE.SUCCESS});
        }
        return new Promise<Response<OnyxKey>>((resolve) => {
            pending.set(command, resolve);
        });
    });
    return pending;
}

/** Resolves an in-flight command's response, failing loudly if that command was never sent. */
function resolveRequest(pending: Map<string, (response: Response<OnyxKey>) => void>, command: string, response: Response<OnyxKey>) {
    const resolve = pending.get(command);
    if (!resolve) {
        throw new Error(`Expected '${command}' to be in flight, but it was never sent`);
    }
    resolve(response);
}

beforeEach(() => {
    setHasRadio(true);
    MainQueue.clear();
    HttpUtils.cancelPendingRequests();
    PersistedRequests.clear();
    SequentialQueue.sequentialQueueRequestThrottle.clear();
    NetworkStore.checkRequiredData();

    return waitForBatchedUpdates()
        .then(() => Onyx.clear())
        .then(() => Onyx.multiSet({[ONYXKEYS.SESSION]: {authToken: 'testToken'}, [ONYXKEYS.CREDENTIALS]: {autoGeneratedLogin: 'test', autoGeneratedPassword: 'passwd'}}))
        .then(waitForBatchedUpdates);
});

afterEach(() => {
    NetworkStore.resetHasReadRequiredDataFromStorage();
    jest.clearAllMocks();
});

/* eslint-disable rulesdir/no-multiple-api-calls */
describe('SearchForTodos concurrency and Onyx deferral', () => {
    test('fires alongside an in-flight write, but its Onyx updates are applied only after that write settles', () => {
        const pending = mockControllableXhr();

        // Given a write is enqueued and SearchForTodos is read on the very next line (as openApp does)
        API.write(WRITE_COMMAND, {transactionID: 'test-transaction', [SPLIT_AMOUNT_PARAM]: 1});
        API.read(READ_COMMANDS.SEARCH_FOR_TODOS, null);

        return waitForBatchedUpdates()
            .then(() => {
                // Then both requests are on the wire at the same time — SearchForTodos did not wait for the write
                expect([...pending.keys()]).toEqual(expect.arrayContaining([WRITE_COMMAND, READ_COMMANDS.SEARCH_FOR_TODOS]));

                // When SearchForTodos responds first, while the write is still pending
                resolveRequest(pending, READ_COMMANDS.SEARCH_FOR_TODOS, {jsonCode: CONST.JSON_CODE.SUCCESS, onyxData: TODOS_ONYX_DATA});
                return waitForBatchedUpdates();
            })
            .then(() => {
                // Then its updates are held back
                return getOnyxValue(ONYXKEYS.NVP_PRIORITY_MODE);
            })
            .then((priorityMode) => {
                expect(priorityMode).toBeUndefined();

                // When the write finally settles
                resolveRequest(pending, WRITE_COMMAND, {jsonCode: CONST.JSON_CODE.SUCCESS});
                return waitForBatchedUpdates();
            })
            .then(() => getOnyxValue(ONYXKEYS.NVP_PRIORITY_MODE))
            .then((priorityMode) => {
                // Then the held-back updates are applied
                expect(priorityMode).toBe(CONST.PRIORITY_MODE.GSD);
            });
    });

    test('applies its Onyx updates immediately when no write is in flight (updates are never stranded)', () => {
        const pending = mockControllableXhr();

        // Given nothing is queued and SearchForTodos is read on its own
        API.read(READ_COMMANDS.SEARCH_FOR_TODOS, null);

        return waitForBatchedUpdates()
            .then(() => {
                resolveRequest(pending, READ_COMMANDS.SEARCH_FOR_TODOS, {jsonCode: CONST.JSON_CODE.SUCCESS, onyxData: TODOS_ONYX_DATA});
                return waitForBatchedUpdates();
            })
            .then(() => getOnyxValue(ONYXKEYS.NVP_PRIORITY_MODE))
            .then((priorityMode) => {
                // Then the updates land without waiting on anything
                expect(priorityMode).toBe(CONST.PRIORITY_MODE.GSD);
            });
    });
});
