import {CIRCULAR_MARKER, maskInspectionEvent, MAX_DEPTH_MARKER, SENSITIVE_VALUE_MASK} from '@libs/XStateInspector/maskSensitive';

import CONST from '@src/CONST';

import {createActor, createMachine} from 'xstate';

describe('maskInspectionEvent', () => {
    it('masks every value in a scenario payload because it can contain arbitrary PII', () => {
        const masked = maskInspectionEvent({
            snapshot: {
                context: {
                    payload: {
                        cardID: 'card-1',
                        legalFirstName: 'John',
                        legalLastName: 'Smith',
                        phoneNumber: '+44123456789',
                        addressStreet: '10 Downing Street',
                        dob: '1990-01-01',
                        isFromMissingDetailsFlow: true,
                    },
                },
            },
        });

        expect(masked).toEqual({
            snapshot: {
                context: {
                    payload: {
                        cardID: SENSITIVE_VALUE_MASK,
                        legalFirstName: SENSITIVE_VALUE_MASK,
                        legalLastName: SENSITIVE_VALUE_MASK,
                        phoneNumber: SENSITIVE_VALUE_MASK,
                        addressStreet: SENSITIVE_VALUE_MASK,
                        dob: SENSITIVE_VALUE_MASK,
                        isFromMissingDetailsFlow: SENSITIVE_VALUE_MASK,
                    },
                },
            },
        });
    });

    it('masks sensitive fields inside child-actor input, output and error, which the sanitize hooks never see', () => {
        const masked = maskInspectionEvent({
            snapshot: {
                status: 'done',
                input: {validateCode: '987654', scenarioName: 'REVEAL_CARD'},
                output: {httpStatusCode: 200, body: {pin: 1234}},
                error: {message: 'failed', response: {token: 'abc'}},
            },
        });

        expect(masked).toEqual({
            snapshot: {
                status: 'done',
                input: {validateCode: SENSITIVE_VALUE_MASK, scenarioName: 'REVEAL_CARD'},
                output: {httpStatusCode: 200, body: {pin: SENSITIVE_VALUE_MASK}},
                error: {message: 'failed', response: {token: SENSITIVE_VALUE_MASK}},
            },
        });
    });

    it('masks the auth-credential keys shared with the log redactor when they ride at the top of actor input', () => {
        const masked = maskInspectionEvent({
            snapshot: {
                input: {
                    authToken: 'aaa',
                    encryptedAuthToken: 'bbb',
                    idToken: 'ccc',
                    twoFactorAuthCode: '123456',
                    partnerUserSecret: 'sss',
                    partnerPassword: 'ppp',
                    autoGeneratedPassword: 'ggg',
                    scenarioName: 'REVEAL_CARD',
                },
            },
        });

        expect(masked).toEqual({
            snapshot: {
                input: {
                    authToken: SENSITIVE_VALUE_MASK,
                    encryptedAuthToken: SENSITIVE_VALUE_MASK,
                    idToken: SENSITIVE_VALUE_MASK,
                    twoFactorAuthCode: SENSITIVE_VALUE_MASK,
                    partnerUserSecret: SENSITIVE_VALUE_MASK,
                    partnerPassword: SENSITIVE_VALUE_MASK,
                    autoGeneratedPassword: SENSITIVE_VALUE_MASK,
                    scenarioName: 'REVEAL_CARD',
                },
            },
        });
    });

    it('masks WebAuthn challenge material wholesale (nonces, signatures and user PII)', () => {
        const masked = maskInspectionEvent({
            snapshot: {
                context: {
                    registrationChallenge: {challenge: 'nonce-abc', user: {id: 'uid', name: 'user@example.com'}},
                    authorizationChallenge: {challenge: 'nonce-def', rpId: 'expensify.com'},
                },
                input: {signedChallenge: 'signature', challenge: 'nonce-ghi'},
            },
        });

        expect(masked).toEqual({
            snapshot: {
                context: {
                    registrationChallenge: {challenge: SENSITIVE_VALUE_MASK, user: {id: SENSITIVE_VALUE_MASK, name: SENSITIVE_VALUE_MASK}},
                    authorizationChallenge: {challenge: SENSITIVE_VALUE_MASK, rpId: SENSITIVE_VALUE_MASK},
                },
                input: {signedChallenge: SENSITIVE_VALUE_MASK, challenge: SENSITIVE_VALUE_MASK},
            },
        });
    });

    it('masks each card secret inside the scenario response body while keeping the response status fields visible', () => {
        const masked = maskInspectionEvent({
            snapshot: {
                context: {
                    scenarioResponse: {httpStatusCode: 200, reason: 'SUCCESS', message: 'ok', body: {pan: '4111111111111111', expiration: '12/30', cvv: '123'}},
                },
            },
        });

        expect(masked).toEqual({
            snapshot: {
                context: {
                    scenarioResponse: {httpStatusCode: 200, reason: 'SUCCESS', message: 'ok', body: {pan: SENSITIVE_VALUE_MASK, expiration: SENSITIVE_VALUE_MASK, cvv: SENSITIVE_VALUE_MASK}},
                },
            },
        });
    });

    it('masks card secrets and registration key material under their own keys when they travel outside a response body', () => {
        const masked = maskInspectionEvent({
            event: {type: 'CARD_DETAILS_REVEALED', cardID: 'card-1', pan: '4111111111111111', expiration: '12/30', cvv: '123'},
            snapshot: {
                input: {keyInfo: {rawId: 'cred-id', type: 'biometrics-hsm', response: {clientDataJSON: 'eyJjaGFsbGVuZ2UiOiJub25jZSJ9', biometric: {publicKey: 'cred-id', algorithm: -7}}}},
            },
        });

        expect(masked).toEqual({
            event: {type: 'CARD_DETAILS_REVEALED', cardID: 'card-1', pan: SENSITIVE_VALUE_MASK, expiration: SENSITIVE_VALUE_MASK, cvv: SENSITIVE_VALUE_MASK},
            snapshot: {
                input: {
                    keyInfo: {
                        rawId: SENSITIVE_VALUE_MASK,
                        type: SENSITIVE_VALUE_MASK,
                        response: {clientDataJSON: SENSITIVE_VALUE_MASK, biometric: {publicKey: SENSITIVE_VALUE_MASK, algorithm: SENSITIVE_VALUE_MASK}},
                    },
                },
            },
        });
    });

    it('keeps machine state values readable when a state node is named like a sensitive key', () => {
        const masked = maskInspectionEvent({
            snapshot: {
                machine: {id: 'mfa'},
                value: {open: {validateCode: {awaitingValidateCode: 'awaitingInput'}, outcome: 'success'}},
                context: {validateCode: '987654'},
            },
        });

        expect(masked).toEqual({
            snapshot: {
                machine: {id: 'mfa'},
                value: {open: {validateCode: {awaitingValidateCode: 'awaitingInput'}, outcome: 'success'}},
                context: {validateCode: SENSITIVE_VALUE_MASK},
            },
        });
    });

    // Hand-built fixtures cannot prove that a real snapshot satisfies `isMachineSnapshot`, and a guard
    // that never fires would silently re-break the inspector for a state named like a sensitive key.
    it('exempts the state value of a real machine snapshot, whose toJSON output no longer carries the machine itself', () => {
        // `validateCode` has to be a compound state: masking rewrites keys, so only a state value that
        // carries the name as a key (not as a leaf string) can regress.
        const machine = createMachine({initial: 'validateCode', states: {validateCode: {initial: 'awaitingInput', states: {awaitingInput: {}}}}});
        const actor = createActor(machine).start();

        const masked = maskInspectionEvent({snapshot: actor.getSnapshot()});
        const maskedAgain = maskInspectionEvent(masked);
        const maskedAfterReconnect = maskInspectionEvent(maskedAgain);
        actor.stop();

        expect(maskedAgain).toBe(masked);
        expect(maskedAfterReconnect).toBe(masked);
        expect(masked).toEqual(expect.objectContaining({snapshot: expect.objectContaining({value: {validateCode: 'awaitingInput'}})}));
    });

    // The exemption exists only because machine state values hold static state-node names. Any other
    // actor logic may put real data in its own `value`, so the exemption must not reach it.
    it('masks the value of a snapshot that is not a machine snapshot, so foreign actor logic cannot leak through the exemption', () => {
        const masked = maskInspectionEvent({
            snapshot: {status: 'active', value: {validateCode: '987654', form: {pin: '1234', attempt: 2}}},
        });

        expect(masked).toEqual({
            snapshot: {status: 'active', value: {validateCode: SENSITIVE_VALUE_MASK, form: {pin: SENSITIVE_VALUE_MASK, attempt: 2}}},
        });
    });

    it('scopes the state-value exemption to snapshot.value', () => {
        const masked = maskInspectionEvent({
            event: {type: 'SUBMIT', keyInfo: {value: 'secret'}},
            snapshot: {
                machine: {id: 'mfa'},
                value: 'idle',
                context: {request: {keyInfo: {value: 'secret'}}},
            },
        });

        expect(masked).toEqual({
            event: {type: 'SUBMIT', keyInfo: {value: SENSITIVE_VALUE_MASK}},
            snapshot: {
                machine: {id: 'mfa'},
                value: 'idle',
                context: {request: {keyInfo: {value: SENSITIVE_VALUE_MASK}}},
            },
        });
    });

    it('keeps non-sensitive values and the inspector metadata untouched, including an event type named like a sensitive key', () => {
        const event = {
            type: '@xstate.event',
            sessionId: 'x:1',
            event: {type: 'token', scenarioName: 'REVEAL_CARD', retries: 3, isOffline: false, reason: null},
        };

        expect(maskInspectionEvent(event)).toEqual(event);
    });

    it('masks arrays under a sensitive key element by element and objects inside non-sensitive arrays', () => {
        const masked = maskInspectionEvent({token: ['a', 'b'], steps: ['init', 'verify'], attempts: [{password: 'hunter2', at: 1}]});

        expect(masked).toEqual({token: [SENSITIVE_VALUE_MASK, SENSITIVE_VALUE_MASK], steps: ['init', 'verify'], attempts: [{password: SENSITIVE_VALUE_MASK, at: 1}]});
    });

    it('honors toJSON the way JSON.stringify would, so snapshots shed their unserializable internals', () => {
        const masked = maskInspectionEvent({
            snapshot: {
                machine: {config: 'unserializable'},
                toJSON: () => ({status: 'active', context: {pin: '1234'}}),
            },
            createdAt: new Date('2026-06-12T00:00:00.000Z'),
        });

        expect(masked).toEqual({
            snapshot: {status: 'active', context: {pin: SENSITIVE_VALUE_MASK}},
            createdAt: '2026-06-12T00:00:00.000Z',
        });
    });

    it('drops functions and symbols from objects and nulls them inside arrays, keeping the result postMessage-safe', () => {
        const masked = maskInspectionEvent({
            snapshot: {context: {action: () => 'secret', tag: Symbol('secret'), kept: 1}},
            list: [() => 'secret', Symbol('secret'), 'kept'],
        });

        expect(masked).toStrictEqual({
            snapshot: {context: {kept: 1}},
            list: [null, null, 'kept'],
        });
    });

    it('collapses circular references to a marker instead of recursing forever', () => {
        const context: Record<string, unknown> = {scenarioName: 'REVEAL_CARD'};
        context.self = context;

        expect(maskInspectionEvent({snapshot: {context}})).toEqual({snapshot: {context: {scenarioName: 'REVEAL_CARD', self: CIRCULAR_MARKER}}});
    });

    it('renders a shared non-circular reference fully in both places', () => {
        const shared = {scenarioName: 'REVEAL_CARD'};

        expect(maskInspectionEvent({snapshot: {context: {scenario: shared}}, event: {scenario: shared}})).toEqual({
            snapshot: {context: {scenario: shared}},
            event: {scenario: shared},
        });
    });

    it('caps the serialization depth with a marker like the default serializer', () => {
        const deep: Record<string, unknown> = {};
        let leaf = deep;
        for (let i = 0; i < 15; i++) {
            const next: Record<string, unknown> = {};
            leaf.next = next;
            leaf = next;
        }

        expect(JSON.stringify(maskInspectionEvent(deep))).toContain(MAX_DEPTH_MARKER);
    });

    it('passes context-less snapshots (promise/callback child actors) through without throwing', () => {
        const masked = maskInspectionEvent({snapshot: {status: 'active', output: undefined, error: undefined, input: undefined}});

        expect(masked).toStrictEqual({snapshot: {status: 'active'}});
    });

    it.each(CONST.SENSITIVE_AUTH_KEYS)('masks the value under the sensitive key "%s", so the shared key set cannot drift away from the serializer', (key) => {
        expect(maskInspectionEvent({snapshot: {context: {[key]: 'sensitive-value'}}})).toEqual({snapshot: {context: {[key]: SENSITIVE_VALUE_MASK}}});
    });

    it('masks a value under a sensitive key even when it hides behind toJSON, so a secret cannot leak through serialization', () => {
        const masked = maskInspectionEvent({
            snapshot: {context: {token: {toJSON: () => 'plaintext-secret'}, note: {toJSON: () => 'visible'}}},
        });

        expect(masked).toEqual({snapshot: {context: {token: SENSITIVE_VALUE_MASK, note: 'visible'}}});
    });

    it('passes a non-object top-level value through unchanged, so odd inputs never throw', () => {
        expect(maskInspectionEvent(null)).toBeNull();
        expect(maskInspectionEvent(42)).toBe(42);
    });
});
