import React, {Component} from 'react';
import PropTypes from 'prop-types';
import _ from 'underscore';
import Onyx, {withOnyx} from 'react-native-onyx';
import lodashGet from 'lodash/get';
import {
    propTypes as validateLinkPropTypes,
    defaultProps as validateLinkDefaultProps,
} from './validateLinkPropTypes';
import * as User from '../../libs/actions/User';
import compose from '../../libs/compose';
import FullScreenLoadingIndicator from '../../components/FullscreenLoadingIndicator';
import ValidateCodeModal from '../../components/ValidateCode/ValidateCodeModal';
import ONYXKEYS from '../../ONYXKEYS';
import * as Session from '../../libs/actions/Session';
import Permissions from '../../libs/Permissions';
import withLocalize, {withLocalizePropTypes} from '../../components/withLocalize';
import AbracadabraModal from '../../components/ValidateCode/AbracadabraModal';
import ExpiredValidateCodeModal from '../../components/ValidateCode/ExpiredValidateCodeModal';
import Navigation from '../../libs/Navigation/Navigation';
import ROUTES from '../../ROUTES';

const propTypes = {
    /** The accountID and validateCode are passed via the URL */
    route: validateLinkPropTypes,

    /** List of betas available to current user */
    betas: PropTypes.arrayOf(PropTypes.string),

    ...withLocalizePropTypes,
};

const defaultProps = {
    route: validateLinkDefaultProps,
    betas: [],
};

class ValidateLoginPage extends Component {
    constructor(props) {
        super(props);

        this.resendValidateCode = this.resendValidateCode.bind(this);
        this.signInWithValidateCode = this.signInWithValidateCode.bind(this);

        this.state = {modal: null};
    }

    componentDidMount() {
        // Validate login if
        // - The user is not on passwordless beta
        if (!this.isOnPasswordlessBeta()) {
            User.validateLogin(this.accountID(), this.validateCode());
            return;
        }

        // Sign in if
        // - The user is on the passwordless beta
        // - AND the user is not authenticated
        // - AND the user has initiated the sign in process in another tab
        if (this.isOnPasswordlessBeta() && !this.isAuthenticated() && this.isSignInInitiated()) {
            Session.signInWithValidateCode(this.accountID(), this.validateCode());
            return;
        }

        this.showPasswordlessModal(false);
    }

    componentDidUpdate(prevProps) {
        if (!lodashGet(this.props, 'credentials.login', null) && lodashGet(this.props, 'credentials.accountID', null)) {
            // The user clicked the option to sign in the current tab
            if (lodashGet(this.props, 'account.requiresTwoFactorAuth', false)) {
                Navigation.navigate(ROUTES.HOME);
            } else {
                Navigation.navigate(ROUTES.REPORT);
            }
            return;
        }
        const justSignedIn = !lodashGet(prevProps, 'credentials.accountID', null) && lodashGet(this.props, 'credentials.accountID', null);
        this.showPasswordlessModal(justSignedIn);
    }

    /**
     * @returns {Boolean}
     */
    isOnPasswordlessBeta = () => Permissions.canUsePasswordlessLogins(this.props.betas);

    /**
     * @returns {String}
     */
    accountID = () => lodashGet(this.props.route.params, 'accountID', '');

    /**
     * @returns {String}
     */
    validateCode = () => lodashGet(this.props.route.params, 'validateCode', '');

    /**
     * @returns {Boolean}
     */
    isAuthenticated = () => Boolean(lodashGet(this.props, 'credentials.autoGeneratedLogin', null));

    /**
     * Whether SignIn was initiated on the current browser.
     * @returns {Boolean}
     */
    isSignInInitiated = () => !this.isAuthenticated() && lodashGet(this.props, 'credentials.login', null);

    resendValidateCode() {
        Session.resendLinkWithValidateCode();
    }

    signInWithValidateCode() {
        Session.signInWithValidateCode(this.accountID(), this.validateCode());
    }

    showPasswordlessModal(justSignedIn) {
        if (!this.isOnPasswordlessBeta()) {
            return;
        }
        if (this.state.modal === 'abracadabra') {
            return;
        }
        if (justSignedIn) {
            this.setState({modal: 'abracadabra'});
            Onyx.merge(ONYXKEYS.CREDENTIALS, {signedWithLink: null});
            return;
        }
        if (!_.isEmpty(lodashGet(this.props, 'account.errors', {})) && this.state.modal != 'expiredCode') {
            this.setState({modal: 'expiredCode'});
            return;
        }
        if (
            (this.isAuthenticated() || !lodashGet(this.props, 'credentials.login', null))
            && !lodashGet(this.props, 'credentials.signedWithLink', null)
            && this.state.modal != 'validateCode') {
                this.setState({modal: 'validateCode'});
            }
    }

    render() {
        return (
            <>
                {this.state.modal === 'expiredCode' && (
                    <ExpiredValidateCodeModal
                        shouldShowRequestCodeLink={lodashGet(this.props, 'credentials.login', null) != null}
                        onRequestCodeClick={this.resendValidateCode}
                    />
                )}
                {this.state.modal === 'abracadabra' && <AbracadabraModal />}
                {this.state.modal === 'validateCode'  && (
                    <ValidateCodeModal
                        code={this.validateCode()}
                        shouldShowSignInHere={!this.isAuthenticated() && !this.isSignInInitiated()}
                        onSignInHereClick={this.signInWithValidateCode}
                    />
                )}
                {!this.state.modal  && <FullScreenLoadingIndicator />}
            </>
        );
    }
}

ValidateLoginPage.propTypes = propTypes;
ValidateLoginPage.defaultProps = defaultProps;

export default compose(
    withLocalize,
    withOnyx({
        account: {key: ONYXKEYS.ACCOUNT},
        betas: {key: ONYXKEYS.BETAS},
        credentials: {key: ONYXKEYS.CREDENTIALS},
    }),
)(ValidateLoginPage);
