"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var INPUT_IDS = {
    CHAT_TYPE: 'chatType',
    CURRENCY: 'currency',
    DESCRIPTION: 'description',
    ERROR_FIELDS: 'errorFields',
    HAS_OUTSTANDING_CHILD_REQUEST: 'hasOutstandingChildRequest',
    HAS_OUTSTANDING_CHILD_TASK: 'hasOutstandingChildTask',
    IS_CANCELLED_IOU: 'isCancelledIOU',
    IS_OWN_POLICY_EXPENSE_CHAT: 'isOwnPolicyExpenseChat',
    IS_PINNED: 'isPinned',
    IS_WAITING_ON_BANK_ACCOUNT: 'isWaitingOnBankAccount',
    LAST_ACTION_TYPE: 'lastActionType',
    LAST_ACTOR_ACCOUNT_ID: 'lastActorAccountID',
    LAST_MESSAGE_HTML: 'lastMessageHtml',
    LAST_MESSAGE_TEXT: 'lastMessageText',
    LAST_READ_SEQUENCE_NUMBER: 'lastReadSequenceNumber',
    LAST_READ_TIME: 'lastReadTime',
    LAST_VISIBLE_ACTION_CREATED: 'lastVisibleActionCreated',
    LAST_VISIBLE_ACTION_LAST_MODIFIED: 'lastVisibleActionLastModified',
    MANAGER_ID: 'managerID',
    NON_REIMBURSABLE_TOTAL: 'nonReimbursableTotal',
    NOTIFICATION_PREFERENCE: 'notificationPreference',
    OLD_POLICY_NAME: 'oldPolicyName',
    OWNER_ACCOUNT_ID: 'ownerAccountID',
    PARTICIPANTS: 'participants',
    PERMISSIONS: 'permissions',
    POLICY_AVATAR: 'policyAvatar',
    POLICY_ID: 'policyID',
    POLICY_NAME: 'policyName',
    PRIVATE_NOTES: 'privateNotes',
    PRIVATE_IS_ARCHIVED: 'private_isArchived',
    REPORT_ID: 'reportID',
    REPORT_NAME: 'reportName',
    STATE_NUM: 'stateNum',
    STATUS_NUM: 'statusNum',
    TOTAL: 'total',
    TYPE: 'type',
    UNHELD_TOTAL: 'unheldTotal',
    WELCOME_MESSAGE: 'welcomeMessage',
    WRITE_CAPABILITY: 'writeCapability',
    VISIBILITY: 'visibility',
};
exports.default = INPUT_IDS;
