import type {ValueOf} from 'type-fest';
import type {SearchAmountFilterKeys, SearchDateFilterKeys, SearchGroupBy, SearchWithdrawalType} from '@components/Search/types';
import CONST from '@src/CONST';
import type {SearchDataTypes} from '@src/types/onyx/SearchResults';
import type Form from './Form';

const DATE_FILTER_KEYS: SearchDateFilterKeys[] = [
    CONST.SEARCH.SYNTAX_FILTER_KEYS.DATE,
    CONST.SEARCH.SYNTAX_FILTER_KEYS.SUBMITTED,
    CONST.SEARCH.SYNTAX_FILTER_KEYS.APPROVED,
    CONST.SEARCH.SYNTAX_FILTER_KEYS.PAID,
    CONST.SEARCH.SYNTAX_FILTER_KEYS.EXPORTED,
    CONST.SEARCH.SYNTAX_FILTER_KEYS.POSTED,
    CONST.SEARCH.SYNTAX_FILTER_KEYS.WITHDRAWN,
];

const AMOUNT_FILTER_KEYS: SearchAmountFilterKeys[] = [CONST.SEARCH.SYNTAX_FILTER_KEYS.AMOUNT, CONST.SEARCH.SYNTAX_FILTER_KEYS.TOTAL, CONST.SEARCH.SYNTAX_FILTER_KEYS.PURCHASE_AMOUNT];

const FILTER_KEYS = {
    POLICY_ID: 'policyID',
    GROUP_BY: 'groupBy',
    TYPE: 'type',
    STATUS: 'status',
    NOT_DATE_ON: 'notDateOn',
    DATE_ON: 'dateOn',
    DATE_AFTER: 'dateAfter',
    DATE_BEFORE: 'dateBefore',
    NOT_SUBMITTED_ON: 'notSubmittedOn',
    SUBMITTED_ON: 'submittedOn',
    SUBMITTED_AFTER: 'submittedAfter',
    SUBMITTED_BEFORE: 'submittedBefore',
    NOT_APPROVED_ON: 'notApprovedOn',
    APPROVED_ON: 'approvedOn',
    APPROVED_AFTER: 'approvedAfter',
    APPROVED_BEFORE: 'approvedBefore',
    NOT_PAID_ON: 'notPaidOn',
    PAID_ON: 'paidOn',
    PAID_AFTER: 'paidAfter',
    PAID_BEFORE: 'paidBefore',
    NOT_EXPORTED_ON: 'notExportedOn',
    EXPORTED_ON: 'exportedOn',
    EXPORTED_AFTER: 'exportedAfter',
    EXPORTED_BEFORE: 'exportedBefore',
    NOT_POSTED_ON: 'notPostedOn',
    POSTED_ON: 'postedOn',
    POSTED_AFTER: 'postedAfter',
    POSTED_BEFORE: 'postedBefore',
    NOT_WITHDRAWAL_TYPE: 'notWithdrawalType',
    WITHDRAWAL_TYPE: 'withdrawalType',
    NOT_WITHDRAWN_ON: 'notWithdrawnOn',
    WITHDRAWN_ON: 'withdrawnOn',
    WITHDRAWN_AFTER: 'withdrawnAfter',
    WITHDRAWN_BEFORE: 'withdrawnBefore',
    NOT_CURRENCY: 'notCurrency',
    CURRENCY: 'currency',
    GROUP_CURRENCY: 'groupCurrency',
    NOT_CATEGORY: 'notCategory',
    CATEGORY: 'category',
    NOT_CARD_ID: 'notCardID',
    CARD_ID: 'cardID',
    NOT_FEED: 'notFeed',
    FEED: 'feed',
    NOT_MERCHANT: 'notMerchant',
    MERCHANT: 'merchant',
    NOT_DESCRIPTION: 'notDescription',
    DESCRIPTION: 'description',
    NOT_REPORT_ID: 'notReportID',
    REPORT_ID: 'reportID',
    NOT_AMOUNT_EQUAL_TO: 'notAmountEqualTo',
    AMOUNT_EQUAL_TO: 'amountEqualTo',
    NOT_AMOUNT_LESS_THAN: 'notAmountLessThan',
    AMOUNT_LESS_THAN: 'amountLessThan',
    AMOUNT_GREATER_THAN: 'amountGreaterThan',
    NOT_TOTAL_EQUAL_TO: 'notTotalEqualTo',
    TOTAL_EQUAL_TO: 'totalEqualTo',
    TOTAL_LESS_THAN: 'totalLessThan',
    TOTAL_GREATER_THAN: 'totalGreaterThan',
    NOT_TAX_RATE: 'notTaxRate',
    TAX_RATE: 'taxRate',
    NOT_EXPENSE_TYPE: 'notExpenseType',
    EXPENSE_TYPE: 'expenseType',
    NOT_TAG: 'notTag',
    TAG: 'tag',
    NOT_KEYWORD: 'notKeyword',
    KEYWORD: 'keyword',
    NOT_FROM: 'notFrom',
    FROM: 'from',
    NOT_TO: 'notTo',
    TO: 'to',
    NOT_PAYER: 'notPayer',
    PAYER: 'payer',
    NOT_EXPORTER: 'notExporter',
    EXPORTER: 'exporter',
    NOT_IN: 'notIn',
    IN: 'in',
    NOT_TITLE: 'notTitle',
    TITLE: 'title',
    NOT_ASSIGNEE: 'notAssignee',
    ASSIGNEE: 'assignee',
    NOT_REIMBURSABLE: 'notReimbursable',
    REIMBURSABLE: 'reimbursable',
    NOT_BILLABLE: 'notBillable',
    BILLABLE: 'billable',
    NOT_ACTION: 'notAction',
    ACTION: 'action',
    NOT_HAS: 'notHas',
    HAS: 'has',
    NOT_IS: 'notIs',
    IS: 'is',
    NOT_PURCHASE_AMOUNT_EQUAL_TO: 'notPurchaseAmountEqualTo',
    PURCHASE_AMOUNT_EQUAL_TO: 'purchaseAmountEqualTo',
    PURCHASE_AMOUNT_LESS_THAN: 'purchaseAmountLessThan',
    PURCHASE_AMOUNT_GREATER_THAN: 'purchaseAmountGreaterThan',
    NOT_PURCHASE_CURRENCY: 'notPurchaseCurrency',
    PURCHASE_CURRENCY: 'purchaseCurrency',
    NOT_WITHDRAWAL_ID: 'notWithdrawalID',
    WITHDRAWAL_ID: 'withdrawalID',
    NOT_ATTENDEE: 'notAttendee',
    ATTENDEE: 'attendee',
} as const;

const ALLOWED_TYPE_FILTERS = {
    [CONST.SEARCH.DATA_TYPES.EXPENSE]: [
        FILTER_KEYS.TYPE,
        FILTER_KEYS.STATUS,
        FILTER_KEYS.FROM,
        FILTER_KEYS.NOT_FROM,
        FILTER_KEYS.TO,
        FILTER_KEYS.NOT_TO,
        FILTER_KEYS.KEYWORD,
        FILTER_KEYS.NOT_KEYWORD,
        FILTER_KEYS.POLICY_ID,
        FILTER_KEYS.EXPENSE_TYPE,
        FILTER_KEYS.NOT_EXPENSE_TYPE,
        FILTER_KEYS.MERCHANT,
        FILTER_KEYS.NOT_MERCHANT,
        FILTER_KEYS.DATE_ON,
        FILTER_KEYS.NOT_DATE_ON,
        FILTER_KEYS.DATE_AFTER,
        FILTER_KEYS.DATE_BEFORE,
        FILTER_KEYS.AMOUNT_EQUAL_TO,
        FILTER_KEYS.NOT_AMOUNT_EQUAL_TO,
        FILTER_KEYS.AMOUNT_GREATER_THAN,
        FILTER_KEYS.AMOUNT_LESS_THAN,
        FILTER_KEYS.TOTAL_EQUAL_TO,
        FILTER_KEYS.NOT_TOTAL_EQUAL_TO,
        FILTER_KEYS.TOTAL_GREATER_THAN,
        FILTER_KEYS.TOTAL_LESS_THAN,
        FILTER_KEYS.CURRENCY,
        FILTER_KEYS.NOT_CURRENCY,
        FILTER_KEYS.GROUP_CURRENCY,
        FILTER_KEYS.CATEGORY,
        FILTER_KEYS.NOT_CATEGORY,
        FILTER_KEYS.TAG,
        FILTER_KEYS.NOT_TAG,
        FILTER_KEYS.PAYER,
        FILTER_KEYS.NOT_PAYER,
        FILTER_KEYS.DESCRIPTION,
        FILTER_KEYS.NOT_DESCRIPTION,
        FILTER_KEYS.CARD_ID,
        FILTER_KEYS.NOT_CARD_ID,
        FILTER_KEYS.FEED,
        FILTER_KEYS.NOT_FEED,
        FILTER_KEYS.POSTED_AFTER,
        FILTER_KEYS.POSTED_BEFORE,
        FILTER_KEYS.POSTED_ON,
        FILTER_KEYS.NOT_POSTED_ON,
        FILTER_KEYS.WITHDRAWAL_TYPE,
        FILTER_KEYS.NOT_WITHDRAWAL_TYPE,
        FILTER_KEYS.WITHDRAWN_AFTER,
        FILTER_KEYS.WITHDRAWN_BEFORE,
        FILTER_KEYS.WITHDRAWN_ON,
        FILTER_KEYS.NOT_WITHDRAWN_ON,
        FILTER_KEYS.TAX_RATE,
        FILTER_KEYS.NOT_TAX_RATE,
        FILTER_KEYS.REIMBURSABLE,
        FILTER_KEYS.NOT_REIMBURSABLE,
        FILTER_KEYS.BILLABLE,
        FILTER_KEYS.NOT_BILLABLE,
        FILTER_KEYS.REPORT_ID,
        FILTER_KEYS.NOT_REPORT_ID,
        FILTER_KEYS.SUBMITTED_ON,
        FILTER_KEYS.NOT_SUBMITTED_ON,
        FILTER_KEYS.SUBMITTED_AFTER,
        FILTER_KEYS.SUBMITTED_BEFORE,
        FILTER_KEYS.APPROVED_ON,
        FILTER_KEYS.NOT_APPROVED_ON,
        FILTER_KEYS.APPROVED_AFTER,
        FILTER_KEYS.APPROVED_BEFORE,
        FILTER_KEYS.PAID_ON,
        FILTER_KEYS.NOT_PAID_ON,
        FILTER_KEYS.PAID_AFTER,
        FILTER_KEYS.PAID_BEFORE,
        FILTER_KEYS.EXPORTED_ON,
        FILTER_KEYS.NOT_EXPORTED_ON,
        FILTER_KEYS.EXPORTED_AFTER,
        FILTER_KEYS.EXPORTED_BEFORE,
        FILTER_KEYS.EXPORTER,
        FILTER_KEYS.NOT_EXPORTER,
        FILTER_KEYS.GROUP_BY,
        FILTER_KEYS.ACTION,
        FILTER_KEYS.NOT_ACTION,
        FILTER_KEYS.HAS,
        FILTER_KEYS.NOT_HAS,
        FILTER_KEYS.PURCHASE_AMOUNT_EQUAL_TO,
        FILTER_KEYS.NOT_PURCHASE_AMOUNT_EQUAL_TO,
        FILTER_KEYS.PURCHASE_AMOUNT_GREATER_THAN,
        FILTER_KEYS.PURCHASE_AMOUNT_LESS_THAN,
        FILTER_KEYS.PURCHASE_CURRENCY,
        FILTER_KEYS.NOT_PURCHASE_CURRENCY,
        FILTER_KEYS.WITHDRAWAL_ID,
        FILTER_KEYS.NOT_WITHDRAWAL_ID,
        FILTER_KEYS.TITLE,
        FILTER_KEYS.NOT_TITLE,
        FILTER_KEYS.ATTENDEE,
        FILTER_KEYS.NOT_ATTENDEE,
    ],

    [CONST.SEARCH.DATA_TYPES.INVOICE]: [
        FILTER_KEYS.TYPE,
        FILTER_KEYS.STATUS,
        FILTER_KEYS.FROM,
        FILTER_KEYS.NOT_FROM,
        FILTER_KEYS.TO,
        FILTER_KEYS.NOT_TO,
        FILTER_KEYS.KEYWORD,
        FILTER_KEYS.NOT_KEYWORD,
        FILTER_KEYS.POLICY_ID,
        FILTER_KEYS.MERCHANT,
        FILTER_KEYS.NOT_MERCHANT,
        FILTER_KEYS.DATE_ON,
        FILTER_KEYS.NOT_DATE_ON,
        FILTER_KEYS.DATE_AFTER,
        FILTER_KEYS.DATE_BEFORE,
        FILTER_KEYS.AMOUNT_EQUAL_TO,
        FILTER_KEYS.NOT_AMOUNT_EQUAL_TO,
        FILTER_KEYS.AMOUNT_GREATER_THAN,
        FILTER_KEYS.AMOUNT_LESS_THAN,
        FILTER_KEYS.TOTAL_EQUAL_TO,
        FILTER_KEYS.NOT_TOTAL_EQUAL_TO,
        FILTER_KEYS.TOTAL_GREATER_THAN,
        FILTER_KEYS.TOTAL_LESS_THAN,
        FILTER_KEYS.CURRENCY,
        FILTER_KEYS.NOT_CURRENCY,
        FILTER_KEYS.CATEGORY,
        FILTER_KEYS.NOT_CATEGORY,
        FILTER_KEYS.TAG,
        FILTER_KEYS.NOT_TAG,
        FILTER_KEYS.PAYER,
        FILTER_KEYS.NOT_PAYER,
        FILTER_KEYS.DESCRIPTION,
        FILTER_KEYS.NOT_DESCRIPTION,
        FILTER_KEYS.CARD_ID,
        FILTER_KEYS.NOT_CARD_ID,
        FILTER_KEYS.FEED,
        FILTER_KEYS.NOT_FEED,
        FILTER_KEYS.POSTED_AFTER,
        FILTER_KEYS.POSTED_BEFORE,
        FILTER_KEYS.POSTED_ON,
        FILTER_KEYS.NOT_POSTED_ON,
        FILTER_KEYS.WITHDRAWAL_TYPE,
        FILTER_KEYS.NOT_WITHDRAWAL_TYPE,
        FILTER_KEYS.WITHDRAWN_AFTER,
        FILTER_KEYS.WITHDRAWN_BEFORE,
        FILTER_KEYS.WITHDRAWN_ON,
        FILTER_KEYS.NOT_WITHDRAWN_ON,
        FILTER_KEYS.TAX_RATE,
        FILTER_KEYS.NOT_TAX_RATE,
        FILTER_KEYS.REPORT_ID,
        FILTER_KEYS.NOT_REPORT_ID,
        FILTER_KEYS.SUBMITTED_ON,
        FILTER_KEYS.NOT_SUBMITTED_ON,
        FILTER_KEYS.SUBMITTED_AFTER,
        FILTER_KEYS.SUBMITTED_BEFORE,
        FILTER_KEYS.APPROVED_ON,
        FILTER_KEYS.NOT_APPROVED_ON,
        FILTER_KEYS.APPROVED_AFTER,
        FILTER_KEYS.APPROVED_BEFORE,
        FILTER_KEYS.PAID_ON,
        FILTER_KEYS.NOT_PAID_ON,
        FILTER_KEYS.PAID_AFTER,
        FILTER_KEYS.PAID_BEFORE,
        FILTER_KEYS.EXPORTED_ON,
        FILTER_KEYS.NOT_EXPORTED_ON,
        FILTER_KEYS.EXPORTED_AFTER,
        FILTER_KEYS.EXPORTED_BEFORE,
        FILTER_KEYS.EXPORTER,
        FILTER_KEYS.NOT_EXPORTER,
        FILTER_KEYS.ACTION,
        FILTER_KEYS.NOT_ACTION,
        FILTER_KEYS.PURCHASE_AMOUNT_EQUAL_TO,
        FILTER_KEYS.NOT_PURCHASE_AMOUNT_EQUAL_TO,
        FILTER_KEYS.PURCHASE_AMOUNT_GREATER_THAN,
        FILTER_KEYS.PURCHASE_AMOUNT_LESS_THAN,
        FILTER_KEYS.PURCHASE_CURRENCY,
        FILTER_KEYS.NOT_PURCHASE_CURRENCY,
        FILTER_KEYS.WITHDRAWAL_ID,
        FILTER_KEYS.NOT_WITHDRAWAL_ID,
        FILTER_KEYS.TITLE,
        FILTER_KEYS.NOT_TITLE,
    ],

    [CONST.SEARCH.DATA_TYPES.TRIP]: [
        FILTER_KEYS.TYPE,
        FILTER_KEYS.STATUS,
        FILTER_KEYS.FROM,
        FILTER_KEYS.NOT_FROM,
        FILTER_KEYS.TO,
        FILTER_KEYS.NOT_TO,
        FILTER_KEYS.KEYWORD,
        FILTER_KEYS.NOT_KEYWORD,
        FILTER_KEYS.POLICY_ID,
        FILTER_KEYS.MERCHANT,
        FILTER_KEYS.NOT_MERCHANT,
        FILTER_KEYS.DATE_ON,
        FILTER_KEYS.NOT_DATE_ON,
        FILTER_KEYS.DATE_AFTER,
        FILTER_KEYS.DATE_BEFORE,
        FILTER_KEYS.AMOUNT_EQUAL_TO,
        FILTER_KEYS.NOT_AMOUNT_EQUAL_TO,
        FILTER_KEYS.AMOUNT_GREATER_THAN,
        FILTER_KEYS.AMOUNT_LESS_THAN,
        FILTER_KEYS.TOTAL_EQUAL_TO,
        FILTER_KEYS.NOT_TOTAL_EQUAL_TO,
        FILTER_KEYS.TOTAL_GREATER_THAN,
        FILTER_KEYS.TOTAL_LESS_THAN,
        FILTER_KEYS.CURRENCY,
        FILTER_KEYS.NOT_CURRENCY,
        FILTER_KEYS.GROUP_CURRENCY,
        FILTER_KEYS.CATEGORY,
        FILTER_KEYS.NOT_CATEGORY,
        FILTER_KEYS.TAG,
        FILTER_KEYS.NOT_TAG,
        FILTER_KEYS.PAYER,
        FILTER_KEYS.NOT_PAYER,
        FILTER_KEYS.DESCRIPTION,
        FILTER_KEYS.NOT_DESCRIPTION,
        FILTER_KEYS.CARD_ID,
        FILTER_KEYS.NOT_CARD_ID,
        FILTER_KEYS.FEED,
        FILTER_KEYS.NOT_FEED,
        FILTER_KEYS.POSTED_AFTER,
        FILTER_KEYS.POSTED_BEFORE,
        FILTER_KEYS.POSTED_ON,
        FILTER_KEYS.NOT_POSTED_ON,
        FILTER_KEYS.TAX_RATE,
        FILTER_KEYS.NOT_TAX_RATE,
        FILTER_KEYS.REPORT_ID,
        FILTER_KEYS.NOT_REPORT_ID,
        FILTER_KEYS.SUBMITTED_ON,
        FILTER_KEYS.NOT_SUBMITTED_ON,
        FILTER_KEYS.SUBMITTED_AFTER,
        FILTER_KEYS.SUBMITTED_BEFORE,
        FILTER_KEYS.APPROVED_ON,
        FILTER_KEYS.NOT_APPROVED_ON,
        FILTER_KEYS.APPROVED_AFTER,
        FILTER_KEYS.APPROVED_BEFORE,
        FILTER_KEYS.PAID_ON,
        FILTER_KEYS.NOT_PAID_ON,
        FILTER_KEYS.PAID_AFTER,
        FILTER_KEYS.PAID_BEFORE,
        FILTER_KEYS.EXPORTED_ON,
        FILTER_KEYS.NOT_EXPORTED_ON,
        FILTER_KEYS.EXPORTED_AFTER,
        FILTER_KEYS.EXPORTED_BEFORE,
        FILTER_KEYS.EXPORTER,
        FILTER_KEYS.NOT_EXPORTER,
        FILTER_KEYS.ACTION,
        FILTER_KEYS.NOT_ACTION,
        FILTER_KEYS.PURCHASE_AMOUNT_EQUAL_TO,
        FILTER_KEYS.NOT_PURCHASE_AMOUNT_EQUAL_TO,
        FILTER_KEYS.PURCHASE_AMOUNT_GREATER_THAN,
        FILTER_KEYS.PURCHASE_AMOUNT_LESS_THAN,
        FILTER_KEYS.PURCHASE_CURRENCY,
        FILTER_KEYS.NOT_PURCHASE_CURRENCY,
        FILTER_KEYS.TITLE,
        FILTER_KEYS.NOT_TITLE,
    ],

    [CONST.SEARCH.DATA_TYPES.CHAT]: [
        FILTER_KEYS.TYPE,
        FILTER_KEYS.FROM,
        FILTER_KEYS.NOT_FROM,
        FILTER_KEYS.TO,
        FILTER_KEYS.NOT_TO,
        FILTER_KEYS.IN,
        FILTER_KEYS.NOT_IN,
        FILTER_KEYS.KEYWORD,
        FILTER_KEYS.NOT_KEYWORD,
        FILTER_KEYS.POLICY_ID,
        FILTER_KEYS.DATE_AFTER,
        FILTER_KEYS.DATE_BEFORE,
        FILTER_KEYS.DATE_ON,
        FILTER_KEYS.NOT_DATE_ON,
        FILTER_KEYS.IS,
        FILTER_KEYS.NOT_IS,
        FILTER_KEYS.HAS,
        FILTER_KEYS.NOT_HAS,
    ],

    [CONST.SEARCH.DATA_TYPES.TASK]: [
        FILTER_KEYS.TYPE,
        FILTER_KEYS.STATUS,
        FILTER_KEYS.TITLE,
        FILTER_KEYS.NOT_TITLE,
        FILTER_KEYS.DESCRIPTION,
        FILTER_KEYS.NOT_DESCRIPTION,
        FILTER_KEYS.IN,
        FILTER_KEYS.NOT_IN,
        FILTER_KEYS.FROM,
        FILTER_KEYS.NOT_FROM,
        FILTER_KEYS.ASSIGNEE,
        FILTER_KEYS.NOT_ASSIGNEE,
        FILTER_KEYS.DATE_ON,
        FILTER_KEYS.NOT_DATE_ON,
        FILTER_KEYS.DATE_AFTER,
        FILTER_KEYS.DATE_BEFORE,
    ],
};

type SearchAdvancedFiltersKey = ValueOf<typeof FILTER_KEYS>;

type SearchAdvancedFiltersForm = Form<
    SearchAdvancedFiltersKey,
    {
        [FILTER_KEYS.GROUP_BY]: SearchGroupBy;

        [FILTER_KEYS.TYPE]: SearchDataTypes;

        [FILTER_KEYS.STATUS]: string[] | string;

        [FILTER_KEYS.DATE_AFTER]: string;
        [FILTER_KEYS.DATE_BEFORE]: string;

        [FILTER_KEYS.DATE_ON]: string;
        [FILTER_KEYS.NOT_DATE_ON]: string;

        [FILTER_KEYS.SUBMITTED_ON]: string;
        [FILTER_KEYS.NOT_SUBMITTED_ON]: string;
        [FILTER_KEYS.SUBMITTED_AFTER]: string;
        [FILTER_KEYS.SUBMITTED_BEFORE]: string;

        [FILTER_KEYS.APPROVED_ON]: string;
        [FILTER_KEYS.NOT_APPROVED_ON]: string;
        [FILTER_KEYS.APPROVED_AFTER]: string;
        [FILTER_KEYS.APPROVED_BEFORE]: string;

        [FILTER_KEYS.PAID_ON]: string;
        [FILTER_KEYS.NOT_PAID_ON]: string;
        [FILTER_KEYS.PAID_AFTER]: string;
        [FILTER_KEYS.PAID_BEFORE]: string;

        [FILTER_KEYS.EXPORTED_ON]: string;
        [FILTER_KEYS.NOT_EXPORTED_ON]: string;
        [FILTER_KEYS.EXPORTED_AFTER]: string;
        [FILTER_KEYS.EXPORTED_BEFORE]: string;

        [FILTER_KEYS.POSTED_ON]: string;
        [FILTER_KEYS.NOT_POSTED_ON]: string;
        [FILTER_KEYS.POSTED_AFTER]: string;
        [FILTER_KEYS.POSTED_BEFORE]: string;

        [FILTER_KEYS.WITHDRAWAL_TYPE]: SearchWithdrawalType;
        [FILTER_KEYS.NOT_WITHDRAWAL_TYPE]: SearchWithdrawalType;

        [FILTER_KEYS.WITHDRAWN_ON]: string;
        [FILTER_KEYS.NOT_WITHDRAWN_ON]: string;
        [FILTER_KEYS.WITHDRAWN_AFTER]: string;
        [FILTER_KEYS.WITHDRAWN_BEFORE]: string;

        [FILTER_KEYS.CURRENCY]: string[];
        [FILTER_KEYS.NOT_CURRENCY]: string[];
        [FILTER_KEYS.GROUP_CURRENCY]: string;

        [FILTER_KEYS.CATEGORY]: string[];
        [FILTER_KEYS.NOT_CATEGORY]: string[];

        [FILTER_KEYS.POLICY_ID]: string[];

        [FILTER_KEYS.CARD_ID]: string[];
        [FILTER_KEYS.NOT_CARD_ID]: string[];

        [FILTER_KEYS.FEED]: string[];
        [FILTER_KEYS.NOT_FEED]: string[];

        [FILTER_KEYS.MERCHANT]: string;
        [FILTER_KEYS.NOT_MERCHANT]: string;

        [FILTER_KEYS.DESCRIPTION]: string;
        [FILTER_KEYS.NOT_DESCRIPTION]: string;

        [FILTER_KEYS.REPORT_ID]: string;
        [FILTER_KEYS.NOT_REPORT_ID]: string;

        [FILTER_KEYS.AMOUNT_EQUAL_TO]: string;
        [FILTER_KEYS.NOT_AMOUNT_EQUAL_TO]: string;
        [FILTER_KEYS.AMOUNT_LESS_THAN]: string;
        [FILTER_KEYS.NOT_AMOUNT_LESS_THAN]: string;
        [FILTER_KEYS.AMOUNT_GREATER_THAN]: string;

        [FILTER_KEYS.TOTAL_EQUAL_TO]: string;
        [FILTER_KEYS.NOT_TOTAL_EQUAL_TO]: string;
        [FILTER_KEYS.TOTAL_LESS_THAN]: string;
        [FILTER_KEYS.TOTAL_GREATER_THAN]: string;

        [FILTER_KEYS.KEYWORD]: string;
        [FILTER_KEYS.NOT_KEYWORD]: string;

        [FILTER_KEYS.TAX_RATE]: string[];
        [FILTER_KEYS.NOT_TAX_RATE]: string[];

        [FILTER_KEYS.EXPENSE_TYPE]: string[];
        [FILTER_KEYS.NOT_EXPENSE_TYPE]: string[];

        [FILTER_KEYS.TAG]: string[];
        [FILTER_KEYS.NOT_TAG]: string[];

        [FILTER_KEYS.FROM]: string[];
        [FILTER_KEYS.NOT_FROM]: string[];

        [FILTER_KEYS.PAYER]: string;
        [FILTER_KEYS.NOT_PAYER]: string;

        [FILTER_KEYS.EXPORTER]: string[];
        [FILTER_KEYS.NOT_EXPORTER]: string[];

        [FILTER_KEYS.TO]: string[];
        [FILTER_KEYS.NOT_TO]: string[];

        [FILTER_KEYS.IN]: string[];
        [FILTER_KEYS.NOT_IN]: string[];

        [FILTER_KEYS.TITLE]: string;
        [FILTER_KEYS.NOT_TITLE]: string;

        [FILTER_KEYS.ASSIGNEE]: string[];
        [FILTER_KEYS.NOT_ASSIGNEE]: string[];

        [FILTER_KEYS.REIMBURSABLE]: string;
        [FILTER_KEYS.NOT_REIMBURSABLE]: string;

        [FILTER_KEYS.BILLABLE]: string;
        [FILTER_KEYS.NOT_BILLABLE]: string;

        [FILTER_KEYS.ACTION]: string;
        [FILTER_KEYS.NOT_ACTION]: string;

        [FILTER_KEYS.HAS]: string[];
        [FILTER_KEYS.NOT_HAS]: string[];

        [FILTER_KEYS.IS]: string[];
        [FILTER_KEYS.NOT_IS]: string[];

        [FILTER_KEYS.PURCHASE_AMOUNT_EQUAL_TO]: string;
        [FILTER_KEYS.NOT_PURCHASE_AMOUNT_EQUAL_TO]: string;
        [FILTER_KEYS.PURCHASE_AMOUNT_GREATER_THAN]: string;
        [FILTER_KEYS.PURCHASE_AMOUNT_LESS_THAN]: string;

        [FILTER_KEYS.PURCHASE_CURRENCY]: string[];
        [FILTER_KEYS.NOT_PURCHASE_CURRENCY]: string[];

        [FILTER_KEYS.WITHDRAWAL_ID]: string;
        [FILTER_KEYS.NOT_WITHDRAWAL_ID]: string;

        [FILTER_KEYS.ATTENDEE]: string[];
        [FILTER_KEYS.NOT_ATTENDEE]: string[];
    }
>;

export type {SearchAdvancedFiltersForm, SearchAdvancedFiltersKey};
export default FILTER_KEYS;
export {DATE_FILTER_KEYS, ALLOWED_TYPE_FILTERS, FILTER_KEYS, AMOUNT_FILTER_KEYS};
