name: Format CodeCov Comment

on:
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write

jobs:
  format-codecov-comment:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    if: github.event.issue.pull_request && github.event.comment.user.login == 'codecov[bot]'
    steps:
      - name: Checkout
      # v1
        uses: getblacksmith/checkout@41cdeedae8edb2e684ba22896a5fd2a3cb85db6b # v1 
      - name: Format CodeCov Comment
        uses: ./.github/actions/javascript/formatCodeCovComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

