name: Format CodeCov Comment

on:
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write

jobs:
  format-codecov-comment:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    if: github.event.issue.pull_request && github.event.comment.user.login == 'codecov[bot]'
    steps:
      - name: Checkout
        uses: useblacksmith/checkout@f50565632710173b0e366f2cd39b928d31362815 # v1.6.0

      - name: Format CodeCov Comment
        uses: ./.github/actions/javascript/formatCodeCovComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
