name: Reassure Performance Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths-ignore: [docs/**, help/**, .github/**, contributingGuides/**, tests/**, '**.md', '**.sh']

jobs:
  baseline-perf-tests:
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout baseline branch
        # v1
        uses: useblacksmith/checkout@41cdeedae8edb2e684ba22896a5fd2a3cb85db6b
        with:
          fetch-depth: 0

      - name: Checkout baseline branch
        shell: bash
        run: |
          set -e
          BASELINE_BRANCH=${BASELINE_BRANCH:="main"}
          git fetch origin "$BASELINE_BRANCH" --no-tags
          git checkout --force --detach "origin/$BASELINE_BRANCH" --no-recurse-submodules

      - name: Setup NodeJS
        uses: ./.github/actions/composite/setupNode

      - name: Run baseline performance tests
        shell: bash
        run: NODE_OPTIONS=--experimental-vm-modules npx reassure --baseline

      - name: Upload baseline performance results
        # v6
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: reassure-baseline-results
          path: ./.reassure/baseline.perf
          include-hidden-files: true

  branch-perf-tests:
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        # v1
        uses: useblacksmith/checkout@41cdeedae8edb2e684ba22896a5fd2a3cb85db6b
        with:
          fetch-depth: 0

      - name: Set dummy git credentials
        run: |
            git config --global user.email "test@test.com"
            git config --global user.name "Test"

      - name: Prepare branch for performance tests
        shell: bash
        run: |
          set -e
          BASELINE_BRANCH=${BASELINE_BRANCH:="main"}
          PR_SHA=${{ github.event.pull_request.head.sha }}
          git fetch origin "$BASELINE_BRANCH" --no-tags
          common_ancestor=$(git merge-base "$PR_SHA" "origin/$BASELINE_BRANCH")
          DELETED_FILES=$(git diff --name-only --diff-filter=D "$common_ancestor" "$PR_SHA")

          git checkout --force --detach "$PR_SHA" --no-recurse-submodules

          for file in $DELETED_FILES; do
            if [ -n "$file" ]; then
              rm -f "$file"
              echo "Deleted file: $file"
            fi
          done

          if ! git merge --no-commit --allow-unrelated-histories "origin/$BASELINE_BRANCH" -X ours; then
            git checkout --ours .
          fi

      - name: Setup NodeJS
        uses: ./.github/actions/composite/setupNode

      - name: Run branch performance tests
        shell: bash
        run: NODE_OPTIONS=--experimental-vm-modules npx reassure --branch="${{ github.head_ref }}" --no-compare

      - name: Upload branch performance results
        # v6
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: reassure-branch-results
          path: ./.reassure/current.perf
          include-hidden-files: true

  validate-perf-tests:
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: blacksmith-4vcpu-ubuntu-2404
    needs: [baseline-perf-tests, branch-perf-tests]
    steps:
      - name: Checkout
        # v1
        uses: useblacksmith/checkout@41cdeedae8edb2e684ba22896a5fd2a3cb85db6b

      - name: Setup NodeJS
        uses: ./.github/actions/composite/setupNode

      - name: Download baseline performance results
        # v7
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131
        with:
          name: reassure-baseline-results
          path: ./.reassure

      - name: Download branch performance results
        # v7
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131
        with:
          name: reassure-branch-results
          path: ./.reassure

      - name: Compare performance results
        run: node -e "require('@callstack/reassure-compare').compare().catch((error) => { console.error(error); process.exit(1); })"

      - name: Validate output.json
        id: validateReassureOutput
        uses: ./.github/actions/javascript/validateReassureOutput
        with:
          DURATION_DEVIATION_PERCENTAGE: 20
          COUNT_DEVIATION: 0
