# Reminder: If this workflow's name changes, update the name in the dependent workflow at .github/workflows/failureNotifier.yml.
name: Remote Build iOS

on:
  workflow_dispatch:
  push:
    branches-ignore: [staging, production, cherry-pick-*]
    paths-ignore: ['docs/**', 'contributingGuides/**', 'help/**', '.github/**', 'scripts/**', 'tests/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  buildStandalone:
    name: Build standalone (DebugDevelopment)
    runs-on: ${{ github.repository_owner == 'Expensify' && 'macos-15-xlarge' || 'macos-15' }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer
    steps:
      - name: Checkout
        # v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          token: ${{ secrets.OS_BOTIFY_TOKEN }}

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode

      - name: Configure AWS Credentials
        # v6
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Rock Remote Build - iOS
        uses: callstackincubator/ios@dd30f7e53eee2ea6a59509793d0a30fbb5c91216
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          destination: simulator
          scheme: 'New Expensify Dev'
          configuration: 'DebugDevelopment'
          comment-bot: false

  buildHybrid:
    name: Build hybrid (Debug)
    uses: ./.github/workflows/buildIOS.yml
    with:
      ref: ${{ github.sha }}
      variant: Debug
    secrets: inherit
