name: Seed caches

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  seedStandalone:
    name: Seed standalone node_modules
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: useblacksmith/checkout@0647fdbab2614a5eb86d2971070e325060d91056 # v1.7.0

      - name: Setup Node (seed)
        uses: ./.github/actions/composite/setupNode
        with:
          SEED_STICKY_DISKS: 'true'

  seedHybrid:
    name: Seed hybrid node_modules
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: useblacksmith/checkout@0647fdbab2614a5eb86d2971070e325060d91056 # v1.7.0
        with:
          submodules: true
          token: ${{ secrets.OS_BOTIFY_TOKEN }}

      - name: Setup Node (seed)
        uses: ./.github/actions/composite/setupNode
        with:
          IS_HYBRID_BUILD: 'true'
          SEED_STICKY_DISKS: 'true'

  seedJestPerfCache:
    name: Seed Jest perf cache
    uses: ./.github/workflows/seedJestPerfCache.yml
