name: Lint shell code

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths: ['**.sh']

jobs:
  lint:
    if: ${{ github.actor != 'OSBotify' || github.event_name == 'workflow_call' }}
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout
        # v1
        uses: getblacksmith/checkout@41cdeedae8edb2e684ba22896a5fd2a3cb85db6b # v1

      - name: Lint shell scripts with ShellCheck
        run: npm run shellcheck
