name: Lint shell code

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths: ['**.sh']

jobs:
  lint:
    if: ${{ github.actor != 'OSBotify' || github.event_name == 'workflow_call' }}
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: useblacksmith/checkout@1c9394c220d293645707b625ba9d79685f093a8f # v1

      - name: Lint shell scripts with ShellCheck
        run: npm run shellcheck
