name: Validate Docs Routes File

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - docs/**

jobs:
  verify:
    if: github.actor != 'OSBotify' && github.actor != 'imgbot[bot]'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: useblacksmith/checkout@f50565632710173b0e366f2cd39b928d31362815 # v1.6.0

      - uses: ./.github/actions/composite/setupNode

      # Verify that no new hubs were created without adding their metadata to _routes.yml
      - name: Validate Docs Routes File
        run: ./.github/scripts/createDocsRoutes.sh
