name: Validate Docs Routes File

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - docs/**

jobs:
  verify:
    if: github.actor != 'OSBotify' && github.actor != 'imgbot[bot]'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: useblacksmith/checkout@1c9394c220d293645707b625ba9d79685f093a8f # v1

      - uses: ./.github/actions/composite/setupNodeStickyDisk

      # Verify that no new hubs were created without adding their metadata to _routes.yml
      - name: Validate Docs Routes File
        run: ./.github/scripts/createDocsRoutes.sh
