name: Validate Github Actions

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths: ['.github/**', 'scripts/**', 'package.json', 'package-lock.json', 'tsconfig.json']

jobs:
  verify:
    if: github.actor != 'OSBotify' && github.actor != 'imgbot[bot]'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        # v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode

      # Rebuild all the actions on this branch and check for a diff. Fail if there is one,
      # because that would be a sign that the PR author did not rebuild the Github Actions
      - name: Verify Javascript Action Builds
        run: ./.github/scripts/verifyActions.sh
