name: Verify Podfile

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths:
      - ios/**
      - "package.json"
      - "package-lock.json"

jobs:
  verify:
    if: github.actor != 'OSBotify' && github.actor != 'imgbot[bot]'
    runs-on: blacksmith-6vcpu-macos-latest
    steps:
      - name: Checkout
        # v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode

      - name: Verify podfile
        run: ./.github/scripts/verifyPodfile.sh
