name: Verify Podfile

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths:
      - ios/**
      - "package.json"
      - "package-lock.json"

jobs:
  verify:
    if: github.actor != 'OSBotify' && github.actor != 'imgbot[bot]'
    runs-on: blacksmith-6vcpu-macos-latest
    steps:
      - name: Checkout
        # v1
        uses: getblacksmith/checkout@41cdeedae8edb2e684ba22896a5fd2a3cb85db6b # v1

      - name: Setup Node
        uses: ./.github/actions/composite/setupNode

      - name: Verify podfile
        run: ./.github/scripts/verifyPodfile.sh
