name: Verify signed commits

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]

jobs:
  verifySignedCommits:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Verify signed commits
        uses: ./.github/actions/javascript/verifySignedCommits
        with:
          GITHUB_TOKEN: ${{ github.token }}
