name: Verify signed commits

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]

jobs:
  verifySignedCommits:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: useblacksmith/checkout@f50565632710173b0e366f2cd39b928d31362815 # v1.6.0

      - name: Verify signed commits
        uses: ./.github/actions/javascript/verifySignedCommits
        with:
          GITHUB_TOKEN: ${{ github.token }}
