name: Verify signed commits

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]

jobs:
  verifySignedCommits:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: useblacksmith/checkout@0647fdbab2614a5eb86d2971070e325060d91056 # v1.7.0

      - name: Verify signed commits
        uses: ./.github/actions/javascript/verifySignedCommits
        with:
          GITHUB_TOKEN: ${{ github.token }}
