name: Check consistency of search parser files

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore: [staging, production]
    paths:
      - 'src/libs/SearchParser/**'

jobs:
  verify:
    if: github.actor != 'OSBotify' && github.actor != 'imgbot[bot]'
    runs-on: blacksmith-6vcpu-macos-latest
    steps:
      - name: Checkout
        uses: useblacksmith/checkout@1c9394c220d293645707b625ba9d79685f093a8f # v1

      - name: Setup Node
        uses: ./.github/actions/composite/setupNodeStickyDisk

      - name: Verify parser files consistency
        run: ./.github/scripts/checkParser.sh
